awslabs/iot-app-kit

- .gitignore
- CHANGELOG.md
- lerna.json
- package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/components/src/testing/renderChart.tsx
- packages/components/src/testing/testing-ground/testing-ground.css
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/related-table/CHANGELOG.md
- packages/related-table/package.json
- packages/source-iotsitewise/CHANGELOG.md
- packages/source-iotsitewise/package.json
* Bump minor version
* Export global styles. This will allow imports from `@iot-app-kit/components/styles.css`
* Remove `release` script. We are already installing and building in the npm publish action
* Copy `NOTICE` and `CHANGELOG.md` to npm package
n/a
> Release 1.1.0

- CHANGELOG.md
- lerna.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/react-components/src/components.ts
- packages/react-components/src/stencil-generated/utils/attachProps.ts
- packages/related-table/CHANGELOG.md
- packages/related-table/package.json
- packages/source-iotsitewise/CHANGELOG.md
- packages/source-iotsitewise/package.json
* attach ResourceExplorer react component onSelectionChange prop
* export table react component
The fix for `onSelectionChange` prop will also fix any function props we want to attach in the future. The downside to this is that for events it will attach the prop to the node and add an event listener.
n/a
> Release 1.2.0

- CHANGELOG.md
- lerna.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/components/src/components/iot-bar-chart/iot-bar-chart.tsx
- packages/components/src/components/iot-kpi/iot-kpi.tsx
- packages/components/src/components/iot-line-chart/iot-line-chart.tsx
- packages/components/src/components/iot-scatter-chart/iot-scatter-chart.tsx
- packages/components/src/components/iot-status-grid/iot-status-grid.tsx
- packages/components/src/components/iot-status-timeline/iot-status-timeline.tsx
- packages/components/src/components/iot-table/iot-table.tsx
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/related-table/CHANGELOG.md
- packages/related-table/package.json
- packages/source-iotsitewise/CHANGELOG.md
- packages/source-iotsitewise/package.json
* Unsubscribe data provider on component updates. This will allow updating the query without continuously requesting previous query, causing glitches on the charts.
* Bump patch version to 1.2.1
> Release 1.2.1

- docs/AWSIoTSiteWiseSource.md
- docs/BarChart.md
- docs/Components.md
- docs/Core.md
- docs/KPI.md
- docs/LineChart.md
- docs/ScatterChart.md
- docs/StatusGrid.md
- docs/StatusTimeline.md
- docs/Table.md
- packages/components/package.json
> feat: update synchro charts to 3.1.0, update docs

- packages/components/src/integration/iot-connector/iot-connector.spec.component.ts
- packages/components/src/integration/iot-line-chart/iot-line-chart.spec.component.ts
- packages/components/src/integration/iot-status-grid/iot-status-grid.spec.component.ts
- packages/components/src/integration/iot-status-timeline/iot-status-timeline.spec.component.ts
- packages/core/src/__mocks__/data-source.ts
- packages/core/src/data-module/IotAppKitDataModule.spec.ts
- packages/core/src/data-module/IotAppKitDataModule.ts
- packages/core/src/data-module/data-cache/caching/caching.spec.ts
- packages/core/src/data-module/data-cache/caching/caching.ts
- packages/core/src/data-module/data-cache/dataActions.ts
- packages/core/src/data-module/data-cache/dataCacheWrapped.spec.ts
- packages/core/src/data-module/data-cache/dataCacheWrapped.ts
- packages/core/src/data-module/data-cache/dataReducer.spec.ts
- packages/core/src/data-module/data-cache/dataReducer.ts
- packages/core/src/data-module/types.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/client.ts
- packages/source-iotsitewise/src/time-series-data/client/getAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/getHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/getLatestPropertyDataPoint.ts
- packages/source-iotsitewise/src/time-series-data/data-source.spec.ts
- packages/source-iotsitewise/src/time-series-data/data-source.ts
`fetchMostRecentBeforeStart` is needed for the line chart to display leading lines and for the status timeline to display pre-viewport status. This PR adds support for this time series data request setting.
Example of leading line:
The current cache behaviour needs to be adjusted so that cache intervals for `fetchMostRecentBeforeStart` requests don't start at `Date(0,0,0)` _unless_ there was no data returned. Core cache logic was added for this case to start at the data point returned.
> feat: support fetchMostRecentBeforeStart time series data request setting

- packages/components/package.json
- packages/components/src/components.d.ts
- packages/components/src/components/common/bindStylesToDataStreams.spec.ts
- packages/components/src/components/common/bindStylesToDataStreams.ts
- packages/components/src/components/common/colorPalette.ts
- packages/components/src/components/iot-bar-chart/iot-bar-chart.tsx
- packages/components/src/components/iot-line-chart/iot-line-chart.tsx
- packages/components/src/components/iot-scatter-chart/iot-scatter-chart.tsx
- packages/components/src/components/iot-status-timeline/iot-status-timeline.tsx
- packages/components/src/components/iot-time-series-connector/iot-time-series-connector.spec.ts
- packages/components/src/components/iot-time-series-connector/iot-time-series-connector.tsx
Provides default colors to be assigned to the following widgets:
- line chart
- scatter chart
- bar chart
- status timeline
This is applied when no `styleSettings` color field is mapped to the associated 'data stream'.
The default color pallete provides 13 colors, it will rotate sequentially, and wrap back to the first color on the 14th datastream.
> feat: support auto-assigning colors for certain components

- packages/source-iotsitewise/package.json
- packages/source-iotsitewise/src/time-series-data/client/client.ts
- packages/source-iotsitewise/src/time-series-data/data-source.spec.ts
Introduce dataloader concept into IoTAppKit. The current implement proxies the existing API calls to SiteWise.
The default batching behaviour being introduced is batch-by-frame leveraging `process.nextTick`. The current implementation mimics the existing request behaviour (see https://quip-amazon.com/LKcsAKkMayVB/Batch-API-Request-Behaviour for some example waterfall charts).
Follow-up work includes:
- create batchable client requests (i.e. `getBatchAggregatedPropertyDataPoints.ts`).
- identify the optimal batch interval by finding the right balance of latency vs. request frequency (via experimentation with common dashboard configurations).
- (optional) expose batch interval as a configurable property
unit tests passing
-  …
> introduce dataloader to proxy existing sitewise API calls

- packages/components/src/testing/testing-ground/testing-ground.tsx
- packages/source-iotsitewise/src/time-series-data/client/batch.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/batch.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
This change implements pagination and edge case fixes for historical data batching. The fixes include:
1. Fixing `maxResults` to handle any positive integer value and ensuring that the `maxResults` for a batch is the sum of the `maxResults` of its entries.
2. Fixing pagination logic so that we only paginate on a batch if there is more data to fetch and we haven't already hit `maxResults` for that batch.
3. Fixing batch chunking so that batches with more than 16 entries are chunked down to at most 16 entries.
4. Add testing for batching and paginating.
> edge case handling for batching historical data

- packages/dashboard/src/components/iot-dashboard/__snapshots__/iot-dashboard.spec.tsx.snap
- packages/dashboard/src/dashboard-actions/move.spec.ts
- packages/dashboard/src/dashboard-actions/move.ts
Fixes widget movement when widgets are dragged to the very top or far left of the grid.
Also adds in a missing snapshot that wasn't generated.
> fix: layout glitch on widgets being positioned on invalid rows/col

- docs/ResourceExplorer.md
- packages/components/package.json
- packages/components/src/components.d.ts
- packages/components/src/components/iot-bar-chart/iot-bar-chart.tsx
- packages/components/src/components/iot-kpi/iot-kpi.tsx
- packages/components/src/components/iot-line-chart/iot-line-chart.tsx
- packages/components/src/components/iot-resource-explorer/iot-resource-explorer.tsx
- packages/components/src/components/iot-resource-explorer/iot-tree-table.tsx
- packages/components/src/components/iot-scatter-chart/iot-scatter-chart.tsx
- packages/components/src/components/iot-status-grid/iot-status-grid.tsx
- packages/components/src/components/iot-status-timeline/iot-status-timeline.tsx
- packages/components/src/components/iot-table/iot-table.tsx
- packages/components/src/integration/iot-resource-explorer/iot-resource-explorer.spec.component.ts
- packages/components/src/integration/iot-resource-explorer/setup.tsx
- packages/related-table/package.json
- packages/related-table/src/HOC/withUseTreeCollection.tsx
- packages/related-table/src/Hooks/useTreeCollection.test.ts
- packages/related-table/src/Hooks/useTreeCollection.ts
- packages/related-table/src/Model/TreeNode.ts
- packages/source-iotsitewise/src/asset-modules/sitewise/requestProcessor.spec.ts
- packages/source-iotsitewise/src/asset-modules/sitewise/requestProcessor.ts
- yarn.lock
Introduce `expanded` feature to `iot-resource-explorer`. When true, recursively expands nodes that have children.
> feat: expand children in resource explorer

- packages/source-iotsitewise/src/initialize.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/client.ts
- packages/source-iotsitewise/src/time-series-data/data-source.ts
- packages/source-iotsitewise/src/time-series-data/types.ts
The ideal batch duration (timeframe in which requests are batched) observed by the sitewise source is highly dependent on factors such as dashboard configuration, widget configuration, browser performance, and latency. Batching by a single browser tick is fine as a default behaviour but needs to be customizable for the use-case.
This change exposes batchDuration as a setting on the sitewise source (and thus on app kit initialize). batchDuration accepts a numeric value representing the batching window in ms.
Documentation to follow.
> expose batchDuration as a configurable setting on sitewise source

- package.json
- yarn.lock
The @types/react version has been locked to 18, but the code is not compatible with it. So specify the version to be 17.
> specify react types package version to be 17

- .github/workflows/run-tests.yml
- packages/dashboard/__mocks__/moduleMock.js
- packages/dashboard/cypress.json
- packages/dashboard/cypress/fixtures/example.json
- packages/dashboard/cypress/plugins/index.js
- packages/dashboard/cypress/support/commands.js
- packages/dashboard/cypress/support/component-index.html
- packages/dashboard/cypress/support/component.js
- packages/dashboard/cypress/tsconfig.json
- packages/dashboard/package-lock.json
- packages/dashboard/package.json
- packages/dashboard/src/components.d.ts
- packages/dashboard/src/components/iot-dashboard/iot-dashboard.css
- packages/dashboard/src/components/iot-dashboard/iot-dashboard.tsx
- packages/dashboard/src/integration/iot-dashboard.spec.component.ts
- packages/dashboard/stencil.config.ts
- packages/dashboard/tsconfig.json
- yarn.lock
- Added cypress based component, in a manner matching that done in the `packages/components` module
- Made `onDashboardConfigurationChange` optional
- Added a plugin for making drag-and-drop functionality easier to test in cypress
- Provide a simple integration test example
I had some issues getting module resolution working in the cypress test suites, which is the reason the `renderDashboard` method is not in a separate file. This should be refactored in the future.
> dashboard component integration testing

- packages/core/src/index.ts
- packages/table/global.d.ts
- packages/table/jest.config.js
- packages/table/package.json
- packages/table/src/index.ts
- packages/table/src/table/index.tsx
- packages/table/src/utils/iconUtilis.spec.ts
- packages/table/src/utils/iconUtils.tsx
- packages/table/src/utils/index.ts
- packages/table/src/utils/spinner.spec.tsx
- packages/table/src/utils/spinner.tsx
- packages/table/src/utils/tableHelpers.spec.ts
- packages/table/src/utils/tableHelpers.tsx
- packages/table/src/utils/types.ts
- packages/table/tsconfig.json
- Add new Table component 
using AWS-UI Table component plus useCollectionHook to support property filtering & sorting.
- add helpers
iconUtilis and tests - copied from Synchro-charts with modifications.
spinner and tests - copied from Synchro-charts with modifications.
tableHelpers and tests - get default configs for table component and hooks.
TODO:
- add tests of Table component for
thresholds
alarms
- WIP: add the wrapper for the new component in @iot-app-kit/component
> Add new Table component

- docs/development.md
- package.json
There's been confusion around how to build and run iot-app-kit. The development docs instructed to use `lerna bootstrap` to install dependencies, but after doing so packages weren't being built. I did some investigation and found the following:
- `lerna bootstrap` installs dependencies, but won't build packages by design
- any lerna version doesn't currently work with yarn v2+
- the development docs are out of date, not including any sort of build step between installing dependencies and running the app locally.
To help clarify what is required to build iot-app-kit and the steps to get started, I've changed the following:
- A new bootstrap script was added
- `engines` are now specified in `package.json` to warn people when they try to run iot-app-kit with incompatible node/yarn versions
- …
> Fix: Development Quick Start Docs/Scripts

- packages/dashboard/src/components.d.ts
- packages/dashboard/src/components/iot-dashboard/iot-selection-box/iot-selection-box-anchor.css
- packages/dashboard/src/components/iot-resizable-panes/iot-resizable-panes.css
- packages/dashboard/src/components/iot-resizable-panes/iot-resizable-panes.spec.ts
- packages/dashboard/src/components/iot-resizable-panes/iot-resizable-panes.tsx
- packages/dashboard/src/testing/testing-ground/testing-ground.css
- packages/dashboard/src/testing/testing-ground/testing-ground.tsx
This PR adds a new component, `<resizable-panes/>`. It consists of a left, center, and right pane, with handles between them that dynamically change the widths of the panes when dragged left or right, similar to a library like [Split.js](https://split.js.org/).
This is a basic first step, and needs to be followed up by several additional changes adding enhancements and covering anticipated edge cases, detailed below.
- We will need to expand the mouse event listeners here to touch event listeners as well. [This is coming shortly in a follow-up PR.]
- We will need to save the state of the pane widths in sessionStorage so they can persist across page refreshes. [This is coming shortly in a follow-up PR.]
- We need to add a window resize listener that recalculates the pane widths when the …
> Basic resizable panes for dashboard

- packages/dashboard/src/components/iot-resizable-panes/iot-resizable-panes.css
- packages/dashboard/src/components/iot-resizable-panes/iot-resizable-panes.tsx
This PR adds two followup changes from #162, the resizable pane PR:
1. It persists pane position in sessionStorage, so the page can be refreshed and they will appear to not move at all -- it 'just works'.
2. It adds a window resize listener that will, if the resize would cause the panes to collide with one another, scales them down proportionally, as if they are being 'squished together'. This is necessary to prevent situations where one pane's handle is not grabbable due to panes overlapping.
https://github.com/awslabs/iot-app-kit/runs/7616444204?check_suite_focus=true
> Persist resizable pane position in sessionStorage and prevent collisions on window resize

- packages/dashboard/src/components/iot-dashboard/iot-dashboard-internal.tsx
- packages/dashboard/src/components/iot-dashboard/iot-dashboard.tsx
- packages/dashboard/src/dashboard-actions/dashboardReducer.ts
- packages/dashboard/src/dashboard-actions/move.ts
- packages/dashboard/src/types.ts
Move managing the previous widget position into dashboard state instead of the internal dashboard
> fix(dashboard):Remove previous position from internal dashboard

- packages/components/package.json
- packages/core/package.json
- packages/source-iotsitewise/package.json
- yarn.lock
Fixes https://github.com/awslabs/iot-app-kit/issues/144.
The bug was called by `dateRangeChange` event incorrectly being emitted when a chart viewport updates while in live mode. This bug was fixed in the syncho charts repository in [this pull request](https://github.com/awslabs/synchro-charts/pull/155).
This pull request bumps the syncho-charts/core version from v5 to v6, which fixes the default refresh rate issue.
> Fix #144 - Default Refresh Rate

- packages/dashboard/src/dashboard-actions/actions.ts
- packages/dashboard/src/dashboard-actions/dashboardReducer.ts
- packages/dashboard/src/dashboard-actions/redo.spec.ts
- packages/dashboard/src/dashboard-actions/redo.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverseMove.spec.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverseMove.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverseResize.ts
- packages/dashboard/src/dashboard-actions/undo.spec.ts
- packages/dashboard/src/dashboard-actions/undo.ts
- packages/dashboard/src/integration/iot-dashboard.spec.component.ts
In a prior PR, I removed the 'widgetId' fields from the move and resize actions. This became a significant problem when trying to undo/redo these actions. The undo/redo would succeed when the widget was still selected, however it would fail if they were not selected. I added back the widgetId field so they can be undoable even when not selected.
> fix(dashboard): Fix bug with undo move/resize

- docs/CodingGuidelines.md
- docs/WhatIs.md
- docs/development.md
Add coding guidelines and other minor documentation fixes.
Made the branding more consistently 'IoT App Kit' (As opposed to IoT Application Kit)
Revision 1: Fixed some minor formatting issues and added more examples in the guidelines
Revision 2: Addressed comments
> docs: Add coding guidelines

- packages/dashboard/src/dashboard-actions/dashboardReducer.ts
- packages/dashboard/src/dashboard-actions/updateDashboardState.spec.ts
- packages/dashboard/src/dashboard-actions/updateDashboardState.ts
Completes https://github.com/awslabs/iot-app-kit/pull/205/files. Not able to update through the original pull request since the source branch is on a fork of app-kit that can't be pushed to.
Creates a separate file for updating the dashboard.
> Create Separate File for Dashboard State Update

- packages/components/src/components.d.ts
- packages/components/src/components/iot-table/iot-react-table.tsx
- packages/components/src/components/iot-table/iot-table.tsx
- packages/table/src/table/index.tsx
- packages/table/src/utils/createCellItem.spec.ts
- packages/table/src/utils/createCellItem.ts
- packages/table/src/utils/createTableItems.spec.ts
- packages/table/src/utils/createTableItems.ts
- packages/table/src/utils/index.ts
- packages/table/src/utils/messages.ts
- packages/table/src/utils/tableHelpers.tsx
- packages/table/src/utils/types.ts
User can override propertyFiltering labels and loading texts by providing messageOverrrides object to the table.
> Add messageOverrrides for table.

- packages/table/babel.config.cjs
- packages/table/jest.config.js
- packages/table/package.json
- packages/table/src/table/index.spec.tsx
- packages/table/src/utils/types.ts
- yarn.lock
- render correct data based on different viewports
- render spinner when a datastream is loading
- render error icon and message when a datastream in error state
- render icon and apply styles when it breaches thresholds
Also configure babel to allow jest test with AWSUI. Ref: https://charles-stover.medium.com/testing-aws-ui-components-with-jest-6983a7f8e985
> add tests for table

- CHANGELOG.md
- packages/components/CHANGELOG.md
- packages/table/jest.config.js
- Update change logs to clearify breaking changes.
- Remove unnecessary jest configuration 
- 'd3-array' map is no longer needed because babel is used in Jest transformation (https://github.com/awslabs/iot-app-kit/pull/215).
> Update docs. Remove unnecessary jest configuration.

- packages/components/package.json
- packages/core/src/__mocks__/data-source.ts
- packages/core/src/data-module/TimeSeriesDataModule.spec.ts
- packages/core/src/data-module/TimeSeriesDataModule.ts
- packages/core/src/data-module/data-cache/caching/caching.spec.ts
- packages/core/src/data-module/data-source-store/dataSourceStore.spec.ts
- packages/core/src/data-module/data-source-store/dataSourceStore.ts
- packages/core/src/data-module/subscription-store/subscriptionStore.spec.ts
- packages/core/src/data-module/subscription-store/subscriptionStore.ts
- packages/core/src/data-module/types.ts
- packages/core/src/index.ts
- packages/source-iotsitewise/src/component-session.ts
- packages/source-iotsitewise/src/initialize.ts
- packages/source-iotsitewise/src/sessions.ts
- packages/source-iotsitewise/src/time-series-data/data-source.spec.ts
- packages/source-iotsitewise/src/time-series-data/data-source.ts
- packages/source-iotsitewise/src/time-series-data/provider.spec.ts
- packages/source-iotsitewise/src/time-series-data/subscribeToTimeSeriesData.spec.ts
- packages/source-iotsitewise/src/time-series-data/subscribeToTimeSeriesData.ts
- yarn.lock
- Add `meta` field to dataStream type to support sources providing meta information into data sources. This will help support alarm feature within the package `@iot-app-kit/source-twinmaker` which is a work in progress. Related commit in Synchro Charts: https://github.com/awslabs/synchro-charts/commit/e3ff0e10c14b45bdd4affffb08bcdd34b39f2aaf
- BREAKING CHANGE: Refactored export from `@iot-app-kit/core` IoTAppKitDataModule to be named TimeSeriesDataModule, and removed the concept of multiple data sources per time series data module
- Remove the `name` fields in queries internally, since it is no longer necessary as each time series data module only maps to one data source, as opposed to a single repository of all time series data sources.
- Upgrade Synchro Charts to latest version, 6.0.1 …
> feat(core)!: Refactor time series data module / add meta field to data source

- packages/dashboard/src/components/iot-dashboard/iot-dashboard-internal.css
- packages/dashboard/src/components/iot-dashboard/iot-dashboard-internal.tsx
- packages/dashboard/src/dashboard-actions/paste.spec.ts
- packages/dashboard/src/dashboard-actions/paste.ts
- packages/dashboard/src/integration/iot-dashboard.spec.component.ts
- packages/dashboard/src/util/select.ts
This PR addresses 3 bugs.
1. The selection box not disappearing on completing the selection action. This was because the gesture was not reactive.
2. Clicking on an element selects all elements that overlap that pixel (not the top most element). To fix this we can sort by the z index and select the highest one in the selection.
3. Paste at position with a selection pastes all the widgets at that position (not the selection at that position). To fix this we can offset the copy group by the difference of paste position.
> fix(dashboard): fix selection bug 

- packages/dashboard/src/dashboard-actions/actions.ts
- packages/dashboard/src/dashboard-actions/changeLayer.spec.ts
- packages/dashboard/src/dashboard-actions/changeLayer.ts
- packages/dashboard/src/dashboard-actions/dashboardReducer.ts
- packages/dashboard/src/dashboard-actions/redo.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverseBringToFront.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverseSendToBack.spec.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverseSendToBack.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverstBringToFront.spec.ts
- packages/dashboard/src/dashboard-actions/undo.spec.ts
- packages/dashboard/src/dashboard-actions/undo.ts
Bring to front and Send to back did not have an implementation for undo / redo. This PR adds those implementations.
> feat(dashboard): add undo redo for bring to front/ send to back 

- package.json
- packages/core/src/__mocks__/data-source.ts
- packages/core/src/data-module/TimeSeriesDataModule.spec.ts
- packages/core/src/data-module/TimeSeriesDataModule.ts
- packages/core/src/data-module/data-source-store/dataSourceStore.spec.ts
- packages/core/src/data-module/data-source-store/dataSourceStore.ts
- packages/core/src/data-module/subscription-store/subscriptionStore.spec.ts
- packages/core/src/data-module/subscription-store/subscriptionStore.ts
- packages/core/src/data-module/types.ts
- packages/related-table/src/Hooks/useTreeCollection.ts
- packages/related-table/src/RelatedTable/RelatedTable.test.tsx
- packages/related-table/src/utils/build.ts
- packages/related-table/src/utils/cleanup.ts
- packages/related-table/src/utils/sort.ts
- packages/related-table/src/utils/utils.test.ts
- packages/source-iotsitewise/src/time-series-data/data-source.spec.ts
- packages/source-iotsitewise/src/time-series-data/data-source.ts
- packages/source-iotsitewise/src/time-series-data/provider.spec.ts
- packages/source-iotsitewise/src/time-series-data/subscribeToTimeSeriesData.spec.ts
Refactor the core TimeSeriesDataModule to make `getRequestsFromQueries` be async. This allows data sources to be implemented where network calls or other async processes are required to interpret a query. This supports TwinMaker, which requires additional network requests to determine the underlying entity structure from a query, however this is useful more generically.
This change to an async getRequestFromQueries is a *BREAKING CHANGE*. To migrate, a data source created utilizing the TimeSeriesDataModule must refactor `getRequestFromQueries` to return a promise.
Additionally resolved more eslint warnings.
> feat(core,source-iotsitewise)!: Async getRequestsFromQueries

- .github/PULL_REQUEST_TEMPLATE.md
Remove necessary test section from template. Tests are ran in the CI, and the results are automatically posted already. having sections of a template that everyone ignores, trains people to in general ignore the PR template which is bad.
> chore: remove unnecessary template section

- package.json
- packages/core/src/__mocks__/data-source.ts
- packages/core/src/data-module/TimeSeriesDataModule.spec.ts
- packages/core/src/data-module/TimeSeriesDataModule.ts
- packages/core/src/data-module/data-cache/caching/caching.ts
- packages/core/src/data-module/types.ts
Append `meta` field to `RequestInformation` type. This allows a data source to specify additional instructions on how it wants to ultimately request data. This is being added to support the TwinMaker data source in being able to look at a query, and construct request Informations which specify it's componentType.
> feat(core): Append meta field to RequestInformation type

- .github/workflows/npm-publish.yml
- package.json
After switching to NPM workspaces (https://github.com/awslabs/iot-app-kit/pull/231) the Github Action for publishing to NPM started to fail because the behaviour of `npm publish -ws` is different from `lerna publish`. Lerna checks the existing version in the registry before publishing but `npm publish` publishes optimistically, which causes the action to 403 if the version was not incremented in the latest push and therefore already exists in NPM.
This change leverages https://github.com/marketplace/actions/npm-publish with `check-version` to mimic the old Lerna behaviour.
I tested this using Docker and https://github.com/nektos/act.
> build: npm publish with npm workspaces

- docs/CodingGuidelines.md
- package.json
Add packages section to Coding Guidelines.
> docs: add documentation for publishing new packages

- packages/dashboard/src/components/iot-dashboard/getDashboardPosition.ts
- packages/dashboard/src/components/iot-dashboard/iot-context-menu/iot-dashboard-context-menu.tsx
- packages/dashboard/src/components/iot-dashboard/iot-dashboard.tsx
- packages/dashboard/src/decorators/events.ts
- packages/dashboard/src/decorators/press.ts
- packages/dashboard/src/integration/iot-dashboard-context-menu.spec.component.ts
- packages/dashboard/src/util/distance.spec.ts
- packages/dashboard/src/util/distance.ts
This adds support for the context menu on a touch device. The trigger is a long press (500ms) on the dashboard grid area. The implementation uses a custom decorator to register the event listeners.
> fix(dashboard): add touch support for context menu

- packages/core/src/viewportManager/viewportManager.spec.ts
- packages/core/src/viewportManager/viewportManager.ts
Introduce a `viewportManager` to `@iot-app-kit/core`.
The viewportManager handles broadcasting updates to a group of subscribers to a viewport group.
This will be the utility used to allow IoT App Kit components to "synchronize" their viewports. An example of what this means can be seen at https://synchrocharts.com/#/Features/Synchronization. If you double click on one of the 3 line charts, all 3 line charts will zoom in, since they are all part of the same viewport group.
- write docs
- export from library
- refactor SynchroCharts to utilize `viewportManager`
- utilize with other IoT App Kit components that are not SynchroCharts based.
> feat(core): Add viewportManager to orchestrate viewport syncing within groups

- packages/components/stencil.config.ts
Github action provides a "2-core CPU" runner for tests. Stencil uses 8 workers by default, which might cause some issues. So we are reducing the max workers limits to 2. 
And this change does not increase the execution time for local testing. It even reduces the total running time. 
2 workers:
```
> time npm run test
> @iot-app-kit/components@2.1.0 test
> stencil test --spec
[02:46.3]  @stencil/core
[02:46.5]  v2.17.4 🐞
[ WARN  ]  Build Warn
dist-custom-elements-bundle is deprecated and will be removed in a future major version release. Use
"dist-custom-elements" instead. If "dist-custom-elements" does not meet your needs, please add a comment to
https://github.com/ionic-team/stencil/issues/3136.
[02:46.7]  testing spec files
[02:46.7]  jest args: --spec --max-workers=2
...
Test Suites: …
```
> chore(components): reduce concurrent workers in testing

- examples/react-app/README.md
- examples/react-app/hot-link.js
- examples/react-app/link.sh
- examples/react-app/package-lock.json
- examples/react-app/package.json
- examples/react-app/src/components/SceneViewer.tsx
- examples/react-app/src/components/VideoPlayer.tsx
- examples/react-app/src/components/componentsTab.tsx
1. Simplify linking process via. bash script.
2. Add `hot-link` convenience utility that automatically relinks, rebuilds, and restarts the dev server.
> chore(examples): easier linking for iot-app-kit packages

- packages/react-components/src/video-player/videoPlayer.spec.tsx
- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/three-fiber/EditorTransformControls.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/__tests__/EntityGroup.spec.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/EnvironmentModelComponent.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/__tests__/EnvironmentModelComponent.spec.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/__tests__/__snapshots__/EnvironmentModelComponent.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/__tests__/__snapshots__/index.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/__tests__/index.spec.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/index.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/nodeUtils.ts
- packages/scene-composer/stories/SceneComposer.stories.tsx
- packages/scene-composer/tests/components/panels/SceneNodeInspectorPanel.spec.tsx
- packages/scene-composer/tests/components/three-fiber/EditorTransformControls.spec.tsx
- packages/scene-composer/tests/components/toolbars/floatingToolbar/items/AddObjectMenu.spec.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Add the EnvironmentModelComponent to adi in possible updates for loading of model later as well as offload responsibility from ModelRefComponent Adds a menu item to the add object menu to add at most 1 environment model Removes Sub model Tree from Environment models
Add more restrictions to the Environment nodes.
- Environment Nodes cannot have children
- Environment Nodes have no Transform Editor
- Environment Nodes cannot have Transform controls
- Environment Nodes cannot have a model shader
- Environment controls cannot have children
Add tests
> feat(EnvironmentModel): Adding support for environment overlay

- packages/scene-composer/README.md
Removes `ada` reference & adds link to React Storybook docs. 
> Fix: Updating documentation for Storybook

- packages/scene-composer/src/components/panels/TopBar.tsx
- packages/scene-composer/tests/components/panels/TopBar.spec.tsx
- packages/scene-composer/tests/components/panels/__snapshots__/TopBar.spec.tsx.snap
This will improve the following:
1. No longer require a feature flag so no special build of grafana is required once feature ships
2. If there are no cameras we don't show the UI as it is confusing
3. This restores not showing the View Options if there are no Motion Indicators
4. Hides the top bar if neither exist for more screen real estate
> chore(CameraView): Removes TopBar Feature Flag Dependency for Camera View

- packages/core/src/common/viewport.ts
- packages/react-components/src/video-player/videoPlayer.spec.tsx
- packages/react-components/src/video-player/videoPlayer.tsx
Due to a bug in `viewportStartDate` from `@iot-app-kit/core`, `propertiesNotChanged` might return `false` for unchanged properties. Add `currentTime` param `viewportStartDate` to fix this issue.
Basically `viewportStartDate` uses `Date.now()` when the viewport passed in is a duration (no `start`). And function `propertiesNotChanged` compares viewports as following:
```
viewportStartDate(this.props.viewport).getTime() === viewportStartDate(prevProps.viewport).getTime() 
```
Usually `viewportStartDate(this.props.viewport).getTime()` and `viewportStartDate(prevProps.viewport).getTime()` should return the same value for the same viewport. However, if there’s some async ops or it is running in a slow machine (like Github actions runner), the return value can be different - since `Date.now()` …
> test(react-components, VideoPlayer): fix flaky test for videoPlayer

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/three-fiber/EditorTransformControls.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/ObjectItemGroup.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/stories/SceneComposer.stories.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
In an effort to prevent the release of resizable tags outright we lock it behind a feature flag.
Flag disabled features:
* Scale row is removed for Tag component in inspector
* Editor Transform Controls will switch back to translate when switching to Tag
* Scale button is disabled in floating toolbar with tag selected
Flag enabled:
* Tags can be resized via inspector
* Tags can be resized via transform controls
> chore(TagResize): Add flag to resizable tags

- packages/scene-composer/src/SceneViewer.spec.tsx
- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/three-fiber/EditorCamera.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/GLTFModelComponent.tsx
- packages/scene-composer/src/interfaces/sceneComposerInternal.ts
- packages/scene-composer/stories/SceneViewer.stories.tsx
- packages/scene-composer/tests/StateManager.spec.tsx
when selectedDataBinding is set before the scene is loaded, the `findSceneNodeRefBy` function will always find nothing (because nodes are not loaded yet) and then set selected node to undefined.
setting camera target before components rendered will not work as expected because the bounding box calculated will be incorrect.
> fix(composer): selectedDataBinding not able to update selected node

- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
`handleAddAnchor` is not listening to the change of `getRefForParenting` which cause the value of new node's `parentRef` to always be the same, so the tag is always attached to root.
https://user-images.githubusercontent.com/9315598/196309048-ddf49881-5f19-4264-bba8-a774bd918c1c.mov
> fix(composer): fix adding tag always attached to root

- packages/scene-composer/package.json
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/tests/augmentations/components/three-fiber/anchor/AnchorWidget.spec.tsx
With the effort to update enhanced editing one of the initial ideas was to use a targetRef. This is no longer something we did at the end but this file remained intact.
To fix the regression the targetRef changes needed to be undone
Also changes the test such that the previous regression would have failed
> fix: Fix the tag scaling with parent scale regression

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/ComponentTypeIcon.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneNodeLabel.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/SceneHierarchyTreeItem.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/SceneNodeLabel.specs.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneHierarchyTreeItem.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneNodeLabel.specs.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/model/ISceneHierarchyNode.ts
- Reduces the number of rerenders significantly in the SceneHierarchy Tree view whenever actions like activating, selecting and removing happen
- Removes redundent On2 loop when computing children for a scene hierarchy node
- Cleans up some new responsibilities for TreeItem and Tree Label that were added in the wrong places.
> fix(SceneHierarchyPerformance): SceneHierarchy Tree Performance

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/scene-components/CameraComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/CameraComponentEditor.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Provide a check for the minimum FOV value and display an error message while also not triggering a settings update
> fix(CameraView): Minimum FOV check introduced

- packages/scene-composer/src/components/panels/scene-components/CameraComponentEditor.tsx
Camera zoom could be changed to less than 1 but the inspector UI did not reflect the changes. Fixed the missing negative sign to determine if the value index existed
> fix: Fix the camera zoom field locked to 1 or greater

- packages/scene-composer/src/components/panels/scene-components/CameraComponentEditor.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Adds a popup success message when clicking the Fix to camera view button in the camera component inspector UI
> fix: Add success popup message when updating camera location

- packages/scene-composer/src/components/three-fiber/ColorOverlayComponent/index.tsx
- packages/scene-composer/src/hooks/useMaterialEffect.ts
model shader material color not restore properly because the original object passed into useMaterial is undefined
before
https://user-images.githubusercontent.com/9315598/197277320-3a43ff43-c74e-4965-abd9-d5d83d9d70de.mov
after
https://user-images.githubusercontent.com/9315598/197277380-f43cc802-894e-4aac-944a-9ee638281dea.mov
> fix(composer): fix model shader material color restore

- package.json
Add missing declaration of the `dashboard` package in the npm workspace configuration.
> fix: add dashboard package to the npm workspace config

- .gitignore
Ignore word docs by default, since we use markdown for documentation.
> chore(IgnoreWordDocs): Ignore Word docs by default

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- fix the issue where only root nodes can be searched
- only show the matching nodes in a flat list, not their children
- gate sub-model feature with flag
- show SubModelTree for ModelRef component and fix duplicated trees when sub model is promoted to a node
search issue:
https://user-images.githubusercontent.com/9315598/199861938-7d02f86d-83d8-4029-a0f8-80f2d30256e4.mov
search fix:
https://user-images.githubusercontent.com/9315598/199862110-74d44955-e29c-4945-80eb-0519a830c8e4.mov
sub-model issue:
https://user-images.githubusercontent.com/9315598/199862147-eb260182-0119-4aa0-9c38-20eb6cbf4ba3.mov
sub-model fix:
https://user-images.githubusercontent.com/9315598/199862174-4c73a1c3-f544-435a-a673-688a84b6a7b3.mov …
> fix(composer): submodel and hierarchy search fix

- packages/scene-composer/src/utils/dataStreamUtils.spec.ts
- packages/scene-composer/src/utils/dataStreamUtils.ts
- packages/scene-composer/tests/data/mockDataStreams.ts
fix the issue when the boolean data in the dataStream is an actual boolean (instead of string 'true' / 'false'), the data will always be converted to false
> fix(composer): boolean data always converted to false

- package.json
@sheilaXu identified an issue where `"d3-color-1-fix"` is sometimes not properly referenced in package-lock.json. I tested with different versions of npm and verified that this is an issue with versions below 8.7, likely due to [this npm bug](https://github.com/npm/cli/issues/4687) with setting overrides in package-lock.
Here I am bumping the minimum version of npm for the package to 8.7, which ensures consistent package-lock generation.
> fix: require npm >=8.7.0 to fix yarn.lock issue with d3-color-1-fix

- package-lock.json
- packages/scene-composer/src/utils/objectThreeUtils.ts
There is a race condition that requires some error handling. We have checks for existence but given the issue might not be that the object is falsey we perform a catch to provide further debug information
> Catch to prevent and debug remove from parent race condition

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/three-fiber/EditorTransformControls.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/stories/SceneComposer.stories.tsx
Due to issues with Multiple World spaces and/or coordinates for Sub Models preventing the ability to adjust the sub-model position ensures that child objects will continue to work. We hide the ability to edit a Sub-model's position behind a new feature flag `SubModelMovement`
> Prevent Sub-Models from being moved without a feature flag

- packages/scene-composer/src/components/three-fiber/ColorOverlayComponent/index.tsx
Opacity filter was incorrectly showing objects when opacity was set to 0. This was a bug in the boolean logic to check if it should apply alpha or not.
> Opacity filter zero

- packages/scene-composer/src/enhancers/draggable.scss
Just inlines the icon for now, but we may need to look at a better way of handling SVGs in CSS.
> fix(DragHandleIcon): Drag Handle icon not showing up without special webpack config

- packages/scene-composer/package.json
- packages/scene-composer/src/hooks/useEditorHelper.ts
- packages/scene-composer/tests/hooks/useEditorHelper.spec.tsx
1. Reverts the previous change to parent to an dobject as this causes an error on delete thanks to React Three Fiber based removal
2. Helper checks each frame whether or not it should remain visible based on the ancestry of the light
`useFrame` gets a bad wrap as the boogeyman but this look up the ancestor tree should not cause performance issues but maintains a simplicity and code cleanliness to get around this issue. Typically only a complex set of calculations would be problematic but most 3D software performs operations every frame. Should we see performance issues we can revisit the implementation
> fix(composer): Fixes the light helper delete 

- packages/scene-composer/package.json
- packages/scene-composer/src/components/three-fiber/CameraComponent/__tests__/CameraComponent.spec.tsx
- packages/scene-composer/src/components/three-fiber/CameraComponent/__tests__/__snapshots__/CameraComponent.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/CameraComponent/index.tsx
- packages/scene-composer/src/hooks/useEditorHelper.ts
- packages/scene-composer/src/utils/objectThreeUtils.ts
- packages/scene-composer/tests/utils/objectThreeUtils.spec.ts
The e.removeFromParent issue seems to be unavoidable so we needed to change what getSafeBoundingBox provides and just avoid having the helpers as children of the root node in general. This reverts to original implementations and uses the recently updated useEditorHelper
> fix(composer): Fix e.removeFromParent and camera focus

- .github/workflows/npm-publish-alpha.yml
Publish dashboard alpha npm package from `feature-dashboard-alpha`
> feat(github): add github workflow to publish alpha dashboard

- .github/workflows/npm-publish-alpha.yml
Add github publish action for publishing dashboard as an alpha version.
> feat(github): add dashboard publish action

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/SubModelTree.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTree.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/index.tsx
- packages/scene-composer/tests/scenes/scene_1.json
Sub Models previously relied on `appendSceneNodeInternal` preventing.a duplicate based purely on the reference Id and the Object3D.id of the original sub model. The problem is both ThreeJS and our Ids are not persisted by design. 
The solution was to add a property specifically to sub models that reference the "ID" of the sub model object. The only persisted case here is the name and changing that within the model in something like Blender is still a way to mess this up however I do believe unless you specifically name objects the most 3D applications will provide a new name. We then check all nodes in the scene for the property matching the name. If we find it we do not add the sub model to the scene as was occurring when within the same session. …
> fix(composer): Fixes the duplication of sub models

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/SceneHierarchyTreeItem.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneHierarchyTreeItem.spec.tsx.snap
Restores previous logic to enable drag-&-drop feature. 
> fix(composer): Restores drag-&-drop functionality in Scene Hierarchy

- package.json
Yet another override fix. There are several different ways to reference overrides: nested objects, various string formats, etc. Apparently they are not all equivalent - the `"package": "other-package"` syntax is supported in some but not all circumstances; as it will successfully apply the override if you clone and install but not if you clone and delete package-lock and then install. Switching to `"package": "npm:other-package@^1.0.0"` fixes this issue.
> fix: fix syntax not supported in all circumstances for package.json override

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTree.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/index.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
- packages/scene-composer/src/interfaces/feature.ts
Forces all sub model children to be physically parented to it's parent. This makes it so that children don't move with the sub model but the render correctly. There is a feature flag to maintain previous implementations so that we can fix later
> fix(composer): SubModel child fix

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/SubModelTree.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTree.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/index.tsx
It was my misunderstanding that we needed to limit multiple instances of the sub models on a per ModelRef basis. This fixes that and also removes the unnecessary property
> fix(composer): One instance of sub models allowed per instance of the model

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
Updating import for `updateSceneNodeInternal` to come from `useSceneDocument` to achieve persist on refresh. 
> fix(composer): Fix to persist drag/drop actions after refresh

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
Reordering nodes was setting parent ref correctly, but wasn't updating the parent's childRefs.
> fix(Reparenting): Fix reparenting nodes

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
Adjusting logic around moving scene nodes to remove errors from duplicate keys. 
> fix(composer): Adjusting logic for reparenting scene nodes

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/stories/SceneComposer.stories.tsx
fix the scene crash when:
1. drag a root node and drop it as a child of another node
2. delete the node moved
3. reload the scene and see crash (null was saved as one of the root node index)
> fix(composer): drag root node crashes scene

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
Fix to unsubscribe in `useEffect` that was triggering error on drag/drop. Includes fix for type safety in `move` function.
> fix(composer): Fix for useEffect error

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
the multiple `updateSceneNodeInternal` calls seem to have conflicts and cause state update event to be missed. since `childRefs` is used during serialization, it's more important. so update it first. 
The long term solution should be combining them to single call.
> fix(composer): reorder doesn't persist after reloading

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/SubModelTree.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTree.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/index.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/GLTFModelComponent.tsx
Named objects under unnamed parents were not showing up in the SubModel Tree.
Previously, we were making some assumptions that named items would have named parents up to the root node, but in some cases this isn't true.
> fix(SubModelHidingChildren): Unnamed children should be skipped not omitted

- .github/workflows/run-tests.yml
Specify node version to 16 to fix the following issue during GH auto test workflow.
```
Run yarn install --frozen-lockfile
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 1[6](https://github.com/awslabs/iot-app-kit/actions/runs/3516513445/jobs/5893168217#step:4:7) || 1[7](https://github.com/awslabs/iot-app-kit/actions/runs/3516513445/jobs/5893168217#step:4:8)". Got "1[8](https://github.com/awslabs/iot-app-kit/actions/runs/3516513445/jobs/5893168217#step:4:9).12.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process …
```
> chore: specify node version to 16

- docs/AWSIoTSiteWiseSource.md
- docs/BarChart.md
- docs/GettingStarted.md
- docs/KPI.md
- docs/LineChart.md
- docs/ResourceExplorer.md
- docs/ScatterChart.md
- docs/StatusGrid.md
- docs/StatusTimeline.md
- docs/Table.md
Many code blocks in our docs have an incorrect param for `initialize`, resulting in errors and the TS complaint `Object literal may only specify known properties, but 'iotsitewiseClient' does not exist in type 'SiteWiseDataSourceInitInputs'. Did you mean to write 'iotSiteWiseClient'?`. The correct casing is [here](https://github.com/awslabs/iot-app-kit/blob/main/packages/source-iotsitewise/src/initialize.ts#L25). This PR fixes all instances of this issue.
> docs: fix initialize param casing

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/scene-components/ValueDataBindingBuilder.tsx
entityId data binding not rendered because the `builderState` is not updated right after `setBuilderState` call
> fix(composer): entityId data binding not rendered

- .github/workflows/publish-storybook.yml
- packages/scene-composer/README.md
Adds a github action workflow that allows a reviewer to download the prebuilt Storybook site for Scene composer at the current revision.
You can download these artifacts from the workflow, and using a local static site tool like `httpserver` run the storybook website and play with new features before approving the CR, without having to check it out and run it locally.
> chore(PublishStorybook): Publish Storybook Site to build artifacts

- packages/dashboard/jest.config.ts
- packages/dashboard/package.json
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/side-panel/index.css
- packages/dashboard/src/components/side-panel/index.tsx
- packages/dashboard/src/components/side-panel/shared/expandableSectionHeader.tsx
- packages/dashboard/src/components/side-panel/shared/styles.css
- packages/dashboard/src/components/side-panel/sub-components/chart-settings.tsx
- packages/dashboard/src/components/side-panel/sub-components/data-settings.tsx
- packages/dashboard/src/components/side-panel/sub-components/properties-alarms-section.tsx
- packages/dashboard/src/components/side-panel/sub-components/thresholds-section.tsx
- import @cloudscape-design/components
- set up expandable section 
- add a shared components `ExpandableSectionHeader` to allow use to handle actions that targets to the whole section. Eg. add a new threshold.
- fix jest transforms with @swc/jest
> feat(dashboard): set up basic layout for side panel

- packages/react-components/src/video-player/customVideoProgressBar.spec.tsx
- packages/react-components/src/video-player/utils/dateRangeUtils.spec.tsx
- packages/react-components/src/video-player/utils/videoProgressUtils.spec.tsx
Create new `Date` object at runtime could lead to inconsistent values in test. For example :
```
packages/react-components/src/video-player/utils/dateTimeUtils.spec.tsx
---
it('should format the Date to DateTime value', () => {
const rawDate = new Date(1665583620000 + new Date().getTimezoneOffset() * 60000);
expect(getFormattedDateTime(rawDate)).toEqual(`10/12\n14:07:00`);
});
---
Error: expect(received).toEqual(expected) // deep equality
- Expected  - 1
+ Received  + 1
10/12
- 14:07:00
+ 15:07:00
```
The issue is related to Daylight saving. The hard coded value 1665583620000 is `Wed Oct 12 2022 10:07:00 GMT-0400` (Eastern Daylight Time) but currently we are in standard time.
```
new Date().getTimezoneOffset() // -> 300
new Date(1665583620000).getTimezoneOffset() //-> 240 
```
This change …
> fix(video-player): use static timestamps in tests

- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/utils/sceneDocumentSnapshotCreator.ts
Checking if document is changed to determine if onSceneUpdated should be triggered, because of issues:
- SnapToFloor doesn't save position change as it's transient operation
- In weird case when multiple actions happening at the same time, the store update seems to be batched/lost which could cause the UPDATE_DOCUMENT operation to be missed. 
The console side is debouncing the save scene function in onSceneUpdated callback, so there won't be extra save scene API call.
To run the storybook build locally, you …
> fix(composer): scene change is sometimes not saved

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/store/slices/EditorStateSlice.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/tests/store/slices/EditorStateSlice.spec.tsx
- packages/scene-composer/tests/store/slices/SceneDocumentSlice.spec.ts
Refactor `move` code to fix
- multiple update node actions cause multiple undo/redo states
- drop to same parent will have duplicate child
- drop to and from root node (still need https://github.com/awslabs/iot-app-kit/pull/390/files#diff-fff361d200b3777ce4c1ecd27e04425c2c1e3203ef65799e4217d182366cf7e0 to be able to drop to root from tree)
```
httpserver
``` …
> fix(composer): reorder to same parent duplicates child

- packages/dashboard/src/components/sidePanel/index.tsx
- packages/dashboard/src/components/sidePanel/sections/chartSettings.tsx
- packages/dashboard/src/components/sidePanel/shared/expandableSectionHeader.tsx
- packages/dashboard/src/components/sidePanel/shared/settingTile.tsx
- packages/dashboard/src/components/sidePanel/shared/styles.css
- packages/dashboard/src/components/sidePanel/utils/index.ts
Sub task of #401 
- add chart setting section 
- update useInput hook. now it reads changes from widget states.
- When one widget is selected
- When multiple widgets are selected
- When no widget is selected
> feat(dashboard): add chart setting section

- packages/dashboard/package.json
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/stories/IotDashboard/IotDashboard.stories.tsx
Duplicate initialization / usage of sitewise query objects were causing the charts not to render in the dashboard.
> fix(dashboard): fix storybook props

- packages/dashboard/src/components/sidePanel/index.css
- packages/dashboard/src/components/sidePanel/sections/chartSettings.tsx
- packages/dashboard/src/components/sidePanel/sections/index.css
- packages/dashboard/src/components/sidePanel/sections/thresholdsSection.tsx
- packages/dashboard/src/components/sidePanel/shared/expandableSectionHeader.tsx
- packages/dashboard/src/components/sidePanel/shared/settingTile.tsx
Add threshold editing section. 
- add color picker
- support to add `XThreshold` 
- new added thresholds will not be displayed/updated with latest value. This is because currently we didn't dispatch action to update the real dashboard definitions. Each threshold can't get real data. This will be fixed once we add support of updating dashboard definitions.
```
httpserver
```
Then open …
> feat(dashboard): add thresholds editing section

- packages/dashboard/package.json
- packages/dashboard/src/components/dragLayer/components/widget.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/widgets/dynamicWidget.tsx
- packages/dashboard/src/components/widgets/list.tsx
- packages/dashboard/src/components/widgets/widget.tsx
- packages/dashboard/src/types.ts
- packages/dashboard/testing/mocks.ts
Changing the way we define queries for a widget. Now we are going to store a list of asset queries instead of the time query returned from the timeSeriesData function. Asset queries are serializable so they work better in redux, and will also be easier to work with from the resource explorer / properties panel.
> feat(dashboard): refactor appkit widget to store asset query definitions instead of time series data queries

- examples/react-app/package-lock.json
- package-lock.json
- packages/react-components/package.json
upgrade video.js to fix dependabot alert:
- https://github.com/awslabs/iot-app-kit/security/dependabot/51
- https://github.com/awslabs/iot-app-kit/security/dependabot/52
- https://github.com/awslabs/iot-app-kit/security/dependabot/61
```
httpserver
``` …
> chore: upgrade video.js to remove xmldom

- package-lock.json
- packages/scene-composer/.svglintrc.js
- packages/scene-composer/package.json
- packages/scene-composer/src/assets/auto-gen/icons/Camera.tsx
- packages/scene-composer/src/assets/auto-gen/icons/Orbit.tsx
- packages/scene-composer/src/assets/auto-gen/icons/Pan.tsx
- packages/scene-composer/src/assets/icons/camera.svg
- packages/scene-composer/src/assets/icons/orbit.svg
- packages/scene-composer/src/assets/icons/pan.svg
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__snapshots__/ComponentTypeIcon.spec.tsx.snap
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
This adds support for svg linting. we ran into an error in firefox where if a width and height were not specified, the icons were not visible
```
httpserver
```
> support linting for svg. Setup a rule to require width and height

- packages/components/src/components/iot-time-series-connector/iot-time-series-connector.spec.ts
- packages/components/src/components/iot-time-series-connector/iot-time-series-connector.tsx
graphs would flicker between the unsupported data warning and the empty graph state due to incomplete data being sent to synchroCharts widget. this prevents this by only rendering data that has a set `dataType`
https://github.com/awslabs/iot-app-kit/issues/405
> fix: prevent stream render if dataType unknown

- packages/dashboard/src/components/sidePanel/sections/index.css
- packages/dashboard/src/components/sidePanel/sections/thresholdsSection.tsx
Add native color picker for updating threshold colors
```
httpserver
```
> feat(dashboard): add color picker

- packages/dashboard/src/components/sidePanel/sections/thresholdsSection.tsx
- packages/dashboard/src/components/sidePanel/utils/index.ts
Support dispatching `updateWidget` action from side panel. 
```
httpserver
```
> feat(dashboard): dispatch updateWidget action from side panel

- packages/core/src/common/time.spec.ts
- packages/scene-composer/package.json
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/__snapshots__/AnchorWidget.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/utils/nodeUtils.ts
Object gets wrong transform during reparenting, issues includes:
- Tag's scales changes during reparenting
- Reparenting object between SubModelRef node and other nodes will cause object the move to wrong position
- Reparenting object to node with scale > 1 will cause object to scale unexpectedly
Before fix:
https://user-images.githubusercontent.com/9315598/212178294-15e88ad1-70b9-4028-adf2-be5a1c7319f9.mov
After fix:
https://user-images.githubusercontent.com/9315598/212178504-5b201180-60b6-4773-bc4c-3cc52af1e2ef.mov
- Download the …
> fix(composer): fix object transforms during reparenting

- .github/workflows/run-tests.yml
- packages/dashboard/.storybook/main.js
- packages/dashboard/package.json
Upgrade to webpack5. This change allows webpack to import ES6 syntax libs like aws-sdk.
https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-internet-explorer-11-in-the-aws-sdk-for-javascript-v3/
Also update run-tests.yml to fix broken tests under the latest Node LTS version. [more info](https://github.com/nodejs/help/issues/4068)
```
httpserver
```
Then open the …
> build(dashboard): upgrade to webpack5

- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/grid/index.tsx
- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/widgets/dynamicWidget.tsx
- packages/dashboard/src/components/widgets/list.tsx
- packages/dashboard/src/components/widgets/primitives/text/index.tsx
- packages/dashboard/src/components/widgets/widget.css
- packages/dashboard/src/components/widgets/widget.tsx
- packages/dashboard/src/store/state.ts
- packages/dashboard/src/types.ts
- packages/dashboard/stories/IotDashboard/IotDashboard.stories.tsx
Add a readonly property for the dashboard which makes the dashboard only render the grid area. It also disables the context menu and the drag and drop functionality.
This adds a new story for readonly mode. The Save button in the Main dashboard story will write the current state to local storage to be used in the readonly story.
> feat(dashboard): add readonly view for dashboard

- packages/dashboard/package.json
- packages/dashboard/src/components/resourceExplorer/components/breadcrumbs.test.tsx
- packages/dashboard/src/components/resourceExplorer/components/breadcrumbs.tsx
- packages/dashboard/src/components/resourceExplorer/components/panel.test.tsx
- packages/dashboard/src/components/resourceExplorer/getCurrentAssetProperties.test.ts
- packages/dashboard/src/components/resourceExplorer/getCurrentAssetProperties.ts
- packages/dashboard/src/components/resourceExplorer/getCurrentAssets.test.ts
- packages/dashboard/src/components/resourceExplorer/getCurrentAssets.ts
- packages/dashboard/src/components/resourceExplorer/index.tsx
As a fast follow for #481, unit tests for the constituent parts of the resource explorer (panel, breadcrumbs, getCurrentAsset, getCurrentAssetProperties).
Closes #490 
> test(dashboard): resource explorer unit tests

- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/store/actions/pasteWidgets/index.spec.ts
- packages/dashboard/src/store/actions/pasteWidgets/index.ts
Bugfix for copy / paste workflow. We want to auto select the newly pasted widget(s) so that it is easier for a user to position them in the correct spot. This also fixes a bug were keyboard shortcuts wouldn't trigger if the target of the event was the document and not specifically the grid container.
> fix(dashboard): select newly added widgets on paste

- packages/dashboard/src/components/sidePanel/sections/textSettingSection/index.spec.tsx
- packages/dashboard/src/components/sidePanel/sections/textSettingSection/text.tsx
Add UI tests for text widget.
```
httpserver
```
> test(dashboard): add tests for Text widget configuration

- packages/scene-composer/src/utils/dataBindingUtils.ts
- packages/scene-composer/tests/utils/dataBindingUtils.spec.ts
when the propertyName used in rules has multiple hyphen characters, the rule won't be evaluated properly because only one occurrence of the hyphen is escaped. this change is to escape all occurrences.
```
httpserver
``` …
> fix: propertyName with multi hyphen not working

- packages/dashboard/src/components/sidePanel/index.tsx
- packages/dashboard/src/components/sidePanel/sections/textSettingSection/link.spec.tsx
- packages/dashboard/src/components/sidePanel/sections/textSettingSection/link.tsx
add link section to setting panel for updating Text widget's link.
```
httpserver
```
> feat(dashboard): add link configuration section for Text widget

- packages/dashboard/src/components/resourceExplorer/components/breadcrumbs.tsx
- packages/dashboard/src/components/resourceExplorer/components/panel.tsx
- packages/dashboard/src/components/resourceExplorer/components/searchbar.tsx
- packages/dashboard/src/components/resourceExplorer/index.tsx
- packages/dashboard/src/components/resourceExplorer/useAssetProperties.test.tsx
- packages/dashboard/src/components/resourceExplorer/useAssetProperties.tsx
- packages/dashboard/src/messages.ts
- packages/dashboard/tsconfig.json
- Previously, the initial version of the resource explorer would make a call to listAssetProperties whenever we move through the resource explorer onto an asset with properties. This is both inefficient and incompatible with a search that must keep a record of all properties, so here I've added a simple cache so we only attempt to retrieve an asset's properties once. This is simple kludge to enable an initial implementation of search, ultimately we want to be pre-loading the whole asset tree.
- Adds a searchbar that allows you to search all assets and properties. The checkboxes for assets and properties do properly filter the search but the alarms checkbox does not function yet.
> feat(dashboard): initial resource explorer search

- package.json
- packages/react-components/src/common/constants.ts
- packages/react-components/src/common/dataTypes.ts
- packages/react-components/src/common/thresholdTypes.ts
- packages/scene-composer/package.json
Port over some of the types and constants from synchro-charts, into `react-components` package to prepare for porting over KPI, Status, Dial and gauge.
> chore(react-components): port over component utils from synchro-charts

- packages/react-components/src/common/constants.ts
- packages/react-components/src/common/iconUtils.tsx
- packages/react-components/src/common/thresholdTypes.ts
- packages/react-components/src/kpi/constants.ts
- packages/react-components/src/kpi/kpi.css
- packages/react-components/src/kpi/kpi.tsx
- packages/react-components/src/shared-components/DataStreamName/DataStreamName.css
- packages/react-components/src/shared-components/DataStreamName/DataStreamName.tsx
- packages/react-components/src/shared-components/DataStreamName/helper.spec.tsx
- packages/react-components/src/shared-components/DataStreamName/helper.ts
- packages/react-components/src/shared-components/ErrorBadge/ErrorBadge.css
- packages/react-components/src/shared-components/ErrorBadge/ErrorBadge.tsx
- packages/react-components/src/shared-components/LoadingSpinner/LoadingSpinner.css
- packages/react-components/src/shared-components/LoadingSpinner/LoadingSpinner.tsx
- packages/react-components/src/shared-components/StatusIcon/StatusIcon.css
- packages/react-components/src/shared-components/StatusIcon/StatusIcon.tsx
- packages/react-components/src/shared-components/Value/Value.tsx
- packages/react-components/src/styles/awsui.css
- packages/react-components/src/styles/globals.css
- packages/react-components/src/styles/tippy-overrides.css
- packages/react-components/src/styles/variables.css
- packages/react-components/src/utils/time.spec.ts
- packages/react-components/src/utils/time.ts
- packages/react-components/stories/kpi/kpi.stories.tsx
This is part of an incremental series of PRs to move over KPI, Status, Dial and Gauge.
Ports over the visual aspect of a KPI with several changes:
- removed the 'trend' functionality. Will add it back if requested by UX, but I think the feature should be reconsidered, as it takes up a lot of space and it's not clear exactly what it means. For that reason I am holding off of the effort to move it over.
- Remove the 'label editing' functionality. This no longer makes sense in the context of IoT App Kit as if a user wants to edit labels, they will use the text component.
To be done:
- some work around breached thresholds, and displaying icons
- porting over unit and integration tests. want to confirm some behaviors with UX before investing time writing tests for all the behaviors 
This …
> chore(react-components): port over kpi-base and associated helpers

- packages/react-components/package.json
- packages/react-components/src/kpi/kpi.tsx
- packages/react-components/src/status/constants.ts
- packages/react-components/src/status/highContrastColor.spec.ts
- packages/react-components/src/status/highContrastColor.ts
- packages/react-components/src/status/status.css
- packages/react-components/src/status/status.tsx
- packages/react-components/src/status/statusBase.tsx
- packages/react-components/src/status/types.ts
- packages/react-components/stories/kpi/kpiBase.stories.tsx
- packages/react-components/stories/status/status.stories.tsx
- packages/react-components/stories/status/statusBase.stories.tsx
Ports over the core parts of the `<Status />` widget, both the visualization portion of the component, and the bindings to IoT App Kit.
Going to follow up with tests after confirming with UX on all the behaviors/configurations.
> chore(react-components): port over status widget

- packages/dashboard/src/components/dashboard/clientContext.ts
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/dragLayer/itemTypes.ts
- packages/dashboard/src/components/resourceExplorer/components/panel.test.tsx
- packages/dashboard/src/components/resourceExplorer/components/panel.tsx
- packages/dashboard/src/components/resourceExplorer/describeCurrentAsset.ts
- packages/dashboard/src/components/resourceExplorer/getCurrentAssetProperties.test.ts
- packages/dashboard/src/components/resourceExplorer/getCurrentAssetProperties.ts
- packages/dashboard/src/components/resourceExplorer/index.tsx
- packages/dashboard/src/messages.ts
- packages/dashboard/stories/IotDashboard/IotDashboard.stories.tsx
This PR:
1. Wraps the dashboard in a ClientContext that allows us to useContext to access the IoTSiteWiseClient passed into the dashboard anywhere. (The Client.getInstance() pattern doesn't seem to work; looking at it, I think we're trying to do something there that requires a React Context -- as written, getInstance() should return undefined when imported in places other than where the Client was instantiated.)
2. Gets alarms with describeAsset and displays them in sidebar. When we are ready to receive dropped alarms on widgets, will be simple to update this to achieve that.
> feat(dashboard): ClientContext and initial resource explorer alarms support

- packages/dashboard/src/components/resourceExplorer/describeCurrentAsset.test.ts
- packages/dashboard/src/components/resourceExplorer/describeCurrentAsset.ts
- packages/dashboard/src/components/resourceExplorer/getCurrentAssetProperties.test.ts
- Adds test for describeCurrentAsset
- Silences another test that was leaking a log into the jest output
> dashboard: describeCurrentAsset test

- packages/dashboard/package.json
- packages/dashboard/rollup.config.js
- packages/dashboard/src/index.ts
fix type exports
was causing `Could not find a declaration file for module` error
> fix(dashboard): type exports

- examples/react-app/package.json
- package.json
- packages/components/package.json
- packages/components/src/components/iot-resource-explorer/iot-resource-explorer.spec.ts
- packages/core/package.json
- packages/react-components/package.json
- packages/related-table/package.json
- packages/scene-composer/package.json
- packages/source-iotsitewise/package.json
- packages/source-iottwinmaker/package.json
- packages/table/package.json
- turbo.json
Changes the monorepo tooling from npm workspaces to turborepo. Adds dev scripts to each package for cross package collaboration.
> Upgrade from NPM Workspaces to Turborepo

- packages/dashboard/src/components/palette/icons/index.tsx
- packages/dashboard/src/components/palette/icons/input-component.tsx
- packages/dashboard/src/components/palette/index.tsx
- packages/dashboard/src/components/widgets/componentMap.ts
- packages/dashboard/src/components/widgets/dynamicWidget.tsx
- packages/dashboard/src/components/widgets/primitives/input/index.tsx
- packages/dashboard/src/messages.ts
- packages/dashboard/src/store/actions/createWidget/presets/index.ts
- packages/dashboard/src/store/actions/createWidget/presets/input.tsx
- packages/dashboard/src/store/actions/createWidget/presets/sizing.ts
- packages/dashboard/src/types.ts
initial scaffolding for input widget
> feat(dashboard): initial scaffolding for input widget

- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.test.tsx
- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.ts
- packages/dashboard/src/hooks/useKeyPress.ts
Move keyboard shortcuts into their own hook to be used in the dashboard. Updated the keypress hook to use the beyKey flag so that we are not using the deprecated which property on a keyboard event.
Note: tests for copy and paste are not included, I was unable to find a way to fire a keydown event which includes the metaKey flag in jest.
> chore(dashboard): refactor keyboard shortcuts to hooks

- packages/react-components/jest.config.ts
- packages/react-components/package.json
- packages/react-components/src/common/iconUtils.tsx
- packages/react-components/src/components/dial/constants.ts
- packages/react-components/src/components/dial/dial.tsx
- packages/react-components/src/components/dial/dialBase.spec.tsx
- packages/react-components/src/components/dial/dialBase.tsx
- packages/react-components/src/components/dial/dialSvg.tsx
- packages/react-components/src/components/dial/types.ts
- packages/react-components/src/components/dial/useArcs.ts
- packages/react-components/stories/dial/dial.stories.tsx
- packages/react-components/stories/dial/dialBase.stories.tsx
Ports over dial component from synchrocharts. Also refactors to remove calls to calculate bounding boxes and eliminate a lot of state mutations, in preference for a simpler, more straightforward implementation
Follow up PR will be made which will add icons, tests, etc. This is the first iteration, and does not expose the dial component publicly.
> chore(dial): port over DialBase from SynchroCharts

- packages/core/src/__mocks__/data-source.ts
- packages/core/src/data-module/TimeSeriesDataModule.spec.ts
- packages/core/src/data-module/TimeSeriesDataModule.ts
- packages/core/src/data-module/data-cache/bestStreamStore.spec.ts
- packages/core/src/data-module/data-cache/bestStreamStore.ts
- packages/core/src/data-module/data-cache/caching/caching.spec.ts
- packages/core/src/data-module/data-cache/caching/caching.ts
- packages/core/src/data-module/data-cache/dataActions.ts
- packages/core/src/data-module/data-cache/dataCacheWrapped.spec.ts
- packages/core/src/data-module/data-cache/dataCacheWrapped.ts
- packages/core/src/data-module/data-cache/dataReducer.spec.ts
- packages/core/src/data-module/data-cache/dataReducer.ts
- packages/core/src/data-module/data-cache/getDataStreamStore.ts
- packages/core/src/data-module/data-cache/toDataStreams.spec.ts
- packages/core/src/data-module/data-cache/toDataStreams.ts
- packages/core/src/data-module/data-cache/types.ts
- packages/core/src/data-module/types.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/data-source.spec.ts
- packages/source-iotsitewise/src/time-series-data/data-source.ts
- packages/source-iotsitewise/src/time-series-data/provider.spec.ts
- add a layer to the cache so that we can support multiple aggregations in the future
```
[dataStreamId: string]: {
rawData: DataStream | undefined,
resolutions: {
[resolution: number]: { 
[aggregationType in AggregateType]?: DataStreamStore | undefined; 
} | undefined;
} | undefined;
} | undefined;
```
still receiving and displaying data properly :) 
> chore(core,source-iotsitewise): add aggregation layer to cache 

- packages/scene-composer/src/components/three-fiber/ModelRefComponent/TilesLoader.ts
3D Tiles for large models with dense geometry would not load all of the tiles in our Scene Composer.
Used 2 models to verify the changes and saw all elements show up as expected.
```
httpserver
```
> fix: TilesLoader will now load all visible tiles

- packages/dashboard/package.json
- packages/dashboard/src/components/contextMenu/index.test.tsx
- packages/dashboard/src/components/contextMenu/index.tsx
- packages/dashboard/src/components/contextMenu/menu.tsx
- packages/dashboard/src/components/internalDashboard/useLayers.spec.tsx
- packages/dashboard/src/components/internalDashboard/useLayers.ts
- packages/dashboard/src/components/userSelection/index.tsx
- packages/dashboard/src/components/widgets/selectionBox.tsx
- packages/dashboard/src/store/actions/bringToFront/index.spec.ts
- packages/dashboard/src/store/actions/bringToFront/index.ts
- packages/dashboard/src/store/actions/sendToBack/index.spec.ts
- packages/dashboard/src/store/actions/sendToBack/index.ts
Add fix for layering bug where you can raise a group of widgets to overlay above the context menu, selection rectangle, and user selection rectangle. 
Adds tests for the context menu.
> fix(dashboard): fix layering of widgets with selection and context menu

- packages/scene-composer/__mocks__/mockComponent.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayComponent.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayDataRow.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayRows.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayComponentSnap.spec.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayContainerSnap.spec.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayDataRowSnap.spec.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayRowsSnap.spec.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayComponentSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayContainerSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayDataRowSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayRowsSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/index.ts
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/styles.scss
- packages/scene-composer/src/components/three-fiber/EntityGroup/ComponentGroup.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/__tests__/ComponentGroup.spec.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/__tests__/EntityGroup.spec.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/__tests__/__snapshots__/ComponentGroup.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
- packages/scene-composer/src/hooks/useCallbackWhenNotPanning.ts
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/Store.ts
- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/internalInterfaces.ts
- packages/scene-composer/tests/scenes/scene_1.json
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Implement the container of data overlay component with simple text content rendering
```
httpserver
```
> feat(composer): Implement data overlay container

- .gitignore
- packages/dashboard/src/components/sidePanel/sections/baseSettingSection/index.spec.tsx
- packages/dashboard/src/components/sidePanel/sections/baseSettingSection/index.tsx
uses the same `trimWidgetPosition` function from `moveWidgetAction` to trim position & size numbers.
also add tests for this behaviour.
> fix(dashboard): remove tailing digits on widget dragging

- packages/scene-composer/src/utils/pathUtils.ts
- packages/source-iottwinmaker/src/utils/s3Utils.ts
Support the GovCloud partition by removing the hardcoded "aws" partition in S3 bucket ARNs.
```
httpserver
```
> chore(govcloud): Remove hardcoded partition in parseS3BucketFromArn

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.test.tsx
- packages/dashboard/src/store/actions/index.ts
- packages/dashboard/src/store/actions/toggleReadOnly/index.spec.ts
- packages/dashboard/src/store/actions/toggleReadOnly/index.ts
- packages/dashboard/src/store/reducer.ts
- packages/dashboard/src/styles/variables.css
- packages/dashboard/stories/IotDashboard/IotDashboard.stories.tsx
Add `readOnly` toggle to switch between edit and preview modes
Add `hasEditPermission` dashboard prop to specify if toggle should be displayed
> chore(dashboard): toggle between view and edit mode

- packages/core/src/__mocks__/data-source.ts
- packages/core/src/data-module/TimeSeriesDataModule.spec.ts
- packages/core/src/data-module/subscription-store/subscriptionStore.spec.ts
- packages/core/src/data-module/types.ts
- packages/source-iotsitewise/src/alarms/iotevents/util/fetchAlarmsFromQuery.ts
- packages/source-iotsitewise/src/index.ts
The purpose of this PR is to reduce the overall exposed public API of IoT App Kit. No data-source specific code should be exported as part of core.
BREAKING CHANGE:
- Removes SiteWise specific typescript type definitions from being exported from @iot-app-kit/core
- Removes SiteWise alarm module from exported from @iot-app-kit/source-iotsitewise
> fix(core, source-iotsitewise)!: remove needed exports 

- README.md
- docs/TimeSync.md
- docs/useViewport.md
- packages/react-components/src/index.ts
The goal of this PR is to enable the usage of `useViewport` to help synchronize time across IoT App Kit widgets.
- Exports `useViewport` hook to be able to be publicly consumable 
- Adds `useViewport` documentation to root README.md for discoverability
- Minor documentation updates
> feat(react-components): release useViewport hook

- packages/source-iotsitewise/package.json
- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetLatestPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/util/deduplication.spec.ts
- packages/source-iotsitewise/src/time-series-data/util/deduplication.ts
Deduplicates individual requests in a batch in the `source-iotsitewise` package. This eliminates duplicate calls to sitewise for the same data, like when multiple charts are rendering the same data at once.
> fix(source-iotsitewise): deduplicate batch requests

- packages/dashboard/src/components/resourceExplorer/stencil/style.css
Updates the resource explorer to maximize available screen real estate depending on the quantity of assets and properties.
In this scenario, multiple pages of assets are listed and take much of the panel, but it's still clear the asset properties section exists.
Once an asset is selected, the properties panel will grow to a maximum value to display more options at once.
When there are fewer assets on a page, the asset properties panel will grow up to the bottom of the asset tree.
> fix(dashboard): grow asset properties panel

- docs/CustomSources.md
- packages/core/src/common/types.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.spec.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
- packages/source-iotsitewise/src/initialize.spec.ts
- packages/source-iotsitewise/src/initialize.ts
- packages/source-iottwinmaker/src/initialize.spec.ts
- packages/source-iottwinmaker/src/initialize.ts
Adds toQueryString method on queries which enables IoT App Kit components to determine if a query has changed on re-render, or if only the reference to the query has been updated. The motivation of this is to make a more performant `useTimeSeriesData` hook.
- Adds `toQueryString` method to the `Query` interface
- Implements `toQueryString` method on iotsitewise queries
- Implements `toQueryString` method on iottwinmaker queries
- Update documentation regarding how to create a custom data source
BREAKING CHANGES:
- Adds new required method `toQueryString(): string` on `Query` type.
> feat(core, source-iotsitewise, source-iottwinmaker)!: toQueryString on query

- packages/scene-composer/package.json
Remove invalid workspace configuration in package.json, which is causing scene composer not to publish: https://github.com/awslabs/iot-app-kit/actions/runs/4328652208/jobs/7558558014
confident it is safe to remove due to this comment: https://github.com/awslabs/iot-app-kit/pull/615/files#r1122423922
> Remove hoist

- .stylelintignore
- packages/components/package.json
In local dev environment, `@iot-app-kit/<package>` will ref to local packages. For any packages imports `@iot-app-kit/components/styles.css` will not find the file, since it will only be generated in `prepack` and will only be included in npm distributions. 
Here's some error on starting dashboard on a new fresh install
```
> @iot-app-kit/dashboard@3.0.0 start
> start-storybook -p 6006
webpack built preview 08fabfdc9281b34ce0be in 9982ms
ModuleNotFoundError: Module not found: Error: Can't resolve '@iot-app-kit/components/styles.css' in '/home/bill/WebstormProjects/iot-app-kit/packages/dashboard/src/components/internalDashboard'
at /home/bill/WebstormProjects/iot-app-kit/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compilation.js:2016:28
at …
```
> build(components): generate `styles.css` on build

- packages/dashboard/src/components/palette/component.css
- packages/dashboard/src/components/palette/icons/index.css
- packages/dashboard/src/components/palette/index.test.tsx
Styling fix to make the drag and drop pointer consistent with the resource explorer. Also adds some e2e tests for dragging and dropping a component onto the grid.
> fix(dashboard): fix styling for component palette and add tests for drag and drop

- .github/workflows/run-e2e-tests.yml
- .github/workflows/run-tests.yml
Utilizing caching to increase CI speed: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
Also splits up the unit tests from E2E so that unit and E2E run in parellel. Because integration tests complete faster, this means we can add a lot more integration tests without impacting the CI completion time.
CI checks won't pass until we edit the repository rules to reflect the updates github action names
> build: Utilize npm cache to increase CI speed

- packages/dashboard/src/customization/widgetPropertiesGeneratorMap.ts
- packages/dashboard/src/customization/widgets/text/component.test.tsx
- packages/dashboard/src/customization/widgets/text/component.tsx
- packages/dashboard/src/customization/widgets/text/styledText/editableText.tsx
- packages/dashboard/src/customization/widgets/text/styledText/index.tsx
- packages/dashboard/src/index.ts
There is a selection bug where if you right click a text widget and delete it, grid gestures would be disabled from the click and not be enabled again once the element was removed. To fix this, a hook is added to the text widget to enable the grid when it is removed.
> fix(dashboard): fix edit mode bugs

- package.json
- packages/scene-composer/src/three/tiles3d/TilesRendererBase.js
- fix error with rendering 3D tiles
- fix local npm install issue
```
httpserver
```
> fix(composer): fix error with rendering 3D tiles

- .github/workflows/lint-commit.yml
- .husky/commit-msg
- commitlint.config.js
- package.json
- enforce conventional commit at time of making a commit
- enforce conventional commit on CI
- update package-lock to account for removal of react-app from workspace
> chore: setup husky, update package-lock to remove react-app dependencies

- .github/workflows/run-e2e-tests.yml
- packages/react-components/package.json
Speed up CI across multiple jobs, ~40% increase in speed of e2e github action
- fix `clean` script in react-components to remove storybook artifacts
- remove unecessary storybook building on build script, preventing additional build times in CI
- scope down e2e run to prevent other packages from building
> ci(e2e): speed up e2e CI by not building storybook on build

- .github/workflows/npm-publish.yml
- .github/workflows/release-please.yml
Set up a pre-release in a semi-manual fashion.
pre-release is not well supported by release please, to unblock the sharing of development versions, this will release a `@nightly` tagged with versions set to 3.0.1-nightly.
> build(publish): manually setup for a nightly release

- packages/scene-composer/src/augmentations/components/three-fiber/viewpoint/ViewCursorWidget.tsx
View cursor svg is not rendered properly and will cause error in console. This change is to remove the svg for now, and fix for the svg will be in a different task.
There is no UI change by this PR since the cursor svg is not rendered correctly without this change.
```
httpserver
``` …
> fix(composer): temporarily remove view cursor svg

- .github/workflows/release-please.yml
Allow release please based release to occur via changes to github workflows. This is important as we can then trigger release by simply altering the 'release as' setting.
> fix(ci): allow releases to be trigged via changes to github workflows

- packages/dashboard/src/customization/widgets/kpi/component.css
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/status/component.css
- packages/dashboard/src/customization/widgets/status/component.tsx
Adds empty states for the KPI and status widgets on the dashboard.
> feat(dashboard): kpi and status widget empty states

- packages/scene-composer/package.json
- packages/source-iotsitewise/package.json
- packages/source-iottwinmaker/jest.config.js
- packages/source-iottwinmaker/package.json
- packages/source-iottwinmaker/src/__mocks__/MockVideoPlayerProps.ts
- packages/source-iottwinmaker/src/__mocks__/iotsitewiseSDK.ts
- packages/source-iottwinmaker/src/__mocks__/iottwinmakerSDK.ts
- packages/source-iottwinmaker/src/__mocks__/kinesisVideoArchivedMediaSDK.ts
- packages/source-iottwinmaker/src/__mocks__/kinesisVideoSDK.ts
- packages/source-iottwinmaker/src/metadata-module/TwinMakerMetadataModule.spec.ts
- packages/source-iottwinmaker/src/time-series-data/client/getPropertyValueHistoryByComponentType.spec.ts
- packages/source-iottwinmaker/src/time-series-data/client/getPropertyValueHistoryByEntity.spec.ts
- packages/source-iottwinmaker/src/video-data/VideoData.spec.ts
- packages/source-iottwinmaker/src/video-data/utils/kvsUtils.spec.ts
- packages/source-iottwinmaker/src/video-data/utils/sitewiseUtils.spec.ts
- packages/source-iottwinmaker/src/video-data/utils/twinmakerUtils.spec.ts
Upgraded the AWS SDK for scene-composer and source-iottwinmaker packages
```
httpserver
```
> chore(AWS-SDK): upgraded AWS SDK for TwinMaker packages

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditorSnap.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/DataOverlayComponentEditorSnap.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/data-overlay/DataOverlayPanelConfigEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/data-overlay/DataOverlayPanelConfigEditor.tsx
- packages/scene-composer/src/components/wrappers/ReactMarkdownWrapper.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Add checkbox to control `isPinned` value for data overlay panel
```
httpserver
```
> feat(composer): add overlay panel config editor

- packages/scene-composer/package.json
- packages/source-iotsitewise/package.json
- packages/source-iottwinmaker/package.json
Fix for the build failure due to internal dependencies of vs.
```
httpserver
```
> fix(aws-sdk): fix the build failure due to internal dependencies

- packages/dashboard/src/components/contextMenu/index.test.tsx
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.test.tsx
- packages/dashboard/src/components/palette/index.test.tsx
- packages/dashboard/src/components/resizablePanes/index.test.tsx
- packages/dashboard/src/components/sidePanel/sections/baseSettingSection/index.spec.tsx
- packages/dashboard/src/components/viewportSelection/index.test.tsx
Incorrect importing causes following error:
```
//import {act} from "react-dom/test-utils" 
console.error
Warning: An update to Menu inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
```
Correct it to 
```
import { act } from '@testing-library/react';
```
```
cd …
```
> chore(dashboard): correct import of `act` to remove warnings

- .github/workflows/lint-commit.yml
Enforce conventional commits on latest commit message within CI
> ci(commit-lint): enforce commit to be conventional

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayDataRow.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayRows.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayDataRowSnap.spec.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayDataRowSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayRowsSnap.spec.tsx.snap
- packages/scene-composer/src/interfaces/dataTypes.ts
- packages/scene-composer/src/utils/dataBindingUtils.ts
- packages/scene-composer/src/utils/dataBindingVariableUtils.spec.ts
- packages/scene-composer/src/utils/dataBindingVariableUtils.ts
- packages/scene-composer/tests/scenes/scene_1.json
Implement the data binding variable support for data overlay.
User can input `${binding-name}` in overlay markdown/string content to display the latest property history value of that configured data binding
```
httpserver
``` …
> feat(composer): data binding variable support for data overlay

- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
Removes the 'chart' suffix from empty state lines.
> fix(dashboard): remove chart suffix from empty states

- packages/source-iottwinmaker/package.json
- packages/source-iottwinmaker/src/initialize.ts
- Fix the build error due to client-iottwinmaker AWS SDK dependency
- Updated `secretsManagerClient` to be an optional parameter in `IoTAppKitInitAuthInputs` 
```
httpserver
```
> fix(iot-app-kit): fix internal build failure

- packages/dashboard/src/components/sidePanel/sections/thresholdsSection/thresholdComponent.tsx
Supports decimals for threshold values.
> fix(dashboard): support decimals for thresholds

- packages/dashboard/src/components/widgets/widget.css
style tweak to remove white borders around widgets in edit mode, replaced with a padding to keep the spacing consistent
> style(Dashboard): remove white border in dashboards edit view

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.test.tsx
- packages/dashboard/src/components/palette/index.test.tsx
- packages/dashboard/src/store/state.ts
- packages/dashboard/src/types.ts
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
- packages/dashboard/tsconfig.json
- remove unused query param from storybook that caused redux errors
- update onSave prop type for dashboard to return promise
- remove deprecated internationlization
- fix key warnings on various UX elements
- enable typescript on storybook, fix ts errors
Addresses https://github.com/awslabs/iot-app-kit/issues/806
> fix(Dashboard): dashboard API changes for onSave etc.

- packages/scene-composer/package.json
- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/panels/SettingsPanel.tsx
- Fixed the black screen issue with Matterport Scene
When navigating in the scene with Matterport space the floor turns black before moving. This is due to the ground plane mesh inserted by WebGLCanvasManager which writes to the depth buffer but is otherwise invisible. Due to quirks of render order sorting, sometimes it gets rendered before the Matterport model mesh, which causes portions below the ground plane to be discarded by depth testing.
Setting its renderOrder to a value greater than zero i.e. 1 so it’s never rendered before the Matterport mesh when scene is using a Matterport space otherwise leave the default render order.
- Also, updated to not show the 3rd Party Resources section in Viewer mode
For `scene-composer` package changes specifically, you can preview the component in …
> fix(composer): black screen on Matterport scene

- packages/scene-composer/public/CookieFactoryWaterTankMatterportTag.scene.json
- packages/scene-composer/src/common/GlobalSettings.ts
- packages/scene-composer/src/components/panels/scene-settings/MatterportIntegration.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/MatterportIntegration.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/MatterportTagSync.spec.tsx.snap
- packages/scene-composer/src/hooks/useMatterportObserver.spec.tsx
- packages/scene-composer/src/hooks/useMatterportObserver.ts
- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- packages/scene-composer/src/utils/matterportTagUtils.ts
- packages/scene-composer/stories/Matterport.stories.mdx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Add Tag Sync button to Matterport Settings panel in TwinMaker Scene Editor
The scene viewer doesn't update as you change a Matterport scene so the easiest way to verify is:
Have a TwinMaker Scene with a fake Matterport Tag imported into already (tag with properties {matterportId: 'someId'} that isn't in your Matterport space
A Matterport space with 2+ tags
Use the Sync button -
the fake Matterport tag should be deleted
the other tags should get added
Manually delete a tag
Manually enter some data bindings on one of the new imported tags
Use the Sync button
Verify: the manually deleted tag returns, verify the added bindings aren't ovewritten when the tag updates
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, …
> feat(Matterport): add Tag Sync button to setting

- packages/dashboard/src/components/internalDashboard/gestures/index.spec.tsx
- packages/dashboard/src/components/palette/index.test.tsx
- packages/dashboard/src/components/sidePanel/sections/axisSettingSection/index.tsx
- packages/dashboard/src/components/sidePanel/sections/propertiesAlarmSection/index.tsx
- packages/dashboard/src/components/sidePanel/sections/thresholdsSection/thresholdsSection.tsx
- packages/dashboard/src/customization/widgets/barChart/plugin.tsx
- packages/dashboard/src/customization/widgets/kpi/plugin.tsx
- packages/dashboard/src/customization/widgets/lineChart/plugin.tsx
- packages/dashboard/src/customization/widgets/scatterChart/plugin.tsx
- packages/dashboard/src/customization/widgets/status/plugin.tsx
- packages/dashboard/src/customization/widgets/table/plugin.tsx
Switch over widget types to match final API for widget configuration
> refactor(Dashboard): remove iot prefix from dashboard widget types

- packages/dashboard/src/components/grid/index.tsx
- packages/dashboard/src/store/actions/moveWidgets/index.spec.ts
- packages/dashboard/src/store/actions/moveWidgets/index.ts
- packages/dashboard/src/store/actions/resizeWidgets/index.ts
- packages/dashboard/src/util/moveSelectionBox.spec.ts
- packages/dashboard/src/util/moveSelectionBox.ts
- packages/dashboard/src/util/resizeSelectionBox.spec.ts
- packages/dashboard/src/util/resizeSelectionBox.ts
- packages/dashboard/src/util/transformWidget.spec.ts
- packages/dashboard/src/util/transformWidget.ts
All drag vectors will be constrained in grid.
- if a vector moves from `10, -10 -> 10, 10`, it would be considered as `10, 0 -> 10, 10`. and the new vector is `0, 10`. which means cursor movements out of bound will be ignored.
- also fixes a strange behaviour on moving a group of widgets out of bound.
> fix(dashboard): constrain drag vector to border of dashboard

- packages/dashboard/src/components/resourceExplorer/stencil/index.tsx
update default column definitions in `iot-resource-explorer.tsx`
fixes: #756 
```
httpserver
```
> feat(resource explorer): allow dashboard to only show asset name

- packages/scene-composer/src/components/toolbars/common/ItemContainer.spec.tsx
- packages/scene-composer/src/components/toolbars/common/ItemContainer.tsx
- packages/scene-composer/src/components/toolbars/common/ToolbarItem.tsx
- packages/scene-composer/src/components/toolbars/common/__snapshots__/ItemContainer.spec.tsx.snap
- packages/scene-composer/src/components/toolbars/common/styledComponents.ts
- packages/scene-composer/src/components/toolbars/common/types.ts
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/CancelMenuItem.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/HistoryItemGroup.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/ObjectItemGroup.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/SceneItemGroup.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
- packages/scene-composer/tests/components/toolbars/common/ToolbarItem.spec.tsx
- packages/scene-composer/tests/components/toolbars/floatingToolbar/items/AddObjectMenu.spec.tsx
- packages/scene-composer/tests/components/toolbars/floatingToolbar/items/HistoryItemGroup.spec.tsx
- packages/scene-composer/tests/components/toolbars/floatingToolbar/items/__snapshots__/HistoryItemGroup.spec.tsx.snap
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
- Implement the basic add menu item for overlay and annotation. Final UX is still pending.
- Fixed selected mode menu item not displayed correctly issue 
- 
```
httpserver
```
> feat(composer): implement add overlay from menu

- packages/scene-composer/src/components/StateManager.tsx
fix default loading the mp scene when user is not changing anything on the scene settings page
```
httpserver
```
> fix(composer): fix default loading the mp scene

- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.spec.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
Move binding styles out of side effect so it always applies the latest style settings.
fixes: #793 
> fix(react-components): fix binding styles in `useTimeSeriesData` hook

- packages/dashboard/package.json
- packages/dashboard/src/components/sidePanel/sections/thresholdsSection/thresholdsSection.tsx
- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/lineChart/component.tsx
- packages/dashboard/src/customization/widgets/scatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/dashboard/testing/mocks/index.ts
- packages/react-components/package.json
- packages/react-components/src/components.ts
- packages/react-components/src/components/bar-chart/barChart.spec.tsx
- packages/react-components/src/components/bar-chart/barChart.tsx
- packages/react-components/src/components/line-chart/lineChart.spec.tsx
- packages/react-components/src/components/line-chart/lineChart.tsx
- packages/react-components/src/components/scatter-chart/scatterChart.spec.tsx
- packages/react-components/src/components/scatter-chart/scatterChart.tsx
- packages/react-components/src/components/status-timeline/statusTimeline.spec.tsx
- packages/react-components/src/components/status-timeline/statusTimeline.tsx
- packages/react-components/src/components/time-sync/index.tsx
- packages/react-components/src/index.ts
- packages/react-components/stories/chart/chart.stories.tsx
pass through the `setViewport` function (from the `useViewports` hook) into the @iot-app-kit/charts package, which will set the viewport on Gesture and will prevent re render if `lastUpdatedBy` is set to be `chart-gesture`
> feat(react-comp): sync viewports using @iot-app-kit/charts pckg

- packages/react-components/src/components/bar-chart/barChart.tsx
- packages/react-components/src/testing/mockWidgetProperties.ts
- packages/react-components/src/utils/thresholdUtils.ts
thresholds were breaking on widgets that supported any data type
fixed this by checking for every possible comparison_operator type in `isThresholdBreached` function 
instead of erroring, the function will return `false` if operators aren't meant to work with the given data type 
> feat(react-comp): isThresholdBreached checks all comparison ops

- packages/dashboard/src/components/sidePanel/sections/axisSettingSection/index.tsx
The status timeline component doesn't support Y axis options. PR removes the Y axis toggle and label from the AxisSettings component when the widget type is status-timeline.
> fix(dashboard): hide y axis settings for status timeline component

- packages/source-iotsitewise/src/__mocks__/alarm.ts
- packages/source-iotsitewise/src/alarms/iotevents/util/completeAlarmStream.spec.ts
- packages/source-iotsitewise/src/alarms/iotevents/util/getAlarmStateProperty.spec.ts
- packages/source-iotsitewise/src/alarms/iotevents/util/getAlarmStateProperty.ts
- packages/source-iotsitewise/src/completeDataStreams.spec.ts
Bugfix to use asset composite model name for AWS/ALARM type models as the name in the data stream.
> fix(source-iotsitewise): use alarm model name in data stream instead of alarm state name

- .gitignore
- .stylelintignore
- packages/react-components/package.json
Port over stylesheets to from `components` package to `react-components` package. Users can import it as 
```
import "@iot-app-kit/react-components/styles.css";
```
to have components styled.
Also update `files` filed `package.json` to update `styles.css` to npm.
> build(dashboard): port over stylesheets to react-components

- packages/dashboard/package.json
- packages/react-components/package.json
an initial live mode viewport was making any scroll jump back to live mode instead of keeping viewport where user had scrolled
> fix(charts): fix live mode viewport scrollingbug

- package.json
- packages/react-components/package.json
- packages/react-components/src/components/bar-chart/barChart.spec.tsx
- packages/react-components/src/components/dial/dial.spec.tsx
- packages/react-components/src/components/dial/dial.tsx
- packages/react-components/src/components/kpi/kpi.spec.tsx
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/line-chart/lineChart.spec.tsx
- packages/react-components/src/components/scatter-chart/scatterChart.spec.tsx
- packages/react-components/src/components/status/status.spec.tsx
- packages/react-components/src/components/status/status.tsx
- packages/react-components/src/components/table/table.spec.tsx
- packages/react-components/src/components/table/table.tsx
Table, KPI and status do not currently support displaying non raw data, but were trying to fetch non-raw data.
Updated configuration to default to requesting raw data
fixes https://github.com/awslabs/iot-app-kit/issues/854
> fix(ReactComponents): configure table, kpi and status to always fetch raw

- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/react-components/src/components/kpi/kpi.spec.tsx
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/index.ts
- packages/react-components/stories/kpi/kpi.stories.tsx
Rename so `KPI` widget remains the same before and after v4 release of IoT App Kit
> refactor(KPI): rename Kpi -> KPI to be consistent with v3

- packages/dashboard/src/components/dragLayer/index.tsx
- packages/dashboard/src/components/resourceExplorer/components/panel.tsx
- packages/dashboard/src/customization/widgets/barChart/plugin.tsx
- packages/dashboard/src/customization/widgets/lineChart/plugin.tsx
- packages/dashboard/src/customization/widgets/queryWidget/multiQueryWidget.tsx
- packages/dashboard/src/customization/widgets/queryWidget/queryWidget.css
- packages/dashboard/src/customization/widgets/scatterChart/plugin.tsx
Allow multi query widgets to define a subset of asset property data types they will allow to be dropped.
> feat(dashboard): disable asset drop for widgets that are not compatible with that data type

- packages/dashboard/src/customization/widgets/text/component.tsx
- enable edit mode for text widget immediately after droping a text widget to grid
- copy & paste widgets contains text will not enable editing mode. so behaviours are identical to previous.
> feat(dashboard): enable edit mode for text widget on widget creation

- packages/dashboard/package.json
remove testing-util as a dependency
> fix(dashboard): remove testing-util as a dependency

- README.md
- docs/AWSIoTSiteWiseSource.md
- docs/AWSIoTTwinMakerSource.md
- docs/BarChart.md
- docs/Components.md
- docs/Core.md
- docs/CustomSources.md
- docs/GettingStarted.md
- docs/KPI.md
- docs/LineChart.md
- docs/ResourceExplorer.md
- docs/ScatterChart.md
- docs/SceneViewer.md
- docs/StatusGrid.md
- docs/StatusTimeline.md
- docs/Table.md
- docs/TimeSeriesDataFeatures.md
- docs/TimeSync.md
- docs/VideoPlayer.md
- docs/ViewportManager.md
- docs/useTimeSeriesData.md
- docs/useViewport.md
Update docs to point to https://awslabs.github.io/iot-app-kit/
> docs: point documentation to doc site

- packages/dashboard/src/components/sidePanel/sections/thresholdsSection/thresholdsSection.tsx
- Empty threshold section doesnt show threshold options
- Closed threshold section expands when create button is made
> fix(dashboard): better empty thresholds pane

- packages/dashboard/package.json
update type path in package json.
This will allow typescript packages to find the correct types file for dashboard.
> fix(dashboard): update type path in package json

- packages/dashboard/src/components/internalDashboard/index.css
Bugfix to prevent external styling breaking the UX for dashboard.
If a user set the text align on a parent element of the dashboard, it would cause the charts and most of the text to shift position.
> fix(dashboard): add css resets

- packages/dashboard/package.json
- packages/dashboard/src/components/internalDashboard/index.css
A dependency of dashboard is using buffer which is not present when trying to install / use the dashboard package.
> fix(dashboard): add buffer to dependencies so consuming apps don't need to install it

- packages/react-components/package.json
> fix(react-components): add core-util as a dependency

- packages/tools-iottwinmaker/README.md
- packages/tools-iottwinmaker/src/commands/init.ts
Quick customer fix
```
httpserver
```
> fix(TwinMakerTools): added a additional condition to prevent saving an s3 folder as a model

- packages/scene-composer/package.json
We weren't declaring `react-intl` as a peer dependency before, leading to build issues and customer confusion.
```
httpserver
```
> fix(PeerDependencies): react-intl should be declared as a peer dependency

- packages/scene-composer/src/components/panels/AddOrRemoveOverlayButton.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/panels/__tests__/AddOrRemoveOverlayButton.spec.tsx
Gate empty overlay section in inspector panel instead of add/remove overlay button to not showing the empty section when overlay is not on.
```
httpserver
```
> fix(composer): gate empty overlay section in inspector

- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/MatterportTagSync.spec.tsx.snap
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Corrected the sync tags logic to handle v1 and v2 of Matterport tags. Also, added a status indicator on sync success.
```
httpserver
```
> fix(composer): Sync tags correctly & addded status

- packages/dashboard/src/components/resourceExplorer/components/mapper.spec.ts
- packages/dashboard/src/components/resourceExplorer/components/mapper.ts
Bugfix for table widget to display alarm name instead of alarm state property name.
> fix(dashboard): update property name for tables when displaying alarms

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
Handle the click event correctly to make sure both regular and matterport scene works fine
```
httpserver
```
> fix(Composer): Handle click event

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayContainerSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/styles.ts
Close button inline style for data overlay
```
httpserver
```
> fix(Composer): Close button inline style in overlay

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/GLTFModelComponent.tsx
- fix Reparent changes object's rotation unexpectedly
- fix After click to adding Tag, parent is selected instead of the new Tag
```
httpserver
```
> fix(composer): fix reparent rotation and add new object issues

- packages/scene-composer/src/components/panels/scene-settings/MatterportIntegration.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayComponent.tsx
- Position data overlay over tag
- Handle undo/redo of Matterport Model Id
```
httpserver
```
> fix(Composer): Position data overlay over tag & model id undo/redo

- packages/scene-composer/src/components/Tree/tree.scss
- packages/scene-composer/src/components/__snapshots__/SceneComposerInternal.spec.tsx.snap
- packages/scene-composer/src/components/panels/TopBar.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/hooks/useMatterportObserver.ts
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
Bug fix to restore loading indicator in scene composer. 
Additionally included minor fix to remove double-border appearing on action icons in the Scene Hierarchy panel. 
```
httpserver
```
> fix(composer): Restores loading indicator for scene-composer

- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
Adds a configuration property to Dashboard to pick which view mode is shown initially (edit / preview).
> feat(dashboard): add initial view mode configuration to dashboard

- packages/scene-composer/src/utils/objectThreeUtils.spec.ts
Test setup code was still importing old ThreeJS imports for RGBFormat vs RGBAFormat. I have updated the imports, and fixed the test.
```
httpserver
```
> fix(754): tests importing invalid import from ThreeJS and suppressing with lint rules

- packages/scene-composer/src/augmentations/components/three-fiber/viewpoint/ViewCursorWidget.tsx
- packages/scene-composer/src/utils/svgUtils.spec.ts
- packages/scene-composer/src/utils/svgUtils.ts
- packages/scene-composer/stories/components/hooks/useLoader.ts
- packages/scene-composer/stories/components/hooks/useSceneMetadataModule.ts
fix ViewCursorWidget for 3D Tiles and made cursor size dynamic based on camera distance
When a user wants to add a tag, motion indicator, or model to the scene with enhanced editing, the mouse becomes a cursor with a projected SVG to show where the widget/object will be placed in relation to the surface of another object. A raycast from the camera to the mouse is used to calculate the intersection distance, position, and orientation for an object in the scene.
For regular 3D models this works fine, but the raycast for 3D Tiles did not work. After investigating I found that the `raycast` method for the 3D Tiles meshes in the scene is not called from the mesh object but from the TilesGroup which is a parent of all meshes in the tileset.
Updated the logic for traversing the scene and …
> fix(composer): fix ViewCursorWidget for 3D Tiles

- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.spec.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
React error was happening when the number of queries passed into useEffect changed
`The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.`
Now useEffect will check against a concatenated string of all the queries so it will always have a length of 1
> fix(react-components): useTimeSeriesData hook works when number of queries changes

- packages/dashboard/src/components/grid/autoCellSize.tsx
- packages/dashboard/src/components/grid/sizedGrid.tsx
Make auto cell size recalculate whenever the width or cell size changes so that it stays in sync with changes outside of this component.
> fix(dashboard): ensure auto size grid recalculates any time cellSize changes from outside component

- packages/scene-composer/src/augmentations/components/three-fiber/viewpoint/ViewCursorWidget.tsx
- packages/scene-composer/src/utils/svgUtils.spec.ts
- packages/scene-composer/src/utils/svgUtils.ts
- packages/scene-composer/stories/components/hooks/useSceneMetadataModule.ts
Merge commit from release-3.x to main:
* [Commit](https://github.com/awslabs/iot-app-kit/commit/a023cf714c187a4d09b765a4fb5a78e526424fc5)
* [PR](https://github.com/awslabs/iot-app-kit/pull/948) 
Updated the logic for traversing the scene and calculating the intersection of rays to objects for the ViewCursorWidget. The list of objects that will call raycast are any TilesGroup node and any non-tileset and non-gizmo meshes.
The size of the projected SVG is a static size which is difficult to see for large objects and a camera that is far away. It is too small and looks like the feature is broken. With this change I update the SVG scale based on the distance of the closest intersection.
Verified in storybook with 3D Tilesets I have in my personal AWS account.
Ran the same tests as in PR #948 …
> fix(composer): fix viewCursorWidget for 3D tiles and made cursor size dynamic

- packages/scene-composer/src/components/three-fiber/ModelRefComponent/TilesModelComponent.tsx
Same change as in the release-3.x branch: https://github.com/awslabs/iot-app-kit/pull/985
Adding a widget to a 3D Tiles model was recently broken.
Added logic from GLTFModelComponent handleAddWidget to TilesModelComponent to find the closest parent node in the scene and attach the widget as a child. Added this onClick action to the component if addingWidget is active.
Same tests as in PR #985 
```
cd <Extracted Zip …
```
> fix(composer): adding widget fix for 3d tiles

- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
Enable data overlay, tag resize, and matterport features
Built locally and tested in Grafana. Was able to see all features enabled in my Scene Viewer panel.
```
httpserver
```
> feat(composer): enable data overlay, tag resize, and matterport features

- .github/workflows/npm-publish.yml
- release-please-config.json
add tools-iottwinmaker to npm publish workflow
```
httpserver
```
> feat(TwinMakerTools): add tools-iottwinmaker to npm publish workflow

- packages/scene-composer/src/components/three-fiber/EditorCamera.tsx
- packages/scene-composer/src/components/three-fiber/controls/OrbitControls.tsx
- packages/scene-composer/stories/SceneViewer.stories.mdx
This fixes a bug in the SceneComposer component when anything would cause the component to be unmounted and remounted, it would crash and require a page refresh.
There's some complicated DOM binding in the OrbitControls bit that was losing the dom element when it was destroyed and recreated, fixing this issue so it was correctly bound to a component resolved the issue.
I added a manual verification test (mounting the entire scene composer in a unit test is a bit crazy), you can see in the storybook output under "scene-viewer" tests. There's a toggle switch that will mount and unmount the component as you toggle it.
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for the `Publish Storybook` action to …
> fix(CrashOnRemount): scene-composer doesn't crash when remounted now

- README.md
drive release of IoT App Kit + minor doc update
```
httpserver
```
> fix(build): drive release of IoT App Kit + minor doc update

- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/__snapshots__/SceneComposerInternal.spec.tsx.snap
- packages/scene-composer/src/components/panels/TopBar.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportIntegration.tsx
- packages/scene-composer/src/components/three-fiber/EditorCamera.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/SceneItemGroup.tsx
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
- packages/scene-composer/stories/Developer/SceneViewer.stories.mdx
- packages/scene-composer/stories/SceneViewer.stories.mdx
- packages/scene-composer/tests/StateManager.spec.tsx
- Fixed the problem related to scene rendering and texture issue when switching from a Matterport to non-Matterport scene.
- Fixed the setting and handling of conditional variable that determines whether scene is Matterport enabled or not
```
httpserver
``` …
> fix(composer): rendering issue when switching from a Matterport to non Matterport scene

- .github/dependabot.yml
- .github/workflows/dependabot-hook.yml
This change turbo charges Dependabot with the following changes:
- Enable up to 25 version bumps a day.
- Enable GitHub Actions version bumps.
- Auto-approve version bump PRs.
- Enable auto-merge with rebase on version bump PRs.
The work automates dependency updates. Dependency updates will only need to be manually touched if a required check fails. If required checks fail, it's often easiest to just close the PR, unless we really want the update.
> ci: turbo charge dependabot

- packages/source-iottwinmaker/src/__mocks__/iottwinmakerSDK.ts
- packages/source-iottwinmaker/src/initialize.ts
- packages/source-iottwinmaker/src/knowledgeGraph-module/KGDataModule.spec.ts
- packages/source-iottwinmaker/src/knowledgeGraph-module/KGDataModule.ts
- packages/source-iottwinmaker/src/knowledgeGraph-module/types.ts
- packages/source-iottwinmaker/src/types.ts
This PR adds TwinMaker Knowledge Graph DataSource for the source-iottwinmaker package. The datasource rely on the ExecuteQueryCommand API.
> feat(Knowledge Graph Comp): Knowledge Graph DataSource

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/actions/settings.tsx
- packages/dashboard/src/components/actions/useGridSettings.spec.tsx
- packages/dashboard/src/components/actions/useGridSettings.ts
- packages/dashboard/src/components/util/labeledInput.tsx
- packages/dashboard/src/store/actions/changeDashboardGrid/changeStretchToFit.spec.ts
- packages/dashboard/src/store/actions/changeDashboardGrid/changeStretchToFit.ts
- packages/dashboard/src/store/actions/changeDashboardGrid/index.ts
- packages/dashboard/src/store/actions/index.ts
- packages/dashboard/src/store/reducer.ts
Adds a toggle in actions that will show a dashboard settings modal. This modal can be used to configure the grid settings of the dashboard. The settings toggle is only visible in edit mode as it may affect the widget positions.
> feat(dashboard): add grid settings configuration ux

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
Close overlay should not auto select the attached Tag, but should keep the current selection
before
https://github.com/awslabs/iot-app-kit/assets/9315598/aff76f95-ea2a-47c4-98c0-e6f65424b4c3
after
https://github.com/awslabs/iot-app-kit/assets/9315598/8c7a2ad4-8f41-4d88-8523-424979ec47aa
```
httpserver
```
This project is …
> fix(composer): close overlay auto select attached tag

- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- Added check for Matterport model Id to fix the issue with initial loading of a scene with Matterport space
```
httpserver
```
> fix(composer): initial loading of Matterport scene

- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/scene-components/DataBindingComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/common/DataBindingMapEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/utils/dataBindingTemplateUtils.spec.ts
- packages/scene-composer/src/utils/dataBindingTemplateUtils.ts
This PR contains following changes,
* Logic to removed components and properties from data binding.
* Logic On the onSelelctionChangeEvent, take entityId from the data binding and provide it to the additionalDatacomponent variable.
* Unit tests.
* Tested on console.
* npm run test
> feat(3dkg): added 3dkg changes for entity data binding

- packages/scene-composer/src/augmentations/components/three-fiber/common/SvgIconToWidgetSprite.spec.tsx
- packages/scene-composer/src/components/__snapshots__/SceneComposerInternal.spec.tsx.snap
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
- packages/scene-composer/src/layouts/SceneLayout/components/FoldableContainer.tsx
- packages/scene-composer/src/layouts/SceneLayout/components/ScenePanel.tsx
- packages/scene-composer/src/layouts/SceneLayout/components/__snapshots__/ScenePanel.spec.tsx.snap
Updating default collapse behavior to only apply to `SceneViewer` left panel.
https://github.com/awslabs/iot-app-kit/assets/6610619/6b5014ed-a786-43eb-a55c-c59bda65fbcf
```
httpserver
```
> fix(scene composer): modifying auto collapse to only apply to viewer

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
Fix the issues:
- click on Tag in 3D scene doesn't select the Tag
- mouse down somewhere, move the camera, release mouse over the overlay or annotation, the camera continues tracking with the mouse until clicking again
```
httpserver
``` …
> fix(composer): click events for tag and overlay

- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/tests/StateManager.spec.tsx
Fix the issue when the composer is unmounted, the queries are still happening
```
httpserver
```
> fix(composer): unsubscribe to queries when unmounting

- packages/scene-composer/.eslintrc.js
- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/CommonPanelComponents.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.spec.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/panels/scene-components/DataBindingComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/DataBindingComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/AnchorComponentEditor.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/common/DataBindingMapEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/common/DataBindingMapEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.tsx
- packages/scene-composer/src/components/panels/scene-components/common/__snapshots__/DataBindingMapEditorSnap.spec.tsx.snap
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/internalInterfaces.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
This PR contains following changes,
UI changes for entity data binding.
Rearranged the imports.
Unit tests
* npm run test
* added unit tests
```
httpserver
```
> feat(scene composer): entity data binding UI changes and unit tests

- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.tsx
Entity search functionality for free text was broken for entity data binding. This cr contains the fix for this bug. 
* npm run test
* npm run build
* Manual testing
```
httpserver
```
> feat(scene composer): fixed entity search bug using free text

- packages/react-components/src/components/knowledge-graph/KnowledgeGraphPanel.tsx
- packages/react-components/src/components/knowledge-graph/index.ts
- Emit and event that other widgets (like the scene viewer) can listen to so that they know to clear their graph based visual items (like 3D highlights)
- Update graph result events to support emitting multiple entities.
This will allow a react developer to highlight multiple items in a linked scene such as 'all roof top units'.
```
httpserver
``` …
> feat(Knowledge Graph): adding clear and render graph results events

- .github/dependabot.yml
Too many Dependabot changes coming in and failing. This change updates the frequency to weekly on Tuesdays (https://en.wikipedia.org/wiki/Patch_Tuesday).
> chore: dependabot updates weekly on tuesdays

- packages/scene-composer/public/CookieFactoryWaterTank.scene.json
- packages/scene-composer/src/SceneViewer.spec.tsx
- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.spec.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/panels/ComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/ComponentEditor.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/panels/__snapshots__/ComponentEditor.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/EntityBindingComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/EntityBindingComponentEditor.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/Store.ts
- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/internalInterfaces.ts
- packages/scene-composer/tests/scenes/CookieFactoryWaterTank.json
Rename DataBinding Component to EntityBinding. Some UX that are generic DataBinding will still be named that.
This will change the Scene.json text strings and BREAK all existing demo scene using 'DataBinding' as the string for EntityBinding
Unit test passes now
Storybook manual test for Highlight passes
```
httpserver
``` …
> feat(3D Knowledge Graph): update DataBinding to EntityBinding release 3x

- packages/scene-composer/public/CookieFactoryWaterTank.scene.json
- packages/scene-composer/src/SceneViewer.spec.tsx
- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/components/SceneComposerInternal.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.spec.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/panels/ComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/ComponentEditor.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/panels/__snapshots__/ComponentEditor.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/EntityBindingComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/EntityBindingComponentEditor.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/Store.ts
- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/internalInterfaces.ts
- packages/scene-composer/tests/scenes/CookieFactoryWaterTank.json
Rename DataBinding Component to EntityBinding.  Some UX that are generic DataBinding will still be named that.
This will change the Scene.json text strings and BREAK all existing demo scene using 'DataBinding' as the string for EntityBinding
Unit test passes now
Storybook manual test for Highlight passes
```
httpserver
``` …
> feat(3D Knowledge Graph): update DataBinding to EntityBinding

- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/lineChart/component.tsx
- packages/dashboard/src/customization/widgets/scatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/utils/computeQueryConfigKey.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
fixing the issue of graphs flashing on adding/removing a query.
1. removed the key prop
2. removed the settimeout within the react hook `useTimeSeriesData`
refer the screencapture above
```
httpserver
``` …
> fix(dashboard): fixed the flash of graphs on change in query(s)

- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/lineChart/component.tsx
- packages/dashboard/src/customization/widgets/scatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/utils/computeQueryConfigKey.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
Reverts awslabs/iot-app-kit#1659
looks like the change in the `useTimeSeriesData` hook removed a `setTimeout` which handled unsubscribing from the data provider which caused a regression
sev2 ticket opened as it is customer impacting.
> fix: Revert "fix(dashboard): fixed the flash of graphs on change in query(s)"

- packages/react-components/src/hooks/useTimeSeriesData/providerStore.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
Because the provider unsubscribe call must be done asynchronously, there is a bug where when the queries are updated, the provider ref is subscribed to and immediately unsubscribed to. This is because the ref utilized in the setTimeout gets updated to the new one. This leaves the previous provider orphaned. This change moves the provider from the react ref to a singleton store. This way we don't lose reference to it when the queries change. 
> fix(react-components): ensure provider is unsubscribed correctly

- .github/workflows/release-please.yml
The latest release for the release-please action is not running correctly. This locks the version to the last working version so we can continue to release code while the action is debugged.
> fix(actions): lock release please to version

- packages/scene-composer/README.md
- packages/scene-composer/stories/components/argTypes.ts
- packages/scene-composer/stories/components/hooks/useDatasource.ts
- packages/scene-composer/stories/components/hooks/useLoader.ts
- packages/scene-composer/stories/components/scene-composer.tsx
Add support for AWS Scenes in the Scene Composer storybook to pull live data from AWS via the iot-app-kit data query system.
From the Readme update: 
If you want to have an AWS Scene pull live data from your TwinMaker workspace you can add a queryJson to the storybook arguments.  Because it's a JSON and not kept as part of the URL parameters the query will have to be reset if you refresh the page.  Below is an example query for a single TwinMaker property value.
```bash
[
{
"entityId": "f913470a-d011-45ca-ac84-3265f6327105",
"componentName": "MetabolicCageOne",
"properties": [{ "propertyName": "Temperature" }]
}
]
```
When using an query for live data the default data range is the last 5 minutes.  You can change this by setting the viewportDurationSecs fields to a custom value.  The field …
> chore(scene): add DataQuery field to storybook for testing options

- packages/dashboard/testing/clients.ts
- packages/dashboard/testing/constants.ts
- packages/dashboard/testing/siteWiseQueries.ts
- turbo.json
This change is a fix to enable the dashboard testing environment to correctly consume the REGION env variable.
> fix: use REGION env variable in dashboard testing environment

- packages/scene-composer/stories/components/hooks/useSceneMetadataModule.ts
- packages/scene-composer/stories/components/scene-composer.tsx
- packages/scene-composer/stories/components/theme-manager.tsx
fix infinite storybook component update that's causing infinite getScene API call when visiting scene settings panel
```
httpserver
```
> fix(composer): fix infinite storybook component update

- packages/scene-composer/src/components/three-fiber/controls/OrbitControls.tsx
A customer brought a 3D model with complex geometry that caused a lot of lag when interacted with in the Scene Composer. The root cause is the raycaster intersection is taking too long.
Updated the Scene Composer's raycaster to ignore nullish faces when calculating intersections. The raycaster is also disabled on scroll since no other mouse interaction that would require the raycaster is necessary on scroll. It is re-enabled on mouse click/pointerdown.
Added 3D models to a real TwinMaker scene that I loaded into storybook. The small but complex model with issues can be interacted with at 120 FPS with this change.
Also tested many other small, large, simple, and complex glTFs/glbs in the scene composer. There is a considerable difference with this change. This also improves the performance …
> fix(scene-composer): update raycaster in OrbitControls

- packages/scene-composer/src/assets/anchors/IconSvgs.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/__snapshots__/AnchorWidget.spec.tsx.snap
- packages/scene-composer/src/common/constants.ts
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/AnchorComponentEditor.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/ColorPickerStyles.ts
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/DecodeSvgString.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/DecodeSvgString.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/SvgParserHelper.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/SvgParserHelper.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/TagColors.ts
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/useSvgParser.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/useSvgParser.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/interface.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetIconEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/SceneRuleTargetIconEditor.spec.tsx
- packages/scene-composer/src/components/three-fiber/AnchorComponent/index.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/polarisUtils.ts
- packages/scene-composer/src/utils/sceneResourceUtils.ts
- packages/scene-composer/src/utils/styleUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
* Added fac flag to toggle the feature.
* Addec color picker component to show basic colors and advanced colors using react-color.
* Added a hook that fills the color and return an img 
* Added logic reflect the chosen color on the 3D object.
* Added all unit test cases.
```
httpserver
```
This project is available under …
> feat(scene composer): color picker changes

- .github/dependabot.yml
- examples/react-app/src/components/SceneViewer.tsx
- examples/react-app/src/configs.ts
- examples/react-app/src/pages/Home/index.tsx
- packages/components/package.json
- packages/related-table/package.json
- packages/scene-composer/package.json
- packages/scene-composer/src/components/SceneComposerInternal.tsx
- packages/scene-composer/stories/components/scene-composer.tsx
- packages/scene-composer/tests/setup-jest.ts
Integrate scene viewer with TimeSync viewport so that consumers can use TimeSync and TimeSelection to control the viewport used by SceneViewer, instead of passing viewport into SceneViewer.
Also downgraded @awsui/design-tokens to fix dark mode.
```
httpserver
``` …
> feat(composer): integrate scene viewer with TimeSync viewport

- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/source-iottwinmaker/src/data-binding-provider/EntityPropertyBindingProviderStore.spec.ts
- packages/source-iottwinmaker/src/data-binding-provider/EntityPropertyBindingProviderStore.ts
- packages/source-iottwinmaker/src/data-binding-provider/createEntityPropertyBindingProvider.ts
- packages/source-iottwinmaker/src/data-binding-provider/types.ts
Add the isStaticData flag to data binding to help determine which UDQ API should be called when fetching data for the binding
```
httpserver
```
> feat(TM-source): flag static property data binding

- packages/scene-composer/src/hooks/useBindingQueries.spec.ts
- packages/scene-composer/src/hooks/useBindingQueries.ts
add hook to convert data bindings to queries
```
httpserver
```
> feat(composer): add hook to convert data bindings to queries

- packages/scene-composer/src/components/three-fiber/controls/OrbitControls.tsx
There is a bug where you cannot click on a tag because the raycaster is ignoring intersections for objects with a nullish face. Added logic to accept intersections with `Sprite` objects.
Removed logic to disable raycaster on a wheel/scroll event. This would mean users have to click twice after a scroll to select something in the scene.
Tested with storybook. Added all widgets types to a complex object and was able to click on all of them. Scrolling is a little slow when directly on a complex object, but it is not too bad. Orbiting and panning is still very fast.
https://github.com/awslabs/iot-app-kit/assets/87385528/9eaa6a7d-2438-4eac-806a-4b688f3bcf2d
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for …
> fix(scene-composer): fix ability to click on tags, revert disable on scroll

- release-please-config.json
Update `group-name` to `groupName` to fix the `Cannot read properties of undefined (reading 'replace')` error.
The release-please action either has recently changed the field name or has this wrong doc for a while which caused the confusion https://github.com/googleapis/release-please/commit/bdd9b0158ce79d958da01ebf54cb6b07925bc125
```
httpserver
``` …
> chore: fix release-please config

- packages/scene-composer/src/assets/anchors/IconSvgs.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/__snapshots__/AnchorWidget.spec.tsx.snap
- packages/scene-composer/src/common/constants.ts
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/AnchorComponentEditor.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/ColorPickerStyles.ts
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/DecodeSvgString.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/DecodeSvgString.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/SvgParserHelper.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/SvgParserHelper.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/TagColors.ts
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/useSvgParser.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/useSvgParser.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/interface.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetIconEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/SceneRuleTargetIconEditor.spec.tsx
- packages/scene-composer/src/components/three-fiber/AnchorComponent/index.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/polarisUtils.ts
- packages/scene-composer/src/utils/styleUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
* Request to merge color picker changes from main to release-3.x.
```
httpserver
```
> feat(scene composer): Color picker release 3.x

- examples/react-app/src/components/SceneViewer.tsx
A css was added to the react example's scene viewer component but it got removed in a merge conflict.
Run react-example and verify that the scene panel displays with full height and isn't squished down.
```
httpserver
``` …
> fix(reactExample): fix removed css in Scene Viewer Component

- packages/dashboard/src/components/queryEditor/__tests__/advancedSearch.spec.tsx
- packages/dashboard/src/components/queryEditor/advancedSearch/advancedResultsTable/advancedResultsTable.tsx
- packages/dashboard/src/components/queryEditor/advancedSearch/advancedResultsTable/index.ts
- packages/dashboard/src/components/queryEditor/advancedSearch/advancedResultsTable/tableConfig.ts
- packages/dashboard/src/components/queryEditor/advancedSearch/advancedSearch.tsx
- packages/dashboard/src/components/queryEditor/advancedSearch/model/property.ts
- packages/dashboard/src/components/queryEditor/queryEditor.tsx
- packages/react-components/src/components/knowledge-graph/KnowledgeGraphQueries.ts
Adding advanced search mode to the query editor. This change adds two tabs to the resource exploration experience. The first is the existing query editor experience that allows drill-down exploration of assets and multi selection to choose properties. The second tab is the new advanced search which uses TwinMaker's KnowledgeGraph API's for efficiently searching through a large number of assets and properties to aid in selecting a property to add to a dashboard.
Some followups I will do:
* Using i18n strings
* Including assetName in table
`<QueryEditor />` can replace `<ResourceExplorer /> ` in the internal dashboard implementation to view an example in our storybook or use in other components. QueryEditor will require a sitewise client and optionally the TwinMaker data source to work. …
> feat(dashboard): add advanced search using knowledge graph to query editor

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneRulesPanel.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetIconEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/SceneRuleTargetEditor.spec.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/sceneResourceUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
* This changes contain rules updated with color picker, 
* removed unwanted hooks from color picker. It does not depend on external variables or props. So adding useCallback does not add value. 
* sufficient unit tests
* https://testrail.twinmaker.iot.aws.dev/index.php?/auth/login/L2Rhc2hib2FyZC1hZDcwMmI4MTlkYmVjOGU3ZDcyYWIwZjI3MjA2YmZkY2FhYWFjZjYxMjFiZDYxYTZlYWY4N2ViNDVmZjViNTRk
* Verified color picker renders upon selecting the custom style.
* Verified color picker display basic colors and + buttons
* Verified Clicking on + opens up chrome picker
* Verified selecting a color from chrome picker
* Verified selecting a color from basic colors
* Verified color code saves with rule target
* Verified no regressions.
For `scene-composer` package …
> feat(scene composer): Added color picker to rules

- packages/react-components/package.json
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/contextMenu/ChartContextMenu.spec.tsx
- packages/react-components/src/components/chart/contextMenu/ChartContextMenu.tsx
- packages/react-components/src/components/chart/hooks/useTrendCursors.ts
- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/tests/useTrendCursorsEvents.spec.tsx
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/chart/utils/getInfo.ts
Adding context menu for charts. this will be per chart i.e when in dashboard this will not be shown instead the dashboard will be updated with the TC options in the follow up CR. 
Refer to the screen capture
https://github.com/awslabs/iot-app-kit/assets/135036199/76a8f5e2-6daa-45b6-9fb6-e46372f96cd0
> feat(react-component): adding context menu per chart

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/common/SvgIconToWidgetSprite.spec.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/common/SvgIconToWidgetSprite.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.tsx
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
Add missing dependency to ValueDataBindingBuilder so it won't revert changes unexpectedly.
Fix warning caused by THREE.Cache.remove().
Tag custom style after change is still working
https://github.com/awslabs/iot-app-kit/assets/9315598/1a0974c3-3ec6-43fb-977a-f34e2c62d713
```
httpserver
```
This project is available under …
> fix(composer): fix warning and cached onChange

- packages/scene-composer/src/utils/dataBindingVariableUtils.spec.ts
- packages/scene-composer/src/utils/dataBindingVariableUtils.ts
- release-please-config.json
Merge https://github.com/awslabs/iot-app-kit/pull/1770 into release-3.x
- fix the issue where 0 will be displayed as "-" in overlay
```
httpserver
```
> fix(composer): fix issue displaying 0 in overlay

- packages/scene-composer/src/components/StateManager.spec.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayComponent.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayComponentSnap.spec.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/utils/eventDataUtils.spec.ts
- packages/scene-composer/src/utils/eventDataUtils.ts
Click an overlay doesn't have data binding information in the onSelectionChange event fired from the SceneViewer and the onWidgetClick event is fired at all.
Create scene with dataoverlay that has 2+ data bindings added to it.
Connect to scene in SceneViewer mode on storybook
Click the overlay widget
verify that the storybook actions log both selection and widget change events with databindings that look like this for array of 2 data bindings:
To run the storybook build locally, you need a local static web …
> fix(data overlay): add onWidgetClick and onSelectionChange event support to data overlays

- packages/scene-composer/src/components/panels/SceneRulesPanel.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetIconEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/SceneRuleTargetEditor.spec.tsx
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/sceneResourceUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
* merging rule changes from release-3.x to main branch.
```
httpserver
```
> feat(scene composer): rule icon using color picker

- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayComponent.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayComponentSnap.spec.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/utils/eventDataUtils.spec.ts
- packages/scene-composer/src/utils/eventDataUtils.ts
- packages/scene-composer/tests/StateManager.spec.tsx
Click an overlay doesn't have data binding information in the onSelectionChange event fired from the SceneViewer and the onWidgetClick event is fired at all.
Ports change to release 3.x as well
Create scene with dataoverlay that has 2+ data bindings added to it.
Connect to scene in SceneViewer mode on storybook
Click the overlay widget
verify that the storybook actions log both selection and widget change events with databindings that look like this for array of 2 data bindings:
To run the storybook build …
> fix(data overlay): add onWidgetClick and onSelectionChange event support to release 3.x

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/hooks/useTrendCursors.ts
- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/tests/getTrendCursor.spec.tsx
- packages/react-components/src/components/chart/tests/handleResize.spec.tsx
- packages/react-components/src/components/chart/tests/useTrendCursorsEvents.spec.tsx
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/chart/utils/getInfo.ts
- packages/react-components/src/components/chart/utils/getTrendCursor.ts
- packages/react-components/src/components/chart/utils/handleResize.ts
- packages/react-components/src/components/chart/utils/handleSync.ts
removing the dependency of the yMin and Ymax and reading the series line markers for TC from echarts
No net new changes except that instead of ymin and ymax, reading the pixel value from echarts
> fix(react-component): removing the dependency of the yMin and Ymax and reading the series line markers for TC from echarts

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/converters/convertOptions.ts
- packages/react-components/src/components/chart/converters/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/converters/convertStyles.spec.tsx
- packages/react-components/src/components/chart/converters/convertStyles.ts
- packages/react-components/src/components/chart/converters/converters.spec.ts
- packages/react-components/src/components/chart/hooks/useChartId.ts
- packages/react-components/src/components/chart/hooks/useChartSetOptionSettings.ts
- packages/react-components/src/components/chart/tests/getInfo.spec.tsx
- packages/react-components/src/components/chart/tests/handleSync.spec.tsx
- packages/react-components/src/components/chart/tests/useTrendCursorsEvents.spec.tsx
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/chart/utils/getColor.ts
- packages/react-components/src/components/chart/utils/getInfo.ts
- packages/react-components/src/components/chart/utils/getStyles.ts
- packages/react-components/src/hooks/useECharts/index.ts
- packages/react-components/src/hooks/useECharts/useEChartOptions.ts
- packages/react-components/src/hooks/useECharts/useECharts.tsx
- packages/react-components/src/hooks/useECharts/useGroupableEchart.ts
- packages/react-components/src/hooks/useECharts/useLoadableEChart.ts
- packages/react-components/src/hooks/useECharts/useResizeableEChart.ts
- packages/react-components/stories/chart/base-chart.stories.tsx
- packages/react-components/stories/chart/chart.stories.tsx
Many structural changes included in this PR.
useECharts has been split into several smaller hooks.
1. useEcharts -> initializes echarts and attaches to the dom
2. useResizeableEChart -> handles resizing of the chart and updating echart
3. useGroupableEChart -> updates the echarts groupid
4. useLoadableEChart -> updates the loading animation state
5. useEChartOptions -> handles updating echarts options
* added a hook for deriving a chart id
* added a hook for calculated style settings for each datastream
* added a hook for converted series and yAxis
moved base chart stories into a separate story so that we can utilize styorbook argtypes which allow us to more easily test prop reactivity. …
> fix(react-components): add memoization for chart reactivity and refactor echarts hook

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
- packages/scene-composer/src/components/three-fiber/AnchorComponent/__tests__/__snapshots__/AnchorComponent.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/AnchorComponent/index.tsx
- packages/scene-composer/src/components/three-fiber/ColorOverlayComponent/__tests__/ColorOverlayComponent.spec.tsx
- packages/scene-composer/src/components/three-fiber/ColorOverlayComponent/index.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayDataRow.tsx
- packages/scene-composer/src/components/three-fiber/MotionIndicatorComponent/MotionIndicatorComponent.tsx
- packages/scene-composer/src/hooks/useBindingData.ts
- packages/scene-composer/src/hooks/useRuleResult.spec.ts
- packages/scene-composer/src/hooks/useRuleResult.ts
- packages/scene-composer/src/utils/dataBindingUtils.spec.ts
- packages/scene-composer/src/utils/dataBindingUtils.ts
- packages/scene-composer/src/utils/dataBindingVariableUtils.ts
support auto query feature for model shader component
https://github.com/awslabs/iot-app-kit/assets/9315598/09abd434-4035-4768-a65e-5ba08c61474a
```
httpserver
```
> feat(composer): auto query support for Model Shader

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/__snapshots__/AnchorWidget.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetEditor.tsx
This change contains the fix to rule with custom icon color.
1. Verify tag color changes if rule meets the criteria.
2. Verify tag color does not change if rule does not meet criteria.
3. Verify when rule does not meet, it shows default custom color for tags.
* unit tests
https://github.com/awslabs/iot-app-kit/assets/54058998/ccd834c7-a22b-4249-b842-0325607cdcf7
```
httpserver
```
Then …
> fix(Tag style): custom color to support icon rules

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayComponent.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayComponentSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayContainerSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/styles.ts
There is an extra invisible space below the overlay and a section on the overlay (the arrow) where if user clicks tag is not getting selected. Updated the overlay arrow CSS to keep the same visuals but the entire area clickable.
Create a tag. Add an overlay to the tag using the node inspector in the Scene Composer.
Click on the tag to show the overlay panel. Click on the tag below the panel, but to the right or left of the arrow, to deselect it. Click on the arrow at the bottom of the panel to reselect the tag. Should be able to click anywhere on the tag to select/deselect, and anywhere on the panel including the arrow to reselect the tag.
https://github.com/awslabs/iot-app-kit/assets/87385528/fbcbf8a5-b7af-43a2-9254-cd1f66b68fe3
For `scene-composer` package changes specifically, you can …
> fix(scene composer): fix overlay arrow clickable space

- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/utils/getTrendCursor.ts
- packages/react-components/src/components/chart/utils/handleViewport.ts
adding transition for TCs is causing lot of issues for resizing and sync functionalities, removing it for now, will circle back after getting some user back. 
right now, UX - @navita is ok to not have a smooth transition
> fix(react-component): removing transition animation for trend cursors

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/SvgParserHelper.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/interface.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetIconEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/SceneRuleTargetEditor.spec.tsx
- packages/scene-composer/src/components/three-fiber/AnchorComponent/index.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/eventDataUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
* bug fixes for color picker
```
httpserver
```
> fix(scene composer): Color picker bug fixes

- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/__snapshots__/SceneRuleTargetEditor.spec.tsx.snap
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/utils/sceneResourceUtils.ts
* remove unused animation option from the rule option. 
```
httpserver
```
> fix(scene composer): fix for broken rule panel

- packages/scene-composer/src/components/three-fiber/hooks/useProgress.spec.tsx
- packages/scene-composer/src/components/three-fiber/hooks/useProgress.tsx
This change contains fix for showing asset bytes downloading status. Initially we were hardcoding it to 0. Now are calculating based on downloaded and already loaded bytes. 
```
httpserver
```
> fix(Load manager): fixed the downloaded bytes onProgress call

- packages/source-iottwinmaker/src/property-value/provider.ts
fix tanstack query import to be from @tanstack/query-core instead of @tanstack/react-query
```
httpserver
```
> fix(TM-source): fix tanstack query import

- packages/scene-composer/package.json
- packages/scene-composer/src/hooks/useBindingData.spec.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
removed unused `OpacityFilter` and `Space` scene component types
```
httpserver
```
> chore(composer): removed unused scene component types

- packages/dashboard/package.json
Reverts awslabs/iot-app-kit#1838 as  `@storybook/addon-styling` version 1.3.7 does not exists internally
> chore(deps-dev): Revert "build(deps-dev): bump @storybook/addon-styling from 1.3.1 to 1.3.7"

- packages/react-components/src/components/menu/menu.css
- packages/scene-composer/package.json
- Upgraded the sass-loader version
- Fixed the RGBA syntax for box-shadow style
> fix(CSS-Loader): updated sass-loader & fixed style

- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/models/SceneModels.ts
- Remove `ILightShadowSettings` because it's not supported right now https://github.com/awslabs/iot-app-kit/blob/main/packages/scene-composer/src/components/three-fiber/LightComponent/lights/DirectionalLight.tsx#L14
- Make type of SubModelRefComponent.selector a string only
```
httpserver
```
This project is available …
> chore(composer): remove unused light shadow setting

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/__snapshots__/AnchorWidget.spec.tsx.snap
Problem: Tags don't consistently triggering onWidgetClicked even though they do onSelectionChange reliably.  
Cause: an Anchor is actually a group with two parts in it: the anchor (circle) and a LineSegment (the white stem ). Only the anchor has onClick eventing.
Solution:  Adding the same onClick handler to the line segment as well allows the onWidgetClick to trigger no matter what part of the anchor is clicked.  
1. Story book scene composer scene with an entity bound tag
2. Move camera to where you can see the tag AND the white stem
3. Click on both the tag and the white stem and observe that both the selectionChanged and widgetClicked events fire in the story book action log.
For `scene-composer` package changes specifically, you can preview the component in the published storybook …
> fix(scene tags): fix anchor stems not triggering onWidgetClick

- packages/dashboard/src/customization/api.ts
- packages/dashboard/src/customization/widgets/lineSymbol/__snapshots__/component.test.tsx.snap
- packages/dashboard/src/customization/widgets/lineSymbol/component.css
- packages/dashboard/src/customization/widgets/lineSymbol/component.test.tsx
- packages/dashboard/src/customization/widgets/lineSymbol/component.tsx
- packages/dashboard/src/customization/widgets/lineSymbol/icon.tsx
- packages/dashboard/src/customization/widgets/lineSymbol/lineAnchor/component.css
- packages/dashboard/src/customization/widgets/lineSymbol/lineAnchor/component.tsx
- packages/dashboard/src/customization/widgets/lineSymbol/plugin.tsx
- packages/dashboard/src/customization/widgets/rectangleSymbol/component.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/dashboard/testing/mocks.ts
This PR is for the line symbol widget. It allows the user to drag and drop a line. The line can be manipulated using the anchors at its ends.
Currently, the line is limited to its bounding box: the bouding box has to be resized to allow a larger line. This is not the final state - in a future PR, the bounding box will be invisible except for during multiple selection and the line will be able to be placed anywhere regardless of it.
Refer to the screen recording below:
https://github.com/awslabs/iot-app-kit/assets/34567765/3d885d29-2d1b-4168-af0b-52e529949029
> feat(dashboard): line symbol

- packages/scene-composer/package.json
- packages/source-iottwinmaker/src/__mocks__/iottwinmakerSDK.ts
- packages/source-iottwinmaker/src/data-binding-provider/EntityPropertyBindingProviderStore.spec.ts
- packages/source-iottwinmaker/src/data-binding-provider/EntityPropertyBindingProviderStore.ts
- packages/source-iottwinmaker/src/metadata-module/TwinMakerMetadataModule.ts
- packages/source-iottwinmaker/src/scene-module/SceneMetadataModule.spec.ts
- packages/source-iottwinmaker/src/scene-module/SceneMetadataModule.ts
- packages/source-iottwinmaker/src/types.ts
add entity APIs to SceneMetadataModule so scene composer has access to those APIs
```
httpserver
```
> feat(TM-source): add entity APIs to SceneMetadataModule

- .github/dependabot.yml
Disable dependabot to not auto update dependencies due to inconsistencies caused in internal repo
> chore(deps): disable dependabot to not auto update dependencies

- packages/core/package.json
This reverts awslabs/iot-app-kit#1869 to fix the internal repo build issue.
> build(deps-dev): Revert "build(deps-dev): bump @types/d3-array from 3.0.5 to 3.0.7"

- packages/scene-composer/package.json
This reverts commit 7465ddb51685d2f3cbfb88f665802cfd4b19ae3c to fix the internal repo build issue.
> build(deps-dev): Revert "build(deps-dev): bump @babel/preset-env from 7.22.5 to 7.22.15"

- packages/scene-composer/package.json
- packages/scene-composer/src/common/entityModelConstants.ts
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/MatterportTagSync.spec.tsx.snap
- packages/scene-composer/src/hooks/useDynamicScene.spec.tsx
- packages/scene-composer/src/hooks/useDynamicScene.ts
- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/internalInterfaces.ts
- packages/scene-composer/src/utils/entityModelUtils/dataBindingUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/dataBindingUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/overlayComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/overlayComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneLayerUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneLayerUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
support sync matterport tag as entities
```
httpserver
```
> feat(composer): support sync matterport tag as entities

- packages/dashboard/src/customization/widgets/table/component.tsx
Wrapped table component into div and stopped onMouseDown event propagation to the parent to stop dragging the table widget while resizing the columns
> fix: resolved table widget column resize issue

- packages/react-components/src/hooks/useECharts/useResizeableEChart.ts
This is to fix the drag issue of resize handle of the echarts in dashboard
> fix(react-components): echarts resize drag fix

- packages/scene-composer/src/components/three-fiber/MotionIndicatorComponent/MotionIndicatorComponent.tsx
Fix the error when switching motion indicator appearance between background and foreground color
```
httpserver
```
> fix(composer): error when switching motion indicator appearance

- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/store/state.ts
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
Updating the initial dashboard viewport default to be 10 minutes instead of 5.
> feat(dashboard): change dashboard viewport default from 5m to 10m

- packages/dashboard/src/components/widgets/tile/index.ts
- packages/dashboard/src/components/widgets/tile/tile.css
- packages/dashboard/src/components/widgets/tile/tile.spec.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/components/widgets/widget.css
- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/lineChart/component.tsx
- packages/dashboard/src/customization/widgets/scatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/hooks/useDeleteWidgets.ts
Adds a tile overlay to line / scatter / bar / status / timeline widgets which displays a title and a remove button. The title overlay is used in the plugin so that it is configurable by any extensibility options.
> feat(dashboard): add widget tile

- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/table/constants.ts
- packages/dashboard/src/customization/widgets/table/plugin.tsx
- packages/dashboard/src/customization/widgets/table/table-config.tsx
- packages/react-components/src/components/table/constants.ts
- packages/react-components/src/components/table/table.tsx
- packages/react-components/src/components/table/tableBase.tsx
- packages/react-components/src/components/table/types.ts
adding the pagination to the table widget and it includes
1. table widget pagination with 20 properties per page as default
2. Sorting is removed for the table widget columns
3. Table header is now sticky
4. Table has view upto 10 properties after that scroll will come
refer to the screen capture
> feat: table widget pagination and sorting disabled

- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
sync tag style from matterport tag only when flag is on
```
httpserver
```
> fix(composer): matterport tag sync tag style under flag

- packages/dashboard/src/components/internalDashboard/collapsiblePanel.spec.tsx
- packages/dashboard/src/components/internalDashboard/collapsiblePanel.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/components/resizablePanes/index.css
- packages/dashboard/src/components/resizablePanes/index.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.css
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.spec.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.tsx
Updated the side panels to expand only when clicking the panel icon and collapse when clicking the arrow button. 
Stories:
* As a user, I can collapse the resource explorer and configuration panel by clicking the collapse arrow at the top of the panel.
* As a user, I don't want the panels to collapse and expand based on the selection state.
Tested with storybook, see the video below.
https://github.com/awslabs/iot-app-kit/assets/87385528/416b4d21-64a7-47bd-b503-3c28001a90a8
To run the storybook build locally, …
> feat(dashboard): update collapsible side panels

- packages/scene-composer/src/components/three-fiber/EditorCamera.tsx
This address an known issue where a scene selection event sends an updated camera target to the Matterport Camera system and the camera moves to an unexpected location such as further away from tag selected.
To fix this we stop trying to send Matterport a desired camera location to look form and let Matterport calculate that internally instead. We only send Matterport's camera the target object location.
Storybook to a matterport scene with known incorrect behavior.
position camera in scene in place that causes known issue
open scene hierarchy
select tag that causes known issue
observe that behavior is improved.
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for the `Publish Storybook` action to …
> fix(matterport): fix zoom to tag

- packages/scene-composer/src/components/panels/CommonPanelComponents.tsx
- packages/scene-composer/src/components/panels/__tests__/__snapshots__/CommonPanelComponents.spec.tsx.snap
- packages/scene-composer/src/components/panels/__tests__/__snapshots__/SceneNodeInspectorPanel.spec.tsx.snap
The 3x3 matrix grid in the scene node inspector panel was not organized semantically correct. This made navigating it with a screen reader an impossible task.
Changes:
- Removed the FormField that wrapped around each row, Polaris recommends only one Input per FormField
- Programmatically associate each Input with a both appropriate labels ie. 'Position X' or 'Rotation Z'
Visual Changes:
Should be none
Pic 1: Before changes
Pic 2: After changes
To run the storybook build locally, you need a local static web …
> fix(composer): associate inputs to labels

- packages/react-components/jest.config.ts
- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/tests/getTrendCursor.spec.tsx
- packages/react-components/src/components/chart/tests/handleSync.spec.tsx
- packages/react-components/src/components/chart/tests/useTrendCursorsEvents.spec.tsx
- packages/react-components/src/components/chart/utils/getTrendCursor.ts
- packages/react-components/src/components/chart/utils/handleSync.ts
On Query change, due to the key change, the entire chart re-renders, this makes the TC default to no markers and X as 0. to avoid this, we check if the chart lines are rendered first and then we paint the TC
> fix(react-components): fix TC behaviour when there is a change in query

- packages/dashboard/src/components/widgets/tile/tile.css
- packages/dashboard/src/components/widgets/tile/tile.tsx
This CR is for the below ticket
https://github.com/awslabs/iot-app-kit/issues/1923
Removed the resize-area icon and related styles
> feat: remove drag icon in chat widget

- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/table/emptyTableComponent.spec.tsx
- packages/dashboard/src/customization/widgets/table/emptyTableComponent.tsx
- packages/react-components/src/components/table/table.tsx
- packages/react-components/src/components/table/tableBase.tsx
Added empty table state design with "No data to display" content.
Please note we have just added empty state design for the table whereas width & height will be taken care in another CR.
> feat: add fixed height and width for the table widget

- .github/workflows/npm-publish.yml
- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
For existing matterport scenes that has already synced tags into scene json file, create them as entities when dynamic scene is enabled and the sync button is clicked 
```
httpserver
```
> fix(composer): create existing matterport tag as entities

- packages/scene-composer/package.json
- packages/scene-composer/src/common/entityModelConstants.ts
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- create default $SCENES and $LAYERS entity roots for private beta. they will be created from backend for GA
- do not set selected node ref when adding matterport tag from sync button, so overlays will not all be opened during sync
```
httpserver
``` …
> fix(composer): create default entity roots

- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/MatterportTagSync.spec.tsx.snap
- packages/scene-composer/src/hooks/useMatterportTags.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
show sync matterport tag status for loading, error and success statuses
https://github.com/awslabs/iot-app-kit/assets/9315598/3db69d08-be71-48f0-9789-c6baf0d02a50
https://github.com/awslabs/iot-app-kit/assets/9315598/a72dd039-aff1-40c8-860b-938702a8c369
https://github.com/awslabs/iot-app-kit/assets/9315598/3be6b12b-22be-457f-964a-ee28a9c91ca1
```
httpserver
``` …
> fix(composer): show sync matterport tag status

- packages/scene-composer/src/components/three-fiber/SceneInfoView.tsx
- packages/scene-composer/src/components/toolbars/common/__snapshots__/ItemContainer.spec.tsx.snap
- packages/scene-composer/src/components/toolbars/common/styledComponents.ts
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
Fix a11y issue where the floating toolbar and the 'Scene Statistics' overlap badly when using a viewport of 360px wide and 256px tall. In addition, the bottom few items of the floating toolbar were completely inaccessible. A11y guidelines dictate all content should reflow or resize to be accessible at these viewport dimensions.
Changes:
- Add max-height to items in the floating toolbar, which is automatically overridden by any height passed in.
- For scenes less than 600px wide, adjust the position of the 'Scene Statistics.' Details of positioning are in code comments
Before, small viewport:
After, small viewport:
After, medium viewport:
After, large viewport (no change to current):
For `scene-composer` package changes specifically, you can preview the component in the published storybook …
> fix(composer): resize/reposition overlaps on small screens

- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/assets/emptyPanel.svg
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/emptyPanel.css
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/emptyPanel.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.spec.tsx
Added a centered icon for the empty state of the widget config panel.
https://github.com/awslabs/iot-app-kit/assets/87385528/0bdcf3eb-be43-4452-b6dc-7ef859f3854f
```
httpserver
```
> feat(dashboard): empty widget configuration panel

- packages/scene-composer/src/components/panels/SceneRulesPanel.tsx
To meet a11y guidelines, focus should move to the first form field in error upon form submission. This PR fixes this issue for the rules panel.
```
httpserver
```
> fix(composer): autofocus on error, rules panel

- packages/dashboard/src/components/internalDashboard/index.tsx
we were using two different timeSync components for edit/view mode, so the viewport would reset if you changed dashboard mode
> fix: use one timesync for all of dashboard

- packages/dashboard/src/customization/widgets/barChart/plugin.tsx
- packages/dashboard/src/customization/widgets/constants.ts
- packages/dashboard/src/customization/widgets/kpi/plugin.tsx
- packages/dashboard/src/customization/widgets/lineChart/plugin.tsx
- packages/dashboard/src/customization/widgets/scatterChart/plugin.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimelinePlugin.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/table/plugin.tsx
This PR is for the chart initial widget size updates. new changes include
Line, scatter, bar, timeline charts will have default size: height- 400, width- 650 and for KPI default size is set to: height-200 and width- 350
> feat: updated chart initial widget size

- packages/react-components/src/components/chart/converters/convertAxis.ts
- packages/react-components/src/components/chart/converters/converters.spec.ts
This fix fixes the x-axis toggle issue, now x-axis toggle will only toggle the visibility of the x-axis
> fix: x-axis toggle will toggle both x and y axis

- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.spec.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.tsx
- packages/dashboard/src/customization/widgets/utils/widgetAggregationUtils.ts
Removing all properties from a chart wont crash the chart anymore :) 
> fix(dashboard): removing all props wont crash chart

- packages/dashboard/testing/getEnvCredentials.ts
This change removes the requirement to set a session token when developing the dashboard locally, allowing usage of non-emphemeral AWS credentials.
> feat: make session token optional for local development

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/typeSection.tsx
This change is made for the bug #1978
Renamed the **step-after** to **step-end** to work as expected 
> fix: fixed step after chart type #1978

- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
Make padding in widget tile consistent
Disable property level y-axis min/max controls when they are not applied to the property
> fix(dashboard): fix styling for tile and config panel

- packages/dashboard/src/components/grid/gestures/useGridDragAndDrop.ts
While panning in edit mode, dashboard elements were being selected. Panning on the bar chart is performed by holding shift and dragging.
This PR disables dragging on the dashboard when the shift key is pressed down.
https://github.com/awslabs/iot-app-kit/assets/87385528/2e7587f2-7223-4af5-a9f7-b4a394d128af
```
httpserver
```
Then open the website http://localhost:8080 to run the doc …
> fix(dashboard): disable dashboard drag when shift key is pressed

- packages/scene-composer/src/common/entityModelConstants.ts
- packages/scene-composer/src/components/panels/CommonPanelComponents.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/common/DataBindingMapEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/data-overlay/DataBindingMapNameEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/data-overlay/DataBindingMapNameEditor.tsx
- packages/scene-composer/src/utils/entityModelUtils/dataBindingUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/dataBindingUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.ts
- update comppnent type id to be 1P version
- debounce component update to reduce UpdateEntity error
```
httpserver
```
> fix(composer): debounce component update to reduce UpdateEntity error

- packages/dashboard/src/customization/widgets/components/no-chart-data.css
- packages/dashboard/src/customization/widgets/components/no-chart-data.spec.tsx
- packages/dashboard/src/customization/widgets/components/no-chart-data.tsx
- packages/dashboard/src/customization/widgets/lineChart/component.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/scatterChart/component.tsx
This change is related to https://github.com/awslabs/iot-app-kit/issues/1919
Added empty state for line, and scatter widgets when there are no assets added to the respective widgets.
> feat: added empty state for line and scatter chart widgets

- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/table/table-config.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/table/table.tsx
adding the preferences for pagination to the table widget ( #1890 ) and it includes
1. preferences is available only in edit mode and not visible in preview mode
2. preferences will persist in preview mode which are applied in edit mode
3. preferences have 3 options (10, 20, 30)
refer to the screen capture
> feat: preferences for pagination in table widget

- packages/dashboard/e2e/tests/dashboard/dashboard.spec.ts
- packages/dashboard/src/components/confirmDeleteModal/index.spec.tsx
- packages/dashboard/src/components/confirmDeleteModal/index.tsx
- packages/dashboard/src/components/customOrangeButton/index.css
- packages/dashboard/src/components/customOrangeButton/index.spec.tsx
- packages/dashboard/src/components/customOrangeButton/index.tsx
- packages/dashboard/src/components/grid/gestures/usePointerTracker.ts
- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.test.tsx
- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.ts
- packages/dashboard/src/components/widgets/tile/tile.spec.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/styles/variables.css
Added confirm modal for delete widget when we click on (X) button on widget tile and click on the 'delete' button in the context menu and when we press 'backspace' or 'delete' buttons in the keyboard. Also, fixed widget dragging when we drag in X icon.
> feat: added delete widget confirm modal #1921

- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
synchro-charts widgets were being unmounted/remounted on viewport change (so all the time) removed the viewport from the key generation to prevent this issue with Synchro-charts
fixes broken gestures, time machine not applying, broken viewport sync across charts
> fix: fix broken synchro-charts widgets

- packages/scene-composer/src/components/panels/SceneRulesPanel.tsx
- packages/scene-composer/src/components/panels/__snapshots__/SceneRulesPanel.spec.tsx.snap
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Remediation for a11y violation. This is a bit of a hack to pass the necessary i18n strings to polaris, and should be updated once the scene-composer migrates from polaris to cloudscape. 
```
httpserver
```
> fix(composer): add aria labels to rules panel

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.css
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledSection.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/source-iotsitewise/src/time-series-data/types.ts
added ability to toggle property visibility in config panel and it includes
1. property toggle now toggles the properties on the chart
2. mouse over shows 'hide' or 'unhide' tooltip wrt property visibility status and also shows opposite visibility icons 
> feat: ability to toggle property visibility in config panel

- packages/dashboard/src/customization/propertiesSections/aggregationSettings/section.tsx
This change fixes a bug preventing changing resolution and aggregation settings for unmodeled data streams.
> fix: enable changing resolution and aggregation of unmodeled data streams

- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/react-components/src/components/chart/baseChart.tsx
Added legend prop to LineScatterChart that reads visible property controlled by toggle. It passes a empty object if true otherwise undefined. This gets read by the BaseChart component who has a conditional render of the legend depending on if the legend prop is defined. 
https://github.com/awslabs/iot-app-kit/assets/145582655/ef070b95-2ddc-4c8a-8139-fccbb77262a2
> fix: toggle working linechar

- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/SceneHierarchyTreeItem.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneHierarchyTreeItem.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditorSnap.spec.tsx
- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.ts
- packages/scene-composer/stories/components/scene-composer.tsx
- Fix node index calculation for static nodes saved to scene file
- Debounce more for dynamic node's transform input box updates
- Remove the extra UpdateEntity call when clicking sync button to update tags
- Disable drag and drop to dynamic nodes
```
httpserver
``` …
> fix(composer): bug fixes for dynamic scene

- packages/scene-composer/src/components/three-fiber/CameraComponent/index.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/hooks/useActiveCamera.ts
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/store/slices/EditorStateSlice.ts
- packages/scene-composer/src/utils/cameraUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/cameraComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/cameraComponent.ts
Add util functions to handle create/update camera component request, and parse camera from entity model back to scene component model.
```
httpserver
```
> feat(composer): utils to handle camera component in entity

- packages/scene-composer/src/components/three-fiber/EditorCamera.tsx
- packages/scene-composer/src/utils/controlUtils.spec.ts
- packages/scene-composer/src/utils/controlUtils.ts
When the camera mode is changed the camera is also returning to the position and target of the last camera command it received. For a fresh scene this is the starting location for example.
Video of Error:
https://github.com/awslabs/iot-app-kit/assets/109186219/5ff48342-1919-452d-b48f-85c64eb52462
Video of Fix:
https://github.com/awslabs/iot-app-kit/assets/109186219/e866463b-eae8-4c98-8510-c689f34535ca
Open story book scene.  Pan camera away from center.  Swap form orbit to pan camera mod.  The camera should stay where it was, but the controls should swap properly.
- …
> fix(scene): fix camera returning to last target on mode change

- packages/dashboard/src/components/dashboard/queryContext.ts
- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/utils/computeQueryConfigKey.ts
- packages/dashboard/src/customization/widgets/utils/createWidgetRenderKey.ts
This change removes viewport and query config from the widget render key, preventing unnecessary unmounting/mounting from viewport and query changes. Instead, the widget ID is utilized.
> fix: remove viewport and query from widget render key

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/useLatestValues/entryIdFactory.ts
This change adds additional handling to allow retrieval of the latest values in the query editor of unmodeled data streams with the typical `/1/2/3/4` slash-based property alias tag hierarchy. The property alias is being reused as a unique identifier for batch data requests and this is causing a 400 error to be thrown.
> fix: remove slashes from property alias when requesting latest in query editor

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/typeSection.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
Fix for updating the aggregation and resolution properties for line-scatter-widget. Update the setting and query in 1 method.
Also fix for the step after chart mapping.
> fix(dashboard): correctly update aggregation and resolution configs

- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/__snapshots__/SceneRuleTargetEditor.spec.tsx.snap
Currently TargetEditor layout has a grid layout. So in order to fit the icon-picker we don't have to use a `div` that will align the layout within the IconTargetEditor. So removing the div will fix the issue. 
npm run test
```
httpserver
``` …
> fix(icon rules): align icon-picker layout with target editor

- packages/scene-composer/src/components/toolbars/common/ToolbarItem.tsx
Remove useCallback from event handlers for the toolbar menu -- it's currently causing a bug requiring multiple clicks/keypresses to execute some actions.
```
httpserver
```
> fix(composer): remove useCallback from menu event handlers

- packages/scene-composer/src/utils/entityModelUtils/modelRefComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/modelRefComponent.ts
* crud functionalities for model ref component. 
Followed the design doc to implement the model ref functionalities. 
* Create a model ref.
* Update a model ref.
* Parse the component. 
npm run test:unit
```
httpserver
``` …
> feat(dynamic scene): crud functionalities for model ref

- packages/scene-composer/src/components/panels/scene-components/CameraComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/CameraComponentEditor.tsx
The camera view inspector panel will overwrite changes unexpectedly.
Changing one of the following four will reset all of the others back to default settings:
FOV, Zoom, Clipping Planes Far, Clipping Planes Near.
This fix makes it such that modifying FOV, Zoom, Clipping Planes Far, and Clipping Planes Near will not reset the other values back to default. Note: Focal length will be changed when FOV is changed; this is expected behavior.
Camera settings before fix:
https://github.com/awslabs/iot-app-kit/assets/87334439/a9005765-ca55-49c8-ad36-782b8609fb85
Camera settings after fix:
https://github.com/awslabs/iot-app-kit/assets/87334439/6c24c563-75d5-4c75-a4d5-12e39dd63db0
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To …
> fix(camera): stop camera view inspector panel from overwriting changes

- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdStyle.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
- packages/react-components/src/components/chart/converters/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/converters/convertThresholds.ts
- packages/react-components/src/components/chart/converters/converters.spec.ts
- packages/react-components/src/components/chart/converters/padYAxis.spec.ts
- packages/react-components/src/components/chart/converters/padYAxis.ts
When a threshold is defined higher than the max or lower than the min of the yAxis on the line and scatter chart it did not show up.
Updated the following:
* When there are no properties or property data customer can still add/edit/delete thresholds. They will just not be shown on the chart.
* When a threshold is set >max or <min and the y-axis is on "Auto" then the axis will be updated to have at least that max/min with some padding
* Thresholds will not work when multiple y-axis are on the chart. Will need to wait to get feedback about that feature in general and this will not be in scope.
* The default threshold style setting is line + filled region
Verified with unit tests and manual tests.
Some edge cases:
1. yAxis is set manually - manual min and/or max is always prioritized and …
> fix(dashboard): chart respects absolute min and max between data and thresholds

- packages/scene-composer/src/components/Tree/TreeItem.tsx
- packages/scene-composer/src/components/Tree/__tests__/TreeItem.spec.tsx
- packages/scene-composer/src/components/Tree/__tests__/__snapshots__/TreeItem.spec.tsx.snap
- packages/scene-composer/src/components/Tree/__tests__/__snapshots__/tree.spec.tsx.snap
- packages/scene-composer/src/components/Tree/__tests__/tree.spec.tsx
- packages/scene-composer/src/components/VisibilityToggle/index.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneHierarchyTreeItem.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTree.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTreeItemLabel.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/index.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
To meet a11y guidelines, all icon buttons must have appropriate aria labels so screen readers users can decipher their purpose.
Changes (nothing visual):
- Add ariaExpanded and ariaLabels to expand/collapse buttons in hierarchy panel
- Add ariaLabel to visibility toggle button
- Add a prop to TreeItem so that `labelText` is not overworked. This fixes a bug that (while not caught by level access) would prevent users using a screen reader from determining the usage of a checkbox in the `SubModelTree`
Pics (no visual change)
Before:
After:
- Select the Summary item on the …
> fix(composer): add aria labels to buttons in hierarchy panel

- packages/scene-composer/src/components/three-fiber/EditorCamera.tsx
- packages/scene-composer/src/components/three-fiber/EditorTransformControls.tsx
- packages/scene-composer/src/hooks/useOverwriteRaycaster.spec.ts
- packages/scene-composer/src/hooks/useOverwriteRaycaster.ts
Ray-casting for the transform controls were disabled to make them on interfere with ray-casting during camera activation, but this may them unclickable for mouse interactions.
https://github.com/awslabs/iot-app-kit/assets/109186219/e9c1ef72-e519-488a-815f-a59907507938
Now ray-casting should only be temporarily disabled for the transform controls while a camera command raycast is being done so the camera looks in the right direction but are restored for user editing after the camera is done moving.
https://github.com/awslabs/iot-app-kit/assets/109186219/a21ba5ab-14e3-4919-b16e-1edadbaf5684
Test in scene composer with a scene that has a camera
1. use all three transform control option on an object (scale, rotation, position)
2. select in the scene hierarchy a camera
3. select that camera in …
> fix(scene): fix transform controls being clickable

- packages/dashboard/src/customization/propertiesSections/aggregationSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/widgets/barChart/plugin.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/plugin.tsx
- packages/dashboard/src/customization/widgets/types.ts
This change provides required defaults for aggregation and resolution for widgets which expose aggregation and resolution controls.
> fix: default resolution and aggregation

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTable.test.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTableColumnDefinitionsFactory.tsx
this PR adds the column visibility for all the columns in resource explorer visible column settings in asset preferences. #1980 
https://ibb.co/6bBzbzS
> feat: resource explorer table preferences columns visibility

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.css
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/hooks/useChartsLegend.tsx
- packages/react-components/src/components/chart/legend/legend.css
- packages/react-components/src/components/chart/legend/legend.tsx
This reverts commit 390cbe3414286bd7cfb1f041a2d21264552e7bd3.
The commit introduced unacceptable regressions to trend cursors and other chart UX.
> revert: updated the chart legend ux(spacing, legend border color, width, tooltip)

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/panels/scene-components/motion-indicator/SpeedEditor.tsx
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/entityModelUtils/createNodeEntity.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/createNodeEntity.ts
- packages/scene-composer/src/utils/entityModelUtils/dataBindingUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/dataBindingUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/motionIndicatorComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/motionIndicatorComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.ts
- packages/scene-composer/src/utils/nodeUtils.spec.ts
- packages/scene-composer/src/utils/nodeUtils.ts
- add utils to convert all nodes to entities
- fix some motion indicator property value issues
```
httpserver
```
> feat(composer): add utils to convert all nodes to entities

- packages/dashboard/src/customization/propertiesSection.ts
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdComponent.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdStyle.spec.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdStyle.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
Issues:
* Certain widgets within the dashboard are difficult to configure thresholds for due to the dropdown being squeezed.
* "=" thresholds should display as a line
Fixes:
* The dropdown for the comparison operator now always expands fully.
* For all thresholds with "=" in the expression there will be a dotted line. For all other expressions it uses the style to determine whether there is a region and/or dotted line.
* The timeline widget now supports the "Contains" comparison operator
* Selecting multiple widgets of the same threshold type then you can update thresholds for all of them at once. If selecting multiple widgets of different threshold types then you see text saying that you must select one threshold.
https://github.com/awslabs/iot-app-kit/assets/87385528/bfaab770-b494-4ba2-9 …
> fix(dashboard): minor threshold fixes

- packages/scene-composer/package.json
- packages/scene-composer/src/components/ConvertSceneModal.spec.tsx
- packages/scene-composer/src/components/ConvertSceneModal.tsx
- packages/scene-composer/src/components/ConvertingProgress.spec.tsx
- packages/scene-composer/src/components/ConvertingProgress.tsx
- packages/scene-composer/src/components/StateManager.spec.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/__snapshots__/ConvertSceneModal.spec.tsx.snap
- packages/scene-composer/src/components/__snapshots__/ConvertingProgress.spec.tsx.snap
- packages/scene-composer/src/components/__snapshots__/StateManager.spec.tsx.snap
- packages/scene-composer/src/components/panels/SettingsPanel.spec.tsx
- packages/scene-composer/src/components/panels/SettingsPanel.tsx
- packages/scene-composer/src/components/panels/__snapshots__/SettingsPanel.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-settings/ConvertSceneSettings.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/ConvertSceneSettings.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/ConvertSceneSettings.spec.tsx.snap
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.spec.tsx
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
- packages/scene-composer/src/store/StoreOperations.ts
- packages/scene-composer/src/store/slices/EditorStateSlice.spec.tsx
- packages/scene-composer/src/store/slices/EditorStateSlice.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Add convert scene button to settings to convert all static scene nodes into dynamic entities
https://github.com/awslabs/iot-app-kit/assets/9315598/7945637d-00a3-4b21-b1ef-0a6acf5b1133
https://github.com/awslabs/iot-app-kit/assets/9315598/0deb8465-d779-4207-9123-c4921b23d1db
```
httpserver
```
This project is available …
> feat(composer): convert nodes to entities UI

- packages/dashboard/src/components/internalDashboard/collapsiblePanel.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/tooltip/tooltip.css
- packages/dashboard/src/components/tooltip/tooltip.test.tsx
- packages/dashboard/src/components/tooltip/tooltip.tsx
This PR is for ticket #2003 and it includes
1. The entire circle button is "hit target" for the "resource explorer" and "config panel" buttons
2. config panel tool tip should say "Configuration"
3. resource explorer tool tip should say "Resource explorer"
https://ibb.co/jwZfhqg
> feat: side-panels toggle open hit and tool-tip on mouse-over

- packages/dashboard/src/components/palette/icons/index.tsx
This change fixes widget drag and drop in Firefox (the best browser).
> fix: firefox dnd

- packages/dashboard/e2e/tests/utils/grid.ts
- packages/dashboard/src/components/internalDashboard/gestures/determineTargetGestures.ts
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/react-components/src/components/chart/baseChart.tsx
- Resizing legend wont move widget around grid, regardless of selection state
- Widget can be selected from anywhere, not just the header area
> fix(dashboard): improve widget drag and resize

- packages/scene-composer/src/components/panels/SceneRulesPanel.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetIconEditor.tsx
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
* Bug fix for saving icon metadata.
* Retrieve icon info upon reload.
https://github.com/awslabs/iot-app-kit/assets/54058998/04a2f87d-6680-4ef4-bbc2-dffe0f8f7123
```
httpserver
```
> feat(scene composer): fix for icon rules and save icon metadata

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/converters/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/hooks/useDataZoom.ts
- packages/react-components/src/components/chart/utils/getXAxis.ts
- move any viewport+echart logic to live in the useDataZoom hook, so we dont have conflicting logic in different files
- X Axis - fix the max value so that selecting an absolute time range works
- Y Axis - create a default y axis to be displayed when series have no data present
> fix(echarts): improved x+y axis min and max

- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
Enabled TagStyle for viewer
```
httpserver
```
> feat: set tagStyle flag to true for viewer

- packages/core/src/common/intervalStructure.spec.ts
- packages/core/src/common/intervalStructure.ts
- packages/core/src/data-module/data-cache/caching/caching.ts
This is for fixing the duplicate data per timestamp. the incoming data is an array of Datapoints and these are sorted but not checked for repeatedness.
https://github.com/awslabs/iot-app-kit/assets/135036199/7a85fdad-78e8-4d34-b5d8-b016f4603b6b
> fix(core): fix for duplicate data per timestamp issue

- packages/scene-composer/src/components/panels/ComponentEditMenu.spec.tsx
- packages/scene-composer/src/components/toolbars/common/ItemContainer.spec.tsx
- packages/scene-composer/src/components/toolbars/common/ItemContainer.tsx
- packages/scene-composer/src/components/toolbars/common/ToolbarItem.tsx
- packages/scene-composer/src/components/toolbars/common/__snapshots__/ItemContainer.spec.tsx.snap
- packages/scene-composer/src/components/toolbars/common/styledComponents.ts
- packages/scene-composer/src/components/toolbars/common/types.ts
- packages/scene-composer/src/components/toolbars/floatingToolbar/FloatingToolbar.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/HistoryItemGroup.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/HistoryItemGroup.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/ObjectItemGroup.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/ObjectItemGroup.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/ObjectItemGroupSnap.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/SceneItemGroup.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/__snapshots__/HistoryItemGroup.spec.tsx.snap
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/__snapshots__/ObjectItemGroupSnap.spec.tsx.snap
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
- packages/scene-composer/tests/components/toolbars/floatingToolbar/FloatingToolbar.spec.tsx
- packages/scene-composer/tests/components/toolbars/floatingToolbar/__snapshots__/FloatingToolbar.spec.tsx.snap
- packages/scene-composer/tests/components/toolbars/floatingToolbar/items/SceneItemGroup.spec.tsx
This change flips the floating toolbar from vertical to horizontal when the screen size gets too small. Per a11y guidelines, all content has to be accessible to users at 1) 320px wide by 255px high and 2) 640px wide by 256px high at 200% zoom. 
Before pic (shows 640px wide by 256px high at 200% zoom):
After video:
https://github.com/awslabs/iot-app-kit/assets/143754227/25e1ac87-4bb4-4170-821c-ef5d1decf283
Added some unit tests, and updated many others.
I have tested manually in storybook and in console. I have not tested in grafana, and I'm not sure how. Is this necessary for this change?
- Click on the …
> fix(composer): floating toolbar orientation dependent on screen size

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/hooks/useHandleChartEvents.ts
- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
* Change cursor to open hand when holding shift while over chart area
* When clicking to pan, change to "grab" hand
* Tooltip is hidden while there is an active gesture
https://github.com/awslabs/iot-app-kit/assets/87385528/f9158635-23f5-45a4-ac22-63a27e261c72
1. Always show the "grab" cursor when shift is held down over the chart canvas
2. Always show the "grabbing" cursor when shift and the mouse is held down over the chart canvas, turn off the tooltip, and drag the canvas left to right
3. Don't show any change in cursor when the mouse is held down
4. Cannot drag on the edges of the canvas, but there is no way to avoid changing the cursor since the event is within the entire canvas
For `scene-composer` package changes specifically, you can preview the component in the published …
> fix(react-components): echarts grab on canvas update cursor and tooltip

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/panels/SettingsPanel.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.tsx
- packages/scene-composer/src/components/three-fiber/Fog.spec.tsx
- packages/scene-composer/src/components/three-fiber/Fog.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Adds a feature flag 'SceneAppearance' that adds an option for a Fog setting in the Scene Composer setting tab.
https://github.com/awslabs/iot-app-kit/assets/109186219/43537422-19a9-4bcb-a795-a55d88d5bc5e
Storybook
Scene Composer - Local Scene
Open Settings Tab
Expand Scene Settings
Expand Fog Settings
Use color picker, near, far, and enable check box to toggle fog settings.
``` …
```
> feat(scene): add fog settings to scene

- packages/dashboard/src/components/tooltip/constants.ts
- packages/dashboard/src/components/tooltip/tooltip.css
- packages/dashboard/src/components/tooltip/tooltip.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.css
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
This PR is to improve the handling of long property names within the dashboards configuration panels "property" section. this includes,
1.  long names are truncated and added ellipses
2. tooltip for the truncated names
3. fixed width for the property Name 
4. No tooltip if full name is showing
> feat: handle long properties names in config pane

- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/palette/index.css
- packages/dashboard/src/components/palette/index.tsx
- packages/dashboard/src/styles/variables.css
Issue: https://github.com/awslabs/iot-app-kit/issues/2036
Description: Added "Widgets" text with horizontal divider to the Widget library panel on the dashboard.
Changes in the CR:
-> Added "Widgets" header with grey-900 font color and a right divider of 2px.
->Added bottom border, 2px grey-200
> feat: added widget text in the widget panel #2036

- packages/scene-composer/.storybook/main.js
Restoring dark mode in storybook for scene composer 
https://github.com/awslabs/iot-app-kit/assets/6610619/0589dd8f-8d8c-450e-81fb-3491cb7b3155
```
httpserver
```
> fix(scene composer): restoring dark mode in stotybook

- packages/dashboard/src/customization/propertiesSections/components/lineStyleDropdown.tsx
- packages/dashboard/src/customization/propertiesSections/components/lineThicknessDropdown.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/lineStyleSection.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
This PR is for ticket: #2029 
made changes as requested and now we can able to customize the line per property. also added a line thickness dropdown(static) in the widget level and property level.
The below screenshots show the changes as requested.
> feat: added line style customization per property

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
Restore the grid line colors which were removed due to the scene flickering issue.
Made sure that the flickering issue is not observed after restoring the grid line colors.
Before:
https://github.com/awslabs/iot-app-kit/assets/43108986/18c1b132-ea07-4b5b-9742-f6c9ff3d1c69
After:
https://github.com/awslabs/iot-app-kit/assets/43108986/28fce331-0eb0-4ac6-86bb-9d8d67d1bb78
```
httpserver …
```
> fix(scene-composer): restore the grid line colors

- package-lock.json
- packages/core/jest.config.ts
- packages/core/package.json
- packages/core/src/data-module/request-scheduler/requestScheduler.spec.ts
- packages/core/src/data-module/request-scheduler/requestScheduler.ts
- packages/source-iotsitewise/jest.config.ts
- packages/source-iotsitewise/package.json
- packages/source-iottwinmaker/jest.config.ts
- packages/source-iottwinmaker/package.json
When the tab becomes de-focused, request intervals become de-synchronized, which leads to inefficient request batching and potentially throttling when visualizing a large number of data streams. This change ensures synchronization of data streams by resetting intervals when the tab goes back into focus.
> fix: synchronize requests after switching tabs

- packages/scene-composer/src/components/panels/scene-components/tag-style/IconPicker/IconPicker.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/IconPicker/IconPickerUtils/IconPickerStyles.ts
Tag icons picker by default showed only 3 rows and customer expressed the need to see all icons and scroll through them to pick instead of relying on search by icon names.
https://github.com/awslabs/iot-app-kit/assets/20994167/153da175-3a2a-4fe8-ba1e-9f24bfbe9d65
```
httpserver
``` …
> fix(scene-composer): add scroll bar to show all tag icons by default

- packages/scene-composer/src/utils/entityModelUtils/motionIndicatorComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/motionIndicatorComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/tagComponent.ts
- Save and parse tag custom icon fields in entities
- change motion indicator default speed value to be double instead of integer
```
httpserver
```
> feat(composer): support tag custom icon in entity

- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/MatterportTagSync.spec.tsx.snap
- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
- packages/scene-composer/src/store/helpers/__tests__/sceneDocumentHelpers.spec.ts
- packages/scene-composer/src/store/helpers/sceneDocumentHelpers.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/utils/entityModelUtils/createNodeEntity.ts
- packages/scene-composer/src/utils/entityModelUtils/overlayComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- append scene node action calls create entity API for dynamic scene
- clean up entity API calls from matterport sync and have the store as the central place to make those requests
```
httpserver
```
> feat(composer): append scene node action creates entity for dynamic scene

- packages/dashboard/src/customization/propertiesSections/components/lineStyleDropdown.tsx
- packages/dashboard/src/customization/propertiesSections/components/lineThicknessDropdown.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/lineStyleSection.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
This PR is for ticket: #2029 
made changes as requested and now we can able to customize the line style and thickness per property.
https://github.com/awslabs/iot-app-kit/assets/139960352/60564465-9f17-4285-848f-a26c5529b8f4
> feat: add line style thickness per property

- packages/core/src/data-module/request-scheduler/requestScheduler.spec.ts
- packages/core/src/data-module/request-scheduler/requestScheduler.ts
When new intervals are created, it's possible for them to be out of sync. With the SiteWise data source, this leads to a failure to batch requests efficiently and could cause API throttling to occur.
This change synchronizes intervals each time a new interval is created.
> fix: synchronize intervals when new intervals are created

- packages/scene-composer/.eslintrc.js
- packages/scene-composer/package.json
- packages/scene-composer/src/common/constants.ts
- packages/scene-composer/src/components/panels/scene-components/LightComponentEditor.tsx
- packages/scene-composer/src/components/three-fiber/LightComponent/__tests__/LightComponent.spec.tsx
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/entityModelUtils/createNodeEntity.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/createNodeEntity.ts
- packages/scene-composer/src/utils/entityModelUtils/lightComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/lightComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.ts
- packages/scene-composer/src/utils/mathUtils.spec.ts
- packages/scene-composer/src/utils/mathUtils.ts
- packages/scene-composer/tests/components/panels/scene-components/LightComponentEditor.spec.tsx
Add utils to handle light component in entity, change colors to be hex string instead of string or number
```
httpserver
```
> feat(component): utils to handle light component in entity

- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/hooks/useECharts/useResizeableEChart.ts
When the user toggles the legend property in the property panel, the legend container is also hidden now. 
https://github.com/awslabs/iot-app-kit/assets/145582655/4dadbe50-ca3b-4316-b964-6ecf15827b2e
> fix(react-components): toggle legend hides container

- packages/scene-composer/src/assets/anchors/IconSvgs.tsx
Fix for when custom tags is chosen from the Tag Style drop down menu it rendered slightly off center.
Before
https://github.com/awslabs/iot-app-kit/assets/20994167/eeb05058-a06f-4774-8a91-22f1645d9707
After
https://github.com/awslabs/iot-app-kit/assets/20994167/fa9a1081-1acf-461b-99c1-f84dacbda68d
```
httpserver
```
This …
> fix(composer): custom tag rendered slightly off the center

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/panels/SettingsPanel.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.tsx
- packages/scene-composer/src/components/three-fiber/Fog.tsx
- packages/scene-composer/src/components/three-fiber/SceneBackground.spec.tsx
- packages/scene-composer/src/components/three-fiber/SceneBackground.tsx
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/stories/Developer/SceneViewer.stories.mdx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Update layout of fog settings to not require expander click and toggle color picker/distance inputs based on enable checkbox
Add scene background settings with color picker.  Does not support background textures.
https://github.com/awslabs/iot-app-kit/assets/109186219/533ea9f7-b88f-4986-9e0b-cdda28c39be4
Use storybook to open a scene composer
visit settings
go to scene settings
use the enable fog and enable background to test setting and see the colors change in the 3d scene
To run the storybook build locally, …
> feat(scene): enable scene backgrounds

- packages/scene-composer/src/components/panels/scene-components/tag-style/IconPicker/IconPicker.tsx
This PR provide a fix for Icon field is not showing the correct value for the tags with custom style. It keeps showing the icon used for the first selected tag on scene load or of the one for which user has configured the icon most recently.
Before
https://github.com/awslabs/iot-app-kit/assets/20994167/1a49db25-28e7-46c6-a370-3aa2a744fc8f
After 
https://github.com/awslabs/iot-app-kit/assets/20994167/9f852fb5-f7b3-4cf1-b829-a0c26d35a5ec
``` …
```
> fix(scene composer): show correct Icon field for tags with Custom Style

- packages/react-components/src/components/tooltip/tooltip.css
Changed Tooltip CSS that when it is placed on the bottom of the button it allows the user to hover over any region of the button instead of just the top part for the button to be active. This fixes a bug in the pagination feature.
https://github.com/awslabs/iot-app-kit/assets/145582655/7ec705f6-fdee-4326-b070-c0a145bc33b1
> fix(react-components): hitbox spans entire pagination button

- package-lock.json
- package.json
This change fixes an dependency resolution issue with a recent upgrade of `@awsui/components-react`.
> fix: cloudscape dependency resolution failure

- packages/scene-composer/src/components/SceneLayers.spec.tsx
- packages/scene-composer/src/components/SceneLayers.tsx
- packages/scene-composer/src/components/panels/scene-settings/ConvertSceneSettings.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/ConvertSceneSettings.spec.tsx.snap
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/utils/entityModelUtils/sceneLayerUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
allow disable/enable layer auto refresh from settings. This is a temporary change before full layer UX is implemented.
```
httpserver
```
> feat(component): allow disable/enable layer auto refresh

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledSection.tsx
Changed ternary operator to ensure that unmodeled data streams can be shown after being hidden.
https://github.com/awslabs/iot-app-kit/assets/145582655/bdb56f36-b2e1-4b1a-8062-42294001e4c2
> fix(dashboard): toggle from hide to show for unmodeled datastreams

- package-lock.json
- package.json
Updated the version of `@cloudscape-design/component-toolkit` package to fix the build failure
> chore(fix-dependency): cloudscape version update

- package-lock.json
Reverts awslabs/iot-app-kit#2185 to fix internal build failure
> build(deps-dev): Revert 'bump browserify-sign from 4.2.1 to 4.2.2'

- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
In this PR Tag style field for newly created tag adjusted  to show Info, since newly created tag uses DefaultAnchorStatus.Info icon anyway so this correctly reflect the default icon that the code default to. No point of hiding that in the UI if we wanted a different Default or new tag creation workflow that should be addressed comprehensively in code.
Before
https://github.com/awslabs/iot-app-kit/assets/20994167/af1cb83c-0e5a-422a-babf-58802052d5a3
After
https://github.com/awslabs/iot-app-kit/assets/20994167/fe47650c-d811-41c9-95de-440f1f89d1fd
- Select the Summary item …
> fix(composer): new tag style field is empty instead of info

- packages/scene-composer/src/components/SceneComposerInternal.tsx
- packages/scene-composer/src/components/__snapshots__/SceneComposerInternalSnap.spec.tsx.snap
- packages/scene-composer/src/hooks/useAwsLightDarkModes.spec.tsx
- packages/scene-composer/src/hooks/useAwsLightDarkModes.ts
- packages/scene-composer/src/hooks/useOverwriteRaycaster.ts
Currently the scene viewer only support dark mode, and it forces it's mode on the whole page including other cloudscape packages.
Build example/react-examples but change the src/index.tsx line 14 to applyMode(Mode.Light) then start the server.
The page when visited should have the dark mode scene composer, but the rest of the page in light mode.
```
httpserver
``` …
> fix(scene): stop scene composer from forcing dark mode on page

- packages/scene-composer/src/components/SceneLayers.spec.tsx
- packages/scene-composer/src/components/SceneLayers.tsx
- packages/scene-composer/src/hooks/useMatterportTags.spec.ts
- packages/scene-composer/src/hooks/useMatterportTags.ts
- packages/scene-composer/src/utils/entityModelUtils/createNodeEntity.ts
- get entityBinding in different query and only for entities in the layer
```
httpserver
```
> fix(composer): get entityBinding in different query

- packages/dashboard/src/customization/widgets/components/no-chart-data.spec.tsx
- packages/dashboard/src/customization/widgets/components/no-chart-data.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/text/plugin.tsx
add the delete option (clicking the "X" button in the top right) for empty widget. this pr includes
1.  delete option for line, status, Timeline and KPI widgets in empty state
2. delete option for table and text widgets in both scenarios (empty and with data)
new changes
[delete-empty-widgets.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/f599469a-771d-4ecf-9856-d011ad375c7e)
> feat: added delete option for empty widget #2139

- package-lock.json
- packages/dashboard/package.json
- packages/dashboard/turbowatch.ts
- turbo.json
Now Devs can run the dashboard in "watch" mode. Recommend only when changes are in multiple packages, might be expensive if the changes are only in dashboard package
```npm run watch-dependencies``` 
[turbowatch ](https://www.npmjs.com/package/turbowatch#restarting-server-when-file-changes-are-detected)
> feat(dashboard): adding watch mode for dashboard

- packages/react-components/src/components/chart/hooks/useViewportToMS.spec.ts
- packages/react-components/src/components/chart/hooks/useViewportToMS.ts
This change ensures the line chart viewport immediately changes when selecting a relative time range. This fixes a bug where there is a 1s delay in the line chart responding when a relative viewport is selected.
> fix: immediately change the line chart viewport when updating relative time range

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/createModeledDataStreamColumnDefinitions.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
- packages/dashboard/src/components/util/dateTimeUtil.spec.tsx
- packages/dashboard/src/components/util/dateTimeUtil.tsx
This PR is to format latest value time values in the resource explorer table to MM/DD/YY HH:MM:SS format. This is related to ticket #2140 
Modeled data stream table
Unmodeled data stream table
> feat: format latest value time in resource explorer table

- packages/react-components/src/components/time-sync/viewportAdapter.spec.ts
Fixes for the viewport adapter tests that check for previous month to see how many milliseconds the viewport changes by
Should pass all unit tests.
> fix(react-components): correct failing viewport adapter tests

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.css
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/legend/legend.css
- packages/react-components/src/components/chart/legend/legend.tsx
- packages/react-components/src/components/chart/legend/useChartsLegend.tsx
for the #1930 updated the chart legend ux and it includes
1. reduced the legend properties spacing
2. default width is increased for legend
3. tooltip added for the truncated names and properties names will truncate based on visibility width
[legend-ux.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/9bc4768e-9eb9-4af2-8099-b3bf3939e593)
> feat: updated the chart legend ux

- package-lock.json
- packages/dashboard/package.json
- packages/dashboard/src/components/csvDownloadButton/index.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/react-components/src/store/config.ts
- Create download button component
- Gate download button component behind `USE_CSV_DOWNLOAD` in localStorage
- Add download button to widget tile IF gate is enabled and widget is not a text widget
https://github.com/awslabs/iot-app-kit/assets/28601414/fe07cc45-fbca-465a-ad85-1e944a2a7c11
> feat(dashboard): gated CSV download button

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/common/constants.ts
- packages/scene-composer/src/components/panels/scene-settings/OverlayPanelVisibilityToggle.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneTagSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneTagSettingsEditor.tsx
- packages/scene-composer/src/interfaces/componentSettings.ts
- packages/scene-composer/src/store/slices/ViewOptionStateSlice.spec.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Issue: Tags clutter the UI when they are always visible through other Meshes
This is especially an issue when you are in immersive mode, like Matterport. Because tags are always rendered closer to the camera than any meshes, large sites with lots of tags become very difficult to navigate in immersive mode.
Fix: Provided an option to show/hide tags through objects in the Scene Tag Settings.
Default behabior:
Tag Occlusion Enabled:
Screen recording:
https://github.com/awslabs/iot-app-kit/assets/43108986/9c2c4cf3-9ce5-49d2-b808-263aa24797b0
- Select the Summary item on the …
> feat(scene-composer): support tag occlusion

- packages/react-components/src/components/time-sync/timeSelection.tsx
- packages/react-components/src/components/time-sync/viewportAdapter.spec.ts
- packages/react-components/src/components/time-sync/viewportAdapter.tsx
Can move forward from relative range. 
https://github.com/awslabs/iot-app-kit/assets/145582655/a105d49f-48c8-4557-8140-c1e928eec570
> fix(react-components): pagination can move forward on first click from relative range

- examples/react-app/package.json
- examples/react-app/src/components/LineChart.scss
- examples/react-app/src/components/LineChart.tsx
- examples/react-app/src/index.tsx
- examples/react-app/src/pages/Home/index.tsx
- examples/react-app/vite.config.ts
- package-lock.json
Adds line chart to the example/react-app that connects an iot-app-kit chart in line format to data in twinMaker based off the selected TwinMaker entity
https://github.com/awslabs/iot-app-kit/assets/109186219/8db641cc-e93b-4360-9304-23721af61c2b
```
httpserver
``` …
> chore(example): add line chart example

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayContainerSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/styles.ts
When using the option to not display all overlays, overlays staying open when not selected can make the screen cluttered.  We want to make overlays only visible if their tag is selected OR we're in display all mode.
Use local storybook composer 
have a scene with 2 tags
ensure that when overlay visible setting is toggled on their both visible.
ensure that when overlay visible setting is toggled off that the overlay is only visible if the tag is selected.
https://github.com/awslabs/iot-app-kit/assets/109186219/b04eee73-d9e5-4436-941d-e6bbc5310e68
- Select the Summary item …
> fix(scene): only show selected tags overlay

- examples/react-app/package.json
- examples/react-app/vite.config.ts
- package-lock.json
Changes in package json to support stencil workaround causes breaks in some environments but stencil is no longer used in the example so we'll revert the changes.
example still builds and run in serve mode with line chart showing properly
```
httpserver
``` …
> fix(example): roll back unneeded package json changes

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/queryEditor.spec.tsx
This PR is for ticket #2115 and to disable add button if no widget and properties selected. 
1. no properties selected  -- disable both Add and Reset button
2. properties selected but no widget is selected  -- disable Add button and enable Reset button
3. both properties and widget selected -- enable both Add and Reset button
[disable-add-button.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/2bfd4f63-cb94-4dc8-b58f-8bc6a4ad741f)
> feat: disable add button when no widget and property selected 

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayContainer.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayContainerSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/styles.ts
Adds the overlay close button back to handles hiding an overlay even though the tag is still selected.
run storybook
select a tag with an overlay
see the X mark and click it to close the overlay
```
httpserver
```
> fix(scene): add overlay close button back

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
This PR is for ticket #2115 and to disable add button if more than 1 widgets selected.
[disable-add-button-when-more-widgets-selected.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/ed037835-b59b-4079-a71a-e17b972f6c80)
> feat: disable add button when more than one widgets are selected

- packages/dashboard/src/components/internalDashboard/dashboardEmptyState.css
This PR is for ticket #2137  and this includes
1. clicking and dragging on the empty state image draws the expected rectangle aligned with where the mouse was clicked and dragged
2. empty state correctly aligned center.
[center-align.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/3616dc0e-9029-4e4f-adef-8dffa5fe5264)
> feat: draw box, corresponding with there the mouse was dragged and center align

- packages/dashboard/src/components/csvDownloadButton/getDescribedTimeSeries.tsx
- packages/dashboard/src/components/csvDownloadButton/index.tsx
- packages/dashboard/src/components/csvDownloadButton/useViewportData.ts
- download button is disabled when download is in progress
- if any dataStreams are in an error state, then the CSV download does not occur
- empty widget does not show download button
> fix: better disabled states and error handling for CSV

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayComponent.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayComponentSnap.spec.tsx.snap
Currently when all overlays are visible the user can't control which is in front without trying to manage the camera. We'd like the selected overlay to always be the one in front
https://github.com/awslabs/iot-app-kit/assets/109186219/6233cb22-0702-4678-b887-1a51d4bbb593
```
httpserver
```
This project is available under …
> fix(scene): ensure the selected overlay is always the one at front

- packages/dashboard/src/msw/useWorker.ts
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
Fix for mock service worker lifecycle in storybook. Adds a decorator to the Mocked data story which will start and stop the service worker on story mount / unmount. This way, the service worker will not be running for any other story.
_Note: if switching between mocked / connected stories, you will need to refresh the page as react query caches all calls in memory, and there is no access to the client at the Storybook story level._
> fix: dashboard mock service worker lifecycle

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/handleDeleteAssetModelProperty.ts
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledSection.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/types.ts
Reverted #2212. We do not have the hide/show from legend feature complete so we will be adding back hide/show in config panel till that is complete for release. Also added a hide/show functionality for the model centric visualization workflow. 
https://github.com/awslabs/iot-app-kit/assets/145582655/7265fef8-b145-4196-b6fc-73f0febc462f
> revert: reverting fix(dashboard): remove hide/show from dashboard definition and config panel

- configuration/eslint-config/index.js
- packages/dashboard/src/components/internalDashboard/index.test.tsx
- packages/dashboard/src/components/palette/index.test.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdStyle.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
- packages/dashboard/src/customization/settings.ts
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/source-iotsitewise/src/asset-modules/mocks.ts
- packages/source-iotsitewise/src/asset-modules/sitewise/session.ts
- packages/source-iotsitewise/src/asset-modules/sitewise/types.ts
This change prevents absolute imports being used between `@iot-app-kit` imports. Without this change, these invalid imports can make it to library consumers before being caught and fail consumer builds.
https://github.com/awslabs/iot-app-kit/pull/2183 is one such example where we retroactively needed to fix the issue after releasing a broken version of `iot-app-kit`.
Imports of types and imports within tests do not cause consumer builds to fail, yet we should prevent all usage of restricted imports to be on the safe side and prevent the coupling of packages through referencing directory structure with absolute imports. Imports of this category were either fixed, when a package export was readily available, or ignored with a FIXME, when the package export was not available.
This PR is …
> fix: restrict @iot-app-kit imports

- package-lock.json
- packages/dashboard/e2e/tests/constants.ts
- packages/dashboard/e2e/tests/dashboard/dashboard.spec.ts
- packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts
- packages/dashboard/e2e/tests/test.ts
- packages/dashboard/e2e/tests/utils/grid.ts
- packages/dashboard/e2e/tests/utils/resourceExplorer.ts
- packages/dashboard/e2e/tests/utils/toolbar.ts
- packages/dashboard/package.json
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
Add integration tests for resource explorer. In order to get mock service worker to work within playwright, a wrapper around the test method is added which utilizes the `playwright-msw` package. This package uses the same handlers as the `msw` implementation but has extra functionality to plug into playwright testing.
Tests Added:
1. basic visibility test
2. asset model happy path test for selecting an asset model and property and adding it to a xy-plot widget.
> feat: dashboard resource explorer e2e tests

- packages/dashboard/src/customization/widgets/barChart/component.tsx
The barchart has two bugs:
1. when adding a datastream to the chart, the position of the bars are not aligned with the axis.
2. when removing the last datastream from the chart, the datastream continues to render.
Before:
After:
To fix these, a key based on the query is added to the bar chart so that we force a rerender when the query changes.
> fix(dashboard): bugfix for barchart positioning

- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
Update the filter query in the line-scatter component to also filter on if the assetModel has no properties. This affects the state of the widget if all properties are hidden when using model centric viz. 
Refer to #2251 for full revert.
https://github.com/awslabs/iot-app-kit/assets/145582655/8f952212-1802-41ad-a4c0-c36ca1698fab
> revert: filter query on asset models

- packages/dashboard/src/components/csvDownloadButton/index.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/react-components/src/store/config.ts
- ungating the CSV feature 
- add aria label to CSV download button 
example file: 
[status-timeline 2023-11-10T20 19 13.377Z.csv](https://github.com/awslabs/iot-app-kit/files/13322924/status-timeline.2023-11-10T20.19.13.377Z.csv)
[bar-chart 2023-11-10T20 19 06.910Z.csv](https://github.com/awslabs/iot-app-kit/files/13322927/bar-chart.2023-11-10T20.19.06.910Z.csv)
[xy-plot 2023-11-10T20 19 01.897Z.csv](https://github.com/awslabs/iot-app-kit/files/13322928/xy-plot.2023-11-10T20.19.01.897Z.csv)
> fix(dashboard): ungate csv download

- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
This PR is for #2266 
Since <ExpandableSectionHeader/> component causing the unique key issue I removed it.
> fix: missing raect key internal space between

- .github/workflows/ui-test-full-suite.yml
This change unblocks our CI, which is currently failing on the full run of UI tests on nearly every PR and every test run.
The root cause appears to be related to an inability to start the dashboard storybook due to a dependency resolution failure with the dashboard's dependency on `@iot-app-kit/react-components`. This failure is, for some reason, only observed on the full test suite and not the suite which runs on the single PR commit.
`ModuleNotFoundError: Module not found: Error: Can't resolve '@iot-app-kit/react-components' in '/home/runner/work/iot-app-kit/iot-app-kit/packages/dashboard/src/components/actions'`
See https://github.com/awslabs/iot-app-kit/actions/runs/6882669479/job/18721635912 for an example test run.
The issue appears to be related to the usage of running the turbo …
> fix: full UI test suite CI

- docs/SceneViewer.md
- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
Enable the auto query feature flag and add documentation
```
httpserver
```
> feat(composer): enable auto query feature

- packages/dashboard/src/components/csvDownloadButton/emptyDownload.test.tsx
- packages/dashboard/src/components/csvDownloadButton/index.tsx
- Download a CSV file when viewport is empty and there are no errors present
- File will still have column names so it not just an empty CSV
- Fix tests to match this new behavior
example empty CSV file:
[xy-plot 2023-11-15T14 48 06.034Z.csv](https://github.com/awslabs/iot-app-kit/files/13366219/xy-plot.2023-11-15T14.48.06.034Z.csv)
> fix(dashboard): csv will download if viewport has no data

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/events/useHandleChartEvents.ts
- enable the brush zoom + zoom reset toolbox
- works in dashboard + in the solo react-component
- does not break existing pan gestures
panning+brush zoom:
trend Cursors:
> feat(react-components): brush zoom line chart

- packages/dashboard/e2e/tests/utils/resourceExplorer.ts
- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/resizablePanes/constants.ts
- packages/dashboard/src/components/resizablePanes/index.test.tsx
- packages/dashboard/src/components/resizablePanes/index.tsx
This PR is for ticket #2256 and to fix resizing issue for configuration and resource explorer panels when the user toggle between edit and preview mode.
1.  first time resource explorer will be open and configuration panel will closed on dashboard open
2. when the user goes to preview mode and comes back to edit mode
- the selected widgets will reset (i.e selected widgets should be an empty array)
- config panel will be closed
- resource explorer will be open  
3. removed the right draghandle  code related to resize listening
[edit-preview.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/bb2dd6e4-3d9b-48d2-a464-62ba4a1960d7)
> fix: panel resizing issue fix

- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/react-components/src/components/chart/eChartsConstants.ts
- always show tile header area in view mode (unless its a text widget)
- change name of `reset zoom` button
> fix: download button and zoom undo button

- packages/scene-composer/src/utils/entityModelUtils/deleteNodeEntity.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/deleteNodeEntity.ts
Delete node entity with child fails with "Cannot delete entity as it has child entities". Set to recursive deletion instead.
```
httpserver
```
> fix(composer): cannot delete node entity with child

- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/constants.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/footer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/index.css
- packages/dashboard/src/styles/variables.css
This PR is for ticket #2114 and to sticky add and reset buttons at bottom right  corner in Resource explorer for Modeled and Unmodeled tabs
[Uploading add-buttons-sticky.webm…]()
**Note:**
Snapshot test not added in this PR because the QueryEditor snap file is always change for the each test. so unit tests are failing. seems id and area-controls values are changing each time for Modeled and Unmodeled tabs (Cloudscape)
> feat: fixed the add and reset buttons to bottom right corner

- packages/dashboard/src/customization/widgets/text/plugin.tsx
This change removes the widget panel from the text widget.
> fix: remove widget panel from text widget

- packages/core/src/index.ts
- packages/core/src/logger/logger.interface.ts
- packages/core/src/metricRecorder/metricsRecorder.interface.ts
- packages/core/src/plugins/loggerSettings.ts
- packages/core/src/plugins/metricsRecorderSettings.ts
- packages/core/src/plugins/pluginsRegistry.spec.ts
- packages/core/src/plugins/pluginsRegistry.ts
1. added experimental plugin exports
2. Refactored experimental plugin to have the following structure:
```
// example of a registration and usage of metricsRecorder plugin
registerPlugin('metricsRecorder', {
provider: () => ({
// record and console log all metrics
record: (metric) => {
console.log(metric);
},
}),
});
// example of getting metricsRecorder plugin
const metricsRecorder = getPlugin('metricsRecorder');
metricsRecorder?.record({
metricName: 'test',
metricValue: 123
});
```
3. previously requires a pair of function per plugin type; making the new structure more scalable
```
registerLogger(...)
getLogger()
registerMetricsRecorder(...)
getMetricsRecorder()
```
added and validated examples; type changes only; …
> fix: added experimental plugin exports

- packages/dashboard/src/components/resizablePanes/constants.ts
- packages/dashboard/src/components/resizablePanes/index.tsx
This PR is for ticket #2292 and to fix resource explorer width in different scenarios
1. default width (500px) on first opening the dashboard
2. default width on expanding resource explorer
3.  default width on changing edit and view mode if width is equal/less than default width
4. persists width between edit and preview view if width is greater than default 
[resource-explorer-width.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/78b80464-28fe-46d4-afd1-d01cfa120292)
> fix: updated the resource explorer default width

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/useSearch.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamQueryEditor.tsx
This PR is for #1994 
Added hasNext, fetchNextPage, isFetching data in useSearch hook and passed them to the ModeledDataStreamsTable component. Also added onNextPageClick in the pagination to call fetchNextPage callback.
https://github.com/awslabs/iot-app-kit/assets/139960352/8549f407-4ba6-47f6-b486-83fd86f0db96
> fix: missing pagination handling for searched model data #1994

- examples/react-app/src/components/SceneViewer.tsx
- packages/scene-composer/src/common/entityModelConstants.ts
- packages/scene-composer/src/components/SceneLayers.spec.tsx
- packages/scene-composer/src/components/SceneLayers.tsx
- packages/scene-composer/src/utils/entityModelUtils/processQueries.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/processQueries.ts
Improve the latency when fetching parentRef of sub model node by querying the relationship instead of calling get entity for each.
```
httpserver
```
> fix(composer): improve load sub model latency

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/useSearch.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTable.test.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/components/resourceExplorerErrorState.spec.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/components/resourceExplorerErrorState.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.test.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/useModeledDataStreams/useModeledDataStreams.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamQueryEditor.tsx
This PR is for ticket (a few sub tasks are covered here(3, 4 & 5)) #2242 and to update error state in Resource explorer tables
1. added error state for browse assets table
2. added error state for browse data streams table
3. added error state for search data streams table
Assets table error state:
Browse data stream table:
Search data stream table:
> feat: added the error state for resource explorer tables

- packages/dashboard/src/components/internalDashboard/index.tsx
Issue: #2309 
Enabled pagination for time machine in both edit and preview mode
https://github.com/awslabs/iot-app-kit/assets/139960352/72f284af-b97f-4575-9aab-6255548d4cdd
```
httpserver
```
> fix: time machine enable in edit and preview mode

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesTable/assetModelPropertiesTableFilter.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTableNameLink.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTablePropertyFilter.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTablePropertyFilter.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
- packages/react-components/src/components/table/messages.ts
Update all property filter aria labels from "your choice" to something actually descriptive
change clickable asset name aria label from "list child assets" to "List child assets of ${assetName}"
> fix: accessible property filter labels

- packages/react-components/src/components/time-sync/viewportAdapter.spec.ts
The tests written for the pagination viewport adapter used the current date. To simplify tests and ensure no blockers occur due to date rules, the date object is mocked to December 24th, 2022. Expect equal values for the tests were then changed accordingly.
> fix(react-components): mock date in viewport adapter date tests

- packages/react-components/src/components/chart/baseChart.tsx
This change removes the tweening animation from the line chart when zooming and panning.
> fix: remove line chart tweening animation

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/styleTab.tsx
- packages/dashboard/src/customization/propertiesSections/widgetTitle/index.tsx
- packages/dashboard/src/customization/propertiesSections/widgetTitle/titleSection.tsx
- packages/dashboard/src/customization/propertiesSections/widgetTitle/widgetTitle.test.tsx
- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/types.ts
This PR is for ticket #2312 and to show working title in Bar and status timeline widgets. and it includes
1. updated functioning tilte for Bar chart widget
2. showing title in empty state for xy-ploy / status-timeline
3. added functioning tilte for status-timeline widget
[bar&timeline-title.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/1c7707ad-e489-4d71-be41-b3a13e419a34)
> feat: added title in bar and status timeline

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
Bugfix for resource explorer selected properties in the modeled datastreams tab to clear the selection whenever the selected asset changes so that only the properties for the current selection are added.
> fix(dashboard): clear selected properties on asset change

- packages/dashboard/src/msw/handlers.ts
- packages/dashboard/src/msw/iot-sitewise/handlers/listAssetProperties/constants.ts
- packages/dashboard/src/msw/iot-sitewise/handlers/listAssetProperties/listAssetProperties.ts
- packages/dashboard/src/msw/iot-sitewise/resources/assetModels/index.ts
This change implements a listAssetProperties call to assetProperties.This enables two actions using MSW. Model Centric Visualization can now display the correct name in the legend and property config panel and the resource explorer can now be used to add datastreams to a widget. 
This is part 1 of a MSW change. Next part will solve the issues of 
- only IDs showing up in the legend when modeled resources are added 
- properties config panel not showing data
- addition of composition models.
https://github.com/awslabs/iot-app-kit/assets/145582655/3150d0a9-e3f3-41c8-a1ca-15845cb56500
> fix(dashboard): listAssetPropertiesCall for msw + path objects for all assetModels

- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.spec.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
Query in the useTimeSeriesData hook had all the style settings 
so every time the query changed the useEffect to fetch data would be triggered
fixed by making a new query object with minimum necessary data 
https://github.com/awslabs/iot-app-kit/assets/28601414/45aaf9b3-6a2e-4384-8f21-a69debf4614f
> fix: update dependency to not include styles

- packages/react-components/src/components/chart/trendCursor/mouseEvents/handlers/mouseover/index.ts
- packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
The trend cursor hotkey (T key) did not specify that the user was in a state to add a TC. To fix this, we change the cursor to a cross hair cursor on keydown to a crosshair instead of on mouse move.
https://github.com/awslabs/iot-app-kit/assets/145582655/68daa931-0b51-420b-897f-e56eca9fd813
> fix(react-components): trendcursor hotkey indicates addition state

- packages/dashboard/src/customization/propertiesSections/shared/colorPicker.tsx
- packages/dashboard/src/customization/propertiesSections/shared/styles.css
Removed div surrounding color picker input and used the input tags default keyboard focus state. Added CSS to maintain status quo visually.
https://github.com/awslabs/iot-app-kit/assets/145582655/bac78cb3-4935-4fb1-9aa9-7fd59c0e27ca
> fix(dashboard): color picker has keyboard focus and can be interacted with

- packages/scene-composer/src/components/StateManager.spec.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.tsx
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
trigger onSceneLoaded after dynamic scene is loaded
Tested with static scene, dynamic scene, static matterport scene and dynamic matterport scene, onSceneLoaded is triggered once after nodes and matterport are ready
```
httpserver
``` …
> fix(composer): trigger onSceneLoaded after dynamic scene is loaded

- packages/react-components/src/components/chart/legend/legend.tsx
Change legend table row key to a unique value (datastream id), instead of the non-unique datastream name.
> fix: use datastream id as legend table row key

- packages/core/src/data-module/TimeSeriesDataModule.spec.ts
- packages/core/src/data-module/TimeSeriesDataModule.ts
- packages/core/src/data-module/data-cache/caching/caching.ts
Prevent requests for each previous second when panning continuously over a viewport with the current time in view.
> fix(core): increase cache and min request interval to prevent making many requests for near now data

- packages/dashboard/src/store/actions/changeDashboardGrid/changeHeight.spec.ts
- packages/dashboard/src/store/actions/changeDashboardGrid/changeWidth.spec.ts
- packages/dashboard/src/store/actions/changeDashboardGrid/updateGrid.ts
This PR is for ticket #2313  and to correctly display columns and rows and it includes
1. widget selection is now updates with columns and rows changes
2. widget width and height will reset back to default when the columns and rows are reduced to less the widget width and height  and set max value again and will persist the x & y values as 0
[readjust-width-height.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/3697e22f-f18f-44dc-9f76-78915da6471b)
> fix: dashboard settings to set correct columns and rows

- packages/scene-composer/public/scene_1.scene.json
- packages/scene-composer/src/components/panels/scene-components/PlaneGeometryComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/PlaneGeometryComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/PlaneGeometryComponentEditorSnap.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/PlaneGeometryComponentEditorSnap.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.tsx
- packages/scene-composer/src/components/three-fiber/ModelGeometryComponents/PlaneGeometryComponent.spec.tsx
- packages/scene-composer/src/components/three-fiber/ModelGeometryComponents/PlaneGeometryComponent.tsx
- packages/scene-composer/src/components/three-fiber/ModelGeometryComponents/__snapshots__/PlaneGeometryComponent.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/SceneBackground.spec.tsx
- packages/scene-composer/src/components/three-fiber/SceneBackground.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/hooks/useTwinMakerTextureLoader.spec.tsx
- packages/scene-composer/src/hooks/useTwinMakerTextureLoader.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/three/TwinMakerTextureLoader.ts
- packages/scene-composer/src/utils/entityModelUtils/planeGeometryComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/planeGeometryComponent.ts
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
- packages/scene-composer/stories/Developer/SceneViewer.stories.mdx
- packages/scene-composer/stories/components/scene-composer.tsx
- packages/scene-composer/stories/components/scene-viewer.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
1.  Add texture selection support for backgrounds and planes
2. Fix camera loading too far out when a ground plane is in use
https://github.com/awslabs/iot-app-kit/assets/109186219/fabb0b63-fa1d-4034-9f2b-c13585612787
1. in stories/componens/scene-composer update the mockAssetBrowserCallBack to point at an image file you have locally instead of the models it defaults too
2. try and select a texture
```
cd …
```
> feat(scene): textures for backgrounds and planes

- packages/dashboard/src/components/actions/index.tsx
Changing the label on the settings button to be more descriptive of what the action enables.
> fix(dashboard): use more descriptive name for the settings label

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/browseSearchToggle.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
Implement metrics recording for query editor flows. Tracking when users add a data stream via modeled / unmodeled / asset modeled, and tracking which browsing feature they use for modeled data.
> feat(dashboard): add metrics for query editor usage

- packages/dashboard/src/components/widgets/tile/tile.css
- The Bar chart was broken due to the property which was add for Line chart.
- rectified it by changing the display value form 'flex' to 'grid'.
Before - 
After -
> fix: bar chart breaks due to css property of line chart

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/util/resourceExplorerTableLabels.tsx
This PR is for ticket #1952  (only for a sub-task) and to disable data streams based on data type and it includes
1. xy-plot and Bar-chart allow only data types Double and Integer to select on resource explorer.
2. disables all other data types and shows alt text "${data type} data not supported for the selected widget."
3. fixed the alt text issue for selected properties and selected all properties
[disable-properties.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/a28d570f-bd8e-4183-bf52-11b9a2d0fc5f)
> feat: xy-plot & bar-chart allow only datatypes (Double and Integer)

- packages/dashboard/src/components/grid/gestures/useDragMonitor.ts
- packages/dashboard/src/util/animate.spec.ts
- packages/dashboard/src/util/animate.ts
This change adds a utility class to the dashboard for interacting with `requestAnimationFrame` to ensure JS animations do not exceed 60 fps on higher refresh rate monitors (see https://github.com/awslabs/iot-app-kit/pull/2374/files?short_path=135a169#diff-135a169ecdaf84fe2e7a46562e86465bc5d44ff213ba9f0e41156c0e74b02c62).
> perf: initial Animator implementation

- package-lock.json
- package.json
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesTable/assetModelPropertiesTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
- packages/react-components/package.json
Bump cloudscape components package to `3.0.421`
to have access to the aria label `resizerRoleDescription` which labels the resizable column separator
> fix: table resize button aria label

- packages/dashboard/src/msw/iot-sitewise/handlers/listAssets/listAssetsHandler.ts
- packages/dashboard/src/msw/iot-sitewise/resources/assets/AssetFactory.ts
- packages/dashboard/src/msw/iot-sitewise/resources/assets/index.ts
Extended the fields in the asset factory to have path and other meta data needed to mock call. This allows the datastream to be completed with the right meta data and therefore display correctly on the dashboard. 
Edited the listAssetHandlers to list assets based on assetModel id if the call is made from the dynamic asset panel to display the values in the asset dropdown after model selection. 
https://github.com/awslabs/iot-app-kit/assets/145582655/25986991-1de3-416f-a230-a1244df81698
> fix(dashboard): datastreams are displayed in msw

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/browseSearchToggle.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
Reverts commit which introduces regression on ability to enter the search workflow on the resource explorer
> fix: Revert "feat(dashboard): add metrics for query editor usage"

- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdComponent.tsx
To provide an accessible name to the dashboard threshold delete button
verified attribute is present: `aria-label="delete threshold"`
> fix: added aria label to dashboard threshold delete button

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/util/resourceExplorerTableLabels.tsx
Search results do not have a data type, leading to always being disabled
Added check where if widget type OR data type are undefined then the item will not be disabled
before:
https://github.com/awslabs/iot-app-kit/assets/28601414/0151a446-5d13-4e13-99de-0243bca7baa9
after: 
https://github.com/awslabs/iot-app-kit/assets/28601414/590a23a4-57bd-402f-a6ab-e0b1f237df5c
> fix: broken search results disabled state

- packages/source-iotsitewise/src/time-series-data/client/batch.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/batch.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetLatestPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/client.ts
This change improves SiteWise data source performance by:
- Increasing the number of historical data points requested from 4k to 20k
- Increasing the batch size of latest value from 16 to 128.
> perf: increase batch size

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/dataStreamSearch.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
Adding back in logging for query editor that was reverted in this commit - [922384c0d13bade9e0491bcc378f1c6e05698969](https://github.com/awslabs/iot-app-kit/commit/922384c0d13bade9e0491bcc378f1c6e05698969)
This PR refactors the segment tracking logs to the search form.
> feat(dashboard): query editor logger

- packages/source-iotsitewise/src/time-series-data/client/batch.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/batch.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetLatestPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/client.ts
This reverts commit 15a6e6ad8b861384775e96616a985a0074d6a379.
This change is being reverted as it introduced an infinite pagination bug for the bar chart and status timeline components. The bug-free optimization will come in a separate PR.
> revert: "perf: increase batch size"

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTablePropertyFilter.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamQueryEditor.tsx
The purpose of this change is to make minor UX changes to the resource explorer that make the work flow more clear.
Users are confused by the filter workflow on the table, and confuse it with search, and often go directly to filter to try to find results.
I've mitigated this by hiding the filter and property table when it does not need to be shown. 
UX changes can be seen in the following screenshots:
> feat(ResourceExplorer):  hide properties table when not needed to be displayed

- packages/scene-composer/public/scene_1.scene.json
- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/panels/SettingsPanel.tsx
- packages/scene-composer/src/components/panels/scene-components/PlaneGeometryComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/PlaneGeometryComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/PlaneGeometryComponentEditorSnap.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/PlaneGeometryComponentEditorSnap.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.tsx
- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.tsx
- packages/scene-composer/src/components/three-fiber/GroundPlane.spec.tsx
- packages/scene-composer/src/components/three-fiber/GroundPlane.tsx
- packages/scene-composer/src/components/three-fiber/ModelGeometryComponents/PlaneGeometryComponent.spec.tsx
- packages/scene-composer/src/components/three-fiber/ModelGeometryComponents/PlaneGeometryComponent.tsx
- packages/scene-composer/src/components/three-fiber/ModelGeometryComponents/__snapshots__/PlaneGeometryComponent.spec.tsx.snap
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/utils/entityModelUtils/planeGeometryComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/planeGeometryComponent.ts
- packages/scene-composer/stories/components/scene-composer.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
1. Move Add ground plane to Scene Settings
2. instead add/remove with ground plane Toggle
3. Swap Enable Fog, to toggle instead
4. remove enable background - always on but with default color 
5. For implementation the ground plane not a toggle, - add transparency and default to a color and 100% transparency so not visible until edited.
6. Ground plane is NOT visible in scene hierarchy
7. Ground plane is edited in Scene Settings NOT node inspector and can set Color, Texture, Transparency. It can't be resized anymore
8. Clicking the ground plane does NOT parent an item to it, instead it parents to the scene root
https://github.com/awslabs/iot-app-kit/assets/109186219/f15e1658-7eb6-4dee-bf33-2ff2a6c929ef
For `scene-composer` package changes specifically, you can preview the component in the …
> feat(scene): move add ground plane to settings

- packages/dashboard/src/store/actions/changeDashboardGrid/changeHeight.spec.ts
- packages/dashboard/src/store/actions/changeDashboardGrid/changeWidth.spec.ts
- packages/dashboard/src/store/actions/changeDashboardGrid/updateGrid.ts
This reverts commit 5eb72e7f92b07e6678227d332031642baa8332ff.
this commit is causing the other widgets to shrink when you drag and drop a "Text" widget
Before 
https://github.com/awslabs/iot-app-kit/assets/135036199/6eeb2e26-cb2f-4631-bef8-691d8a182749
After 
https://github.com/awslabs/iot-app-kit/assets/135036199/753a0b65-0cc1-41fa-80ea-36dd968fffdc
> revert: fix - dashboard settings to set correct columns and rows #2313"

- packages/dashboard/src/customization/propertiesSections/textSettings/link.tsx
This PR fixes the accessibility issue [#2362](https://github.com/awslabs/iot-app-kit/issues/2362)
Accessibility report using axe DevTools before fix:
Accessibility report using axe DevTools after fix:
Screen reader is able to read the URL Input field.
> fix: added aria-label to the config panel text link control for accessibility

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/yAxis.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/chart/chartOptions/axes/yAxis.ts
- packages/react-components/src/components/chart/chartOptions/converters.spec.ts
- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/types.ts
This PR is for the ticket: #2378 
- Added Y-axis input field in the config panel under widget level-> y-axis container.
- Also added nameLocation and nameGap props to set the location and alignment for the y-axis label.
- Added y-axis label updater callback to update the y-label in the line scatter widget.
https://github.com/awslabs/iot-app-kit/assets/139960352/0195057a-67b4-4544-b1a2-123e35608eb1
> feat: xy-plot y axis lable changes #2378

- packages/dashboard/e2e/tests/dashboard/dashboard.spec.ts
- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/assetModelSelection/assetModelSelect.tsx
- packages/dashboard/src/components/assetModelSelection/assetModelSelection.css
- packages/dashboard/src/components/assetModelSelection/assetModelSelection.tsx
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/dashboard/view.test.tsx
- packages/dashboard/src/components/internalDashboard/collapsiblePanel.tsx
- packages/dashboard/src/components/internalDashboard/dashboardHeader.spec.tsx
- packages/dashboard/src/components/internalDashboard/dashboardHeader.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/palette/index.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetsForAssetModelSelect/assetForAssetModelSelect.tsx
- packages/dashboard/src/styles/variables.css
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
- packages/react-components/src/components/time-sync/timeSelection.tsx
This change is for the ticket #1947 
- Added new header design at the top.
- Displayed dashboard title on the left side and time series and actions buttons on the right side.
- Also displayed the asset model selection dropdown on the white background toolbar in preview mode.
- Fixed scroll issue and bar chart alignment issue due to new header height.
https://github.com/awslabs/iot-app-kit/assets/139960352/fc438b1d-fc4f-4f73-a49a-cca82414df65
> feat: dashboard new header design #1947

- packages/dashboard/src/msw/iot-sitewise/handlers/batchGetAssetPropertyValue/batchGetAssetPropertyValueHandler.ts
Currently, the value provided to `timeInSeconds` is in `ms` but the expected unit is `s`.
This PR fixes the value provided to `timeInSeconds` by dropping the last 3 digits.
> fix: msw batchGetAssetPropertyValueHandler response timeInSeconds values

- packages/dashboard/src/customization/propertiesSections/shared/colorPicker.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/text.tsx
This PR addresses the accessibility issue [#2361](https://github.com/awslabs/iot-app-kit/issues/2361)
There was no difference in screen reader behaviour with this change, the screen reader was already announcing the color label and color control without this change because aria-label is already present.
**DOM before making this change:**
**DOM after making this change:**
> fix: programatically linked the color picker control with color label in config panel text

- packages/react-components/src/components/chart/eChartsConstants.ts
confining the tooltip within chart area
refer to the screen share
https://github.com/awslabs/iot-app-kit/assets/135036199/f56b3d90-774e-4e6f-8fec-133ca05a9210
> fix(react-components): confining the tooltip within chart area

- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetLatestPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/withinLatestPropertyDataThreshold.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/withinLatestPropertyDataThreshold.ts
- packages/source-iotsitewise/src/time-series-data/data-source.spec.ts
This PR added logic to avoid unnecessary raw data requests. This is achieved by selectively calling `BatchGetAssetPropertyValue` only for live. Previously, additional calls to `BatchGetAssetPropertyValueHistory` are made for live.
More about the logic:
1. `batchGetLatestPropertyDataPoints` accepts the `fetchMostRecentBeforeEnd` request when the end date is within 10 seconds, and the request is sent to `BatchGetAssetPropertyValue`
1. `batchGetHistoricalPropertyDataPoints` accepts the `fetchMostRecentBeforeEnd` request when the end date is older than 10 seconds, and the request is sent to `BatchGetAssetPropertyValueHistory`
2. no changes made to `batchGetAggregatedPropertyDataPoints` since `batchGetAggregatedPropertyDataPoints` is expected to handle any aggregate data (historical and live) …
> perf: improve raw batching

- packages/react-components/global-jest-setup.js
- packages/react-components/jest.config.ts
- packages/react-components/src/components/time-sync/viewportAdapter.spec.ts
- turbo.json
This change fixes a broken test for relative month duration by explicitly setting the timezone used by Jest. The calculation for number of days was removed as the date is hard-coded and not dynamic (i.e., it's not necessary).
See https://stackoverflow.com/questions/56261381/how-do-i-set-a-timezone-in-my-jest-config for solution information.
> fix: relative month test

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesSectionsStyle.css
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdComponent.css
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdComponent.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdStyle.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
Added 8px padding on the left to every item in each tab in the config panel. Also removed the horizontal scroll on the threshold panel. 
> fix(dashboard): padding for tabs in config panel + remove scroll in threshold panel

- packages/react-components/src/components/chart/chart.css
set outline property to none in chart css to remove the focus border
Before:
https://github.com/awslabs/iot-app-kit/assets/145582655/48dc70bd-6014-4b71-9273-f18e2c72e002
After:
https://github.com/awslabs/iot-app-kit/assets/145582655/7de8c2c6-2eb6-4999-a29c-806f2bbb0aa8
> fix(react-components): remove secondary selection state when using TCs or gestures

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.css
- packages/dashboard/src/customization/propertiesSections/settings/section.tsx
Change property-label width from 288px to 355px to span the entire container. 
Added padding to KPI widget
Before:
After:
> fix(dashboard): increase width of property label in config panel to span width of panel

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chartOptions/convertOptions.ts
- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/chartOptions/style/convertStyles.ts
- packages/react-components/src/components/chart/hooks/useVisualizedDataStreams.ts
- packages/react-components/src/components/chart/trendCursor/constants/index.ts
- packages/react-components/src/hooks/useECharts/useEChartOptions.ts
- packages/react-components/src/hooks/useECharts/useGroupableEchart.ts
- packages/react-components/src/hooks/useECharts/useLoadableEChart.ts
- packages/react-components/src/utils/useEffectDebugger.ts
1. to avoid unnecessary calculations on change of certain input props, adding appropriate memo and useEffect with dependencies converted into string using JSON.stringify 
This should helps us save some cycles and stop unnecessary setting of echart options.
2. added a utility debugger useEffect which can used to debug useEffect when required. 
https://github.com/awslabs/iot-app-kit/assets/135036199/ae322030-91ed-438f-99a8-9a37f9ab0498
> fix(react-components): performance fixes for chart component

- packages/dashboard/src/customization/widgets/text/styledText/index.tsx
- packages/dashboard/src/customization/widgets/text/styledText/textArea.tsx
issue: #2429
as mentioned - 
- added the padding, instead of 2-4px I have added 8px because 8px gives the clear spacing for content.
- the blinking cursor is there already, it was just hiding due to no padding.
- removed the background of the textbox.
[screen-capture (3).webm](https://github.com/awslabs/iot-app-kit/assets/65999096/333513f2-306f-44a5-b5ed-5fa0a8d74684)
> fix: text widget enhancement - 2429

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.css
- packages/react-components/src/components/chart/legend/legend.css
- packages/react-components/src/components/chart/legend/legend.tsx
This PR makes the UI changes for section 'User experience of the chart component' on ticket #2277 
1. With scrollbar
[legend-UI-with-scroll.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/1f0ba2f7-1b95-41bf-b665-6ead82f19f8c)
2. Without scrollbar
[legend-UI-without-scroll.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/b60b63ca-3b8b-4a3f-9039-c998e87c1378)
> feat: Changed UI experience of chart legend based on legend position

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/disableAdd.spec.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/disableAdd.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
or kpi/status disable add of RE when an property is already added
disable add for kpi/status when they already have a property 
This was previously merged but was revered due to not be able to add a property when the user copies a widget, removes the property and tries to add a property again. 
https://github.com/awslabs/iot-app-kit/assets/135036199/606b14e5-7696-43a1-bd70-b6a9d8e3014d
> fix(dashboard): disable add for kpi/status when they already have a property

- packages/source-iotsitewise/src/time-series-data/client/batch.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/batch.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/data-source.spec.ts
The following options could be all true at a given time `fetchMostRecentBeforeStart`, `fetchMostRecentBeforeEnd`, and `fetchFromStartToEnd`; however, the current code logic does not handle them correctly when more than 1 option at a time.
This PR fixes the issue aforementioned.
more about what the options should do, see [doc](https://awslabs.github.io/iot-app-kit/?path=/docs/core-time-series-data--docs)
Manual testings - panning with aggregation/row data
> fix: source-iotsitewise batch API options

- packages/core/src/data-module/TimeSeriesDataModule.ts
- packages/core/src/data-module/data-cache/dataCacheWrapped.ts
- packages/core/src/data-module/data-cache/dateUtils.ts
- packages/dashboard/src/components/dashboard/queryContext.ts
- packages/dashboard/testing/siteWiseQueries.ts
- packages/source-iotsitewise/src/initialize.ts
- packages/source-iotsitewise/src/time-series-data/fetchTimeSeriesData.ts
implement fetchTimeSeriesData which is an async function which returns dataStreams from the cache
does NOT complete data streams due to current limitations with our dataSource
works with multiple widgets now :)
https://github.com/awslabs/iot-app-kit/assets/28601414/51e6271e-8268-4b53-8a1c-b6fe2f551b2f
> feat: fetchTimeSeriesData

- packages/doc-site/.storybook/main.js
canvas not recognised automatically so need to update storybook config
https://github.com/awslabs/iot-app-kit/assets/135036199/5a983df8-8364-4b27-a824-3e0de5e49a53
> fix(doc-site): canvas not recognised automatically

- packages/dashboard/src/data/listAssetPropertiesMap/fetchListAssetPropertiesMap.tsx
- packages/dashboard/src/data/listAssetPropertiesMap/query.tsx
- packages/dashboard/src/data/listAssetPropertiesMap/selectData.tsx
- packages/dashboard/src/hooks/useAssetDescriptionQueries.ts
create async version of `useListAssetPropertiesMapQuery`
and add shared logic into nicely organized files :) 
had to pull out shared code in order to preserve existing caching logic
by using the same cache key for both the hook and the async function, they can share a cache thanks to the magic of tanstack :) 
> feat: async listAssetPropertiesDescription

- packages/core/src/data-module/TimeSeriesDataModule.ts
- packages/core/src/data-module/data-cache/dataCacheWrapped.spec.ts
- packages/core/src/index.ts
- packages/source-iotsitewise/src/initialize.ts
- packages/source-iotsitewise/src/time-series-data/fetchTimeSeriesData.ts
Add request settings to the async fetchTimeSeriesData function to gracefully handle bar charts and their resolution mapping.
Bar charts do not support raw data so when resolution is set to auto, the bar chart has a custom mapping of auto resolution => new resolution
> fix: add request settings to fetchTimeSeriesData

- packages/react-components/src/components/chart/contextMenu/ChartContextMenu.tsx
- packages/react-components/src/components/chart/eChartsConstants.ts
* Fix for an issue where chart tooltips will overlap and display on top of a charts context menu, which makes it harder to use the context menu since it should always be on top
* This change increases the z-index for the context menu such that it appears on top of the tooltip
* I wasn't sure of a better solution than just hardcoding z-index greater than the tooltip, so let me know if you have any other ideas
1. Create any chart
2. Hover mouse over chart to see tooltip
3. Right click to see context menu
4. Validate context menu displays on top of tooltip
https://github.com/awslabs/iot-app-kit/assets/66272633/b39c68b4-9558-4618-bf5f-24506234a7a3
> fix: make context menu appear on top of chart tooltip

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/legendSection.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.spec.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/yAxis.tsx
This PR is for ticket #2467 and it includes
1. disable legend options if the legend is hidden
2. disable Y-axis options if the Y-axis is hidden
[disable-legend-yaxis.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/50e21713-827f-489f-ad6f-db35d73faab4)
> fix: disable options in legend or yaxis section if legend or y-axis is hidden

- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyPanel.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/__snapshots__/SceneHierarchyPanel.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
- packages/scene-composer/stories/Developer/SceneViewer.stories.mdx
- packages/scene-composer/stories/FirstPerson.stories.mdx
- packages/scene-composer/stories/Highlight.stories.mdx
- packages/scene-composer/stories/Matterport.stories.mdx
- packages/scene-composer/stories/SceneViewer.stories.mdx
Removed the following feature flags that are already available to all customers:
* i18n
* SceneHierarchySearch
* SceneHierarchyReorder
* SubModelSelection
* ENHANCED_EDITING
Ran unit tests and verified functionality of local scene composer and viewer on storybook.
```
httpserver
``` …
> chore(scene-composer): remove old feature flags part 1

- packages/react-components/src/components/chart/chartOptions/axes/yAxis.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
video of zoom working with default y axis:
https://github.com/awslabs/iot-app-kit/assets/28601414/97e8e9d6-eaf1-4de7-8f05-638309f59bce
video of zoom working with multiple custom y axis and NOT defaulting to 0:
https://github.com/awslabs/iot-app-kit/assets/28601414/e7712028-52f7-43b4-b2ba-907d2f37d7d5
video of axis adjusting as user scrolls:
https://github.com/awslabs/iot-app-kit/assets/28601414/0ef0c9fb-d457-4091-b984-ed20d929bebe
---
> fix: improved zoom and default values for y axis

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.css
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
Change width of property label from 355 to 350px to make sure no overflow of delete button on any browser
> fix(dashboard): decrease width of property label in config panel to stop overflow of delete button

- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyPanel.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/__snapshots__/SceneHierarchyPanel.spec.tsx.snap
- packages/scene-composer/src/components/panels/SettingsPanel.spec.tsx
- packages/scene-composer/src/components/panels/SettingsPanel.tsx
- packages/scene-composer/src/components/panels/__snapshots__/SettingsPanel.spec.tsx.snap
- packages/scene-composer/src/components/panels/__tests__/SceneNodeInspectorPanel.spec.tsx
- packages/scene-composer/src/components/panels/__tests__/TopBar.spec.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/SceneRuleTargetEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/__tests__/__snapshots__/SceneRuleTargetEditor.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/ColorOverlayComponent/index.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/layouts/SceneLayout/SceneLayout.spec.tsx
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
- packages/scene-composer/stories/Developer/SceneViewer.stories.mdx
- packages/scene-composer/stories/FirstPerson.stories.mdx
- packages/scene-composer/stories/Highlight.stories.mdx
- packages/scene-composer/stories/Matterport.stories.mdx
- packages/scene-composer/stories/SceneViewer.stories.mdx
Removed the following feature flags that are already available to all customers:
* CameraView
* OpacityRule
* TagResize
* Overlay
Ran unit tests and verified functionality of local scene composer and viewer on storybook.
```
httpserver
``` …
> chore(scene-composer): remove old feature flags part 2

- packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts
- packages/dashboard/e2e/tests/utils/resourceExplorer.ts
- packages/dashboard/src/components/queryEditor/helpers/isModeledPropertyInvalid.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesTable/assetModelPropertiesTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
Templating/Dynamic Assets table disables a property if its dataType is not supported by the chart 
---
> fix: template asset table disables invalid dataTypes

- packages/dashboard/src/customization/propertiesSections/settings/index.tsx
- packages/react-components/src/components/chart/chartOptions/axes/yAxis.ts
- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSeriesAndYAxis.ts
Add significant digits settings to XY Plot
(style looks different but is fixed by https://github.com/awslabs/iot-app-kit/pull/2492) 
https://github.com/awslabs/iot-app-kit/assets/28601414/810866b0-42ae-48fd-8818-536be432e866
> fix: add signigicant digits to xy plot

- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.css
- packages/react-components/src/components/chart/tests/baseChart.spec.tsx
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/trend-cursor-sync/trendCursorSync.spec.tsx
- packages/react-components/src/hooks/useECharts/useResizeableEChart.ts
- packages/react-components/src/hooks/useECharts/useResizeableEchart.spec.ts
- packages/react-components/src/hooks/utils/pxToPercentage.spec.ts
- packages/react-components/src/hooks/utils/pxToPercentage.ts
- packages/react-components/stories/chart/base-chart.stories.tsx
- packages/react-components/stories/trend-cursor-sync/timesync.stories.tsx
This PR is for ticket #2277 (Saving the legend height and width to the dashboard definition)
Made changes on resizing the legend width(In the left and right position) and height(in the bottom position) to save the legend size in redux and on clicking the save button saves the data in localStorage(db). In this PR I used percentage(%) as width and height for the calculations of legend, chart, and left legend sizes.
Without left legend:
https://github.com/awslabs/iot-app-kit/assets/139960352/9a348446-89ed-4128-94a3-0f015dd2da2d
With left legend:
https://github.com/awslabs/iot-app-kit/assets/139960352/d6b8a039-bd59-4f8e-a4a6-953fd2819535
> feat: legend resize

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/workspaceSelector/workspaceSelector.tsx
This PR adds below functionality to the workspace dropdown in resource explorer #2384 
1. Automatically selects first available workspace from the options list, if nothing was selected previously
2. If some workspace option was selected previously, it is stored in localStorage, and on next load, the same option is set as default(i.e. automatically selected)
3. If Previously selected option which is stored in localStorage is no longer present in the workspace options list, it will not be selected automatically, instead first option from the list will be selected.
First time load:
[Screencast from 05-01-24 05:31:06 PM IST.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/4ec97422-7430-4325-88e1-939130f3af0b)
Next renders:
[Screencast from 05-01-24 05:32:01 PM …
> feat: auto select previously selected workspace or first workspace from options

- packages/dashboard/src/components/internalDashboard/dashboardEmptyState.css
fix the dashboard's empty state overflowing into the nav area by adding a margin and removing the transform/positioning
temporary fix until nischay's rework of the entire panel/layout system 
issue was due to a mixed use of `overflow: hidden` and `position: fixed` with a transform which do not work together
---
before: 
after:
[video](https://github.com/awslabs/iot-app-kit/assets/28601414/e7bde06a-14a2-45eb-b76b-0cc847d80384)
> fix: empty state overflow

- packages/dashboard/src/customization/propertiesSections/components/legendDisplaySection.tsx
- packages/dashboard/src/customization/propertiesSections/constants.ts
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/legendSection.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.spec.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/chart/legend/table/legendTableAdapter.tsx
This PR is for ticket #2277  and implemented display unit feature and it includes
1.  default display property units is true
2. user can toggle the display unit in the config legend section
3. for undefined unit value showing/displaying empty
[display-unit.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/98a1738f-ca73-43b7-aabf-bbf22e8710cd)
> feat: display legend unit conditionally 

- examples/react-app/package.json
- package.json
undo version bump of vite 4.5.1 
package-lock inspected
```
httpserver
```
> chore(example): drop vite back to 4.5.1

- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
Saw on the Console that the 3D model modal did not appear when first trying to click on "+" --> "Add 3D model". It only worked after trying to add another widget to the scene. This is due to making the `handleAddModel` function use a `useCallback`. Removing this fixes the issue.
Verified that adding any other widget for the first time on page load is not impacted as well.
Verified the fix in storybook, see the videos below.
Before:
https://github.com/awslabs/iot-app-kit/assets/87385528/8fd8d253-dd45-4409-8865-3a25632014a3
After:
https://github.com/awslabs/iot-app-kit/assets/87385528/efc2ac41-21eb-4951-8392-c46bcedb43d3
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for the `Publish Storybook` action to …
> fix(scene-composer): 3D model selection broken on first click

- packages/react-components/src/components/chart/chartOptions/axes/yAxis.ts
This PR is for #2471 
Increased nameGap to avoid overlapping yAxis Labels with yAxis name but it supports up to 5 digits/characters only, and there is an open issue(#9265) and In-review CR(19534) in the echarts. 
TODO: Will update this nameGap once CR gets fixed from the echarts team.
https://github.com/awslabs/iot-app-kit/assets/139960352/b47e7464-3c6c-4d91-afcb-b071986e9ea6
NA
> fix: yAxis label collides with yAxis name #2471

- packages/dashboard/src/components/dashboard/view.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
fix: view only mode did not work since it did not have a tanstack provider 
fix: main mode storybook now saves dashboard config to localStorage and makes the dashboard reload with new config, making the dev experience match the centurion implementation
better storybook dev: 
fixed view mode:
> fix: realistic dev experience on storybook

- packages/dashboard/src/components/widgets/widget.css
Currently, when you place widgets near each other in edit mode and then preview them, the spacing between them disappears. This was due to widgets having a "selection box" that was rendering around the widgets.
The widget positions in the dashboard defintion were correct. We can see that because one of the placed widget starts at 0,0 and has width 18. The next widget starts at 0,18. 
To fix this, we changed the widget box-sizing property to be "content-box" from "border-box" to limit the selection state within the widget border. 
https://github.com/awslabs/iot-app-kit/assets/145582655/357a7111-300a-4537-a226-fd572b454f86
> fix(dashboard): spacing issues on editable grid

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesTable/assetModelPropertiesTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/disableAdd.spec.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/disableAdd.ts
The issue was that we were not checking the selection properties count
when we add  a kPI / status, we are allowing the user to add more than 1 property
this particular bug was becasue, when we selected kpi, we check if it already has properties added but did not check if more than 1 is selected. given for other widget type we can add more than one, the logic was obviously wrong.
Also, this was done only for modeled data and had missed unmodeled and asset models
https://github.com/awslabs/iot-app-kit/assets/135036199/68a9f83f-1734-49ea-a5b7-aab9c5683827
This project is available under the [Apache 2.0 License](http://www.apache
.org/licenses/LICENSE-2.0.html).
> fix: kpi add prop bug

- packages/dashboard/src/components/widgets/widget.css
Currently, when you place widgets near each other in edit mode and then preview them, the spacing between them disappears. This was due to widgets having a "selection box" that was rendering around the widgets. Rendering this border for read-only widgets solves the issue.
https://github.com/awslabs/iot-app-kit/assets/145582655/90c27bd6-91d9-4920-8d5a-7aaeb1fa3432
> fix(dashboard): fix spacing between widgets without selection box

- packages/scene-composer/public/overlay.scene.json
- packages/scene-composer/public/scene_1.scene.json
- packages/scene-composer/public/scene_2.scene.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/tests/scenes/matterport.json
- packages/scene-composer/tests/scenes/scene_1.json
- packages/scene-composer/tests/scenes/scene_2.json
clean up unused scene model fields
- defaultCameraIndex
- BaseUrl
```
httpserver
```
> chore(composer): clean up unused scene model fields

- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/react-components/src/components/chart/store/context.tsx
- packages/react-components/src/components/chart/store/store.ts
- packages/react-components/src/store/chartStoreSlice.ts
- packages/react-components/src/store/index.ts
This change solves https://app.asana.com/0/1204375185707273/1206385082271207 using persist() in the Zustand library. https://docs.pmnd.rs/zustand/integrations/persisting-store-data#hashydrated
- Linked and persisted each chartStore with the widget id, so each store has its own unique store that remains populated with the correct data through edit/preview modes and refresh. 
- Persisted the global store, so that it does not reset to an empty object on edit/preview modes and refresh
These cases are outlined in the ticket linked above. I tested more within each video to try to catch edge cases. 
Case 1:
https://github.com/awslabs/iot-app-kit/assets/145582655/3e21a6d1-318c-4411-bd47-0ebb7d1759c2
Case 2:
https://github.com/awslabs/iot-app-kit/assets/145582655/2695ea46-ddd9-48c7-a388-a60cbce6044 …
> fix: hidden and highlighted datastreams persist correctly

- packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts
- packages/dashboard/e2e/tests/utils/resourceExplorer.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- changed current useEffect hook that resets selected items to depend on selectedAsset asset id primitive instead of selected asset object.
- added useEffect hook that deselects already selected options that are not compatible with widget type 
https://github.com/awslabs/iot-app-kit/assets/145582655/0fab202f-5281-4d66-8025-1b54b416df13
> fix(dashboard): selected assets do not deselect on widget selection

- packages/scene-composer/src/common/entityModelConstants.ts
- packages/scene-composer/src/utils/entityModelUtils/overlayComponent.spec.ts
The property string length limit has increased to 2048 in backend, therefore making this update in frontend.
Tests done:
- Overlay component with multiple pieces of contents can still be rendered properly, updating the content will split the content into pieces using the new 2048 length limit
- Overlay content splitted with the new 2048 limit can still be rendered correctly in the composer using the old 256 limit, updating the content will split the content into pieces using the old 256 length limit
To run the …
> fix(composer): update property string length limit to 2048

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/workspaceSelector/workspaceSelector.tsx
On-click of search the "selected workspace" field throws error inspite of being defaulted to the first available or previously selected 
https://github.com/awslabs/iot-app-kit/assets/135036199/78cc5721-3a48-4101-884c-e51261dac002
> revert: feat- automatically selecting previously selected workspace or first workspace

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
Scene Composer component does not have the sub-model selection feature enabled by default. Needed to update the `useMemo` variable dependency list with the `model` variable.
Tested on storybook.
Image before - no sub-model selection tree:
Image after - sub-model selection tree shows up and I am able to add a sub-model to the scene hierarchy:
```
httpserver
``` …
> fix(scene-composer): fix sub-model selection

- packages/react-components/src/components/chart/eChartsConstants.ts
toolbox zoom on x+y would cut off data points within x range but outside y range
set filter mode to none 
https://github.com/awslabs/iot-app-kit/assets/28601414/30d47fa0-ad23-4c26-9fd2-17d0c570e8a9
similar to this issue: https://github.com/apache/echarts/issues/12247
> fix: fix filtered data on zooms

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
Scene hierarchy does not list nodes in viewer mode. Fixed the line that locked the hierarchy items to edit mode.
Verified on storybook.
Before the change:
After the change:
```
httpserver
```
> fix(scene-composer): fix scene hierarchy in viewer mode

- .github/workflows/npm-publish.yml
Set the node version to match all the other yml files with v16.x.x
> fix: set npm-publish node version to v16

- packages/scene-composer/src/common/entityModelConstants.ts
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
Save scene level data to scene root entity if exists and gated by a new feature flag DynamicSceneAlpha.
```
httpserver
```
> feat(composer): save scene level data to scene root entity

- examples/react-app/src/pages/Home/index.tsx
Updates to our event API mean that the sceneViewer onSelectionChange event may return multiple components.  So the exampel can no longer assume that binding information is located at index Zero. It needs to check the list of component types in the event data and then use that index to find the element of the same index in the additionalData property.
Run the react example using a workspace with models that have Entity Binding and at least on other component like a shader etc
Click a model with a bound entity in the scene.
the models name should should show up in the knowledge graph widget
the model should turn red
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for the `Publish Storybook` action to …
> fix(example):  make sure selection change uses the entity binding component index

- packages/dashboard/src/customization/propertiesSections/textSettings/text.tsx
Changes to resolve the accessibility issue #2547 
When user focuses on text color style buttons using tab key, the outline color will help user to identify the focused state.
Before the outline color contrast was low for those buttons:
[faint-tab-focus-configPanelText-buttons.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/1a7cfdef-86f0-44d1-b6ca-895886f5f0f7)
Now with this PR, color contrast is changed:
[blue-outline-tab-focus.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/4cd5ad11-6782-4383-ac77-a8485feb527d)
> feat: color contrast ratio on tab focus of buttons in config panel text style

- packages/scene-composer/src/store/helpers/__tests__/sceneDocumentHelpers.spec.ts
- packages/scene-composer/src/store/helpers/sceneDocumentHelpers.ts
Fix cannot delete scene node of a child and then its parent.
https://github.com/awslabs/iot-app-kit/assets/9315598/e630525e-19b5-49fd-83ca-0468dc41b023
```
httpserver
```
> fix(composer): cannot delete scene node of a child and then its parent

- packages/core-util/package.json
- packages/core/package.json
- packages/dashboard/package.json
- packages/source-iotsitewise/package.json
Allows the consumer application to bring in different versions of the dependencies (than AppKit specified) while being compatible with AppKit.
An application is using a version of AWS SDK client and want to initialize AppKit with that client. E.g. `const { query } = initialize({ iotSiteWiseClient });` in ([AppKit doc](https://awslabs.github.io/iot-app-kit/?path=/docs/overview-getting-started--docs)).
Example - [when the consumer app inits with AWS clients](https://github.com/awslabs/iot-application/blob/6b0bb7a82757ea100e44e4f59a0de39833521f7a/apps/client/src/routes/dashboards/dashboard/dashboard-page.tsx#L40-L47) and causes compatibility issue:
1. Ran storybook on connected and mocked data, and verified functional
2. [Built and use npm package under IoT …
> fix: aws clients marked as peer dependencies

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/types.ts
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
add a viewMode property to the `onSave` function so that parent component can handle preserving state of dashboard onSave
example in dashboard consumer
```
const [initialViewMode, setInitialViewMode] = useState('edit');
const onSave = async (dashboard: DashboardConfiguration, viewMode?: 'preview' | 'edit') => {
viewMode && setInitialViewMode(viewMode);   // initialViewMode will be stored locally
... rest of save functionality
};
// setInitialViewMode is then passed to the dashboard
<Dashboard initialViewMode={setInitialViewMode} ...rest of dashboard config/>
```
https://github.com/awslabs/iot-app-kit/assets/28601414/58ff57f9-b854-49f3-ba40-3ddcb801f342
> fix: preserve viewMode onSave

- package.json
- packages/react-components/package.json
- packages/react-components/src/components/knowledge-graph/tests/__snapshots__/KnowledgeGraphPanel.spec.tsx.snap
- packages/react-components/src/components/tooltip/tooltip.tsx
Bump all cloudscape packages to latest versions
`@cloudscape-design/collection-hooks: "1.0.36"`
`@cloudscape-design/components: "3.0.518"`
`@cloudscape-design/design-tokens: "3.0.34"`
`@cloudscape-design/global-styles: "1.0.23"`
And remove unused dependency:
`@cloudscape-design/component-toolkit: "1.0.0-beta.26"`
> chore: update cloudscape to latest versions

- packages/core/src/common/types.ts
- packages/scene-composer/src/common/GlobalSettings.spec.ts
- packages/scene-composer/src/common/GlobalSettings.ts
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.spec.tsx
- packages/scene-composer/src/interfaces/sceneComposerInternal.ts
- packages/scene-composer/stories/components/scene-composer.tsx
- packages/scene-composer/stories/components/theme-manager.tsx
- packages/source-iottwinmaker/src/data-binding-provider/EntityPropertyBindingProviderStore.spec.ts
- packages/source-iottwinmaker/src/index.ts
- packages/source-iottwinmaker/src/metadata-module/TwinMakerMetadataModule.spec.ts
- packages/source-iottwinmaker/src/metadata-module/TwinMakerMetadataModule.ts
- packages/source-iottwinmaker/src/metadata-module/types.ts
- add prop in SceneComposerInternal component to show flash massage
- add `meta` field to ErrorDetails to pass through additional metadata from data source
```
httpserver
```
> feat(composer): support showing flash message

- packages/scene-composer/src/components/three-fiber/ModelRefComponent/TilesModelComponent.tsx
- packages/scene-composer/src/three/tiles3d/TilesRenderer.js
- packages/scene-composer/src/three/tiles3d/raycastTraverse.js
- packages/scene-composer/src/utils/objectThreeUtils.ts
The raycasting for 3D Tiles has not been optimized like other GLTF models. This PR enables three-mesh-bvh `acceleratedRaycasting` to improve the calculation of intersections for raycasting in the scene.
The [3D Tiles renderer](https://github.com/NASA-AMMOS/3DTilesRendererJS) that we use calls a couple raycast methods `raycastTraverse()` and `raycastTraverseFirstHit()`. These methods use the helper `intersectTileScene()` which forces the built-in `raycast` method of the Object3D / Mesh class. This helper must be overwritten to use the object instance's `raycast` method, which we overwrite in `TilesModelComponent`.
I copied over the version of the `raycastTraverse.js` script that AppKit uses, version `0.3.16`.
* [Reference](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/fada8f7394b7a98 …
> feat(scene-composer): enable accelerated raycasting for 3D Tiles

- packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.spec.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdComponent.tsx
This PR addresses the accessibility issues #2512  and #2513 
1. Added visible label 'Operator' for arithmetic operator
2. Added visible label 'Value' for threshold input
**Before (there were no visible labels):**
**After adding visible labels to arithmetic operator and threshold value input:**
**UPDATE**:
We have raised single PR for two tickets, as adding only one label made it look incomplete like this:
> feat: added visible labels for config panel threshold controls

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/assetModelSelection/assetModelSelection.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/palette/component.tsx
- packages/dashboard/src/components/palette/index.tsx
- packages/react-components/src/components/time-sync/timeSelection.tsx
This PR is to address accessibility issue related to Toolbars mentioned in ticket #2510 
Before making changes, this is how screen reader announces the toolbars:
https://github.com/awslabs/iot-app-kit/assets/142866907/d4441e93-f5b1-41e7-90ec-e658099dcb07
After adding aria-labels to containers, screen reader announces it and stops, unless user tabs over to particular element inside that container, it doesn't announce the element example: save and preview buttons.
https://github.com/awslabs/iot-app-kit/assets/142866907/9e75a230-31ee-492e-8eb4-bbbdc841ca5a
> feat: added accessible labels to different toolbar containers

- packages/scene-composer/e2e/tests/local-scene/scene-composer--local-scene.spec.ts
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneNodeLabel.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/SceneNodeLabel.specs.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneNodeLabel.specs.tsx.snap
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/panels/__tests__/__snapshots__/SceneNodeInspectorPanel.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/EntityGroup/index.tsx
Setting up `data-testid` handling to remove brittle logic from e2e test in scene composer. 
```
httpserver
```
> feat(scene composer): adding data-testid to improve e2e test

- packages/doc-site/package.json
This change is intended to resolve an npm package resolution issue preventing release of iot-app-kit. See https://github.com/awslabs/iot-app-kit/actions/runs/7888775192/job/21527045689?pr=2546#step:4:8 for workflow failure.
> fix: testing-util as devDependency of doc-site

- packages/react-components/src/components/chart/hooks/useDataStreamMaxMin.ts
- packages/react-components/src/components/chart/store/dataStreamMinMaxStore.ts
- packages/react-components/src/components/chart/store/store.ts
- packages/react-components/src/echarts/configure.ts
- packages/react-components/src/echarts/extensions/index.ts
- packages/react-components/src/echarts/extensions/minMaxDataStreamValues/index.ts
- packages/react-components/src/echarts/extensions/minMaxDataStreamValues/minMaxDataStreamSync.ts
- packages/react-components/src/echarts/extensions/minMaxDataStreamValues/updateDataStreamMinMax.ts
Manage data for min/max on chart by using the echarts extension to go through points in each series find the min/max, and store it in the chartStore by id. 
> feat(react-components): calculate min/max and store value in store for chart to consume

- .release-please-manifest.json
- packages/doc-site/package.json
- release-please-config.json
add doc-site to release-please config so that it's dependencies can be updated together with other packges
```
httpserver
```
> fix: add doc-site to release-please config

- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/client.ts
- packages/source-iotsitewise/src/time-series-data/client/edge/client.spec.ts
- packages/source-iotsitewise/src/time-series-data/client/edge/client.ts
- packages/source-iotsitewise/src/time-series-data/client/edge/getAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/edge/getHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/edge/getLatestPropertyDataPoint.ts
- packages/source-iotsitewise/src/time-series-data/data-source.ts
- packages/source-iotsitewise/src/time-series-data/types.ts
- packages/source-iotsitewise/src/time-series-data/util/flattenRequestInfoByFetch.spec.ts
- packages/source-iotsitewise/src/time-series-data/util/flattenRequestInfoByFetch.ts
- packages/source-iotsitewise/src/time-series-data/util/timeConstants.ts
This PR introduce `edgeMode` in `source-iotsitewise` to serve as a stopgap missing APIs on edge. In summary, Edge Mode uses non-batching APIs for data retrievals
NOTE:
- data fetching logic `getAggregatedPropertyDataPoints.ts`, `getHistoricalPropertyDataPoints.ts`, and `getLatestPropertyDataPoint.ts` copied from previous commit https://github.com/awslabs/iot-app-kit/commit/b7a38e225199989524914b88f8da43ca77af2e54#diff-4f4c44bc9a94777afdbecc23e97e62005ceaa4e9737505657916981922ddbcfd
Added unit tests and manual validated in dashboard connected to edge (additional changes needed)
> feat: introduce edgeMode in source-iotsitewise

- packages/scene-composer/__mocks__/@cloudscape-design/components.tsx
- packages/scene-composer/src/components/modals/DeleteComponentModal.tsx
- packages/scene-composer/src/components/modals/DeleteComponentModalSnap.spec.tsx
- packages/scene-composer/src/components/modals/DeleteConfirmationModal.tsx
- packages/scene-composer/src/components/modals/DeleteConfirmationModalSnap.spec.tsx
- packages/scene-composer/src/components/modals/DeleteNodeModal.tsx
- packages/scene-composer/src/components/modals/DeleteNodeModalSnap.spec.tsx
- packages/scene-composer/src/components/modals/__snapshots__/DeleteComponentModalSnap.spec.tsx.snap
- packages/scene-composer/src/components/modals/__snapshots__/DeleteConfirmationModalSnap.spec.tsx.snap
- packages/scene-composer/src/components/modals/__snapshots__/DeleteNodeModalSnap.spec.tsx.snap
- packages/scene-composer/src/components/panels/ComponentEditMenu.spec.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/panels/scene-components/ColorOverlayComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/ColorOverlayComponentEditor.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/ObjectItemGroup.spec.tsx
- packages/scene-composer/src/components/toolbars/floatingToolbar/items/ObjectItemGroup.tsx
- packages/scene-composer/src/hooks/__snapshots__/useSceneModal.spec.tsx.snap
- packages/scene-composer/src/hooks/useSceneModal.spec.tsx
- packages/scene-composer/src/hooks/useSceneModal.tsx
- packages/scene-composer/src/store/StoreOperations.ts
- packages/scene-composer/src/store/slices/EditorStateSlice.spec.tsx
- packages/scene-composer/src/store/slices/EditorStateSlice.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
- show delete confirmation modal for dynamic scene when deleting a node or component
- show success bar when delete action succeeded
<Note: button style shown in screenshots below is different because they were captured early before reinstalling local workspace. they will look the same as the buttons in the first screenshot>
```
httpserver
```
Then open the website http://localhost:8080 …
> feat(composer): show delete confirmation modal for dynamic scene

- packages/dashboard/e2e/tests/constants.ts
- packages/dashboard/e2e/tests/dataStreamMinMax/dataStreamMaxes.spec.ts
- packages/dashboard/src/customization/propertiesSections/constants.ts
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.spec.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/plugin.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/factory.spec.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/factory.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/maximumValue/index.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/maximumValue/maximumCell.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/maximumValue/maximumHeader.tsx
- packages/react-components/src/components/chart/legend/table/legendTableAdapter.tsx
- packages/react-components/src/components/chart/legend/table/table.tsx
- packages/react-components/src/components/chart/types.ts
Adding ability to toggle max column from config panel. The max value is pulled from the data store and displayed in a dataStreamMax cell.
https://github.com/awslabs/iot-app-kit/assets/145582655/1fc6534b-5b20-4422-abbf-6334a8f99bd0
> feat(react-components): add max column to legend

- packages/dashboard/e2e/tests/constants.ts
- packages/dashboard/e2e/tests/dataStreamMinMax/dataStreamMins.spec.ts
- packages/dashboard/src/customization/propertiesSections/constants.ts
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/factory.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/minimumValue/index.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/minimumValue/minimumCell.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/minimumValue/minimumHeader.tsx
- packages/react-components/src/components/chart/types.ts
Adding ability to toggle min column from config panel. The max value is pulled from the data store and displayed in a dataStreamMin cell.
https://github.com/awslabs/iot-app-kit/assets/145582655/a70eb845-8c2d-4d20-8c13-f7b5f2bc69f6
> feat(react-components): add min column to legend

- packages/react-components/src/components/kpi/kpi.css
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/kpi/updatedKpiBase.tsx
- packages/react-components/stories/kpi/kpiBaseUpdated.tsx
Updated KPI style gated behind localStorage `USE_UPDATED_KPI`
current:
new:
feature gate working in dashboard:
https://github.com/awslabs/iot-app-kit/assets/28601414/d7b7bd96-b93b-4702-91c3-dbded0479d0a
> feat: updated KPI style (gated)

- packages/dashboard/src/customization/propertiesSections/constants.ts
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.spec.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/plugin.tsx
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chartOptions/useChartConfiguration.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/factory.spec.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/factory.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/latestValue/index.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/latestValue/latestValueCell.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/latestValue/latestValueHeader.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/trendCursor/trendCursorCell.tsx
- packages/react-components/src/components/chart/legend/table/legendTableAdapter.tsx
- packages/react-components/src/components/chart/legend/table/table.spec.tsx
- packages/react-components/src/components/chart/legend/table/table.tsx
- packages/react-components/src/components/chart/legend/table/types.ts
- packages/react-components/src/components/chart/types.ts
This PR is for ticket #2277  and implemented display latest value feature and it includes
1. default display property latest value is true
2. user can toggle the display latest value in the config legend section
[latestvalue-in-legend.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/98c17ee0-c639-41a4-a912-c2a6bb62afdd)
for a few properties latest value is showing in specific point:
[latestvalue-display.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/77a8f207-447f-4b3d-9618-f8510322da66)
> feat: conditionally display latest value in legend table

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.css
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/tests/baseChart.spec.tsx
This PR is for ticket #2470 and added viewport timestamps in XY-plot and it includes
1. shows timestamps in the bottom of the widget when the legend is positioned in left/right
2. shows timestamps in the bottom of the chart and above the legend section when the legend is positioned in the bottom
https://github.com/awslabs/iot-app-kit/assets/142866907/7c7d9dcf-9d88-4972-b0bf-0c5019248804
> feat: added viewport timestamps in xy plot

- packages/dashboard/e2e/tests/configPanel/ConfigPanel.ts
- packages/dashboard/e2e/tests/dataStreamMinMax/dataStreamMaxes.spec.ts
- packages/dashboard/e2e/tests/dataStreamMinMax/dataStreamMins.spec.ts
- packages/dashboard/src/customization/propertiesSections/components/legendDisplaySection.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/plugin.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/factory.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/maximumValue/maximumCell.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/minimumValue/minimumCell.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/trendCursor/trendCursorCell.tsx
- packages/react-components/src/components/chart/legend/table/legendTableAdapter.tsx
- packages/react-components/src/components/chart/legend/table/table.spec.tsx
- packages/react-components/src/components/chart/legend/table/types.ts
- Minimum and Maximum columns are not enabled on widget add
- Changed column ids for Min and Max column on legend table
- Added values as part of DataStreamInformation type
- Refactored Minimum and Maximum Cell to use DataInformation type to follow pattern of TrendCursor cell
- Added sorting operators for Min and Max cells
https://github.com/awslabs/iot-app-kit/assets/145582655/ba6662ce-9747-4f8e-978b-8f36b1638909
> fix: min max is sortable and not present on widget add

- packages/dashboard/src/components/internalDashboard/dashboardHeader.tsx
- packages/dashboard/src/styles/variables.css
- packages/react-components/src/components/time-sync/timeSelection.test.tsx
- packages/react-components/src/components/time-sync/timeSelection.tsx
This PR is to add a descriptive label 'Time range' for the viewport picker in dashboard header #2559
Before:
After:
> feat: added label time range for viewport picker in dashboard header

- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/palette/component.css
- packages/dashboard/src/components/palette/component.tsx
- packages/dashboard/src/components/palette/index.test.tsx
- packages/dashboard/src/components/palette/index.tsx
Updates to the component library for accessibility. 
1. Change markup to a button so that the element is focusable via the keyboard instead of directly setting the tabIndex.
2. Add click and keyboard handlers so that widgets can be added with a single action.
3. Add draggable attribute to indicate item functionality correctly
> feat(dashboard): make component library keyboard accessible

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelExplorer/assetModelSelection/types.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesExplorerEdge.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/iotSiteWiseQueryEditor.tsx
- packages/dashboard/src/hooks/useAssetModel/useAssetModel.ts
This PR enables dynamic assets on edge mode
Summary of the changes:
- Added an edge version of the AssetModelPropertiesExplorer to use the `useAssetModel` hook instead of `useAssetModelProperties` to mitigate the missing API ListAssetModelProperties.
- `useAssetModel` hook to call `DescribeAssetModel` for model properties on edge mode
Happy flow:
https://github.com/awslabs/iot-app-kit/assets/50635800/eae81f08-964c-4161-94d1-c0144ed31694
Error retry on model props explorer:
https://github.com/awslabs/iot-app-kit/assets/50635800/5cf1b79c-ad47-44ec-b0a9-fb7c8aedea8f
> feat: enable dynamic assets on edge mode

- packages/dashboard/e2e/tests/dashboard/DashboardPage.ts
- packages/dashboard/src/components/csvDownloadButton/index.tsx
- packages/dashboard/src/components/widgets/selectionBoxAnchor.tsx
- packages/dashboard/src/components/widgets/tile/tile.css
- packages/dashboard/src/components/widgets/tile/tile.spec.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/components/widgets/widget.css
- packages/dashboard/src/components/widgets/widget.tsx
- packages/dashboard/src/components/widgets/widgetActions.css
- packages/dashboard/src/components/widgets/widgetActions.test.tsx
- packages/dashboard/src/components/widgets/widgetActions.tsx
- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/components/no-chart-data.spec.tsx
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/testing/mocks.ts
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chartOptions/useChartConfiguration.ts
This PR is for the ticket #2439 
- Removed widget header from widgetTile component.
- Added functionality to display remove and download buttons on hover and widget selected state.
- Moved widget title for line-scatter to echart component and for bar and timeline to inside widget tile and truncated the title when widget was resized.
- Displayed only the download button on hover in live mode for line-scatter(xy-plot), bar-chart, and status-timeline widgets and hidden widget actions toolbox for the rest of all widgets.
https://github.com/awslabs/iot-app-kit/assets/139960352/b9a0b94f-b4cd-4584-84c4-1f9b3f5fe6cb
> feat: widget tool box on mouse hover and selection state

- packages/react-components/src/common/dataTypes.ts
- packages/react-components/src/components/kpi/constants.ts
- packages/react-components/src/components/kpi/kpi.css
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/kpi/types.ts
- packages/react-components/src/components/kpi/updatedKpiBase.tsx
- packages/react-components/src/components/status/constants.ts
- packages/react-components/src/components/status/status.tsx
- packages/react-components/src/components/status/types.ts
- packages/react-components/stories/kpi/kpi.stories.tsx
- packages/react-components/stories/kpi/mock-data.ts
- packages/react-components/stories/utils/query.ts
- some minor style fixes and 
- add new API values to KPI and Status settings includes: 
- showTimestamp
- showAssetName
- backgroundColor
values not yet configurable in dashboard
> fix: update public API for status and KPI

- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
This PR is for ticket #2565 and updated viewport settings for the dynamic input timestamp
https://github.com/awslabs/iot-app-kit/assets/142866907/c55e94c2-6846-442d-8c77-2c72d7675216
> fix: updated the viewport settings for dynamic input

- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.spec.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.tsx
This PR is for #2604 
Made changes to set "Style" tab as default when changing the widget selection. 
https://github.com/awslabs/iot-app-kit/assets/139960352/6ec04b64-3075-4afb-91b5-98857521c172
> fix: default Style tab upon widget selection

- packages/dashboard/src/customization/propertiesSections/aggregationSettings/helpers.tsx
- packages/dashboard/src/customization/propertiesSections/aggregationSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/constants.ts
- packages/dashboard/src/customization/propertiesSections/displaySettingsSection/index.tsx
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/styleTab.tsx
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/kpi/plugin.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/customization/widgets/status/plugin.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/kpi/updatedKpiBase.tsx
- packages/react-components/src/components/status/status.tsx
- packages/react-components/stories/kpi/kpi.stories.tsx
Config panel changes to add: 
- display options: hide/show unit, name, and timestamp
- show aggregation/resolution picker for gated status and KPI
- get thresholds working with gated KPI implementation
- hide color picker for property on new KPI/Status implementation
video confirming all property panel changes with gate enabled:
https://github.com/awslabs/iot-app-kit/assets/28601414/26e99a95-b475-4b89-9417-62cd9e84e3a6
video confirming that gate blocks all changes in dashboard:
https://github.com/awslabs/iot-app-kit/assets/28601414/f7af5d39-cdc6-4fb4-bb18-76221e7bd232
Other bonus changes:
- remove unused functions
- combine the 2 different aggregation/resolution pickers into One 
> feat: kpi and status gated config panel (gated) 

- packages/dashboard/src/components/widgets/widgetActions.tsx
updated the UX as per comments in https://github.com/awslabs/iot-app-kit/pull/2589 for the ticket [#2439](https://github.com/awslabs/iot-app-kit/issues/2439). and updated the vertical padding and the border radius to 2px and 8px.
old: 
new update:
> fix: updated the ux for widget actions

- packages/core/src/common/types.ts
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/defaultThresholds.ts
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/kpiThresholds.ts
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdStyle.spec.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdStyle.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsList.spec.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsList.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
- packages/dashboard/src/customization/settings.ts
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/common/widgetPropertiesFromInputs.ts
- packages/react-components/src/components/chart/chartOptions/convertThresholds.ts
- packages/react-components/src/components/chart/hooks/useVisualizedDataStreams.ts
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/kpi/kpi.css
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/kpi/types.ts
- packages/react-components/src/components/kpi/updatedKpiBase.tsx
- packages/react-components/src/utils/breachedThreshold.ts
- packages/react-components/src/utils/thresholdUtils.spec.ts
Add threshold style settings to KPI and Status (gated only!) 
this is what the different settings look like
with/without timestamp + with line or filled widget
video of threshold being added to new KPI widget 
https://github.com/awslabs/iot-app-kit/assets/28601414/c2a06a01-2563-45b2-ad2b-503831bc37c9
Also cleaned up some types 
> feat: add threshold settings to KPI

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
Remove duplicate aggregation/resolution picker now that its one component
> fix: remove double aggregation picker

- packages/dashboard/e2e/tests/widgets/text.spec.ts
- packages/dashboard/src/customization/propertiesSections/textSettings/link.tsx
We have made create link toggle button keyboard accessible as per @jmbuss comment on ticket #2363
"focusing the "Create link" toggle and pressing enter does not actually toggle the text as a link. This will need to be fixed for the entire section to be considered accessible."
Also, screen reader now announces the expandable section as 'Text widget link settings' and the toggle as "Create link".
**Using mouse control:**
[create link toggle using mouse.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/685592db-c660-4f31-8e76-67b8727ed77e)
**Using keyboard (tab focus and enter key):**
[create link toggle using keyboard.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/c224d67f-a934-42e1-8fa0-f522e675af31)
**Screen reader:**
Unable to upload a video with audio on …
> feat: added keyboard accessibility for create link toggle button

- packages/scene-composer/src/common/sceneModelConstants.ts
- packages/scene-composer/src/utils/emptyScene.ts
- packages/scene-composer/src/utils/entityModelUtils/SceneLifecycleModule.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/SceneLifecycleModule.ts
- packages/source-iottwinmaker/src/__mocks__/iottwinmakerSDK.ts
- packages/source-iottwinmaker/src/scene-module/SceneMetadataModule.spec.ts
- packages/source-iottwinmaker/src/scene-module/SceneMetadataModule.ts
- packages/source-iottwinmaker/src/types.ts
Implement createDynamicScene util and SceneLifecycleModule
npm run test passes.
```
httpserver
```
> feat(composer): createDynamicScene util

- packages/scene-composer/src/components/StateManager.tsx
Customers report OnSelectionChange not firing in certain instances.  It's possible that if OnSelectionChange changes over the life time of the application that the useEffect firing it isn't being updated properly because it's not in the dependency list
use storybook and click on hierarchy objects and ensure that Action still logs selection changes.
```
httpserver
```
Then open the …
> fix(scene): update dependency for selection change use effect

- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/status/status.tsx
remove fetchMostRecentBeforeStart setting from status and kpi components
which was making extra API calls
before "last 5 min" made two API calls:
after "last 5 minutes" makes one API call:
> fix: remove fetchMostRecentBeforeStart from status and kpi

- packages/dashboard/src/components/widgets/tile/tile.css
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/components/widgets/widgetActions.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
A recent change to the widget tile moved the title of the xy-plot widget from the tile component into the chart. The tile title acted as a drag area for the widget, meaning the widget drag UX degraded. As a temporary fix, this change adds the title back to the tile.
> fix(dashboard): revert the title change for line chart

- package.json
Removing dead script. `turbo dev` was originally created in PR #562 & was later removed in PR #680. This PR removes the script referencing it. 
Resolves Issue #1749
```
httpserver
```
> chore(app kit): removing dead turbo command

- packages/dashboard/src/components/assetModelSelection/assetModelSelection.css
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/resizablePanes/index.tsx
In order to make the dashboard accessible, the content needs to reflow correctly at small or zoomed in screen sizes. It should be accessible at a minimum viewport width of 320px without requiring horizontal scrolling.
These fixes are so that the toolbar and resource / config panels do not cause overflow when the viewport is small.
> fix(dashboard): style fixes to make the dashboard accessible at small screensizes

- packages/dashboard/src/components/widgets/widgetActions.css
- packages/react-components/src/components/chart/chartOptions/useChartConfiguration.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
Updated the UX as per comments in #2589  for ticket #2439 . Provided top 6 for the echart toolbox and padding 4 to echart title to avoid overlapping with the widget toolbox. 
https://github.com/awslabs/iot-app-kit/assets/139960352/38def2f0-462e-4e27-9d50-a2ab9039d935
> fix: chart gesture icons overlap on mouse hover

- packages/dashboard/e2e/tests/widgets/table.spec.ts
Because of rounding, sometimes the last digit rounds to 0 and is not displayed. Hence we want to check a range of [sig digits - 1, sig digits] in our tests.
This is to fix a flaky test for table widgets.
> fix: add range for table significant digits test

- packages/react-components/src/echarts/extensions/minMaxDataStreamValues/updateDataStreamMinMax.ts
Lowered throttle of min/max sync to 1 second to match TC throttle
https://github.com/awslabs/iot-app-kit/assets/145582655/255f1142-bb67-4d12-a546-ae3e2292bffd
> fix(react-components): lowered min/max throttle to match TC throttle

- .github/workflows/doc-site-deploy.yml
Release is blocked due to [failing builds](https://github.com/awslabs/iot-app-kit/actions/workflows/doc-site-deploy.yml) on Node version. Adding flag to correct the issue. 
> chore(doc site): adding node version to doc site workflow

- .github/dependabot.yml
This change sets Dependabot to target `rc` instead of `main` to reduce the risk of merge conflicts during release process.
> chore: set dependabot to target rc

- packages/dashboard/src/customization/propertiesSections/textSettings/text.tsx
With this PR, the style group for text config is made accessible for the screen reader as per issue #2360 
Before:
https://github.com/awslabs/iot-app-kit/assets/154328164/b4794167-fe2a-4b38-8cbe-2ff4036b4b36
After:
https://github.com/awslabs/iot-app-kit/assets/154328164/a7ed02c2-aeba-49c6-b80f-1b4709ec6a50
The style buttons are now first announced as group "Style" then user can tab over individual controls
Please download the videos and play on your machine to watch video with audio.
> fix: grouped the style buttons and associated with style label

- packages/scene-composer/e2e/tests/local-scene/scene-composer--local-scene.spec.ts
- packages/scene-composer/e2e/tests/utils/sceneHelpers.ts
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
Adding an empty scene node causes an error
Viewing a scene with an empty node already existing causes the scene hierarchy panel to be blank
Use storybook composer local to test adding an Empty node 
use storybook viewer AWS to try and view a Cookie Factory demo scene. Open the Scene Hierarchy panel, all nodes should be present and visible.
```
httpserver
``` …
> fix(scene): fix Scene Hierarchy Tree item for node with no components

- packages/react-components/src/components/chart/legend/table/legendTableAdapter.tsx
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2660 and updated the condition to check the unit in the legend datastream name. shows empty If the property has a unit undefined
**Before:**
**After:**
> fix: unit shows empty if it's undefined in the legend table datastreams

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2659 and added the reset selection list logic after the user clicks the Add button in the unmodeled section.
https://github.com/awslabs/iot-app-kit/assets/142866907/d0e5fecd-7412-47b8-83ed-b414d19cd029
> fix: clear the selection list after clicking add in unmodeled section

- packages/react-components/src/components/chart/legend/table/columnDefinitions/latestValue/latestValueCell.tsx
- Only missing loading indication was LatestValue column in line chart legend. Added dash to match loading states of other columns when value is undefined.
https://github.com/awslabs/iot-app-kit/assets/145582655/a5f27e94-54de-42bd-be51-08e39a6add77
> fix: add missing loading indication for widget values

- packages/react-components/src/hooks/useTheming/applyTokens.ts
Added support for border theming options in useTheme hook as per #2668 
Note: this PR only supports some of the properties from the #2668 , we will be raising more PRs for other properties and dark mode fixes.
- [] Support `borderRadiusButton`.
- [] Support `borderRadiusContainer`.
- [] Support `borderRadiusDropdown`.
- [] Support `borderRadiusInput`.
- [] Support `colorBorderButtonNormalActive`.
- [] Support `colorBorderButtonNormalDefault`.
- [] Support `colorBorderButtonNormalDisabled`.
- [] Support `colorBorderButtonNormalHover`.
- [] Support `colorBorderButtonPrimaryDisabled`.
**Tested by importing useTheme in below component:**
```/home/kausarshaikh/Amazon/iot-app-kit/packages/dashboard/src/components/widgets/widget.tsx```
```
import { useTheme } from …
```
> feat: added support for border theming options #2668

- packages/dashboard/src/components/internalDashboard/collapsiblePanel.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/footer.tsx
- packages/dashboard/src/components/widgets/selectionBoxAnchor.css
- packages/dashboard/src/components/widgets/selectionBoxAnchor.tsx
- packages/dashboard/src/customization/widgets/components/no-chart-data.tsx
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2668  and updated background color tokens to support theming.
This includes background color tokens for the empty widgets, resource explorer footer, widget header.
**Note:** The follow-up PRs will fix the remaining issues (as mentioned in the ticket, updating the changes incrementally, instead of doing all of the changes in the single PR).
https://github.com/awslabs/iot-app-kit/assets/142866907/42c3b7d6-cd41-41d7-9ac1-76d7d7005c75
> feat: updated background color tokens to support theming

- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.tsx
- packages/scene-composer/src/hooks/useTwinMakerTextureLoader.tsx
1. Opacity doesn't change when a texture is selected for the ground plane which can make it seem like it did not load.  Now if it's zero the opacity will change 1 when a new texture is set. If the opacity is greater than zero it will not change.
2. Bad texture files could fail to load but get set as a material leading to error messages when the bad texture is removed from the ground plane.
1. run story book scene composer
2. select the default composer scene
3. set the scene setting -> ground plane opacity to 0
4. select a texture for the ground plane.  verify the texture appears and the ground plane opacity is now 100%
5. edit the scene composer storybook to use an empty text file, or a non-texture fiile.
6. run storybook select texture for the scene composer ground plane in.  The file …
> fix(scene): handle bad texture files gracefully and toggle opacity on selection

- packages/react-components/src/components/l4eWidget/constants.ts
- packages/react-components/src/components/l4eWidget/contributingPropertiesTable/columnDefinitions.tsx
- packages/react-components/src/components/l4eWidget/contributingPropertiesTable/contributingPropertiesTable.tsx
- packages/react-components/src/components/l4eWidget/hooks/useSetDataSet.tsx
- packages/react-components/src/components/l4eWidget/hooks/useSetTitle.tsx
- packages/react-components/src/components/l4eWidget/hooks/useSetXAxis.tsx
- packages/react-components/src/components/l4eWidget/index.tsx
- packages/react-components/src/components/l4eWidget/types.ts
- packages/react-components/src/components/l4eWidget/utils/formatTooltip.ts
- packages/react-components/stories/l4e/l4e.stories.tsx
- packages/react-components/stories/l4e/mockData.ts
clean up l4e code:
- update types to be a flat widget API 
- handle custom viewports if passed in
- move setOption useEffects into their own hooks
example custom 7 day viewport
> fix: l4e code clean up

- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.tsx
Ground plane opacity show decimal values at certain intervals of +/- 1 percent due to floating point percision as it's stored as 1 to 0 in the system.  The input widget will do a rounding to whole percentage points to make the widgets performance consistent.
run storybook and open a scene in composer
go to the settings tab and open the scene settings
click up and down with the spinner to move the opacity from 0 to 100.  It should not show decimal values only whole percent. 
Same for manually typing in values. …
> fix(scene): round ground plane opacity to whole percent

- packages/scene-composer/public/invalidInputTest.scene.json
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorSelectorCombo/ColorSelectorCombo.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/FogSettingsEditor.tsx
- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.tsx
- packages/scene-composer/src/interfaces/interfaces.tsx
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/utils/colorUtils.spec.ts
- packages/scene-composer/src/utils/colorUtils.ts
Scene json load invalid values for
color hexcodes
opacity ranges
fog near and far distances.
If an invalid value is detected on load then the value will be replaced with the default value.
Run storybook and load the invalidInputTest.scene.json file to verify that invalid values are converted to defaults
```
httpserver
``` …
> fix(scene): validation scene json on deserialize

- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/layouts/SceneLayout/__snapshots__/SceneLayout.spec.tsx.snap
- packages/scene-composer/src/store/Store.ts
- packages/scene-composer/src/store/middlewares.ts
- packages/scene-composer/src/store/slices/DataStoreSlice.ts
- packages/scene-composer/src/store/slices/EditorStateSlice.ts
- packages/scene-composer/src/store/slices/NodeErrorStateSlice.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/store/slices/ViewOptionStateSlice.spec.ts
- packages/scene-composer/src/store/slices/ViewOptionStateSlice.ts
- packages/scene-composer/tests/utils/objectUtils.spec.ts
Zustand made breaking changes when moving from version 3 to version 4. This commit upgrades the zustand dependency to the latest version 4.5.2, updates the codebase to accommodate the changes introduced in version 4, and removes obsolete test validation steps related to the previous version.
```
httpserver
``` …
> chore: upgrade dependent package zustand to 4.5.2

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.tsx
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/gauge/constants.ts
- packages/react-components/src/components/gauge/gauge.tsx
- packages/react-components/stories/allChartsWithDefaultSettings/defaultCharts.stories.tsx
> fix: add default settings to charts

- packages/scene-composer/package.json
- packages/scene-composer/src/store/helpers/__tests__/serializationHelpers.spec.ts
Adding unit test coverage to scene property deserialization validation
new unit test passes
```
httpserver
```
> chore(scene): add test for json deserialization of scene properties

- .github/workflows/npm-publish.yml
This PR added a GitHub workflow job to trigger the brazil-npm-sync after the Npm publish of IoT AppKit packages.
Successful invocation example: https://github.com/awslabs/iot-app-kit/actions/runs/8746101246/job/24002318908?pr=2745
> chore: github workflow update for brazil-npm-sync

- packages/dashboard/src/components/palette/icons/index.css
- packages/dashboard/src/components/palette/icons/index.tsx
As part of theming issue #2668 , fixed the UI of widget panel tooltip to support dark mode and theming options
**BEFORE** (RC)
Light mode 
Dark mode
---
Light mode
Dark mode
> fix: migrated widget tooltip css to styled-components for theming #2668

- packages/doc-site/.storybook/preview.js
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2718 and added the CSS import in the preview file for the storybook to load the CSS style sheet in the doc site.
font-family is applied from the CSS style sheet for the widget after this fix.
> fix: fix for css style issue in doc-site

- packages/scene-composer/src/common/constants.ts
- packages/scene-composer/src/components/SceneComposerInternal.spec.tsx
- packages/scene-composer/src/components/SceneComposerInternalSnap.spec.tsx
- packages/scene-composer/src/components/StateManager.spec.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/__snapshots__/StateManager.spec.tsx.snap
- packages/scene-composer/src/components/modals/ConvertSceneModal.spec.tsx
- packages/scene-composer/src/components/modals/ConvertSceneModal.tsx
- packages/scene-composer/src/components/panels/scene-settings/MatterportIntegration.tsx
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- packages/scene-composer/src/utils/matterportIntegrationUtils.spec.ts
- packages/scene-composer/src/utils/matterportIntegrationUtils.ts
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
- packages/source-iottwinmaker/src/scene-module/SceneMetadataModule.ts
- packages/source-iottwinmaker/src/types.ts
- update convert scene to attached scene component 
- load scene level data from scene component for dynamic scene
- with DynamicSceneAlpha flag off, convert scene correctly creates scene root entity without component
- static scene can be rendered
- matterport scene can be rendered
- dynamic scene can be rendered
```
httpserver
```
Then open the website http://localhost:8080 to run the …
> feat(composer): update convert to attached scene component and load data from it

- packages/tools-iottwinmaker/README.md
- packages/tools-iottwinmaker/functional-tests/basic-functional/basic-functional.test.ts
- packages/tools-iottwinmaker/src/commands/deploy.spec.ts
- packages/tools-iottwinmaker/src/commands/deploy.ts
- packages/tools-iottwinmaker/src/commands/destroy.ts
- packages/tools-iottwinmaker/src/commands/init.ts
- packages/tools-iottwinmaker/src/lib/aws-clients.ts
- packages/tools-iottwinmaker/src/lib/workspace.ts
Adding support for specifying a different endpoint URL for interacting with IoT TwinMaker. This is an optional parameter for the init, deploy, and destroy commands.
When deploying a TMDT workspace from scratch, if the endpoint url points to TwinMaker gamma then the IAM role must have a trust policy with the gamma service principal.
Was running into a bug where my workspace name caused S3 to throw an error when creating a bucket with too long a name. Added a method `generateS3BucketName` to ensure the S3 bucket name character limit is met.
Tested each command with a gamma workspace successfully.
- Click …
> feat(tmdt): support endpoint-url parameter and respect S3 bucket name character limit

- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/kpi/kpiBase.tsx
- packages/react-components/src/components/kpi/types.ts
- packages/react-components/stories/kpi/kpi.stories.tsx
before the font was not accounting for custom background colors, threshold colors, and dark/light mode
leading to illegible widgets
> fix(react-components): KPI better handling of light/dark mode + thresholds

- packages/react-components/src/data/transformers/anomaly/object/transformer.ts
- packages/react-components/src/echarts/themes/registerCloudscapeThemes.ts
Add legend pagination dark/light mode colors
Sort streams in alphabetical order so they match an alphabetically ordered tooltip
> fix(react-components): sort and legend pagination colors

- packages/scene-composer/package.json
- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
- packages/scene-composer/src/common/entityModelConstants.ts
- packages/scene-composer/src/components/SceneLayers.spec.tsx
- packages/scene-composer/src/components/SceneLayers.tsx
- packages/scene-composer/src/components/StateManager.spec.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/__snapshots__/StateManager.spec.tsx.snap
- packages/scene-composer/src/components/modals/ConvertSceneModal.spec.tsx
- packages/scene-composer/src/components/modals/ConvertSceneModal.tsx
- packages/scene-composer/src/components/three-fiber/hooks/useProgress.tsx
- packages/scene-composer/src/store/Store.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/nodeComponent.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneComponent.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneComponent.ts
1. enable loading query results with child nodes.
2. remove dependent layer concept.
```
httpserver
```
> feat: ds ga

- packages/react-components/src/components/anomaly-widget/constants.ts
- packages/react-components/src/data/dataSourceLoader/dataSourceLoader.spec.ts
- packages/react-components/src/data/transformers/anomaly/object/input.ts
- packages/react-components/src/data/transformers/anomaly/object/transformer.spec.ts
- packages/react-components/src/queries/useGetAssetPropertyValueHistory/getAssetPropertyValueHistoryQueryKeyFactory.ts
- packages/react-components/src/queries/useGetAssetPropertyValueHistory/getGetAssetPropertyValueHistoryRequest.ts
- packages/react-components/src/queries/useGetAssetPropertyValueHistory/useGetAssetPropertyValueHistory.ts
- packages/react-components/src/queries/useSiteWiseAnomalyDataSource/parseAnomaly/parseAnomalyEvent.ts
- packages/react-components/src/queries/useSiteWiseAnomalyDataSource/parseAnomaly/types.ts
- packages/react-components/src/queries/useSiteWiseAnomalyDataSource/useAnomalyEventsViewport.ts
- packages/react-components/stories/anomaly/mockData.ts
Fix pagination for get property value history. The hook no longer fetches all programmatically using Tanstack, but instead fetches all in the command handler. Tanstack advises this as the best practice.
Update the datasource to use the timestamp from the TQV data point instead of the anomaly event timestamp which is a string. The string is not correctly formatted to represent a unix timestamp.
> fix(react-components): fix get value history request

- packages/dashboard/src/components/palette/icons/index.tsx
- packages/react-components/src/components/tooltip/tooltip.tsx
This PR is to fix an issue (#2785)  with a styled component inside another component.
Resolve this by creating new StyledComponents outside of the render method and function component.
before:
https://github.com/awslabs/iot-app-kit/assets/142866907/50be5d0e-4f33-4174-803e-f2f8e3e11329
after:
https://github.com/awslabs/iot-app-kit/assets/142866907/2f887b87-4c1e-4547-a6ed-bab73955d65a
> fix: tooltip styled component issue is fixed

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/assetExplorer/assetTable/assetTable.tsx
This PR fixes the issue mentioned in #2751
if navigating out of an asset using the breadcrumbs link at the top, the properties table will clear now.
[clear-properties-table-using-breadcrumbs.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/be4a8059-beea-42aa-ad88-eb79832f75be)
> fix: clearing the properties table when navigated using breadcrumbs

- packages/scene-composer/src/store/helpers/sceneDocumentHelpers.ts
Dynamic scene changes introduced a regression in updating scene nodes that change the nodes parent/child relationship such as when doing drag in drop. This impacts static & dynamic nodes equally.  
Observed behavior:  When you drag a node with a visual 3D element to a new parent the node is reparented in the scene hierarchy correctly but a second visual representing appears in the scene in the wrong location.
Use a storybook scene with a hierarchy like
root -
Model
Model 2
Tag
Model 3
Drag Model 2 to be parented to Model 3.
No new models or tags should appear in the scene.  The existing models and tags should not change location.
You should be able to update the tag transform and only the tag changs.
You should be able to update the Model 2 transform and have both the Model 2 and Tag …
> fix(scene): fix regression in updateSceneNode for reparenting nodes

- packages/react-components/src/queries/useSiteWiseAnomalyDataSource/parseAnomaly/parseAnomalyEvent.ts
- packages/react-components/src/utils/time.spec.ts
- packages/react-components/src/utils/time.ts
Support data point time object that is constructed from seconds and nanoseconds.
> fix(react-components): time support

- packages/dashboard/e2e/tests/configPanel/ConfigPanel.ts
- packages/dashboard/e2e/tests/constants.ts
- packages/dashboard/e2e/tests/widgets/kpi.spec.ts
- packages/dashboard/e2e/tests/widgets/line.spec.ts
- packages/dashboard/e2e/tests/widgets/table.spec.ts
- packages/dashboard/src/customization/propertiesSections/components/dataStreamLabelComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/table/useTableItems.ts
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/chart/chartOptions/useChartConfiguration.ts
- packages/react-components/src/components/chart/hooks/useVisualizedDataStreams.ts
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/chart/utils/getStyles.ts
- Add name property to style settings object for non-line widgets
- Add name property style chart options for line chart
- created label editing component for config panel
- users can now edit names of individual properties from config panel or revert to original name
https://github.com/awslabs/iot-app-kit/assets/145582655/e5653326-5aed-4d6b-840e-6998ffc0e7e6
> feat(widgets): add name style settings for line/table + edit label in config panel

- packages/doc-site/stories/components/chart/Docs.mdx
- Added missing name property to the style settings object docs
- Added two examples of how to use the style settings object, one a simple name and color property change and one that details line style changes
- should show up on the docsite itself
> chore: add examples of refId style object to docsite

- packages/react-components/src/components/anomaly-widget/anomalyWidgetError.tsx
- packages/react-components/src/components/anomaly-widget/converters/convertXAxis.ts
- packages/react-components/src/components/anomaly-widget/index.tsx
Fix component display bug when toggling error. This implementation prefers not to hide the chart so that we do not need to recreate a chart instance. Instead we overlay the error state onto the empty chart. **Note: leaving the chart element does not cause extra api calls to be made**
> fix(react-components): fix error state display

- packages/core/src/data-module/subscription-store/refreshRate.ts
Spelling correction in documentation as per #2777
> fix: corrected the spelling in refresh rate error documentation 

- packages/doc-site/stories/components/anomalyChart/Data.mdx
- packages/doc-site/stories/components/anomalyChart/Docs.mdx
- packages/doc-site/stories/components/anomalyChart/Query.mdx
- packages/doc-site/stories/data-sources/AWSIoTSiteWiseSource.mdx
Added public doc site for anomaly chart 
includes 3 pages:
1. main docs anomaly chart 
2. page for anomaly chart `data`
3. page for anomaly chart `queries`
> chore: public doc site for anomaly widget

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.tsx
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2809 and fixed the child key errors for the status timeline properties tab.
https://github.com/awslabs/iot-app-kit/assets/142866907/bbdc4400-3a5d-47cd-a7ac-c24f81cc6341
> fix: fixed the status timeline properties tab child key errors

- packages/scene-composer/src/utils/entityModelUtils/copySceneNodes.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/copySceneNodes.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
The Console has a bug when copying scenes where the new scene root entity ID uses the same sceneId as the original scene.
Verified by copying over the `dist/` folder to the Console code and copying over the scene with a more easily identifiable scene root entity using the copy sceneId.
```
httpserver
```
This project is …
> fix(DynamicScenes): copySceneNodes should take the new sceneId as an argument

- packages/react-components/src/components/anomaly-chart/tests/mockDataSources.ts
- packages/react-components/src/data/dataSourceLoader/dataSourceLoader.spec.ts
- packages/react-components/src/data/transformers/anomaly/object/input.ts
- packages/react-components/src/data/transformers/anomaly/object/transformer.spec.ts
- packages/react-components/src/data/transformers/anomaly/object/transformer.ts
- packages/react-components/stories/anomaly/mockData.ts
It is possible for there to be data points where no anomaly was detected, but where it has an anomaly score with diagnostics. We are specifically removing these points from the dataset as we do not have a UI to support displaying these types of points.
> fix: anomaly data filter

- packages/dashboard/src/data/listAssetPropertiesMap/query.tsx
This PR fixes the issue in #2808 
If some of the resources added in widget do not exist anymore, then the properties panel will load with currently existing resources only.
[properties-panel-with-undefined-properties.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/dff5ed24-394b-4c40-b4d4-453b41053d0c)
> fix: properties panel not loading if some resources do not exist

- packages/scene-composer/src/components/SceneLayers.spec.tsx
- packages/scene-composer/src/components/SceneLayers.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
When a dynamic scene has it's root entity deleted the scene no longer functions because it doesn't have a parent entity to attach other entities to.  The scene composer should detect this and provide an error message alerting the users instead of letting them attempt changes and then giving an error.
Create a Dynamic Scene
Manually Delete the Sceen Root Entity
Open the scene in Storybook and observe the error message
```
npm install -g …
```
> chore(scene): detect dynamic scenes missing their root entity

- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/use-asset-properties/use-asset-property-search.ts
- packages/react-components/src/components/resource-explorers/testing/table-variant/asset-property-table.spec.tsx
Adding `property_data_type` to SW executeQuery query to allow for check for unsupported types when adding to widget.
> chore: add dataType to RE

- packages/scene-composer/src/components/SceneLayers.spec.tsx
- packages/scene-composer/src/components/SceneLayers.tsx
Had a bug that did not render empty scenes at all - the grid/canvas did not appear.
Verified by copying over the Scene Composer component local build to my local Console build.
Saw that I could interact with new empty scenes, and can add widgets to the scene without issue.
```
httpserver
```
This project is available under …
> fix(DynamicScenes): fix bug to render empty scenes

- packages/dashboard/src/index.ts
- packages/dashboard/src/migration/constants.ts
- packages/dashboard/src/migration/convert-monitor-to-app-defintion.spec.ts
- packages/dashboard/src/migration/convert-monitor-to-app-defintion.ts
- packages/dashboard/src/migration/getters.ts
- packages/dashboard/src/migration/types.ts
- packages/dashboard/src/types.ts
Moving over the migration script used by centurion into app-kit so it can be used by multiple consumers.
All tests passing should verify this change.
> feat(dashboard): move dashboard migration utility to app-kit

- packages/scene-composer/src/components/SceneLayers.spec.tsx
- packages/scene-composer/src/components/SceneLayers.tsx
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Reverted the commit: https://github.com/awslabs/iot-app-kit/commit/c56522e05570157552f0df1184d219c14bcdc955
There was a bug where items added/removed from a dynamic scene would disappear. The entities would be updated correctly, but the scene state does not load correctly. 
Verified by copying over the Scene Composer component local build to my local Console build.
Saw that I could add and remove widgets to the scene without issue.
```
npm …
```
> fix(DynamicScenes): revert detect dynamic scenes missing their root entity

- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.ts
Dynamic Scenes don't load the entity binding on a node in the Scene Composer even though it's saved on the scene entity
In scene composer for a dynamic scene add an entity binding
verify that the entity binding got saved to the isVisualOf property of the scene nodes 3d. node component
refresh the scene composer
the entity binding should load when you inspect the scene node again 
``` …
```
> fix(scene): fix dynamic scene entity binding reload on query

- packages/react-components/src/components/chart/chartOptions/axes/yAxis.ts
- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSeriesAndYAxis.ts
> fix(react-components): do not use decimal places setting in y axis

- packages/dashboard/src/migration/convert-monitor-to-app-defintion.ts
- packages/dashboard/src/migration/getters.ts
- packages/dashboard/src/migration/types.ts
Update migration logic to use `metric.label` as the `property.name`
plus some minor bug fixes
> fix(dashboard): migration migrates custom name for properties

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/dashboard/view.test.tsx
- packages/dashboard/src/components/internalDashboard/dashboardHeader.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/types.ts
- packages/dashboard/stories/dashboard/mocked-dashboard-custom-toolbar.stories.tsx
Users can now pass in their own toolbar render function which will replace the default toolbar. This will allow users to provide their own on save button, date picker, and viewmode switcher
the custom toolbar will be rendered in the same area as the default toolbar
video: custom toolbar and viewmode change button & showing a different dashbaord w default toolbar 
https://github.com/awslabs/iot-app-kit/assets/28601414/e6f1d514-fe90-4d01-af85-b7ff39fb5273
> feat(dashboard): support custom toolbar

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/dashboard/wrapper.tsx
- packages/dashboard/src/components/internalDashboard/dashboardHeader.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/hooks/useStableDashboardConfiguration.ts
- packages/dashboard/src/hooks/useSyncDashboardConfiguration.ts
- packages/dashboard/src/index.ts
- packages/dashboard/src/types.ts
- packages/dashboard/src/util/convertToDashbaoardConfiguration.ts
- packages/dashboard/stories/dashboard/edge-dashboard.stories.tsx
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard-no-toolbar.stories.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
Add new dashboard option that provides a callback for on dashboard configuration change. This allows consumers to manage the configuration object state locally.
Dashboard configuration can be changed in edit mode by modifying the dashboard display settings, the refresh rate, the widgets, or the default viewport. Primarily this is changed by modifying the widget. (Move / Resize / Add / Remove / Add query / Modify properties). 
In order to guard against unnecessary re-renders, this change introduces a wrapper to the dashboard which will track the internal dashboard configuration and the passed in dashboard configuration, and only re-render the dashboard if they are not structurally equal. …
> feat(dashboard): add on configuration change

- packages/react-components/src/components/anomaly-chart/constants.ts
- packages/react-components/src/echarts/unboundedZoom/useUnboundedDataZoom.ts
Fix for 2 bugs related to anomaly chart datazoom
1. bar flickering on tick. To fix this we apply a sampling function when the data density is larger than the pixel size. This ensures that there are not z-index issues when rendering the points.
2. toolbox datazoom does nothing. To fix this, all zoom handling in the datazoom hook is throttled using request animation frame. This ensures the correct ordering of events and allows us to cancel zoom handling that no longer applies.
> fix: anomaly data zoom

- packages/dashboard/src/components/actions/settings.tsx
- packages/dashboard/src/components/dashboard/viewOnlyWrapper.tsx
- packages/dashboard/src/components/dashboard/wrapper.tsx
- packages/dashboard/src/components/defaultViewport/defaultViewport.tsx
Update the Dashboard Settings Modal to have a `cancel` and `apply changes` button so that updating the grid on the fly doesn't mess up the layout
https://github.com/awslabs/iot-app-kit/assets/28601414/e1603cd6-4844-44af-abad-77349f062c02
> fix(dashboard): add apply and cancel buttons to settings modal

- packages/dashboard/src/customization/propertiesSections/thresholdSettings/comparisonOperators.ts
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
* Currently, gauge widgets allow a threshold to be created using the `=` or `Contains` comparison operators. This was not intended since gauges conceptually don't support these.
* This change makes `=` and `Contains` operators disabled for gauge widgets. 
* It also makes the default operator `>` for gauge thresholds since the default for other charts (`=`) is disabled.
https://github.com/awslabs/iot-app-kit/assets/66272633/c3918ac4-8895-4347-817d-aba517d68baf
> fix: disable equals and contains operators in gauge thresholds

- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/three-fiber/hooks/useProgress.tsx
- packages/scene-composer/src/store/Store.ts
- packages/scene-composer/src/store/middlewares.ts
- packages/scene-composer/src/store/slices/DataStoreSlice.ts
- packages/scene-composer/src/store/slices/EditorStateSlice.ts
- packages/scene-composer/src/store/slices/NodeErrorStateSlice.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/store/slices/ViewOptionStateSlice.spec.ts
- packages/scene-composer/src/store/slices/ViewOptionStateSlice.ts
- packages/scene-composer/tests/utils/objectUtils.spec.ts
The latest scene viewer panel in Grafana fails to load the scene canvas:
After digging deeper into this error I found that the latest AppKit version we added to Grafana upgrade zustand from v3 to v4 which uses `useSyncExternalStore` internally. Found a [thread online](https://github.com/pmndrs/zustand/issues/1164) that explained how this version of zustand, along with state from multiple renderers like React and react-three/fiber (r3f) causes issues. 
Since this is breaking existing Grafana customers I downgraded zustand back to v3. This should not introduce any breaking or impactful changes to the consuming packages of the AppKit (TwinMaker Console, Grafana plugin, etc.). Reverting this commit: https://github.com/awslabs/iot-app-kit/pull/2724
1. Tested in storybook - loaded a dynamic …
> fix(scene-composer): reverting zustand upgrade due to Grafana issues related to zustand, react, r3f

- packages/dashboard/src/components/widgets/widgetActions.tsx
Changed button variant from inline-icon to icon and removed padding, so button hitbox spans entire container instead of just icon.
https://github.com/awslabs/iot-app-kit/assets/145582655/9a1d4699-7183-4e62-85ce-95f3909055ef
> fix(dashboard): expand hitbox for widget action buttons

- packages/scene-composer/src/components/SceneLayers.tsx
In some applications the query for the refetch interval can be undefined when the interval is evaluated.
Try to load a scene using the examples/react app.  It should not  have the scene composer block out with an error message of: 
Cannot read properties of undefined (reading ‘state’)
```
httpserver
```
This project is …
> fix(scene): fix possible undefined query state

- packages/dashboard/e2e/tests/dashboard/DashboardPage.ts
- packages/dashboard/e2e/tests/test.ts
- packages/dashboard/e2e/tests/widgets/gauge.spec.ts
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.tsx
* Adding E2E gauge tests to the dashboard tests
* Since Gauge isn't released yet, added a `gaugeReleased` flag to not run the gauge tests until we add gauge to the dashboard
* Once Gauge is released, run `npm run test:ui` from dashboard package and validate the tests are run and pass
> feat: add e2e gauge tests to dashboard tests

- packages/react-components/src/components/anomaly-chart/anomalyChartStyles.css
- packages/react-components/src/components/anomaly-chart/constants.ts
- packages/react-components/src/components/anomaly-chart/converters/convertLegend.ts
- packages/react-components/src/components/anomaly-chart/hooks/useAnomalyEchart.ts
- packages/react-components/src/components/anomaly-chart/loading-icon.tsx
Move loading state for anomaly widget 
> fix(react-components): anomaly chart move loading state

- packages/dashboard/src/migration/constants.ts
Updating the default dashboard cell size in migration script to 20 as per edge2web request.
> fix(dashboard): update default cellsize in migration to 20

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chartOptions/useChartConfiguration.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
The `gestures` prop actually enables/disables data zoom now!
> fix(react-components): gestures prop works

- packages/dashboard/src/customization/widgets/constants.ts
- packages/dashboard/src/customization/widgets/gauge/plugin.tsx
* Make the default size for gauge widgets smaller on the dashboard so there is less white space
> fix: make gauge widget default size smaller

- packages/react-components/src/components/gauge/gauge.css
* Change the gauge css so its rendered from the bottom 20% of the widget
* I looking at echarts gauge configuration to add a rich text label to make data quality party of the echarts settings, but I wasn't able to figure it out and from testing this css change it seems like it will be sufficient. I would like feedback on if this could go wrong though. The problem with this approach is we don't guarantee the data quality won't overlap with the value, but with our current default it does work.
> fix: move data quality widget on gauge to be closer to value

- packages/react-components/src/components/gauge/utils/getThresholdRangeFromMinMax.ts
Before: negative thresholds were not working properly when y-axis min was a negative value
Now: all y-axis properly render the thresholds
> fix(react-components): gauge thresholds with negative ranges

- packages/dashboard/src/customization/propertiesSections/components/dataStreamLabelComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/getPropertyDisplay.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/react-components/src/components/chart/hooks/useVisualizedDataStreams.ts
The default label matches the name of the data stream. It does not contain the assetName.
> fix: label matches kpi name

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
Add conditional assetName in case of unmodeled data for configPanel of line chart
hanges
> fix(dashboard): assetName displays conditionally in config panel for linechart

- packages/dashboard/src/migration/convert-monitor-to-app-defintion.ts
- packages/dashboard/src/migration/getters.ts
- packages/dashboard/src/migration/types.ts
Edge2Web uses the SiteWiseWidgetType instead of the MonitorWidgetType. Migration script now supports both.
For reference: https://code.amazon.com/packages/IotBlackPearlApp/blobs/mainline/--/src/views/Dashboards/originalDashboardDefinitionShim.ts
Before: 
Migrated: 
> fix(dashboard): migration for sitewise component + blackpearl widget types

- packages/dashboard/package.json
- packages/dashboard/src/customization/widgets/text/link/index.tsx
Validating urls for text widget.
https://github.com/user-attachments/assets/ebf631c8-05d2-4408-a692-4cab6d67ee3c
Test cases used: 
javascript:prompt(1)
&#106&#97&#118&#97&#115&#99&#114&#105&#112&#116&#58&#99&#111&#110&#102&#105&#114&#109&#40&#49&#41
\x6A\x61\x76\x61\x73\x63\x72\x69\x70\x74\x3aalert(1)
javascript://%0Aalert(1)
javascript://anything%0D%0A%0D%0Awindow.alert(1)
> fix(dashboard): sanitize href input in text widget

- packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelExplorer/assetModelSelection/assetModelSelect.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelExplorer/useAssetModels/useAssetModels.ts
- packages/dashboard/src/msw/iot-sitewise/resources/assetModels/AssetModelFactory.ts
- packages/dashboard/src/msw/iot-sitewise/resources/assetModels/index.ts
- packages/dashboard/src/msw/iot-sitewise/resources/assetModels/summarizeAssetModel.ts
* Since component asset models are not associated with any properties, they cannot be used in our query editor to add to dashboards, so this change filters component asset models from the selection in the dynamic assets tab.
* Use the query editor when your account has a component asset model created. Check the dynamic assets tab and make sure no component asset models are displayed there.
> fix: filter component models from query editor

- packages/scene-composer/src/utils/entityModelUtils/sceneUtils.ts
Current MATCH statement for queries can lead to queries timing out and backend has recommended this a better option for fast queries of the scene entity graph.
Created AWS scene with full 10 node deep tree and placed a unique entity binding on each node to test 'isVisualOf' part of query.
Use storybook to query and render scene
Node are Empty Nodes so no 3D elements are expected (not an error)
```
cd <Extracted Zip …
```
> feat(dynamic scene): reverse query structure for improved query speed

- packages/dashboard/src/components/dashboard/viewOnlyWrapper.tsx
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
* In a bug bash we discovered that the DashboardViewWrapper exposed to customers was missing the timeZone prop passing to support timezones. This change corrects this.
* Pass `timeZone` prop to `DashboardViewWrapper` and check timestamps displayed
* Example of tokyo timezone provided to DashboardView:
> fix: add timeZone prop to DashboardViewWrapper

- packages/scene-composer/public/cameraSortStaticScene.scene.json
- packages/scene-composer/src/components/panels/TopBar.tsx
- packages/scene-composer/stories/Developer/SceneViewer.stories.mdx
Scenes with lots of cameras can be hard to navigate the camera selector drop down as the order of camera is not obvious to the user.
To make it easier to reliably find cameras and maintain the camera list it will now list the camera in alphabetical name
Added cameraSortStaticScene scene to storybook datasets to allow local testing on a static scene to verify camera's are listed correcttly.
Screen shot of Dynamic Scene without change:
Screen shot of Dynamic Scene with change:
To run the storybook build locally, …
> feat(scene): alphabetize camera drop down

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledExplorer/modeledExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/timeSeriesExplorer/timeSeriesExplorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/internal-asset-property-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/types.ts
- packages/react-components/src/components/resource-explorers/explorers/time-series-explorer/internal-time-series-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/time-series-explorer/types.ts
- packages/react-components/src/components/resource-explorers/variants/resource-table/resource-table-filter.css
Add description prop to all resource explorer tables. Pass in corresponding description from query editor. 
> fix(dashboard): add descriptions to all RE tables

- packages/react-components/src/queries/useDescribeAssetModels/describeAssetModelQueryKeyFactory.ts
- packages/react-components/src/queries/useDescribeAssetModels/index.ts
- packages/react-components/src/queries/useDescribeAssetModels/useDescribeAssetModels.spec.ts
- packages/react-components/src/queries/useDescribeAssetModels/useDescribeAssetModels.ts
- packages/react-components/src/queries/useDescribeAssets/index.ts
- packages/react-components/src/queries/useDescribeAssets/useDescribeAssets.spec.tsx
- packages/react-components/src/queries/useDescribeAssets/useDescribeAssets.ts
To support SiteWise alarms and the useAlarms hook we need to fetch the asset and asset model summaries for alarm requests. These hooks use tanstack `useQueries` to batch queries to describe the given assets and asset models.
The query hooks take an `IoTSiteWiseClient | IoTSiteWise` client type and uses `useIoTSiteWiseClient()` to generate a promise-like client to use. This aligns with our request function effort [here](https://github.com/awslabs/iot-app-kit/pull/2963).
The hooks are an extension of the existing `useDescribeAsset` [hook](https://github.com/awslabs/iot-app-kit/blob/main/packages/react-components/src/queries/useDescribeAsset/useDescribeAsset.ts).
Unit tests and local build passes
For `scene-composer` package changes specifically, you can preview the component in the …
> feat(react-components): useDescribeAssets and useDescribeAssetModels queries implemented

- packages/react-components/src/queries/useHistoricalAssetPropertyValues/historicalAssetPropertyValueKeyFactory.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/batcher.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/getHistoricalAssetPropertyValueRequest.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/index.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/types.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/useHistoricalAssetPropertyValues.spec.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/useHistoricalAssetPropertyValues.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/useRefreshRate.ts
- packages/react-components/src/queries/useLatestAssetPropertyValues/latestAssetPropertyValueKeyFactory.ts
- packages/react-components/src/queries/useLatestAssetPropertyValues/types.ts
- packages/react-components/src/queries/useLatestAssetPropertyValues/useLatestAssetPropertyValues.spec.ts
- packages/react-components/src/queries/useLatestAssetPropertyValues/useLatestAssetPropertyValues.ts
- packages/react-components/src/queries/utils/useTimeSeriesDataQuerySync.ts
- packages/react-components/stories/queries/queriesBase.stories.tsx
Tanstack wrapper around `getAssetPropertyValueHistory`, `batchGetAssetPropertyValueHistory`. These can be used to fetch historical asset property values by assetId + propertyId or propertyAlias for a given viewport.
Note: Caching works based on an entire request in this implementation. Partial request caching is not supported. Late data configuration is also not supported. Instead, a refreshRate can be given, or one will be determined based on a percentage of the provided viewport, and will refresh the whole viewport range.
This hook will work if the client provided implements either / both getAssetPropertyValueHistory, batchGetAssetPropertyValueHistory. The hook will prefer to use the batch api if both are provided. …
> feat(react-components): use historical asset property values

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/iotSiteWiseQueryEditor.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledExplorer/modeledExplorer.tsx
- packages/react-components/src/components/resource-explorers/constants/table-resource-definitions.ts
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/internal-asset-property-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/types.ts
- packages/react-components/src/components/resource-explorers/testing/table-variant/asset-property-table.spec.tsx
We had added timezone support in the old RE [#2944](https://github.com/awslabs/iot-app-kit/pull/2944/files). Making the new RE component have feature parity with the old.
Local:
With Tokyo timezone:
> fix(dashboard): add timezone support for new RE

- packages/react-components/src/queries/useHistoricalAssetPropertyValues/useHistoricalAssetPropertyValues.spec.ts
- packages/react-components/src/queries/useLatestAssetPropertyValues/useLatestAssetPropertyValues.spec.ts
- packages/react-components/src/queries/utils/useTimeSeriesDataQuerySync.ts
Bug fix for queries status. The enabled flag was possibly undefined due to the value of the sync variable. enabled = undefined is defaulted to true in react-query, meaning that the query could be enabled and disabled for a frame. This would allow the query to move from an idle fetch state into a fetching fetch state, causing the query to read as a status of loading even if that is not possible given the invariants.
> fix(react-components): ensure enabled flag is never undefined for queries

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/iotSiteWiseQueryEditor.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledExplorer/modeledExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/timeSeriesExplorer/timeSeriesExplorer.tsx
- packages/react-components/src/components/resource-explorers/constants/table-resource-definitions.ts
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/internal-asset-property-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/types.ts
- packages/react-components/src/components/resource-explorers/explorers/time-series-explorer/internal-time-series-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/time-series-explorer/types.ts
- packages/react-components/src/components/resource-explorers/testing/table-variant/time-series-table.spec.tsx
Adding support for significant digits in the RE as well as adding in required changes for timezone support on unmodeled datastreams, a miss on previous PR.
https://github.com/user-attachments/assets/7a71485d-eb33-4af6-bd0d-98bfd3d0f5df
> fix(dashboard): re reflects significant digits + timezone support for unmodeled

- packages/react-components/src/components/resource-explorers/constants/defaults.ts
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/internal-asset-property-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/time-series-explorer/internal-time-series-explorer.tsx
Moved render functions defined in internal property explorers into default file, wrapped in a higher order function that takes in either timezone/significant digits to render latest value or latest value time.
https://github.com/user-attachments/assets/b52b89b8-19af-4609-89e3-424ebc6fd5b9
> fix(dashboard): fast follow to clean up messy code for table cell render

- packages/react-components/src/hooks/useAlarms/hookHelpers/index.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/predicates.spec.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/predicates.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmAssets.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useLatestAlarmPropertyValue.spec.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useLatestAlarmPropertyValue.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.spec.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.ts
- packages/react-components/src/hooks/useAlarms/utils/queryUtils.ts
- packages/react-components/src/queries/useDescribeAssetModels/useDescribeAssetModels.spec.ts
- packages/react-components/src/queries/useDescribeAssetModels/useDescribeAssetModels.ts
- packages/react-components/src/queries/useDescribeAssets/useDescribeAssets.spec.tsx
- packages/react-components/src/queries/useDescribeAssets/useDescribeAssets.ts
- packages/react-components/src/testing/alarms/mockAlarmData.ts
- packages/react-components/src/testing/alarms/mockSiteWiseClient.ts
Add `useLatestAlarmPropertyValue` hook as an abstraction over `useLatestAssetPropertyValues` to fetch the latest alarm property value for "state", "type", or "source" properties. Hook injects the property data into the running AlarmData list.
Decided to make `useLatestAlarmPropertyValue` generic with a field for the `alarmPropertyFieldName` (`'state' | 'type' | 'source'`). There is a predicate to check which AlarmData of the running list has that property field, and fetches the latest data for each. The hook is self-contained and will only cause a re-render if that property field changes.
`useAlarms` builds AlarmData by passing the output of one hook into the other.
* Minor: renamed the input for `useDescribeAssets` and `useDescribeAssetModels` to be `requests` to standardize across all …
> feat(react-components): add useLatestAlarmPropertyValue hook to fetch alarm prop vals in useAlarms

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/iotSiteWiseQueryEditor.tsx
Pass in timezone + significant digits props into the asset property table in Dynamic Assets tab to support that functionality.
https://github.com/user-attachments/assets/384a2230-c832-45b9-8d25-1409545bd90d
> fix(dashboard-RE-improvements): add timezone + sig digits to dynamic tab

- packages/react-components/src/hooks/useAlarms/hookHelpers/index.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/predicates.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmModels.spec.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmModels.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useLatestAlarmPropertyValue.spec.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.spec.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.ts
- packages/react-components/src/hooks/useAlarms/utils/alarmModelUtils.ts
- packages/react-components/src/queries/common/types.ts
- packages/react-components/src/queries/index.ts
- packages/react-components/src/queries/predicates/index.ts
- packages/react-components/src/queries/useDescribeAlarmModels/describeAlarmModelQueryKeyFactory.ts
- packages/react-components/src/queries/useDescribeAlarmModels/index.ts
- packages/react-components/src/queries/useDescribeAlarmModels/useDescribeAlarmModels.spec.ts
- packages/react-components/src/queries/useDescribeAlarmModels/useDescribeAlarmModels.ts
- packages/react-components/src/queries/useDescribeAssetModels/useDescribeAssetModels.ts
- packages/react-components/src/queries/useDescribeAssets/useDescribeAssets.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/types.ts
- packages/react-components/src/queries/useLatestAssetPropertyValues/types.ts
- packages/react-components/src/testing/alarms/index.ts
- packages/react-components/src/testing/alarms/mockAlarmData.ts
- packages/react-components/src/testing/alarms/mockAlarmModel.ts
- packages/react-components/src/testing/alarms/mockEventsClient.ts
- packages/react-components/src/testing/alarms/mockIds.ts
- packages/react-components/src/testing/alarms/mockProperties.ts
- packages/react-components/stories/queries/queriesBase.stories.tsx
Add useAlarmModels hook as an abstraction over useDescribeAlarmModels to fetch the latest IoT Events alarm model for an `IOT_EVENTS` alarm type. Hook injects the `DescribeAlarmModelResponse` into the running AlarmData list.
`useAlarms` calls this hook after the asset, assetModel, and latest alarm asset property values are fetched. The IoT Events alarm model ARN is found in the alarm source asset property. 
After the alarm models are fetched we need to handle the use case where the `AlarmRequest` has an `assetId` and `inputPropertyId` ("find all alarms associated with an inputProperty on an asset)
* `useAlarmAssets` will fetch alarms for requests assets and assetModels. If there is an `inputPropertyId` in the request the `AlarmData.inputProperty` field is filled in with the AssetProperty …
> feat(sitewise-alarms): add useAlarmModels hook to fetch iot events alarm models in useAlarms

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelDataStreamExplorer.tsx
When a page is refreshed, the asset selection dropdown would show the asset id instead of the name. To get the name, we are currently filtering based on ID after calling a describe asset model call. Initially, the call returns undefined. 
Added a useEffect call to update selected asset once API call provides data. 
https://github.com/user-attachments/assets/2572a051-8b63-44d2-aa4b-9dea8864ace9
> fix(dashboard-dynamic-asset): asset name should be shown on refresh in dropdown

- packages/react-components/src/components/anomaly-chart/index.tsx
- packages/react-components/src/components/chart/baseChart.tsx
* Fix for console error `Cannot update a component ('Timestamp') while rendering a different component ('BaseChart')
To locate the bad setState() call inside 'BaseChart', follow the stack trace`
* Wrap `setState` call for timezone in `useEffect`
* Load a dashboard with data, confirm in console you don't see the above error
> fix(timeZone): wrap timezone setState in useEffect

- packages/react-components/src/components/resource-explorers/requests/use-latest-values/create-request-entry-batches.ts
Fix bug which prevents loading all properties if a single property has an alias 
before:
https://github.com/user-attachments/assets/8cb98696-4266-46f3-a31a-31a04fc8ec43
after:
https://github.com/user-attachments/assets/fe5c2a6e-b04b-4146-adb0-63c9c0dc34ef
> fix(resource-explorer): only use alias to query if present

- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmAssets.spec.ts
- packages/react-components/src/hooks/useAlarms/utils/alarmDataUtils.ts
Bugfix for `useAlarmAssets`. If the `useDescribeAssets / useDescribeAssetModels` queries were loading for the first time, their response will be undefined. In that case, we were not returning any AlarmData objects. This means that we could not correctly access the `isLoading` flags. The hook will now return an empty AlarmData object with the query status if the `useDescribeAssets / useDescribeAssetModels` queries responses are undefined. 
> fix(alarms): return blank alarm data when queries are loading

- packages/tools-iottwinmaker/src/commands/deploy.spec.ts
- packages/tools-iottwinmaker/src/lib/workspace.ts
Change log bucket to use S3 Policy instead of ACL
> fix(bucket policy): switch from ACL to bucket policy for access logs

- packages/dashboard/src/components/dashboard/clientContext.ts
- packages/dashboard/src/components/dashboard/getClients.ts
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/view.test.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.spec.tsx
- packages/dashboard/src/types.ts
- packages/dashboard/stories/dashboard/edge-dashboard.stories.tsx
A public API change when upgrading the dashboard got released that breaks the dashboard experience. Removing the api change before release. To do so separated the type that was being used by both the dashboard and the client context, so only the client context has the promise based client. The client is now always generated internally from passed in credentials.
> fix(dashboard): remove promise client from public API and internally generate it

- packages/dashboard/src/components/dashboard/index.tsx
- packages/tools-iottwinmaker/src/commands/deploy.spec.ts
- packages/tools-iottwinmaker/src/lib/workspace.ts
When the wrapping application changes layout it triggers a rerender of the dashboard and the un-memoized function parameters get called resulting in the initial dashboard state being applied even though the dashboard props haven't changed. This results in the unsaved changes being discarded and the user losing progress.
All called functions used to set dashboard props are run through useMemo first to make them stable.
While running dashboard inside a wrapping app layout, change the page layout by closing a tab, side navigation panel, notification bar, etc. 
The dashboard should keep any edits made even if not saved.  It should not swap between preview and edit modes.
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do …
> fix(dashboard): memo dashboard props to app changes resulting in dashboard reverting state

- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState/types.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState/updateAlarmStateValues.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState/updateStatus.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState/useAlarmState.spec.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState/useAlarmState.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState/useQueryMode.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.spec.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.ts
- packages/react-components/src/hooks/useAlarms/utils/queryUtils.ts
- packages/react-components/src/testing/alarms/mockProperties.ts
- packages/react-components/src/testing/alarms/mockSiteWiseClient.ts
Refactor alarm state values into its own hook. The hook can handle multiple contexts:
1. fetching the latest alarm state without a viewport (Resource Explorer)
2. fetching the latest alarm state for a given viewport (KPI, Status, Dial, Gauge)
3. fetching alarm state for a historical viewport (Line Chart)
4. fetching alarm state for a live viewport (Line Chart)
> feat(alarms): use alarm state hook

- packages/react-components/src/components/resource-explorers/constants/defaults.ts
- packages/react-components/src/components/resource-explorers/constants/drop-down-resource-definitions.ts
- packages/react-components/src/components/resource-explorers/constants/table-resource-definitions.ts
- packages/react-components/src/components/resource-explorers/explorers/alarm-explorer/alarm-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/alarm-explorer/index.ts
- packages/react-components/src/components/resource-explorers/explorers/alarm-explorer/internal-alarm-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/alarm-explorer/transformAlarmData.ts
- packages/react-components/src/components/resource-explorers/explorers/alarm-explorer/types.ts
- packages/react-components/src/components/resource-explorers/explorers/index.ts
- packages/react-components/src/components/resource-explorers/index.ts
- packages/react-components/src/components/resource-explorers/testing/drop-down-variant/alarm-drop-down.spec.tsx
- packages/react-components/src/components/resource-explorers/testing/table-variant/alarm-table.spec.tsx
- packages/react-components/src/components/resource-explorers/types/resources.ts
- packages/react-components/src/hooks/requestFunctions/useIoTEventsClient.spec.ts
- packages/react-components/src/hooks/requestFunctions/useIoTEventsClient.ts
- packages/react-components/src/hooks/requestFunctions/useIoTSiteWiseClient.spec.ts
- packages/react-components/src/hooks/requestFunctions/useIoTSiteWiseClient.ts
- packages/react-components/src/hooks/useAlarms/constants.ts
- packages/react-components/src/hooks/useAlarms/transformers/index.ts
- packages/react-components/src/hooks/useAlarms/transformers/parseAlarmStateProperty.ts
- packages/react-components/src/queries/useAssetPropertyValues/utils/toDataPoint.ts
- packages/react-components/stories/resource-explorers/alarm-explorer.stories.tsx
- packages/react-components/stories/resource-explorers/explorer-combinations.stories.tsx
Adds an Alarm resource explorer which uses the useAlarms hook to display a table of alarms from either asset or asset model parameters.
Note: Some of the tests for the explorers are commented out. They will be revisited in a following PR once the asset property values hooks part useAlarms are completed and stable.
> feat(alarms): add alarm resource explorer

- packages/react-components/src/hooks/useAlarms/types.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.ts
Updated `AlarmData.status` `errors` to be a single `error`. We decided that it is not useful to provide multiple error objects for devs or other customers to parse. We still need to determine exactly what will be placed in this field, but for now we agree that a single error is more useful than an array of errors.
Also marked the `useAlarms` hook as experimental. We do not need to expose this in the public API yet either way.
```
npm …
```
> feat(sitewise-alarms): alarm data status now single error and marked useAlarms as experimental

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/footer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/footer/index.css
Having the left: 0 was causing issues in Juicebox RE footer due to there being a sidenav. This places it at the bottom of the screen instead.
> fix(dashboard): remove absolute positioning for RE footer

- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmThreshold.spec.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmThreshold.ts
- packages/react-components/src/hooks/useAlarms/utils/alarmThresholdValueFilterer.ts
- packages/react-components/src/hooks/useAlarms/utils/updateAlarmValues.ts
Static alarm thresholds were being filtered when a viewport was provided. This change updates the logic to always prioritze static alarm threshold values. Thresholds were being filtered to use anything within viewport.
Changes: 
1. prioritize static thresholds
2. always create `mostRecentBeforeEndValueQueries` as long as queryMode !== latest
3. filter all thresholdData that is after the viewport end
| Alarm(s) | Viewport | Outcome |
| -------- | ------- | ------- |
| custom alarm property with a static threshold | last 10 minutes | static threshold is used |
| custom alarm property with a static threshold | none | static threshold is used |
| demo alarm with ingested threshold | last 10 minutes | will fetch and use last threshold before end of viewport |
| demo alarm with ingested …
> fix(alarm thresholds): only filter threshold values past the viewport end date

- packages/dashboard/src/msw/iot-sitewise/handlers/listAssetModels/listAssetModels.ts
[Flaky test](https://github.com/awslabs/iot-app-kit/blob/f371eae2fa80e3ae4399dfd8f4194b971a55b4b7/packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts#L304) was passing before bc the API call to listAssetModels would not always be quick enough to render the composite model property. It should have failed everytime because MSW was returning all assetModels regardless of filter.
Added filter based on query parameters to MSW listAssetModels call to reflect filtering of models of COMPONENT_MODEL type in dynamic assets tab.
All tests pass, including flaky [one](https://github.com/awslabs/iot-app-kit/blob/f371eae2fa80e3ae4399dfd8f4194b971a55b4b7/packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts#L304) …
> fix(dashboard: testing): filter by asset model type in MSW to fix flaky test

- packages/react-components/src/components/bar-chart/barChart.tsx
- packages/react-components/src/queries/utils/convertAlarmQueryToAlarmRequest.ts
- packages/react-components/src/utils/transformAlarmsToThreshold.ts
- packages/source-iotsitewise/src/alarms/iotevents/index.ts
- packages/source-iotsitewise/src/index.ts
Add alarms to the bar chart by using the synchr-charts threshold props 
https://github.com/user-attachments/assets/1b5b97d4-3a16-4550-9f61-630cd78c0347
custom alarm only:
demo alarm only:
zoomed in so label isnt hidden: 
Tests:
| Test    | Outcome |
| -------- | ------- |
| Custom alarm  | Alarm renders properly |
| Demo alarm | Alarm renders properly     |
| Custom and Demo Alarm    | Both alarms render properly    |
> feat(bar chart alarms): add alarms to bar chart

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelDataStreamExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/createAssetModelQuery.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/getAssetModelQueryInformation.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/iotSiteWiseQueryEditor.tsx
- packages/dashboard/src/components/queryEditor/queryEditor.tsx
- packages/react-components/src/utils/transformAlarmsToThreshold.ts
Fix for screen jumping to top when selecting dashboard model properties. To fix, removed useState call and moved selectedAsset state up to parent QueryEditor component.
In doing so found the following bugs and fixed them as well.
- Asset Model RE keeps state of old selected asset properties after changing asset
- fix: added clearing selected properties to useEffect of when asset changes
- Asset Properties table does not change selection mode based on widget type
- fix: passed in missing 'correctSelectionMode' prop into table
- Asset Model Tab breaks if you add duplicate properties after edit/preview change
- deduped properties in hook where we reduce properties to ids for later use
https://github.com/user-attachments/assets/69206819-d696-496e-921a-ed3e73f28206
This project is available …
> fix(dashboard): state fixes for dynamic assets tab

- packages/react-components/src/components/gauge/gauge.tsx
- packages/react-components/src/components/kpi/kpi.tsx
properly memo thresholds for KPI and gauge
> fix(alarms): gauge and kpi alarm thresholds

- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/batchResponseProcessor.ts
Bugfix for historical requests which fully paginate without finding any single datapoint. When a query fully paginates it will be added to the skipped queries response. This adds a check for that to set the is completed flag if there are no further pages to look at.
> fix(alarms): complete skipped queries

- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/useInputPropertyTimeSeriesData.ts
Bugfix for useAlarms AlarmData mapping. The internal alarms data in useInputPropertyTimeSeriesData is only being modified when the property changes. This ensures we don't call time series data every time any irrelevant property changes in the alarms model, but it also means the internal model may not be up to date. To fix this, we only call useTimeSeriesData with the internal model, so that it is not overly reactive, but map the output with the up to date models.
> fix(alarms): fix data mapping from input property values

- packages/dashboard/src/components/dashboard/queryContext.ts
Bugfix for adding alarm by asset model. Ensure that we don't return an empty query when only asset model alarms are configured.
> fix(alarms): asset model alarms

- packages/scene-composer/src/components/StateManager.tsx
Adding `useEffect` to update store with decoder path override. 
```
httpserver
```
> fix(draco): updating global settings

- examples/react-app/vite.config.ts
Attempting to use the react example app as a stand alone app base can result in the HDR files form scene composer not loading and breaking at run time under vite.
To make using the example be a better starting point for new appliation development adding stand alone vite support for HDR files to the default vite.config.ts settings.
Runs when built inside iot-app-kit.  
If examples/react-app is copied to it's own folder and npm install and npm run start are run on it as a stand alone application the vite server should not through any errors about not having a loader for hdr files.
- Click on the workflow …
> fix(example): fix HDR loader in react example

- packages/dashboard/e2e/tests/assistant/assistant.spec.ts
- packages/dashboard/src/components/assistant/assistantFloatingMenu.tsx
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
- Add e2e tests to dashboard for assistant and chatbot
```
httpserver
```
> chore(dashboard): assistant dashboard e2e

- package.json
Fix: Remove lint and tests from publish-packages command, to fix npm publish action
```
httpserver
```
> fix: remove lint and tests from publish-packages command

- packages/react-components/src/components/chart/baseChart.tsx
When there was a title present, legend resizing vertically would automatically set the height of the legend to the maximum size and allow no user interaction. This was because we were setting the height to be the adjustedChartHeight value, that considers the title being present. However, in the hook where we get the chartHeight/Width the chart height is already factored in. This was making the chart default to something too large, hence always being stuck at the max-constraint.
Simple fix: just use the chartHeight given by our useResizableEChart hook.
https://github.com/user-attachments/assets/7f0f0f6d-bc4f-46f1-95f2-945a43702a52
> fix(react-components): allow vertical legend reszing when title present on widget

- packages/dashboard/src/components/assistant/chatbot.tsx
- packages/dashboard/src/components/dashboard/getClients.ts
- packages/dashboard/src/components/dashboard/getQueries.ts
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/dashboard/view.tsx
- packages/dashboard/src/hooks/useAssistantConfiguration.ts
- packages/dashboard/src/messages.ts
- packages/dashboard/src/types.ts
- Fix issue to call assistant API.
- Remove private iot sitewise client
- Adjust copy for assistant dashboard copy based on customer feedback. 
- Manual tests
```
httpserver
```
> fix: assistant failed to fetch

- packages/dashboard/src/components/assistant/chatbot.tsx
- packages/react-components/src/common/assistantProps.ts
- packages/react-components/src/components/assistant-common/types.ts
- packages/react-components/src/components/chart/hooks/useNormalizedDataStreams.ts
- packages/react-components/src/components/chart/legend/table/legendTableAdapter.tsx
- packages/react-components/src/components/chart/legend/table/types.ts
- packages/react-components/src/index.ts
Given feedbacks from external and internal customers a couple of prompt engineering improvements were done to increase the probably of positive response from the Sitewise assistant API. 
Changes:
- When 1 property is selected the prompt provided to the assistant will be `generate a property summary`
- When 1 alarm is selected the prompt provided will be  `generate an alarm summary`
- When +1 properties are selected the prompt provided will be `generate property summaries and compare`
- When 1 alarm and (1 to 2) properties are selected the prompt provided will be `generate summaries and compare`
- When +1 alarm are selected the prompt provided will be `generate summaries and compare`
- When customer types a question direct in the chatbot field, the dashboard will gather data from all …
> feat: improve assistant dashboard prompt engineering

- apps/doc-site/stories/overview/GettingStarted.mdx
- apps/doc-site/stories/overview/GettingStartedWithTW.mdx
- Refactor Get Started page, split steps into two pages one for Sitewise and another for Twinmaker.
- Add all dependencies
- Update code examples
- Add links to sitewise and twinmaker documentation.
https://github.com/user-attachments/assets/f0f7e59a-4042-4216-8f91-714791a275f3
```
httpserver
```
This project is available …
> chore: get-started page updates

- packages/scene-composer/package.json
- packages/tools-iottwinmaker/package.json
This change fixes a mistake in the scene-composer package type export definition. Without this change, types will not be declared correctly for consumers of the package.
> fix: scene-composer type export

- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
Adding optional check before accessing `$metadata` (`e?.$metadata.httpStatusCode`)
> fix: optional property check for error metadata

- .github/workflows/validate.yml
- apps/dev-env/package.json
- apps/doc-site/package.json
- configuration/vite-config/package.json
- configuration/vite-config/src/definePackageConfig.ts
- configuration/vite-config/src/scripts/postbuild.ts
- configuration/vite-config/src/scripts/postpack.ts
- configuration/vite-config/src/scripts/prepack.ts
- configuration/vite-config/src/validation/validateBuildArtifacts.ts
- examples/react-app/package.json
- package-lock.json
- packages/core-util/package.json
- packages/core/package.json
- packages/dashboard/package.json
- packages/data-mocked/package.json
- packages/helpers/package.json
- packages/react-components/package.json
- packages/scene-composer/package.json
- packages/source-iotsitewise/package.json
- packages/source-iottwinmaker/package.json
- packages/testing-util/package.json
- packages/tools-iottwinmaker/package.json
- turbo.json
This change improves the stability of the build by adding validation steps to the build and release processes. 
After a package is built, newly added validations run, inspecting the contents of the package's dist to ensure they are correct. Validations also occur before and after `npm pack` is run on a package, ensuring the package in the correct condition to pack, then extracting and validating the tarball contents.
Additionally, the GH actions now run `turbo pack`, which runs the packaging steps for each package, including their validation steps.
These new tests ensure the stability of our build and packaging steps preventing mistakes impacting these steps from being merged.
> chore: add build system tests

- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/components/widgets/widgetActions.css
- packages/dashboard/src/components/widgets/widgetActions.tsx
- packages/dashboard/src/styles/variables.css
- packages/react-components/src/components/status-timeline/alarmTransforms.ts
> fix: update hover states and alarm colors

- packages/dashboard/src/components/csvDownloadButton/emptyDownload.test.tsx
- packages/dashboard/src/components/csvDownloadButton/errorDownload.test.tsx
- packages/dashboard/src/components/csvDownloadButton/index.tsx
- packages/dashboard/src/components/csvDownloadButton/succesfulDownload.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/dashboard/view.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetsForAssetModelSelect/useAssetsForAssetModel/useAssetsForAssetModel.ts
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.spec.tsx
- packages/dashboard/src/customization/widgets/table/useTableItems.ts
- packages/dashboard/src/hooks/useAssetDescriptionQueries.ts
- packages/dashboard/src/hooks/useAssetModel/useAssetModel.ts
Remove usage of the query client provider from the Dashboard components in favor of using the client singleton directly.
> feat(dashboard): remove query client provider

- .github/workflows/validate.yml
- .gitignore
- iot-app-kit.sh
- package-lock.json
- packages/react-components/package.json
- prep-smoke-test-env.sh
- testing/smoke-test/README.md
- testing/smoke-test/index.html
- testing/smoke-test/package-lock.json
- testing/smoke-test/package.json
- testing/smoke-test/playwright.config.ts
- testing/smoke-test/src/App.tsx
- testing/smoke-test/src/main.tsx
- testing/smoke-test/src/vite-env.d.ts
- testing/smoke-test/tests/smoke-test.spec.ts
- testing/smoke-test/tsconfig.app.json
- testing/smoke-test/tsconfig.json
- testing/smoke-test/tsconfig.node.json
- testing/smoke-test/vite.config.ts
The purpose of this change is to ensure our package consumers may reliably install, re-install, utilize, and bundle our packages. The change accomplishes this by installing, testing, and bundling the dashboard package tarball outside of the context of `npm` workspaces.
Please see the [`README.md`](https://github.com/awslabs/iot-app-kit/pull/3116/files#diff-8a8f0089acd1721b25d7b585c6e939abd3ac1c8f4bf82b003334f1cf96d9cb8f) for complete details.
The scope of this change includes `dashboard` and all of its direct and transitive iot-app-kit dependencies, including `core`, `core-util`, `react-components`, `source-iotsitewise`, and `source-iottwinmaker`. `scene-viewer` and `tools-iottwinmaker` are not validated and are therefore still susceptible to failure. …
> chore: smoke test

- .github/workflows/validate.yml
- smoke-test.sh
This change fixes the playwright installation in the smoke test by moving its installation, which happens in check_for_playwright, to after npm install is run. Running npm install after installing playwright seems to be uninstalling playwright.
Also changed:
- Removed redundant playwright installation in the GH action outside of the script
- Turned on debug mode in the GH action, because, why not? More info is good? :D
> fix: smoke test playwright installation

- packages/react-components/src/echarts/extensions/trendCursors/echartsActions/extension.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetLatestPropertyDataPoints.ts
This PR contains possible fixes for two types of client side errors.
(1) We received type errors that could not be reproduced that look like this:
`error: Cannot read properties of null (reading 'getCoordinateSystems') stackTrace: TypeError: Cannot read properties of null (reading 'getCoordinateSystems')`
This means that the ExtensionAPI was null somewhere in the code. Adding these null checks (`!api`) are harmless and will hopefully prevent these errors from occurring again.
(2) We received another type error when trying to read `$metadata`:
`error: Cannot read properties of undefined (reading 'httpStatusCode') stackTrace: TypeError: Cannot read properties of undefined (reading 'httpStatusCode')`
Changes for this include explicitly typing errors as `IoTSiteWiseServiceExceptions` and …
> fix: client side errors from unexpected null/undefined values
