- CHANGELOG.md
- lerna.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/related-table/CHANGELOG.md
- packages/related-table/package.json
- packages/source-iotsitewise/CHANGELOG.md
- packages/source-iotsitewise/package.json
> Release 1.0.0

- packages/components/src/index.ts
> fix: resolves #83

- README.md
- docs/GettingStarted.md
- docs/ResourceExplorer.md
- docs/development.md
Improve documents, and actually link to table of contents instead of root of the docs folder.
> feat: improve documentation

- .github/workflows/run-tests.yml
> Run tests on pull request

- README.md
> Update readme for Related Table

- docs/BarChart.md
- docs/KPI.md
- docs/LineChart.md
- docs/ScatterChart.md
- docs/StatusGrid.md
- docs/StatusTimeline.md
- docs/Table.md
- docs/WhatIs.md
> feat: Improve documentation formatting

- docs/ResourceExplorer.md
Re-write the resource explorer docs to be consistent with the rest of the documentation
> feat: Improve resource explorer docs

- packages/components/package.json
- packages/core/package.json
- packages/source-iotsitewise/package.json
- yarn.lock
Update to the latest version of synchro-charts.
This resolves https://github.com/awslabs/iot-app-kit/issues/107 by fixing an edge case in synchro charts. More info on the actual fix contained in https://github.com/awslabs/synchro-charts/pull/144
> use most recent synchro-charts version, 4.0.1

- CHANGELOG.md
- lerna.json
- package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/related-table/CHANGELOG.md
- packages/related-table/package.json
- packages/source-iotsitewise/CHANGELOG.md
- packages/source-iotsitewise/package.json
Bump minor version
* support auto-assigning colors for certain components ([8df4f15](https://github.com/awslabs/iot-app-kit/commit/8df4f150be4d8d1d8c3b55fe46ec91e6d9a7bb9a))
* bump synchro-charts to 4.0.1 ([977f461](https://github.com/awslabs/iot-app-kit/commit/977f461504292409cbde7e82166fa32ef0c9a93c))
* add expanded property to iot-resource-explorer ([dda6ef8](https://github.com/awslabs/iot-app-kit/commit/dda6ef8957617cfcb1c99d4bea06036a896c6aae))
> Bump minor version

- packages/dashboard/src/components.d.ts
- packages/dashboard/src/components/iot-dashboard/__snapshots__/iot-dashboard.spec.tsx.snap
- packages/dashboard/src/components/iot-dashboard/getDashboardPosition.ts
- packages/dashboard/src/components/iot-dashboard/iot-dashboard-widget/iot-dashboard-widget.tsx
- packages/dashboard/src/components/iot-dashboard/iot-dashboard.spec.tsx
- packages/dashboard/src/components/iot-dashboard/iot-dashboard.tsx
- packages/dashboard/src/components/iot-dashboard/iot-selection-box/iot-selection-box-anchor.css
- packages/dashboard/src/components/iot-dashboard/iot-selection-box/iot-selection-box-anchor.tsx
- packages/dashboard/src/components/iot-dashboard/iot-selection-box/iot-selection-box.css
- packages/dashboard/src/components/iot-dashboard/iot-selection-box/iot-selection-box.tsx
- packages/dashboard/src/components/iot-dashboard/trimWidgetPosition.spec.ts
- packages/dashboard/src/components/iot-dashboard/trimWidgetPosition.ts
- packages/dashboard/src/dashboard-actions/resize.spec.ts
- packages/dashboard/src/dashboard-actions/resize.ts
- packages/dashboard/src/testing/testing-ground/mockDashboardConfiguration.ts
- packages/dashboard/src/testing/testing-ground/testing-ground.tsx
- packages/dashboard/src/types.ts
Create group resize feature, supporting resize via the 4 corners and 4 sides of the selection box.
> Implement resize functionality

- packages/dashboard/src/components/iot-dashboard/iot-dashboard.tsx
- Refactor `iot-dashboard.tsx` to have a more clear and consistent structure
- Implement the ability to hold shift to append to a selection
There's some quirks around the shift selection based union selection and requires some more work to be complete. Need to setup cypress to be able to have some integration tests to more fully test the dashboard.
> Add basic union selection feature

- packages/dashboard/package.json
- packages/dashboard/src/components/iot-dashboard/iot-dashboard.tsx
- packages/dashboard/src/dashboard-actions/paste.spec.ts
- packages/dashboard/src/dashboard-actions/paste.ts
- packages/dashboard/src/integration/iot-dashboard.spec.component.ts
Implement copy and paste functionality into the dashboard.
> Feature: dashboard copy and paste widgets

- packages/table/package.json
- packages/table/src/table/index.tsx
- packages/table/src/utils/tableHelpers.spec.ts
- packages/table/src/utils/tableHelpers.tsx
Fix issue when key in columnDefinition doesn't exist in TableItems
- fix an issue when property if missing from tableItem. 
like:
| Name | Legs |
| ---- | ----|
| Chicken | 2       |  
| Tiger | 4 |
| Car | \<empty> // doesn't have the property |
```
const item = { property: {value:10} }
const columnDefinitions = [{
key: 'notExist',
header: 'Non Exist'
}]
const [{cell}] = getDefaultColumnDefinitons(columnDefinitions)
cell(item) // => <span></span>
```
- add new test case for default cell function
- update default cell function
> Table v2 bug fix

- packages/components/src/components/iot-time-series-connector/iot-time-series-connector.spec.ts
- packages/core/src/common/audioAlertManager.spec.ts
- packages/core/src/common/audioAlertManager.ts
- packages/core/src/common/audioPlayer.spec.ts
- packages/core/src/common/constants.ts
Minor changes to make documentation more clear, change the tests to make them more clear, use shorthand, and make variable name more clear.
> fix: modify audio alert documentation and tests

- docs/Table.md
- packages/table/README.md
Update docs. Add README.md for new table component.
View in another page:
https://github.com/square-li/iot-app-kit/blob/feature-table/docs/Table.md
> Update docs. Add README.md for new table component.

- packages/table/src/utils/tableHelpers.tsx
Add missing brackets in JSX to display values.
> bugfix: add missing brackets.

- packages/components/src/testing/testing-ground/testing-ground.tsx
Add an example the usage of audio alerts in testing ground.
> feat: add audio alert to testing ground

- packages/components/src/components.d.ts
Rebuild packages after merge, update [components.d.ts](https://github.com/awslabs/iot-app-kit/pull/186/files#diff-cf3adf0ab49ef95d6065a7564b4f2eb8f91cea3a44930e8ffe898b95c2ec7ae4) file generated by stencilJS.
> update components.d.ts 

- packages/core/src/common/audioAlertManager.ts
- packages/core/src/common/audioAlertPlayer.spec.ts
- packages/core/src/common/audioAlertPlayer.ts
- packages/core/src/common/constants.ts
- packages/core/src/common/types.ts
Add an edge case about what if `soundID` is 0, remove the constructor in `AudioAlertPlayer`, fix documentation style, and change name from `AudioPlayerInterface` to `AudioPlayer`.
> fix: add edge case check and fix documentation

- packages/core/src/common/audioAlertManager.ts
Move the location of a comment to the correct line.
> fix: correct a comment line

- packages/dashboard/src/dashboard-actions/dashboardReducer.spec.ts
- packages/dashboard/src/dashboard-actions/redo.spec.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reverseMove.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reversePaste.spec.ts
- packages/dashboard/src/dashboard-actions/reverse-actions/reversePaste.ts
Simplify the way reverseMove and reversePaste are written.
> fix(dashboard): simplify reverse move and paste

- docs/UndoRedo.md
Provide documentation for undo/redo functionality
> feat: Undo/redo documentation

- docs/CodingGuidelines.md
Organizes guidelines into related sections. Reduces "wordiness" by minimizing duplication between rules. Updates formatting of document.
> Update Coding Guidelines Doc

- CHANGELOG.md
- docs/Table.md
- lerna.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/core/package.json
- packages/react-components/package.json
- packages/related-table/package.json
- packages/source-iotsitewise/package.json
- packages/table/package.json
- Update docs
- Major version bump since it contains breaking change.
> Update docs for Table and major version bump

- CHANGELOG.md
- docs/Table.md
- package-lock.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/related-table/CHANGELOG.md
- packages/related-table/package.json
- packages/source-iotsitewise/CHANGELOG.md
- packages/source-iotsitewise/package.json
- packages/table/CHANGELOG.md
- packages/table/package.json
- update changelogs & docs
- version bumps 
- bump all packages to `2.0.0`
- update all @iot-app-kit dependency version to `2.0.0`
> chore: update changelogs & docs / version bump

- packages/components/src/styles/awsui.css
Adding imports for
- table/body-cell
- table/header-cell
- autosuggest
> fix(components): import missing style sheets.

- packages/components/src/styles/awsui.css
resolve merge conflicts with feature branch https://github.com/awslabs/iot-app-kit/pull/248
> chore(alarms): merge with main

- packages/components/src/components/iot-table/iot-table.tsx
add alarm support to `iot-table`.
> feat(components): support alarms in iot-table

- docs/CodingGuidelines.md
Update link for viewport manager in coding guidelines.
> doc: update link in coding guidelines

- README.md
- docs/AWSIoTTwinMakerSource.md
- docs/Components.md
- docs/SceneViewer.md
- docs/VideoPlayer.md
update TwinMaker docs and link them to the main doc to address doc related  comments from https://github.com/awslabs/iot-app-kit/pull/252
> doc(TwinMaker): update TwinMaker docs and link them to the main doc

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/scene-components/CameraComponentEditor.tsx
Fixes the Camera Component Editor for Lens and Clipping planes updates when changing between cameras
> chore: Fixes the Camera Component Editor Inspector bug

- packages/scene-composer/src/augmentations/components/three-fiber/viewpoint/ViewCursorWidget.tsx
Fix to correct behavior with `esc` key while using Enhanced Editing feature. 
> Fix: Allows user to hit Esc key to cancel Enhanced Editing

- docs/GettingStarted.md
add TwinMaker components to GettingStarted doc
> doc: add TwinMaker components to GettingStarted doc

- packages/scene-composer/__mocks__/mockComponent.tsx
- packages/scene-composer/src/SceneViewer.spec.tsx
- packages/scene-composer/src/augmentations/three/Anchor.ts
- packages/scene-composer/src/common/errors.ts
- packages/scene-composer/src/components/DefaultErrorFallback/__tests__/DefaultErrorFallback.spec.tsx
- packages/scene-composer/src/components/DefaultErrorFallback/__tests__/__snapshots__/DefaultErrorFallback.spec.tsx.snap
- packages/scene-composer/src/components/SceneComposerInternal.spec.tsx
- packages/scene-composer/src/components/__snapshots__/SceneComposerInternal.spec.tsx.snap
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
address some comments from https://github.com/awslabs/iot-app-kit/pull/252
> chore: code cleanup

- packages/scene-composer/src/components/panels/TopBar.tsx
- packages/scene-composer/tests/components/panels/__snapshots__/TopBar.spec.tsx.snap
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Update the Cameras drop down to be named Camera View for clarity of purpose
> chore: Update the text from Cameras in the drop down to Camera View

- packages/scene-composer/package.json
- packages/scene-composer/src/GlobalStyles.ts
- packages/scene-composer/src/assets/auto-gen/icons/Camera.tsx
- packages/scene-composer/src/assets/icons/camera.svg
- packages/scene-composer/src/components/Tree/tree.scss
- packages/scene-composer/src/components/VisibilityToggle/index.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/__snapshots__/SceneHierarchyPanel.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/ComponentTypeIcon.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__snapshots__/ComponentTypeIcon.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneHierarchyTreeItem.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/SubModelTree.scss
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/SubModelTreeItemLabel.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTreeItemLabel.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/layout/__snapshots__/layout.spec.tsx.snap
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/layout/index.tsx
- packages/scene-composer/src/enhancers/draggable.scss
CSS cleanup for Scene Hierarchy. 
> Chore: CSS updates to Scene Hierarchy

- package.json
> chore: fix internal build

- .github/workflows/release-please.yml
- .release-please-manifest.json
- CHANGELOG.md
- package.json
- packages/components/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/react-components/CHANGELOG.md
- packages/related-table/CHANGELOG.md
- packages/scene-composer/CHANGELOG.md
- packages/source-iotsitewise/CHANGELOG.md
- packages/source-iottwinmaker/CHANGELOG.md
- packages/table/CHANGELOG.md
- release-please-config.json
setup release-please action to auto create/update the release PR which includes version bump and CHANGELOG update.
test code is available in https://github.com/awslabs/iot-app-kit/tree/test/release-please
example release PR generated from the branch https://github.com/awslabs/iot-app-kit/pull/299
> chore: setup release-please

- packages/scene-composer/translations/IotAppKitSceneComposer.de_DE.json
- packages/scene-composer/translations/IotAppKitSceneComposer.en_UK.json
- packages/scene-composer/translations/IotAppKitSceneComposer.es_ES.json
- packages/scene-composer/translations/IotAppKitSceneComposer.fr_FR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.id_ID.json
- packages/scene-composer/translations/IotAppKitSceneComposer.it_IT.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ja_JP.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ko_KR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.pt_BR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_CN.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_TW.json
> fix(composer): update translations

- release-please-config.json
Fix the configuration for release please to be aware of the `dashboard` module
> fix: Add dashboard to release-please-config

- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/resizablePanes/index.css
- packages/dashboard/src/components/resizablePanes/index.test.tsx
- packages/dashboard/src/components/resizablePanes/index.tsx
This is a rewrite of the resizable pane feature from #162 #187 from Stencil to React.
> feat(dashboard): resizable panes rewritten in react

- packages/scene-composer/src/components/toolbars/floatingToolbar/items/AddObjectMenu.tsx
- packages/scene-composer/src/utils/__snapshots__/nodeUtils.spec.ts.snap
- packages/scene-composer/src/utils/nodeUtils.ts
Camera's do not get the right positioning when placed on a SubModelRef. This fix uses the non-submodel space for a sub model while maintaining hierarchical placement
> fix(composer): Fix camera view positioning under sub model

- packages/scene-composer/package.json
- packages/scene-composer/src/components/Tree/tree.scss
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/SubModelTree.scss
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/SubModelTreeItemLabel.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/__tests__/__snapshots__/SubModelTreeItemLabel.spec.tsx.snap
Fixes for layout in Console, SubModel layout updates, bug fix for SubModel interactive highlights
> fix(composer): Fixes for SubModel layout in Console & interactive highlights. 

- packages/scene-composer/package.json
- packages/scene-composer/src/components/Tree/TreeItem.tsx
- packages/scene-composer/src/components/Tree/__tests__/TreeItem.spec.tsx
- packages/scene-composer/src/components/Tree/__tests__/__snapshots__/TreeItem.spec.tsx.snap
Restores ability to deselect radio buttons with direct click on button. 
> fix(composer): Adding ability to deselect by click radio button

- packages/scene-composer/package.json
- packages/scene-composer/src/components/Tree/tree.scss
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/enhancers/draggable.scss
Fix to restore drag-&-drop placement after refresh
> fix(composer): Fix to restore drag-&-drop placement after refresh

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
Fix for breaking drag/drop introduced in last PR & removes drag/drop icon from SubModels. 
> fix(composer): Fix for bug on drag/drop 

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
Fix to hide children of matching nodes when viewing search results. 
> fix(composer): Fix for displaying children on search results

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/index.tsx
Fix for duplicate submodels in tree on adding objects to scene
> fix(composer): Fix for duplicate submodels

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/GLTFModelComponent.tsx
Enhanced Edit set the last operation performed in the wrong order leading to the state for undo not being added
> fix(composer): Enhanced Edit now allows for undo operation

- packages/scene-composer/src/components/panels/SceneHierarchyPanel/SceneHierarchyDataProvider.tsx
The position needs to be calculated for the new parent so that when it transitions to it's local space we get the correct position
> fix(composer): Maintain the position in 3D space regardless of the parent

- packages/scene-composer/src/SceneViewer.tsx
- packages/scene-composer/src/__snapshots__/SceneViewer.spec.tsx.snap
Enable the new features that are planned to be released at 11/17 for SceneViewer
> fix(composer): enable new features for SceneViewer

- packages/dashboard/package.json
- packages/dashboard/src/components/grid/index.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/hooks/useKeyPress.ts
- packages/dashboard/src/store/actions/deleteWidgets/index.spec.ts
- packages/dashboard/src/store/actions/deleteWidgets/index.ts
- packages/dashboard/src/store/actions/index.ts
- packages/dashboard/src/store/reducer.ts
Adds delete widget functionality and keyboard hotkey support to dashboard internal
> feat(dashboard): add delete action

- packages/related-table/src/Hooks/useTreeCollection.test.ts
- packages/related-table/src/Hooks/useTreeCollection.ts
Fixes https://github.com/awslabs/iot-app-kit/issues/348
> fix(related-table): expanded toggling already expanded nodes

- packages/dashboard/src/components/side-panel/utils/index.ts
- yarn.lock
- Create helper functions `getProperty` and `setProperty` for fetching and updating widget states.
- Create `useInput` hook 
with these, we can easily create components to update widget states. For example, we have 
```
const widget: Widget = {
...
annotations: {
y: [
{
value: 10,
color: 'black',
},
],
},
}; 
```
if we want to add an input field to change the color of the YAnnotation, all I need to do is
```
const AnnotationSettings = () => {
const [color, updateColor] = useInput<string>('annotations.y.0.color');
return (
<Input
value={color}
onChange={(event) => {
updateColor(event.detail.value);
}}
/>
);
};
```
and it will automatically get the color value.
when users update it value, it will create a new widget state without modify the old state, which is very helpful when adapting …
> feat(dashboard-side-panel): Create helper functions

- packages/dashboard/src/components/side-panel/utils/index.ts
Cherry pick https://github.com/awslabs/iot-app-kit/pull/385
> feat(dashboard-side-panel): create `useInput` hook

- package-lock.json
- package.json
- packages/scene-composer/.eslintrc.js
- packages/scene-composer/package.json
- packages/scene-composer/tools/watch-build.js
add script to auto build composer change
> chore(composer): add script to auto build composer change

- packages/scene-composer/package.json
- packages/scene-composer/src/components/Tree/tree.scss
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
Fix to allow dragging nodes to root. 
* Includes fix for expand/collapse button for submodels as children
> fix(composer): Allows nodes to be dropped at root level

- .github/workflows/run-tests.yml
- packages/core/src/common/time.spec.ts
specify the node version to fix the failing tests disabled in https://github.com/awslabs/iot-app-kit/pull/477
```
httpserver
```
> chore: specify node version to 16

- packages/dashboard/src/components/sidePanel/index.tsx
- packages/dashboard/src/components/sidePanel/sections/baseSettingSection/index.spec.tsx
- packages/dashboard/src/components/sidePanel/sections/baseSettingSection/index.tsx
Add BaseSettingSection replacing Chart setting section.
> feat(dashboard): add BaseSettingSection

- packages/dashboard/src/components/resourceExplorer/components/searchbar.test.tsx
- packages/dashboard/src/components/resourceExplorer/index.test.tsx
Unit test for resource explorer searchbar.
> test(dashboard): resource explorer searchbar

- packages/dashboard/package.json
> chore(dashboard): bump 3.0.0-alpha.2

- packages/dashboard/package.json
- packages/dashboard/src/components/internalDashboard/determineTargetGestures.ts
- packages/dashboard/src/components/internalDashboard/gestures/types.ts
- packages/dashboard/src/components/internalDashboard/gestures/useSelection.spec.tsx
- packages/dashboard/src/components/internalDashboard/gestures/useSelection.ts
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/widgets/widget.tsx
- packages/dashboard/src/types.ts
- packages/dashboard/src/util/select.spec.ts
- packages/dashboard/src/util/select.ts
Refactor selection gestures from internal dashboard into a separate hook. Add tests for that hook and the supporting functions.
> chore(dashboard): move selection handling to hook

- packages/dashboard/src/components/grid/index.tsx
- packages/dashboard/src/components/internalDashboard/gestures/determineTargetGestures.ts
- packages/dashboard/src/components/internalDashboard/gestures/index.spec.tsx
- packages/dashboard/src/components/internalDashboard/gestures/index.ts
- packages/dashboard/src/components/internalDashboard/gestures/useMove.spec.tsx
- packages/dashboard/src/components/internalDashboard/gestures/useMove.ts
- packages/dashboard/src/components/internalDashboard/gestures/useResize.spec.tsx
- packages/dashboard/src/components/internalDashboard/gestures/useResize.ts
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/widgets/selectionBox.tsx
- packages/dashboard/src/components/widgets/selectionBoxAnchor.tsx
- packages/dashboard/src/components/widgets/widget.tsx
- packages/dashboard/src/util/position.spec.ts
- packages/dashboard/src/util/position.ts
Refactor resize and move gestures into their own hooks.
Refactor general gesture handling into its own hook.
> chore(dashboard): refactor resize and move gestures into hooks

- packages/dashboard/.storybook/main.js
- packages/dashboard/package.json
resolve pretty paths in storybook
> fix(dashboard): resolve pretty paths in storybook

- packages/dashboard/jest.config.ts
- packages/dashboard/package.json
- packages/dashboard/rollup.config.js
- packages/dashboard/src/components/palette/icons/input-component.tsx
- packages/dashboard/src/components/sidePanel/index.tsx
- packages/dashboard/src/components/sidePanel/sections/inputSettingsSection/index.spec.tsx
- packages/dashboard/src/components/sidePanel/sections/inputSettingsSection/index.tsx
- packages/dashboard/src/components/sidePanel/utils/index.ts
- packages/dashboard/src/components/widgets/primitives/input/index.spec.tsx
- packages/dashboard/src/components/widgets/primitives/input/index.tsx
- packages/dashboard/src/messages.ts
- packages/dashboard/src/types.ts
- packages/dashboard/testing/jest-setup.ts
- packages/dashboard/testing/mocks.ts
- packages/dashboard/tsconfig.json
Add configuration settings for input widget
https://user-images.githubusercontent.com/6397726/218612141-fc36eb0e-1386-4b44-bbbb-f17d408e47f2.mov
> feat(dashboard): add input widet configuration

- .release-please-manifest.json
- release-please-config.json
Add the dashboard package to the release pretty please configuration
> chore(release): add dashboard to the release manifest

- packages/components/src/components.d.ts
- packages/components/tsconfig.json
Exclude testing files under path `components/src/testing`
Changes in `packages/components/src/components.d.ts` is auto generated by running `npm run build`.
Size changes: 
```
// before
➜  components git:(main) ✗ du -sh dist
25M     dist
// after
➜  components git:(main) ✗ du -sh dist   
14M     dist
```
> build(components): exclude testing and demo components from build

- examples/react-app/package.json
> React18 internal

- packages/related-table/src/RelatedTable/RelatedTable.tsx
The current implementation prevents us (cloudscape) from releasing a new feature in the table. 
Please note: We don't generally expect internal functions such as this to be called outside of the table component.
This PR is a copy of CR-82829151
```
httpserver
``` …
> fix: Support additional parameters in intercepting calls to table cell

- packages/dashboard/package.json
- packages/source-iottwinmaker/package.json
- Upgrade to react18 compatible dnd library
- Upgrade webpack minor version to address dependabot alert
> chore(dep): upgrade react drag and drop and webpack dependencies on dashboard

- .github/workflows/e2e-playwright.yml
- .github/workflows/run-e2e-tests.yml
- .github/workflows/run-tests.yml
Speed up CI by filtering changes based on last commit
> ci(unit-tests): filter by last commit to increase CI speed

- packages/scene-composer/package.json
resolves https://github.com/awslabs/iot-app-kit/security/dependabot/90
> chore(dev-deps): upgrade webpack to resolve security issue

- .github/workflows/release-please.yml
Release as 4.0.0-nightly@nightly
> chore: release 4.0.0-nightly

- .github/workflows/release-please.yml
release at 4.0.0-nightly@nightly
> fix(release): release as 4.0.0-nightly

- .github/workflows/e2e-playwright.yml
- .github/workflows/npm-publish.yml
- .github/workflows/release-please.yml
> fix(ci): release as 3.0.1@alpha

- configuration/eslint-config/index.js
- configuration/eslint-config/package.json
- package-lock.json
- packages/components/package.json
- packages/core/src/index.ts
- packages/dashboard/package.json
- packages/dashboard/src/components/contextMenu/option.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/components/resourceExplorer/index.tsx
- packages/dashboard/src/components/sidePanel/index.tsx
- packages/dashboard/src/components/sidePanel/sections/propertiesAlarmSection/index.test.tsx
- packages/dashboard/src/components/widgets/dynamicWidget.tsx
- packages/dashboard/src/hooks/useKeyPress.ts
- packages/react-components/src/components/video-player/requestVideoUpload.tsx
- packages/react-components/src/components/video-player/videoPlayer.tsx
- packages/related-table/src/HOC/withUseTreeCollection.tsx
- packages/related-table/src/RelatedTable/ButtonWithTreeLines.tsx
- packages/scene-composer/.eslintignore
- packages/scene-composer/package.json
- packages/scene-composer/tests/utils/objectThreeUtils.spec.ts
- packages/source-iotsitewise/src/asset-modules/sitewise/cache.spec.ts
- packages/source-iotsitewise/src/time-series-data/data-source.ts
Enforce more strict rules around imports
Remove unused chai-related rules.
> refactor(ESLint): enforce import related eslint rules across monorepo

- packages/core/src/viewportManager/viewportManager.spec.ts
- packages/core/src/viewportManager/viewportManager.ts
Fix a prototype pollution vulnerability.
> fix(core): use Map to avoid prototype pollution

- packages/dashboard/src/components/internalDashboard/index.css
Allows toolbar to be the height of its contents, which removes the vertical scrollbar.
Fixes https://github.com/awslabs/iot-app-kit/issues/788
> fix(DashboardToolbar): remove scrollbar from toolbar

- packages/dashboard/src/components/sidePanel/sections/propertiesAlarmSection/index.test.tsx
- packages/dashboard/src/components/sidePanel/sections/propertiesAlarmSection/propertyComponent.tsx
Addresses https://github.com/awslabs/iot-app-kit/issues/794
Removes unneeded information. Will revisit how to introduce this information in the future.
> style(Dashboard): remove property information from property section

- packages/dashboard/src/components/contextMenu/index.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/resizablePanes/index.css
- packages/dashboard/src/components/resourceExplorer/stencil/style.css
Removes scroll bars from being rendered when no scroll bar is necessary
> style(Dashboard): remove scroll bars when not needed

- packages/react-components/src/components/bar-chart/barChart.tsx
resolves https://github.com/awslabs/iot-app-kit/issues/796
> fix(BarChart): prevent bar chart from trying to request raw data by default

- README.md
- docs/development.md
A lot has changed since the develpoment.md documentation was written on how to contribute. Updating to reflect the changes in how the monorepo operates to help integrate new developers onto IoT App Kit.
> docs(DevelopersGuide): update develoeprs guide

- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/components/status/status.tsx
Updates required for kpi and status component props based on recent refactor of those react components.
> fix(dashboard): update props passed to kpi and status components based on new api

- packages/dashboard/src/components/palette/index.tsx
- packages/dashboard/src/components/resourceExplorer/components/panel.tsx
- packages/dashboard/src/components/resourceExplorer/stencil/index.tsx
- packages/dashboard/src/components/sidePanel/sections/propertiesAlarmSection/index.tsx
- packages/dashboard/src/messages.ts
Update labels to 
- Component library
- Time machine
- Asset properties
- Asset name
- Properties and alarms
> fix(dashboard): use sentence casting for labels

- packages/dashboard/src/components/sidePanel/sections/textSettingSection/text.tsx
Remove font dropdown selection and text position dropdowns. 
> fix(dashboard): remove font dropdown and text position dropdowns

- packages/dashboard/src/components/dragLayer/index.tsx
- packages/dashboard/src/components/grid/index.css
- packages/dashboard/src/components/grid/index.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/palette/component.tsx
- packages/dashboard/src/components/resizablePanes/index.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
Bugfix for grid scrolling. Bugfix to prevent grid scrolling on pane resize. Bugfix for component drag and drop in firefox.
> fix(dashboard): fix grid scrolling issues

- packages/dashboard/src/customization/settings.ts
- packages/dashboard/src/customization/widgets/text/link/index.tsx
- packages/dashboard/src/customization/widgets/text/styledText/index.tsx
- packages/dashboard/src/customization/widgets/text/styledText/textArea.tsx
remove fontFamily from public api
> refactor(dashboard): temporarily remove fontFamily from public api

- packages/react-components/src/components/bar-chart/barChart.tsx
- packages/react-components/src/components/line-chart/lineChart.tsx
- packages/react-components/src/components/scatter-chart/scatterChart.tsx
- packages/react-components/src/components/status-timeline/statusTimeline.tsx
Remove legend for v4 release. Will come back and add it as an optional property with a more well thought out behavior
> refactor(ChartLegend): remove legend property

- packages/dashboard/src/customization/widgets/utils/assignDefaultStyleSettings.ts
Bugfix for chart colors resetting on property addition.
> fix(dashboard): bugfix for color reset on new property drop

- .github/workflows/npm-publish.yml
- .release-please-manifest.json
- packages/core-util/package.json
remove the private flag for core-utils
> fix(core-util): remove private flag for the core-util packages

- packages/dashboard/src/customization/settings.ts
- packages/dashboard/src/customization/widgets/types.ts
Remove legend property from widget type
> refactor(dashboard): remove legend property until config is implemented

- .github/workflows/npm-publish.yml
> fix(actions): update publish action for core-util

- .github/workflows/npm-publish.yml
run publish workflow on change to the workflow
> fix(actions): run publish workflow on change to the workflow

- packages/core-util/package.json
update publish config for core-utils
> fix(core-util): update publish config for core-utils

- packages/source-iotsitewise/package.json
> fix(source-iotsitewise): move testing util to dev dep

- .github/workflows/npm-publish.yml
Remove alpha tags from all packages except scene-composer.
> chore: remove alpha tag for all packages except scene-composer

- packages/dashboard/src/components/dragLayer/index.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
bugfix for text selection occurring during drag and drop events.
> fix(dashboard): disable user select on drag to prevent text selection

- packages/tools-iottwinmaker/README.md
Update readme to only pull most recent commit
```
httpserver
```
> chore(TwinMakerTools): update README

- packages/scene-composer/package.json
> fix(PeerDependencies): react-intl should be declared as a peer dependency

- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/DataOverlayComponent.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/DataOverlayComponentSnap.spec.tsx
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/__tests__/__snapshots__/DataOverlayComponentSnap.spec.tsx.snap
- packages/scene-composer/src/components/three-fiber/DataOverlayComponent/styles.scss
define overlay components' css under the parent class name to prevent css overriding due to same class name
```
httpserver
```
> fix(composer): update overlay css

- .github/dependabot.yml
Enable dependabot to perform daily dependency updates on the monorepo.
> chore: create .github/dependabot.yml

- commitlint.config.js
- configuration/eslint-config/package.json
Change is being made to prevent dependabot commits from failing. Discussed with @diehbria prior to making the change.
> fix: increase commitlint body-max-line-length to 250

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
fix flicker grid on moving
before
https://user-images.githubusercontent.com/9315598/231302504-46812ae3-8f08-4104-8b93-8abd8bd19a5c.mov
after
https://user-images.githubusercontent.com/9315598/231302536-c2b684bc-2b1f-454f-a96e-b6f354f94879.mov
```
httpserver
``` …
> fix(composer): flicker grid lines

- .github/workflows/release-please.yml
remove flags added previously in attempts to get a 'release candidate' version released.
> build(release-please): remove prerelease flag

- packages/scene-composer/src/components/panels/SettingsPanel.tsx
- packages/scene-composer/src/components/panels/__tests__/__snapshots__/SettingsPanel.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/DataOverlayComponentEditorSnap.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-settings/ComponentVisibilityToggle.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneTagSettingsEditor.tsx
- packages/scene-composer/src/components/panels/scene-settings/__snapshots__/ComponentVisibilityToggle.spec.tsx.snap
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
update overlay and settings UI based on latest UX mock change
```
httpserver
```
> fix(composer): update overlay and settings UI

- .github/workflows/autorebase.yml
> build: enable ability to auto-rebase

- packages/dashboard/e2e/tests/dashboard/dashboard.spec.ts
- packages/dashboard/e2e/tests/utils/dragAndDrop.ts
- packages/dashboard/src/components/grid/gestureable.tsx
- packages/dashboard/src/components/grid/gestures/constrainPosition.ts
- packages/dashboard/src/components/grid/gestures/positionTracker.ts
- packages/dashboard/src/components/grid/gestures/types.ts
- packages/dashboard/src/components/grid/gestures/useDragMonitor.ts
- packages/dashboard/src/components/grid/gestures/useDropMonitor.ts
- packages/dashboard/src/components/grid/gestures/useGridDragAndDrop.ts
- packages/dashboard/src/components/grid/gestures/usePointerTracker.ts
- packages/dashboard/src/components/grid/grid.tsx
- packages/dashboard/src/components/grid/index.tsx
- packages/dashboard/src/components/grid/sizedGrid.tsx
- packages/dashboard/src/store/actions/changeDashboardGrid/changeCellSize.ts
Refactor grid component so that the gesture logic is more maintainable.
Add another e2e test to verify simple resize, move, and select gestures
> fix(dashboard): refactor grid component to make it more maintainable

- packages/scene-composer/translations/IotAppKitSceneComposer.de_DE.json
- packages/scene-composer/translations/IotAppKitSceneComposer.en_UK.json
- packages/scene-composer/translations/IotAppKitSceneComposer.es_ES.json
- packages/scene-composer/translations/IotAppKitSceneComposer.fr_FR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.id_ID.json
- packages/scene-composer/translations/IotAppKitSceneComposer.it_IT.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ja_JP.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ko_KR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.pt_BR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_CN.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_TW.json
add translations
```
httpserver
```
> chore(composer): add translations

- packages/dashboard/e2e/tests/dashboard/dashboard.spec.ts
- packages/dashboard/e2e/tests/utils/dragAndDrop.ts
- packages/dashboard/e2e/tests/utils/grid.ts
- packages/dashboard/e2e/tests/utils/locator.ts
- packages/dashboard/e2e/tests/utils/mousePosition.ts
Add a grid helper util for e2e testing.
> feat(dashboard): add utils for e2e testing dashboard

- .github/workflows/release-please.yml
Alter release-please github action to not limit execution based on which files were altered.
> fix(CI): execute release-please action on all commits

- packages/react-components/src/components/video-player/videoPlayer.tsx
- Corrected the percentage calculation of the new seek position on the progress bar
```
httpserver
```
> fix(video-player): video seek percent calculation

- packages/source-iottwinmaker/src/__mocks__/iottwinmakerSDK.ts
- packages/source-iottwinmaker/src/initialize.ts
- packages/source-iottwinmaker/src/knowledgeGraph-module/KGDataModule.spec.ts
- packages/source-iottwinmaker/src/knowledgeGraph-module/KGDataModule.ts
- packages/source-iottwinmaker/src/knowledgeGraph-module/types.ts
- packages/source-iottwinmaker/src/types.ts
Merge  knowledge graph datasource into main branch.
> feat(knowledge graph): knowledge graph datasource

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- Support enhanced editing for the Matterport scenes
```
httpserver
```
> feat(composer): support enhanced editing in Matterport scene

- docs/Core.md
> fix(docs): udpate dataStream docs

- packages/scene-composer/.eslintrc.js
- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/panels/scene-components/DataBindingComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/DataOverlayComponentEditorSnap.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/common/DataBindingMapEditor.tsx
- packages/scene-composer/src/utils/dataBindingTemplateUtils.ts
- packages/scene-composer/src/utils/dataBindingUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
Fixed entity and overlay binding bugs.
```
httpserver
```
> feat(scene composer): fixed entity data binding data format

- packages/scene-composer/package.json
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.spec.tsx
- packages/scene-composer/src/components/panels/AddComponentMenu.tsx
- packages/scene-composer/src/components/panels/CommonPanelComponents.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.spec.tsx
- packages/scene-composer/src/components/panels/ComponentEditMenu.tsx
- packages/scene-composer/src/components/panels/SceneNodeInspectorPanel.tsx
- packages/scene-composer/src/components/panels/scene-components/DataBindingComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/DataBindingComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/AnchorComponentEditor.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/__snapshots__/DataOverlayComponentEditorSnap.spec.tsx.snap
- packages/scene-composer/src/components/panels/scene-components/common/DataBindingMapEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/common/DataBindingMapEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/common/ValueDataBindingBuilder.tsx
- packages/scene-composer/src/components/panels/scene-components/common/__snapshots__/DataBindingMapEditorSnap.spec.tsx.snap
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/models/SceneModels.ts
- packages/scene-composer/src/store/helpers/serializationHelpers.ts
- packages/scene-composer/src/store/internalInterfaces.ts
- packages/scene-composer/src/utils/dataBindingTemplateUtils.spec.ts
- packages/scene-composer/src/utils/dataBindingTemplateUtils.ts
- packages/scene-composer/src/utils/dataBindingUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
This commit has all the changes of entity binding. Merging it from main branch to release-3.x branch. 
```
httpserver
```
> feat(3dkg): added 3dkg changes for entity data binding

- examples/react-app/src/components/index.tsx
Update examples/react to connect the Graph Display query parameter and Scene Viewer onSelectionChange event so that:
-selecting in the Graph Display won't trigger new query, 
-selecting an already selected Scene Node won't trigger a graph query
-selecting an entity bound scene node that isn't the current one under selection will trigger a new graph query for entityID
misc. clean up to make sure query result and selected Entity highlight continue to behave properly.
To run the storybook build locally, you need a …
> chore(3DKG): stable KG query trigger from scene selection events

- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/lineChart/component.tsx
- packages/dashboard/src/customization/widgets/scatterChart/component.tsx
- packages/dashboard/src/hooks/useChartSize.ts
- packages/react-components/src/common/chartTypes.ts
- packages/react-components/src/components/bar-chart/barChart.tsx
- packages/react-components/src/components/chart/addTrendCursor.ts
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/converters/converters.spec.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/chart/useVisualizedDataStreams.spec.ts
- packages/react-components/src/components/iot-app-kit-config/defaultValues.ts
- packages/react-components/src/components/iot-app-kit-config/index.tsx
- packages/react-components/src/components/iot-app-kit-config/types.ts
- packages/react-components/src/components/line-chart/lineChart.tsx
- packages/react-components/src/components/scatter-chart/scatterChart.tsx
- packages/react-components/src/hooks/useECharts/useECharts.tsx
- packages/react-components/src/hooks/useHasFeatureFlag/index.ts
- packages/react-components/src/hooks/useHasFeatureFlag/useHasFeatureFlag.spec.ts
- packages/react-components/src/hooks/useHasFeatureFlag/useHasFeatureFlag.ts
- packages/react-components/src/index.ts
- packages/react-components/src/utils/aggregationFrequency.spec.ts
- packages/react-components/stories/chart/chart.stories.tsx
create the appKit context component, which will hold feature flags and any other future configurable aspects such as translations, theme, etc.
2 ways to use this new config:
1. wrap all your widgets in a provider. example: `dashboard/src/components/dashboard/index.tsx`. For now the provider accepts a `customFeatureConfig` which toggles feature flags
2. do nothing and use default values chosen by us :) 
also created the following hooks: 
`useHasFeatureFlag` (featureName) => boolean
`useAppKitConfig` () => config
example of config we could have in the future:
```
{
featureConfig: { 
HAS_FEATURE_A: false, 
HAS_FEATURE_B: true    
},
themeColors: {
background: #...,
mainText: #...
}
};
``` …
> feat: feature flag

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
* This change contains mocking the onWidgetClick event and validate the anchor widget response. 
* npm run test
After
Before
```
httpserver
```
> feat(scene composer): added unit test by mocking onWidgetClick event

- examples/react-app/src/index.tsx
Fix KG component CSS, edge name appears as a black box.
```
httpserver
```
> fix(reactExample): fix css in Knowledge Graph Component

- packages/react-components/.env.example
- packages/react-components/stories/chart/chart.stories.tsx
- packages/react-components/stories/utils/query.ts
- turbo.json
Adding a story for base chart that uses a real sitewise query.
Adds utils for creating the query with the correct clients.
> feat(react-components): add a sitewise connected chart story

- packages/scene-composer/src/utils/dataBindingVariableUtils.spec.ts
- packages/scene-composer/src/utils/dataBindingVariableUtils.ts
fix the issue where 0 will be displayed as "-" in overlay
```
httpserver
```
> fix(composer): fix issue displaying 0 in overlay

- packages/react-components/src/components/chart/hooks/useChartsLegend.tsx
- packages/react-components/src/components/chart/legend/legend.tsx
- packages/react-components/stories/chart/chart.stories.tsx
adding sorting ability for the legend table. using the out of the box useCollection hook for sorting. 
refer to screen capture
> feat(react-component): adding sorting ability for the chart legends

- packages/scene-composer/src/augmentations/components/three-fiber/anchor/AnchorWidget.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/AnchorWidget.spec.tsx
- packages/scene-composer/src/augmentations/components/three-fiber/anchor/__tests__/__snapshots__/AnchorWidget.spec.tsx.snap
- packages/scene-composer/src/components/StateManager.spec.tsx
- packages/scene-composer/src/components/StateManager.tsx
- packages/scene-composer/src/hooks/useBindingData.spec.ts
- packages/scene-composer/src/hooks/useBindingData.ts
- packages/scene-composer/src/hooks/useBindingQueries.spec.ts
- packages/scene-composer/src/hooks/useBindingQueries.ts
- packages/scene-composer/src/interfaces/feature.ts
- packages/scene-composer/src/store/Store.ts
- packages/scene-composer/src/store/StoreOperations.ts
- packages/scene-composer/src/store/slices/ViewOptionStateSlice.spec.ts
- packages/scene-composer/src/store/slices/ViewOptionStateSlice.ts
- packages/scene-composer/src/utils/dataBindingTemplateUtils.spec.ts
- packages/scene-composer/src/utils/dataBindingTemplateUtils.ts
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
- packages/scene-composer/stories/components/scene-composer.tsx
- packages/source-iottwinmaker/src/data-binding-provider/createEntityPropertyBindingProvider.ts
- packages/source-iottwinmaker/src/data-binding-provider/types.ts
- packages/source-iottwinmaker/src/time-series-data/completeDataStreams.ts
- implement useBindingData that can fetch data for all data bindings
- integrate the hook to Tag
https://github.com/awslabs/iot-app-kit/assets/9315598/f639f630-3e85-401b-b287-850367f5f5ea
```
httpserver
```
> feat(composer): implement useBindingData and integrate to Tag

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/converters/convertAxis.ts
- packages/react-components/src/components/chart/converters/convertOptions.ts
- packages/react-components/src/components/chart/converters/convertStyles.spec.tsx
- packages/react-components/src/components/chart/converters/converters.spec.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/hooks/useChartSetOptionSettings.ts
- packages/react-components/src/components/chart/hooks/useContextMenu.ts
- packages/react-components/src/components/chart/hooks/useTrendCursors.ts
- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/hooks/useViewportToMS.ts
- packages/react-components/src/components/chart/hooks/useXAxis.ts
- packages/react-components/src/components/chart/tests/getInfo.spec.tsx
- packages/react-components/src/components/chart/tests/getTrendCursor.spec.tsx
- packages/react-components/src/components/chart/tests/handleResize.spec.tsx
- packages/react-components/src/components/chart/tests/handleSync.spec.tsx
- packages/react-components/src/components/chart/tests/useTrendCursorsEvents.spec.tsx
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/chart/utils/getInfo.ts
- packages/react-components/src/components/chart/utils/getTrendCursor.ts
- packages/react-components/src/components/chart/utils/handleResize.ts
- packages/react-components/src/components/chart/utils/handleSync.ts
- packages/react-components/src/components/chart/utils/handleViewport.ts
This is to add live mode. i.e the charts obey the given viewport
refer to the screen share
https://github.com/awslabs/iot-app-kit/assets/135036199/aef5a294-43e0-418b-a7d4-cb550be0c235
> feat(react-components): supporting live mode in echarts

- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPickerUtils/SvgParserHelper.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/interface.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetEditor.tsx
- packages/scene-composer/src/components/panels/scene-rule-components/SceneRuleTargetIconEditor.tsx
- packages/scene-composer/src/interfaces/components.ts
- packages/scene-composer/src/utils/eventDataUtils.ts
- packages/scene-composer/translations/IotAppKitSceneComposer.en_US.json
This change contains color-picker bug fixes. This change is already merged to release-3.x branch. 
```
httpserver
```
> feat(scene composer): color picker bug fixes

- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/tag-style/ColorPicker/ColorPicker.tsx
* Adjust the spacing as per UX requirements.
* Fixed the toggle issue between two color picker instance by using random string ID.
https://github.com/awslabs/iot-app-kit/assets/54058998/2b86c14b-00bf-4f2e-9bba-e264db0217c4
```
httpserver
``` …
> fix(scene composer): fix spacing issue between elements

- packages/dashboard/custom.d.ts
- packages/dashboard/jest.config.ts
- packages/dashboard/package.json
- packages/dashboard/rollup.config.js
- packages/dashboard/src/customization/widgets/barChart/icon.svg
- packages/dashboard/src/customization/widgets/barChart/icon.tsx
- packages/dashboard/svgTransform.js
- packages/dashboard/tsconfig.json
adding support for .svg files
refer to the screen recording
> fix(dashboard): adding a ts module file for supporting svg files

- packages/react-components/src/components/chart/contextMenu/ChartContextMenu.spec.tsx
Adding test cases for per chart context menu
> chore(react-components): add per chart context menu test cases

- packages/scene-composer/src/components/WebGLCanvasManager.tsx
Fix to go with React/Node 18 upgrades to restore scene grid. 
```
httpserver
```
> fix(scene composer): fix for missing grid

- packages/scene-composer/translations/IotAppKitSceneComposer.de_DE.json
- packages/scene-composer/translations/IotAppKitSceneComposer.en_UK.json
- packages/scene-composer/translations/IotAppKitSceneComposer.es_ES.json
- packages/scene-composer/translations/IotAppKitSceneComposer.fr_FR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.id_ID.json
- packages/scene-composer/translations/IotAppKitSceneComposer.it_IT.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ja_JP.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ko_KR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.pt_BR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_CN.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_TW.json
add new translations
```
httpserver
```
> fix(composer): add new translations

- packages/react-components/src/components/chart/eChartsConstants.ts
letting echarts calculate the yaxis instead of providing a formatter
> fix(react-components): fixing the duplicate yAxis values

- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/converters/convertOptions.ts
- packages/react-components/src/components/chart/converters/converters.spec.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/types.ts
- packages/react-components/stories/chart/base-chart.stories.tsx
- packages/react-components/stories/trend-cursor-sync/timesync.stories.tsx
just making some UX updates and minor refactor of the convertOptions 
> fix(react-components): updating echarts ux

- packages/react-components/src/components/chart/hooks/useChartSetOptionSettings.ts
- packages/react-components/src/components/chart/hooks/useDataZoom.ts
- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/utils/handleViewport.ts
> fix(react-components): fixing TCs on data zoom

- packages/dashboard/src/components/viewportSelection/index.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/lineChart/component.tsx
- packages/dashboard/src/customization/widgets/scatterChart/component.tsx
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.css
- packages/react-components/src/components/chart/converters/convertOptions.ts
- packages/react-components/src/components/chart/hooks/useXAxis.ts
1. fixed viewport
2. fixed some styling issue
3. updated time machine to reflect the actual viewport 
> fix(react-components): fixing the viewport and some styling elements

- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-components/AnchorComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/DataOverlayComponentEditor.tsx
- packages/scene-composer/src/components/panels/scene-components/EntityBindingComponentEditor.tsx
- packages/scene-composer/src/store/helpers/__tests__/updateEntityHelper.spec.ts
- packages/scene-composer/src/store/helpers/componentMapHelpers.ts
- packages/scene-composer/src/store/helpers/interfaceHelpers.ts
- packages/scene-composer/src/store/helpers/updateEntityHelper.ts
- packages/scene-composer/src/store/middlewares.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.ts
- packages/scene-composer/src/utils/entityModelUtils/overlayComponent.ts
- packages/scene-composer/stories/Developer/SceneComposer.stories.mdx
* Update tag using updateEntity call.
* Update dataoverlay using updateEntity call.
* Update Binding using updateEntity call.
* Organized the imports.
* unit tests
```
httpserver
```
> feat(dynamic scenes): update entities using dynamic scenes

- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/hooks/useDataZoom.ts
adding 300ms debounce to setting the viewport on zoom
https://github.com/awslabs/iot-app-kit/assets/135036199/f8eca218-a336-472a-9f9d-a83fe905f258
> fix(react-components): adding debounce to the echarts zoom handler

- packages/scene-composer/src/components/three-fiber/EditorCamera.tsx
- packages/scene-composer/tests/components/three-fiber/EditorCamera.spec.tsx
When picking a camera view to active we set a fixed distance of 10 units in front of the camera for the orbit camera target point that the camera will rotate around.  But this doesn't scale appropriately to the scene size resulting in unresponsive and unexpected camera behavior in large scenes.
Now when a camera is made active a ray cast is performed from the new camera position. If it finds an object ahead of the camera then that object's intersection point is used as the camera target instead of an arbitrary distance in front of the camera. If the camera was configured without an object ahead of it then it will still use the old default of a point 10 units ahead of the camera.
1st part of video is old behavior, 2nd is improved behavior. …
> fix(camera): selecting camera view uses raycast to set better target distance for orbit

- packages/dashboard/src/components/internalDashboard/index.tsx
The Dashboard background color is updated to grey-125
> fix: updated dashboard background color to grey-125 

- packages/dashboard/src/components/internalDashboard/index.tsx
> fix(dashboard): set initial viewport to 5m

- packages/dashboard/src/components/dashboard/getClients.ts
- packages/dashboard/src/components/queryEditor/useQuery.ts
- packages/dashboard/src/components/resizablePanes/constants.ts
- packages/dashboard/src/customization/propertiesSections/propertiesPanel/emptyPanel.css
- packages/dashboard/src/customization/widgets/lineScatterChart/plugin.tsx
- packages/dashboard/src/customization/widgets/utils/widgetAggregationUtils.ts
- packages/dashboard/src/hooks/useAssetDescriptionQueries.ts
> fix(echarts): bugs for demo

- packages/react-components/src/components/chart/hooks/useTrendCursorsEvents.ts
- packages/react-components/src/hooks/useECharts/useGroupableEchart.ts
echarts sync was not working with second chart
the echarts connect call was only happening once instead of after every chart was added
> fix: groupable echarts

- packages/react-components/src/components/chart/converters/converters.spec.ts
Fixes unit test broken by https://github.com/awslabs/iot-app-kit/commit/8641b1f737919b868da7b309cb7ebc6183ef1918
```
httpserver
```
> fix: update unit test

- packages/dashboard/e2e/tests/utils/grid.ts
- packages/dashboard/e2e/tests/utils/mousePosition.ts
- packages/dashboard/src/components/internalDashboard/gestures/determineTargetGestures.ts
- packages/dashboard/src/components/widgets/selectionBox.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
> fix: dont move widget when resizing legend

- packages/dashboard/src/customization/widgets/table/component.spec.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/table/constants.ts
- packages/dashboard/src/customization/widgets/table/table-config.tsx
- packages/react-components/src/components/table/tableBase.tsx
> feat: add filtering ability

- packages/dashboard/src/components/internalDashboard/dashboardEmptyState.tsx
Update icon path since components have been moved
> fix(dashboard): update icon path for empty dashboard

- packages/dashboard/src/components/queryEditor/useQuery.ts
- packages/dashboard/src/customization/propertiesSections/aggregationSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/getPropertyDisplay.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/onDeleteProperty.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/propertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/sectionTypes.ts
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledSection.tsx
- packages/dashboard/src/customization/widgets/barChart/component.tsx
- packages/dashboard/src/customization/widgets/kpi/component.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/customization/widgets/status/component.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/dashboard/src/customization/widgets/utils/assetQuery/applyAggregationToQuery.ts
- packages/dashboard/src/customization/widgets/utils/assetQuery/applyDefaultStylesToQuery.tsx
- packages/dashboard/src/customization/widgets/utils/assetQuery/applyResolutionToQuery.ts
- packages/dashboard/src/customization/widgets/utils/assetQuery/assignDefaultRefId.ts
- packages/dashboard/src/customization/widgets/utils/assignDefaultStyleSettings.ts
- packages/dashboard/src/hooks/useAssetDescriptionQueries.ts
- packages/dashboard/src/hooks/useWidgetDataTypeSet.ts
- packages/dashboard/src/types.ts
- packages/dashboard/testing/mocks.ts
- packages/source-iotsitewise/src/completeDataStreams.ts
- packages/source-iotsitewise/src/initialize.ts
This PR enables the dashboard to utilize unmodeled data streams.
> feat: unmodeled data streams

- packages/dashboard/src/components/actions/index.tsx
Fix a broken build issue present in iot-app-kit 8.0.1
> fix(Dashboard): fix breaking build due to invalid import

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chart.css
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/hooks/useChartsLegend.tsx
- packages/react-components/src/components/chart/legend/legend.css
- packages/react-components/src/components/chart/legend/legend.tsx
for the #1930 updated the chart legend ux and it includes
1. reduced the legend properties spacing 
2. added the new color to legend border
3. default width is increased for legend
4. tooltip added for the truncated names and names will truncate based on visibility  
https://ibb.co/G5kcxzh
> feat: updated the chart legend ux(spacing, legend border color, width, tooltip if name truncated)

- packages/dashboard/src/components/queryEditor/useQuery.ts
- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/settings/index.tsx
- packages/dashboard/src/customization/propertiesSections/sizeAndPositionSettings/index.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/plugin.tsx
- packages/dashboard/src/customization/widgets/utils/widgetAggregationUtils.ts
BREAKING CHANGE: widget type change from line-scatter-chart -> xy-plot
> chore(dashboard): change line-scatter-chart to xy-plot

- packages/dashboard/src/customization/widgets/utils/assignDefaultStyleSettings.ts
Fix assignment of default aggregation and resolution so bar chart renders properly 
> fix(dashboard): bar chart default aggregation+resolution

- .github/workflows/codeql-analysis.yml
- packages/dashboard/playwright.config.ts
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/utils/getXAxis.ts
The xaxis should not tick on every re-render, this will mess with the absolute viewport 
> fix(react-components): fixing the xaxis and viewport dependency

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/converters/convertGrid.ts
- packages/react-components/src/components/chart/converters/convertOptions.ts
- packages/react-components/src/components/chart/converters/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/converters/converters.spec.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/legend/multiYAxis.tsx
- packages/react-components/src/components/chart/legend/yAxisMenu.css
- packages/react-components/src/components/chart/legend/yAxisMenu.tsx
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/components/menu/menu.css
- packages/react-components/src/components/menu/option.tsx
- packages/react-components/src/hooks/useECharts/useResizeableEChart.ts
Bugfix for multi y axis not a number display.
Style fixes for multi y axis legend. Fix spacing and font sizing.
> fix: style updates and bugfixes for multi y axis

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/createModeledDataStreamColumnDefinitions.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/unmodeledDataStreamExplorer/unmodeledDataStreamTable/unmodeledDataStreamTable.tsx
This fix for the ticket: #2054 
add a fix for the latest value and latest value times filtering and sorting in both modeled and unmodeled tables.
https://imgur.com/a/3B59Yyo
> fix: latest value filtering and sorting

- packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
The line and scatter chart threshold toggle: "Hide all thresholds" was broken. 
Fixed the toggle in this PR.
https://github.com/awslabs/iot-app-kit/assets/87385528/238af0f6-8343-4280-a83d-21dbf4504330
```
httpserver
``` …
> fix(dashboard): fix toggle hide thresholds

- packages/dashboard/src/components/dashboard/getQueries.ts
This change ensures batching of requests is done correctly on the dashboard by requiring a 100 ms collection window before firing batch requests.
> fix: synchronize batching

- packages/react-components/src/components/chart/converters/convertSeriesAndYAxis.ts
the dashbaord was throwing an exception when the ymin and max was set per property
RC : 
we were adding a min and max of 0 , 1000 when there is no data but this was an array of single object. 
in reality yaxis can be array of multi elements based on the per property limits.
the series data then points which yaxis index to use. given we were defaulting to a single element array, the series which has yaxisIndex > 0 would blow up
https://github.com/awslabs/iot-app-kit/assets/135036199/3dbe61f7-db68-4c0f-bcd1-29b6350fb641
> fix(react-components): fixing the prod issue of dashboard throwing exception

- packages/dashboard/src/components/internalDashboard/index.tsx
TrendCursorSYnc has to be child of TimeSync
> fix(dashboard): tc sync fix

- packages/tools-iottwinmaker/README.md
- packages/tools-iottwinmaker/src/lib/workspace.ts
> fix(TMDT): added proper error handling for S3 Bucket ACL customer issue and updated README

- packages/react-components/jest.config.ts
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/trendCursor/constants/index.ts
- packages/react-components/src/components/chart/trendCursor/getTrendCursor/components/markers/index.ts
- packages/react-components/src/components/chart/trendCursor/resize/updateYValues.ts
- packages/react-components/src/components/chart/trendCursor/resize/useHandleResize.ts
- packages/react-components/src/components/chart/trendCursor/series/useHandleSeries.ts
- packages/react-components/src/components/chart/trendCursor/tests/handleResize.spec.tsx
- packages/react-components/src/components/chart/trendCursor/useTrendCursors.ts
- packages/react-components/src/components/chart/trendCursor/yMinMax/useHandleYMinMax.ts
- packages/react-components/src/components/chart/utils/useDelayedRender.ts
> fix(react-components): Trendcursors ymin max handling and styling fixes

- packages/dashboard/src/components/csvDownloadButton/types.ts
- packages/dashboard/src/components/csvDownloadButton/useViewportData.ts
add useCSVData hook which pulls from the query and useDataStream hook to get data needed for a future CSV feature 
example graph (modeled data)
example data (modeled data)
```
[
{
"id": "1a89034b-0705-416c-a67f-340e574affd8---c4b0344e-4961-4e16-854d-05642ffd96c1",
"value": 43.26532776414541,
"unit": "Degrees",
"timestamp": "2023/10/28 20:00:00",
"aggregationType": "AVERAGE",
"resolution": 86400000,
"assetId": "1a89034b-0705-416c-a67f-340e574affd8",
"propertyId": "c4b0344e-4961-4e16-854d-05642ffd96c1",
"dataType": "DOUBLE",
"propertyName": "Wind Direction",
"assetName": "Demo Turbine Asset 4"
},
{
"id": "1a89034b-0705-416c-a67f-340e574affd8---c4b0344e-4961-4e16-854d-05642ffd96c1",
"value": 51.44607894935983,
"unit": "Degrees",
"timestamp": "2023/10/29 20:00:00",
"aggregationType": …
```
> feat(dashboard): csv data hook

- packages/dashboard/e2e/tests/dashboard/dashboard.spec.ts
- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/view.test.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/customization/propertiesSections/axisSettings/section.spec.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/section.test.tsx
- packages/dashboard/src/customization/propertiesSections/settings/section.test.tsx
- packages/dashboard/src/customization/propertiesSections/sizeAndPositionSettings/section.spec.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/link.spec.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/text.spec.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.spec.tsx
- packages/dashboard/src/customization/widgets/lineSymbol/component.test.tsx
- packages/dashboard/src/store/index.ts
- packages/dashboard/src/store/state.ts
- packages/dashboard/src/types.ts
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
- packages/react-components/src/components/time-sync/timeSelection.tsx
This PR is for [1947](https://github.com/awslabs/iot-app-kit/issues/1947)
Added new header design as per mockup, to do it I used <ContentLayout /> component from cloudscape design. 
In the below-recorded video, I added a "Test Dashboard" title name for demo video. In reality, this name will come from IoT-application(To receive the dashboard name from Iot-application I created a PR(https://github.com/awslabs/iot-application/pull/1615)
https://github.com/awslabs/iot-app-kit/assets/139960352/085bb538-f94f-4027-bf72-193f0fd4b16e
> feat: header design update

- package-lock.json
- packages/dashboard/package.json
- packages/dashboard/src/components/csvDownloadButton/types.ts
- packages/dashboard/src/components/csvDownloadButton/useViewportData.ts
- import package to convert a list of objects to a CSV
- remove some extraneous values in the CSVObject type 
- update dates to be ISO string
> feat(dashboard): json to csv package

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/trendCursor/calculations/calculateSeriesMakers.ts
- packages/react-components/src/components/chart/trendCursor/chartOptions/handleOptions.ts
- packages/react-components/src/components/chart/trendCursor/getTrendCursor/getTrendCursor.ts
- packages/react-components/src/components/chart/trendCursor/mouseEvents/handlers/drag/update.ts
- packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/trendCursor/resize/useHandleResize.ts
- packages/react-components/src/components/chart/trendCursor/series/useHandleSeries.ts
- packages/react-components/src/components/chart/trendCursor/sync/useHandleSync.ts
- packages/react-components/src/components/chart/trendCursor/types/index.ts
- packages/react-components/src/components/chart/trendCursor/useTrendCursors.ts
- packages/react-components/src/components/chart/trendCursor/viewport/useHandleViewport.ts
- packages/react-components/src/components/chart/trendCursor/yMinMax/useHandleYMinMax.ts
1. Adding significant Digits as one of the props for TC
2. updated animation flag for live and non-live mode, this should fix the jiggery ness on panning
3. rearranged events file for readability
https://github.com/awslabs/iot-app-kit/assets/135036199/4e0635ac-4bda-4025-8397-c4366a274734
https://github.com/awslabs/iot-app-kit/assets/135036199/8a15741f-754e-47fa-bd92-f6a3eaeaf7f4
> feat(react-components): adding significant digits to trendcursors

- packages/react-components/src/components/time-sync/viewportAdapter.spec.ts
update viewportAdapter tests for month and minutes
> fix(react-components): update viewportAdapter tests for month and minutes

- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledSection.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
- packages/dashboard/src/customization/widgets/types.ts
Remove the hide/show feature from the configuration panel and dashboard definition.
> fix(dashboard): remove hide/show from dashboard definition and config panel

- packages/dashboard/src/components/csvDownloadButton/index.tsx
> fix: change test id for download button

- packages/dashboard/src/components/grid/gestures/useDragMonitor.ts
This change improves the performance when dragging widgets around the dashboard by ensuring the dragging movement is aligned with browser repainting using requestAnimationFrame.
https://github.com/awslabs/iot-app-kit/assets/67283114/5d913a56-0bee-4d11-a5da-7f9f20e6bea1
https://github.com/awslabs/iot-app-kit/assets/67283114/8530fed4-45c9-46fb-875c-64705bd8b12b
> perf: use requestAnimationFrame when dragging widgets on the dashboard

- packages/dashboard/src/components/palette/icons/index.css
- packages/dashboard/src/customization/widgets/barChart/icon.tsx
- packages/dashboard/src/customization/widgets/components/widgetIcon.tsx
- packages/dashboard/src/customization/widgets/kpi/icon.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/icon.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimelineIcon.tsx
- packages/dashboard/src/customization/widgets/status/icon.tsx
- packages/dashboard/src/customization/widgets/table/icon.tsx
- packages/dashboard/src/customization/widgets/text/icon.tsx
Fixed twitchy behaviour on hovering edge of the widget panel buttons.
Verification:
[Twitchy-Widget-icons-.webm](https://github.com/awslabs/iot-app-kit/assets/81667589/15d52b81-4daa-4d67-a1a2-bf65afa915f9)
> fix: twitchy widget icons #2143

- packages/dashboard/e2e/tests/dashboard/dashboard.spec.ts
- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/view.test.tsx
- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/components/internalDashboard/index.tsx
- packages/dashboard/src/customization/propertiesSections/axisSettings/section.spec.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/section.test.tsx
- packages/dashboard/src/customization/propertiesSections/settings/section.test.tsx
- packages/dashboard/src/customization/propertiesSections/sizeAndPositionSettings/section.spec.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/link.spec.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/text.spec.tsx
- packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.spec.tsx
- packages/dashboard/src/customization/widgets/lineSymbol/component.test.tsx
- packages/dashboard/src/store/index.ts
- packages/dashboard/src/store/state.ts
- packages/dashboard/src/types.ts
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
- packages/react-components/src/components/time-sync/timeSelection.tsx
This reverts commit fe71669d26dd4a618c691c58785302fe42a8bb8c.
> fix: Revert header design update

- packages/dashboard/src/components/csvDownloadButton/getDescribedTimeSeries.tsx
- packages/dashboard/src/components/csvDownloadButton/index.tsx
- packages/dashboard/src/components/csvDownloadButton/types.ts
- packages/dashboard/src/components/csvDownloadButton/useViewportData.ts
- packages/dashboard/src/components/widgets/tile/tile.tsx
good old async/await request for unmodeled data stream descriptions
> feat(dashboard): describe unmodeled data stream

- packages/core/src/index.ts
- packages/core/src/logger/logger.interface.ts
- packages/core/src/metric-recorder/metricsRecorder.interface.ts
- packages/core/src/plugins/loggerSettings.ts
- packages/core/src/plugins/metricsRecorderSettings.ts
- packages/core/src/plugins/pluginsRegistry.spec.ts
- packages/core/src/plugins/pluginsRegistry.ts
High level description of each components:
* AppKit - see [IoT AppKit](https://github.com/awslabs/iot-app-kit)
* [NEW] PluginsRegistry - a basic / stand-in registry to register and provide plugins - an initial plugin system until we have a better design
* [NEW] StorageLogger - a plugin to handle received log and metric emissions and send to Storage; not yet implemented;
* [NEW] Storage - a log and metric storage; not yet implemented;
* Client - extra; please ignore;
> feat: experimental plugins registry; logger and metrics recorder plugins

- examples/react-app/src/components/VideoPlayer.tsx
- examples/react-app/src/configs.ts
- packages/react-components/src/components/video-player/videoPlayer.tsx
- Fixed the toggle playback mode functionality
- Updated the video player to respond to the time range changes
https://github.com/awslabs/iot-app-kit/assets/43108986/cd5590b2-9144-487e-9f9f-0c61f08b1c16
- Run the react-app example from iot-app-kit
- Use the video player in this app to test the functionality
> fix(video-player): toggle playback mode and update time range

- .github/workflows/ui-test-for-commit.yml
Fix for unblocking CI on the ui tests for commit step. This change is so that the command matches the fix applied in this PR - https://github.com/awslabs/iot-app-kit/pull/2275
> fix: update test run command for ui tests

- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/trendCursor/constants/index.ts
- packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
- packages/react-components/stories/utils/query.ts
removing animation for the series lines. 
leaving rest of the animation as true during absolute time viewport (user is panning / zooming ). 
https://github.com/awslabs/iot-app-kit/assets/135036199/0dfdcc5e-e6b6-412b-aaa5-366e39296cc4
> fix(react-components): removing animation from series lines 

- packages/react-components/src/components/chart/hooks/useDataZoom.ts
The purpose of this change is to restore chart performance by preventing manual data zoom dispatching when the data zoom event is triggered through a gesture. The code was already attempting to provide this guard, yet the guard was ineffective, as it relied on toggling state within the same handler. React optimizes state changes through batching, so it was not possible to control the toggle effectively within a single handler.
Other optimizations include:
- Using a ref instead of state to prevent re-renders during events.
- Using requestAnimationFrame to throttle the data zoom event and synchronize the animation with the browser refresh rate.
> fix: chart gesture performance

- packages/dashboard/src/components/internalDashboard/keyboardShortcuts.ts
- packages/dashboard/src/customization/widgets/text/styledText/textArea.tsx
- packages/dashboard/src/hooks/useKeyPress.ts
This PR is for ticket #2136 
I added an event listener for copy-and-paste.
https://github.com/awslabs/iot-app-kit/assets/139960352/58234a9e-1542-4404-9f11-d5e4fb8a41b7
> fix: copy paste issue on macos

- packages/dashboard/src/components/widgets/tile/tile.css
- packages/dashboard/src/components/widgets/tile/tile.tsx
Issue: #2164
- The issue was the delete icon gets invisible if the title is too long.
- Now the title is getting wrapped and shows in a ellipsis (...) form.
[screen-capture.webm](https://github.com/awslabs/iot-app-kit/assets/65999096/e4f1a76c-4e4e-4035-946a-30abf412ef39)
> fix: resolved delete button invisible issue #2164

- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/styledPropertyComponent.tsx
- packages/dashboard/src/customization/propertiesSections/shared/colorPicker.tsx
- packages/dashboard/src/customization/widgets/components/no-chart-data.tsx
Accessibility fixes :
Ensures all elements with a role attribute use a valid value : Abstract role cannot be directly used: widget:
Ensures buttons have discernible text: aria-label attribute does not exist or is empty
Ensures every form element has a label: aria-label attribute does not exist or is empty (color-picker)
> fix: accessibility fixes

- packages/dashboard/src/customization/propertiesSections/textSettings/text.tsx
Changed div element into button element to make it focusable and interactive by keyboard users. 
https://github.com/awslabs/iot-app-kit/assets/145582655/3b71a8f8-00c0-4b83-968c-a00fce1a470e
> fix(dashboard): bold, italics, underline interactable by keyboard

- packages/dashboard/src/components/palette/component.tsx
- packages/dashboard/src/components/palette/index.css
- packages/dashboard/src/components/palette/index.tsx
Fix for accessibility issue with list markup.
> fix: toolbar accessibility

- package-lock.json
- packages/components/package.json
- packages/core-util/package.json
- packages/dashboard/package.json
- packages/react-components/package.json
- packages/scene-composer/package.json
- packages/source-iotsitewise/package.json
- packages/source-iottwinmaker/package.json
- packages/testing-util/package.json
bumping version of synchro-charts for a bugfix in bar and status-timeline
> fix: bump charts core version

- package-lock.json
- packages/dashboard/src/components/palette/component.tsx
- packages/dashboard/src/components/palette/index.css
- packages/dashboard/src/components/palette/index.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/modeledDataStreamTable/modeledDataStreamTable.tsx
- packages/dashboard/src/msw/handlers.ts
- packages/dashboard/src/msw/iot-sitewise/handlers/listAssetProperties/constants.ts
- packages/dashboard/src/msw/iot-sitewise/handlers/listAssetProperties/listAssetProperties.ts
- packages/dashboard/src/msw/iot-sitewise/resources/assetModels/index.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.spec.ts
- packages/react-components/src/hooks/useTimeSeriesData/useTimeSeriesData.ts
- fix issue where invalid datatype flashes frequently
- Reduce amount of re-requests due to changes in color and y-axis settings in the dashboard
> chore: release dashboard improvements

- packages/react-components/src/components/video-player/constants.ts
- packages/react-components/src/components/video-player/videoPlayer.tsx
Updated the video player implementation to work correctly after migration to React 18 and a functional component. These changes were done after comparing with the previous implementation (class component).
Verified that video player is working fine in the example react-app.
- Live mode
- On-Demand mode
- Toggling playback node
- Changing time range for on-demand mode
- Auto play with muted on player load
```
httpserver
```
> chore(video-player): refactor based on React 18

- package-lock.json
> fix: missed rebase markers

- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.tsx
Issue: https://github.com/awslabs/iot-app-kit/issues/2308
Verification:
[disable-tab.webm](https://github.com/awslabs/iot-app-kit/assets/81667589/26adc072-a290-4912-895b-601d1d0587a8)
> feat: tabs on config panel present that are unusable #2308

- package-lock.json
- packages/feature-toggles/.eslintignore
- packages/feature-toggles/.eslintrc.js
- packages/feature-toggles/README.md
- packages/feature-toggles/jest.config.ts
- packages/feature-toggles/package.json
- packages/feature-toggles/src/context/feature-context.tsx
- packages/feature-toggles/src/hooks/__tests__/useFeature.spec.tsx
- packages/feature-toggles/src/hooks/useFeature.ts
- packages/feature-toggles/src/index.ts
- packages/feature-toggles/src/models/feature.ts
- packages/feature-toggles/src/providers/__tests__/feature-provider.spec.tsx
- packages/feature-toggles/src/providers/feature-provider.tsx
- packages/feature-toggles/src/resources/EvidentlyFeatureRepository.ts
- packages/feature-toggles/src/resources/IFeatureRepository.ts
- packages/feature-toggles/src/resources/OverridableFeatureRepository.ts
- packages/feature-toggles/src/resources/StaticFeatureRepository.ts
- packages/feature-toggles/src/resources/__tests__/EvidentlyFeatureRepository.spec.ts
- packages/feature-toggles/src/resources/__tests__/OverridableFeatureRepository.spec.ts
- packages/feature-toggles/src/resources/__tests__/StaticFeatureRepository.spec.ts
- packages/feature-toggles/tsconfig.json
Base feature toggle system we can use in AppKit, and supports integration with Evidently, NeoWeblab, and static feature toggles.
```
httpserver
```
> feat: adding feature toggle system implementation

- packages/dashboard/src/customization/propertiesSections/propertiesPanel/panel.tsx
Issue: https://github.com/awslabs/iot-app-kit/issues/2308
Verification
> feat: fix tabs on config panel present that are unusable #2308

- package-lock.json
- packages/dashboard/.eslintrc.js
- packages/dashboard/package.json
- packages/dashboard/src/components/contextMenu/option.tsx
- packages/dashboard/src/components/grid/grid.tsx
- packages/dashboard/src/components/internalDashboard/collapsiblePanel.tsx
- packages/dashboard/src/components/resizablePanes/index.tsx
- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/customization/propertiesSections/shared/expandableSectionHeader.tsx
- packages/dashboard/src/customization/propertiesSections/shared/styleExpandableSection/styleExpandableSection.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/link.tsx
- packages/dashboard/src/customization/widgets/components/widgetIcon.tsx
- packages/dashboard/src/customization/widgets/table/component.tsx
- packages/react-components/.eslintrc.js
- packages/react-components/package.json
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/legend/useChartsLegend.tsx
- packages/react-components/src/components/menu/option.tsx
- packages/react-components/src/components/tooltip/tooltip.tsx
This change adds accessibility linting to the dashboard and react-components packages using the jsx-a11y eslint plugin. All existing violations handled by directly ignoring the broken rule.
> feat: lint accessibility

- packages/dashboard/src/customization/propertiesSections/lineAndScatterStyleSettings/section.tsx
Add logging for y-axis configuration usage.
> feat(dashboard): add logging for custom y-axis

- docs/development-practices/Animation.md
The change adds a development guide for effectively throttling JavaScript animations.
> docs: document JS animation throttling development practices

- packages/dashboard/src/components/internalDashboard/index.css
- packages/dashboard/src/styles/variables.css
> fix: add left border to configuration panel

- packages/react-components/src/components/chart/legend/legend.css
- packages/react-components/src/components/chart/legend/useChartsLegend.tsx
- packages/react-components/src/components/chart/trendCursor/getTrendCursor/components/header/index.ts
- packages/react-components/src/components/chart/trendCursor/getTrendCursor/getTrendCursor.ts
- packages/react-components/src/components/chart/trendCursor/mouseEvents/handlers/drag/update.ts
- packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
- packages/react-components/src/components/chart/trendCursor/sync/useHandleSync.ts
- packages/react-components/src/components/chart/trendCursor/tests/getTrendCursor.spec.tsx
- packages/react-components/src/components/chart/trendCursor/tests/handleSync.spec.tsx
- packages/react-components/src/components/chart/trendCursor/tests/useTrendCursorsEvents.spec.tsx
- packages/react-components/src/components/chart/trendCursor/types/index.ts
- packages/react-components/src/components/chart/trendCursor/useTrendCursors.ts
- packages/react-components/stories/chart/base-chart.stories.tsx
> feat(dashboard): trend cursor colors

- packages/scene-composer/src/common/constants.ts
- packages/scene-composer/src/components/WebGLCanvasManager.tsx
- packages/scene-composer/src/components/panels/scene-settings/GroundPlaneSettingsEditor.tsx
- packages/scene-composer/src/components/three-fiber/GroundPlane.tsx
- packages/scene-composer/src/components/three-fiber/ModelGeometryComponents/PlaneGeometryComponent.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/GLTFModelComponent.tsx
- packages/scene-composer/src/components/three-fiber/ModelRefComponent/TilesModelComponent.tsx
Perform clean up for items found in https://github.com/awslabs/iot-app-kit/pull/2393
```
httpserver
```
> chore(scene): clean up plane code

- package-lock.json
- packages/dashboard/package.json
- packages/dashboard/src/components/dashboard/index.tsx
conditionally adding an FPS display to monitor performance
https://github.com/awslabs/iot-app-kit/assets/135036199/28fc721b-4827-45a7-b067-4ed41d0549bc
> feat(react-components): adding a fps display

- packages/dashboard/src/msw/iot-sitewise/handlers/batchGetAssetPropertyValue/batchGetAssetPropertyValueHandler.ts
Previously, there was a bug introduced to the MSW where the batchGetAssetPropertyValueHistoryHandler responding with timestamp off by 1000x (3 digits) (commit: [fix: msw batchGetAssetPropertyValueHandler response timeInSeconds values](https://github.com/awslabs/iot-app-kit/commit/e45e87008cb2486693f3f1656d5344e39d719a52)).
This PR fixes the bug by making sure the request start/endDate are consistently in Date objects after conversion (seconds -to-milliseconds) and parsing.
https://github.com/awslabs/iot-app-kit/assets/50635800/d59d7270-3623-4b78-94ba-3a2350973198
> fix: msw batchGetAssetPropertyValueHistoryHandler timestamp

- packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts
During the implementation of composite models this test was commented out to get it into production. Performance changes since then allow this test to pass, so we are uncommenting it to add to the test coverage.
> fix(dashboard): composite model tests run correctly

- packages/doc-site/.storybook/main.js
The story book is not recognizing the canvas area, needs a config update
https://github.com/awslabs/iot-app-kit/assets/135036199/06d20820-41bc-4336-8df6-786769df798e
> fix(doc-site): the canvas area rendering issue is fixed

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/events/useHandleChartEvents.ts
- packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
fix the mouse events for charts
https://github.com/awslabs/iot-app-kit/assets/135036199/09ae671e-d6b0-4610-9aa4-50a4661cc179
> fix: fixing chart mouse events

- package.json
Ensures we aren't using a vulnerable version of fast-xml-parser in our dependency chain.
```
httpserver
```
> fix(V1011333107): vulnerbility in fast-xml-parser dependabot couldn't resolve

- packages/dashboard/src/customization/propertiesSections/axisSettings/section.tsx
- packages/dashboard/src/customization/propertiesSections/settings/section.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/link.tsx
- packages/dashboard/src/customization/propertiesSections/textSettings/text.tsx
improve styling of properties panel
text widget:
---
table widget:
---
status widget:
---
kpi widget:
---
status timeline widget:
---
bar widget
> fix: improve properties panel styling

- docs/PRBestPractices.md
Adding PR best practices doc, as decided and agreed upon internally.
> docs: pull request best practices

- README.md
This change updates our README.md to link to various development docs to make them more discoverable.
> docs: make development docs discoverable

- .github/workflows/composite/action.yml
- .github/workflows/run-tests-full-suite.yml
splitting full-suites tests to run in different jobs per package to help with scaling
refer to the build checks and respective logs
> chore: splitting full-suites tests to run in different jobs to help with scaling

- packages/react-components/stories/chart/base-chart.stories.tsx
React-components Chart story-book error
> fix: React-components Chart story-book error

- .github/workflows/npm-publish.yml
> chore: merge rc into main 

- packages/dashboard/e2e/tests/configPanel/ConfigPanel.ts
- packages/dashboard/e2e/tests/dashboard/DashboardPage.ts
- packages/dashboard/e2e/tests/resourceExplorer/ResourceExplorer.ts
- packages/dashboard/e2e/tests/test.ts
- packages/dashboard/e2e/tests/widgets/LineWidget.ts
- packages/dashboard/e2e/tests/widgets/line.spec.ts
- packages/dashboard/e2e/tests/widgets/text.spec.ts
- packages/dashboard/playwright.config.ts
- packages/react-components/src/hooks/useECharts/useECharts.tsx
This is adding functional e2e tests for Line and Text Widgets
I have covered most of the use cases, feel free to let me know if you think anything other cases would be critical to test 
UI tests passing below
> chore: adding line and text e2e test cases

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/dataStreamSearch.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/workspaceSelector/workspaceSelector.tsx
This PR is for ticket #2384 and fixed the required workspace error when it auto-selected
[workspace-autoselect.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/9876e101-d3ec-4d21-bd5e-e99e74556865)
> fix: fixed the workspace required error in search section

- packages/dashboard/e2e/tests/configPanel/ConfigPanel.ts
- packages/dashboard/e2e/tests/dashboard/DashboardPage.ts
- packages/dashboard/e2e/tests/resourceExplorer/ResourceExplorer.ts
- packages/dashboard/e2e/tests/test.ts
- packages/dashboard/e2e/tests/utils/getDecimalPlaces.ts
- packages/dashboard/e2e/tests/widgets/kpi.spec.ts
- packages/dashboard/src/customization/propertiesSections/settings/section.tsx
- packages/dashboard/src/customization/widgets/status-timeline/statusTimeline.tsx
- packages/dashboard/src/msw/iot-sitewise/handlers/batchGetAssetPropertyValue/batchGetAssetPropertyValueHandler.ts
- packages/react-components/src/components/kpi/kpiBase.tsx
KPI tests include:
- adding property
- disabled add property if one has already been added
- disabled add property if multiple properties are selected
- changing the sig digits settings works
- thresholds change value color if they are crossed
> chore: add KPI playwright test

- packages/dashboard/e2e/tests/dashboard/DashboardPage.ts
- packages/dashboard/e2e/tests/test.ts
- packages/dashboard/e2e/tests/widgets/status.spec.ts
- packages/react-components/src/components/status/statusBase.tsx
Tested:
- adding property
- disable the add button if property already added
- disable the add button if multiple properties selected in RE
- changing significant digits settings is reflected in widget
- thresholds change widget color if they are crossed
> chore: add Status playwright tests

- packages/dashboard/e2e/tests/dashboard/DashboardPage.ts
- packages/dashboard/e2e/tests/test.ts
- packages/dashboard/e2e/tests/widgets/table.spec.ts
- packages/react-components/src/components/table/tableHelpers.tsx
Tested:
- adding property
- single property addition
- muliti select property addition
- changing significant digits settings is reflected in widget
- thresholds change widget color if they are crossed
added TODO comment to test status field in table once MSW supports it
> chore: add tests for table widget

- packages/scene-composer/src/components/panels/__tests__/SceneNodeInspectorPanel.spec.tsx
- packages/scene-composer/src/components/panels/__tests__/__snapshots__/SceneNodeInspectorPanel.spec.tsx.snap
Cleaning up `undefined` occurrences in snapshots from previous update. 
```
httpserver
```
> chore(scene composer): cleaning up undefines in snapshots

- packages/dashboard/e2e/tests/dataStreamMinMax/dataStreamMaxes.spec.ts
- packages/dashboard/e2e/tests/dataStreamMinMax/dataStreamMins.spec.ts
- packages/react-components/src/components/chart/chartOptions/useChartConfiguration.ts
- packages/react-components/src/echarts/extensions/minMaxDataStreamValues/minMaxDataStreamSync.ts
- packages/react-components/src/echarts/extensions/minMaxDataStreamValues/updateDataStreamMinMax.ts
Changing the significant digits in the config panel is reflected in the table cell for min/max
https://github.com/awslabs/iot-app-kit/assets/145582655/069fd934-aa91-437b-b53e-b11b8c1eb0b9
> fix: min/max values have correct significant digits

- packages/react-components/src/components/kpi/kpi.css
- packages/react-components/src/components/status/status.tsx
New status widget (which will use KPI under the hood) 
> feat: new design status (gated)

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/dataStreamSearch/workspaceSelector/workspaceSelector.tsx
This PR is for ticket #2566 and fixed the bug for saving workspace in localstorage
https://github.com/awslabs/iot-app-kit/assets/142866907/2ab6eced-c105-4ccc-b0bd-9ec740915296
https://github.com/awslabs/iot-app-kit/assets/142866907/2a67217c-6771-490a-8748-6b34a98c56ec
> fix: fixed the bug in saving workspace in localstorage

- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/dashboard/index.tsx
- packages/dashboard/src/components/internalDashboard/index.tsx
Reverts awslabs/iot-app-kit#2611
> Revert "fix: updated the viewport settings for dynamic input"

- packages/dashboard/src/components/widgets/tile/tile.tsx
- packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx
Adding back in the bottom bar for xy-plot, bar-chart, and status-timeline component.
Removing title bar for kpi / status
> fix(dashboard): style updates to widget title bar

- packages/dashboard/src/components/util/dateTimeUtil.spec.tsx
fixed the timezone issue in unit test for the ticket #2623 
> fix: fixed the timezone issue in unit test

- packages/core/src/data-module/types.ts
- packages/source-iotsitewise/src/time-series-data/util/toDataPoint.ts
Adding quality attribute to `DataPoint`
> feat: add data quality attribute to data-point

- packages/core/src/data-module/types.ts
- packages/dashboard/src/components/dashboard/index.test.tsx
- packages/dashboard/src/components/querySettingsSync/constants.ts
- packages/dashboard/src/components/querySettingsSync/refreshRateDropDown.tsx
- packages/dashboard/src/components/querySettingsSync/types.ts
- packages/dashboard/src/customization/hooks/useRefreshRate.ts
- packages/dashboard/src/store/actions/changeRefreshRate/index.ts
- packages/dashboard/src/types.ts
- packages/dashboard/stories/dashboard/mocked-dashboard.stories.tsx
- packages/react-components/src/components/bar-chart/barChart.tsx
Addressing nits found on [#2669](https://github.com/awslabs/iot-app-kit/pull/2669)
- moved RefreshRate type to core package
- removed duplicate DEFAULT_REFRESH_RATE
> fix: remove duplicate constants and types

- packages/dashboard/src/customization/propertiesSections/formatDataSettings/index.tsx
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2605 and updated the aggregation change update logic in the query when the resolution changes
https://github.com/awslabs/iot-app-kit/assets/142866907/1821c450-b154-43d6-bbda-cedb3d5b47be
> fix: fixed the issue with no aggregation change

- packages/react-components/src/components/table/createCellItem.ts
- packages/react-components/src/components/table/createTableItems.ts
- packages/react-components/src/components/table/tableHelpers.spec.tsx
- packages/react-components/src/components/table/tableHelpers.tsx
- packages/react-components/src/components/table/types.ts
Added data quality icon and text next to value in table #2664 
[table-data-quality.webm](https://github.com/awslabs/iot-app-kit/assets/154328164/1ecc3e26-58af-4021-93e6-b0f74001b19f)
> feat: added data quality icon and text next to value in table

- packages/doc-site/stories/data-sources/AWSIoTSiteWiseSource.mdx
Add refresh rate API changes in core to docsite with example on how to use it in a query. 
> chore: update docsite with refresh rate API changes

- packages/dashboard/src/components/palette/icons/index.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/datastream/highlightToggle.tsx
- packages/react-components/src/hooks/useTheming/applyTokens.ts
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2668 (only button text and background color are covered in this PR) and updated theming support for buttons text and background color.
**Note:** The follow-up PRs will fix the remaining issues (as mentioned in the ticket, updating the changes incrementally, instead of doing all of the changes in the single PR).
The palette text color and color highlighttoggle button in the legend now support theming
https://github.com/awslabs/iot-app-kit/assets/142866907/e4afe75f-cc0e-4049-b235-27433ba2ff5e
> fix: updated theming support for buttons text and background color

- packages/react-components/src/components/l4eWidget/constants.ts
- packages/react-components/src/components/l4eWidget/fakeData.ts
- packages/react-components/src/components/l4eWidget/index.tsx
- packages/react-components/src/components/l4eWidget/types.ts
- packages/react-components/src/components/l4eWidget/utils/formatTooltip.ts
- packages/react-components/stories/l4e/l4e.stories.tsx
create timeline widget, only uses mock data and is not exported for public use yet 
https://github.com/awslabs/iot-app-kit/assets/28601414/1a9ecc91-f958-47ec-a94f-5aad40aa5edf
---
TODO in future PRs:
- update public API for component
- create tests
- create and actual table component
> feat: l4e timeline (mock data only)

- packages/react-components/src/components/l4eWidget/constants.ts
- packages/react-components/src/components/l4eWidget/contributingPropertiesTable/columnDefinitions.tsx
- packages/react-components/src/components/l4eWidget/contributingPropertiesTable/contributingPropertiesTable.tsx
- packages/react-components/src/components/l4eWidget/index.tsx
- packages/react-components/src/components/l4eWidget/types.ts
- packages/react-components/stories/l4e/l4e.stories.tsx
- packages/react-components/stories/l4e/mockData.ts
Add table to l4e widget (widget is still unreleased so props will change in followup PRs)
https://github.com/awslabs/iot-app-kit/assets/28601414/295502f6-2610-472b-ae0b-366d006c66ed
> feat: l4e table

- packages/react-components/src/components/gauge/constants.ts
- packages/react-components/src/components/gauge/gauge.tsx
- packages/react-components/src/components/gauge/gaugeBase.tsx
- packages/react-components/src/components/gauge/gaugeOptions/series/useEmptyGaugeSeries.ts
- packages/react-components/src/components/gauge/gaugeOptions/series/useProgressBarGaugeSeries.ts
- packages/react-components/src/components/gauge/gaugeOptions/series/useThresholdOutsideArcSeries.ts
- packages/react-components/src/components/gauge/hooks/useGaugeConfiguration.ts
- packages/react-components/src/components/gauge/hooks/useGaugeFormatterValue.ts
- packages/react-components/src/components/gauge/hooks/useGaugeThresholds.ts
- packages/react-components/src/components/gauge/types.ts
- packages/react-components/src/components/gauge/utils/getDecimalValueFromMinMax.spec.ts
- packages/react-components/src/components/gauge/utils/getDecimalValueFromMinMax.ts
- packages/react-components/src/components/gauge/utils/getThresholds.ts
- packages/react-components/src/utils/getPreciseValue.spec.ts
- packages/react-components/src/utils/getPreciseValue.ts
- packages/react-components/stories/gauge/gauge.stories.tsx
- packages/react-components/stories/gauge/mock-data.ts
This PR is for the ticket gauge component #2624 , #2631 
TODO: 
1. The component should work with connected mode.
2. Implement error state.
3. Implement data quality.
https://github.com/awslabs/iot-app-kit/assets/139960352/d65320af-d229-4a62-9f9f-9d09d0141149
Loading state:
> feat: guage component initial commit

- packages/scene-composer/CHANGELOG.md
Dummy commit for purposes of triggering repo processes
n/a
```
httpserver
```
> chore(dummy): push dummy commit to trigger automation

- packages/doc-site/stories/components/gauge/Docs.mdx
- packages/doc-site/stories/components/gauge/Gauge.stories.tsx
- packages/doc-site/stories/mockSinWaveData.ts
- packages/react-components/src/components/gauge/gauge.css
- packages/react-components/src/components/gauge/gaugeBase.tsx
- packages/react-components/src/components/gauge/gaugeErrorText.tsx
- packages/react-components/src/components/gauge/hooks/useGaugeConfiguration.ts
- packages/react-components/src/index.ts
- packages/testing-util/src/data/mockTimeSeriesDataRealTime.ts
This PR is for ticket #2631 
Added Guage component in the doc-site package. and also exported the Gague component from react-components.
https://github.com/awslabs/iot-app-kit/assets/139960352/bba9d1a1-a12f-463d-ba5c-5bd43dc8adc6
> feat: add gauge component in doc site package

- packages/react-components/src/components/anomaly-widget/constants.ts
- packages/react-components/src/components/anomaly-widget/hooks/useAnomalyEchart.ts
- packages/react-components/src/components/anomaly-widget/tooltip/diagnostic.tsx
- packages/react-components/src/components/anomaly-widget/tooltip/formatTooltipData.ts
- packages/react-components/src/echarts/index.ts
- packages/react-components/src/echarts/themes/registerCloudscapeThemes.ts
- packages/react-components/src/echarts/unboundedZoom/constants.ts
- packages/react-components/src/echarts/unboundedZoom/useUnboundedDataZoom.ts
- packages/react-components/src/hooks/useECharts/useZoomableECharts.ts
- packages/react-components/stories/anomaly/anomaly.stories.tsx
- packages/react-components/stories/anomaly/mockData.ts
- fix minor bug where multiple l4e widgets had duplicated data 
- add toolbox for zooming in
- disable legend click
- minor performance improvement through delaying tooltip display
- multiply tooltip values by 100% so they are real percentages
- default sort tooltip by value from big to small
- implement cloudscape dark and light mode theming 
> feat: minor bugs and cloudscape theming

- packages/react-components/src/components/anomaly-widget/anomalyWidgetError.tsx
- packages/react-components/src/components/anomaly-widget/index.tsx
- packages/react-components/stories/anomaly/anomaly.stories.tsx
- packages/react-components/stories/anomaly/mockData.ts
Handle other states -- empty dataset, loading, failed, and error
> fix(react-components): add error state

- packages/react-components/src/components/anomaly-widget/constants.ts
- packages/react-components/src/components/anomaly-widget/converters/convertGrid.ts
- packages/react-components/src/components/anomaly-widget/converters/convertXAxis.ts
- packages/react-components/src/components/anomaly-widget/converters/convertYAxis.ts
- packages/react-components/src/components/anomaly-widget/converters/index.ts
- packages/react-components/src/components/anomaly-widget/hooks/types.ts
- packages/react-components/src/components/anomaly-widget/hooks/useAnomalyEchart.ts
- packages/react-components/src/components/anomaly-widget/index.tsx
- packages/react-components/src/components/anomaly-widget/types.ts
- packages/react-components/stories/anomaly/anomaly.stories.tsx
Update axis option for anomaly widget to be the same structure as the other widgets.
Add new replace merge strategy to setOption so that we properly reset the series on the widget if the datasource changes.
> feat(react-components): anomaly widget axis

- packages/react-components/src/components/anomaly-widget/anomalyWidgetError.tsx
> fix(react-components): center error state

- packages/scene-composer/src/components/panels/scene-settings/SceneTagSettingsEditor.spec.tsx
- packages/scene-composer/src/components/panels/scene-settings/SceneTagSettingsEditor.tsx
Cleaning up state management for tag settings panel. 
Before
https://github.com/awslabs/iot-app-kit/assets/6610619/6d508738-2fb3-430b-9404-78e25fdd346a
After
https://github.com/awslabs/iot-app-kit/assets/6610619/3933210c-9508-40bf-a1f4-37fb29ed0990
```
httpserver
``` …
> fix(scene composer): correcting state logic for tag settings

- packages/scene-composer/package.json
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/SceneHierarchyTreeItem.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/SceneHierarchyTreeItem.spec.tsx
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SceneHierarchyTree/__tests__/__snapshots__/SceneHierarchyTreeItem.spec.tsx.snap
- packages/scene-composer/src/store/helpers/sceneDocumentHelpers.ts
- packages/scene-composer/src/store/slices/SceneDocumentSlice.spec.ts
- packages/scene-composer/src/utils/entityModelUtils/updateNodeEntity.ts
1. enable drag and drop.
```
httpserver
```
> feat: ds ga

- packages/react-components/src/data/transformers/anomaly/object/transformer.ts
- packages/react-components/src/hooks/useECharts/useZoomableECharts.ts
- packages/react-components/stories/anomaly/anomaly.stories.tsx
Group anomaly widget so it syncs viewports with other widgets in same viewport group 
> fix(react-components): viewport fixes

- packages/dashboard/src/components/widgets/widgetActions.tsx
This PR is for ticket https://github.com/awslabs/iot-app-kit/issues/2650 and fixed the button actions issue showing in view mode and edge mode.
Before:
After:
> fix: fixed the view mode edge mode actions issue #2650

- packages/dashboard/testing/siteWiseQueries.ts
- packages/react-components/src/components/anomaly-chart/hooks/useTransformedData.ts
- packages/react-components/src/components/anomaly-chart/index.tsx
- packages/react-components/src/components/anomaly-chart/tests/anomalyWidgetTests.spec.tsx
- packages/react-components/src/components/anomaly-chart/types.ts
- packages/react-components/src/queries/predicates/index.ts
- packages/react-components/src/queries/useDescribeAsset/useDescribeAsset.ts
- packages/react-components/src/queries/useDescribeAssetModelCompositeModel/useDescribeAssetModelCompositeModel.ts
- packages/react-components/src/queries/useDescribeAssetProperties/useDescribeAssetProperties.ts
- packages/react-components/src/queries/useDescribeAssetProperty/useDescribeAssetProperty.ts
- packages/react-components/src/queries/useGetAssetPropertyValueHistory/useGetAssetPropertyValueHistory.ts
- packages/react-components/src/queries/useSiteWiseAnomalyDataSource/parseAnomaly/completeAnomalyEvents.spec.ts
- packages/react-components/src/queries/useSiteWiseAnomalyDataSource/parseAnomaly/parseAnomalyEvents.spec.ts
- packages/react-components/src/queries/useSiteWiseAnomalyDataSource/useSiteWiseAnomalyDataSource.ts
- packages/react-components/stories/anomaly/anomaly.stories.tsx
- packages/react-components/stories/anomaly/connected-anomaly-chart.tsx
- packages/source-iotsitewise/src/index.ts
- packages/source-iotsitewise/src/initialize.ts
- packages/source-iotsitewise/src/time-series-data/types.ts
Add query support to anomaly chart
> feat: anomaly chart query

- packages/scene-composer/package.json
- packages/scene-composer/src/components/ConvertingProgress.spec.tsx
- packages/scene-composer/src/components/ConvertingProgress.tsx
- packages/scene-composer/src/components/modals/ConvertSceneModal.spec.tsx
- packages/scene-composer/src/components/modals/ConvertSceneModal.tsx
> fix(dynamicscene): converting empty scene locks ui

- packages/react-components/src/components/resource-explorers/testing/drop-down-variant/asset-model-drop-down.spec.tsx
- packages/react-components/src/components/resource-explorers/testing/table-variant/asset-model-table.spec.tsx
Comment out flaky tests blocking release of iot-app-kit
> fix(react-components): comment out flaky resource expl tests

- packages/doc-site/stories/components/anomalyChart/AnomalyChart.stories.tsx
- packages/doc-site/stories/components/anomalyChart/Data.mdx
- packages/doc-site/stories/components/anomalyChart/Query.mdx
- packages/doc-site/stories/components/anomalyChart/data.ts
broken anomaly widget doc site page
> fix(doc-site): anomaly chart docs not loading

- packages/doc-site/stories/components/anomalyChart/Data.mdx
To fix the style to follow (datatype, optional) and to remove the bold for after brackets
```
httpserver
```
> chore: update anomaly chart docs

- packages/react-components/src/components/anomaly-chart/hooks/useAnomalyEchart.ts
- packages/react-components/src/components/anomaly-chart/index.tsx
- packages/react-components/src/echarts/unboundedZoom/useUnboundedDataZoom.ts
- packages/react-components/src/hooks/useECharts/useZoomableECharts.ts
- packages/react-components/src/hooks/useViewport/useUtilizedViewport.ts
Fix the anomaly datasource query for the anomaly widget when it is used outside of the time sync component.
> fix(react-components): fix support for anomaly datasource outside of time sync

- packages/dashboard/src/migration/collision-logic.ts
- packages/dashboard/src/migration/constants.ts
- packages/dashboard/src/migration/convert-monitor-to-app-defintion.spec.ts
- packages/dashboard/src/migration/convert-monitor-to-app-defintion.ts
- migrated over the collision logic in SWM described in the vue-grid-layout library
- added tests to ensure collision logic is working as expected
- all unit tests should pass
> feat(dashboard): migration logic now supports avoiding collisions that lead to overlap

- packages/scene-composer/translations/IotAppKitSceneComposer.de_DE.json
- packages/scene-composer/translations/IotAppKitSceneComposer.es_ES.json
- packages/scene-composer/translations/IotAppKitSceneComposer.fr_FR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.id_ID.json
- packages/scene-composer/translations/IotAppKitSceneComposer.it_IT.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ja_JP.json
- packages/scene-composer/translations/IotAppKitSceneComposer.ko_KR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.pt_BR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.th_TH.json
- packages/scene-composer/translations/IotAppKitSceneComposer.tr_TR.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_CN.json
- packages/scene-composer/translations/IotAppKitSceneComposer.zh_TW.json
Backlog of translation updates to prepare for feature launch.
```
httpserver
```
> chore(translations): updating translations for dynamic scenes launch

- packages/dashboard/e2e/tests/trendCursors/trendCursors.spec.ts
> chore(dashboard): fix flaky trend cursor test

- packages/react-components/src/components/anomaly-chart/hooks/useAnomalyEchart.ts
- packages/react-components/src/components/anomaly-chart/index.tsx
- packages/react-components/src/hooks/useECharts/useZoomableECharts.ts
Bugfix for anomaly chart responsiveness and default sizing.
> fix(react-components): make anomaly chart responsive

- packages/dashboard/src/migration/convert-monitor-to-app-defintion.spec.ts
- packages/dashboard/src/migration/convert-monitor-to-app-defintion.ts
- packages/dashboard/src/types.ts
- packages/doc-site/stories/utilities/migrateDashboard.mdx
Add documentation for migrateDashboard utility function
> chore(doc-site): add doc site page for migration utility

- packages/tools-iottwinmaker/src/commands/init.spec.ts
- packages/tools-iottwinmaker/src/commands/init.ts
Customer has complained about a bug where 3D Tiles content was not downloaded and copied to other workspaces correctly.
Upon testing, the sync buffer stream would not be chunked correctly for a large number of downloaded assets. The solution is to implement async streaming and pipe a read stream directly to disk. For `gltf` content it is downloaded again to memory for further parsing.
Built locally and ran `init` for multiple large 3D Tiles models, then ran `deploy` to a new workspace. The 3D Tiles content loaded in the scene successfully.
- Select the Summary item on the …
> fix(tmdt): stream 3D assets from S3 on init

- packages/doc-site/stories/components/anomalyChart/AnomalyChart.mdx
- packages/doc-site/stories/components/bar-chart/Docs.mdx
- packages/doc-site/stories/components/dashboard/Docs.mdx
Update dashboard doc site with new public API changes.
Update bar chart doc site with doc writer provided copy.
Fix anomaly doc site styling.
> chore(docsite): update doc site

- packages/dashboard/src/components/dashboard/index.tsx
make on save optional so custom toolbar users dont need to provide it
> fix(dashboard): make onSave optional

- packages/react-components/stories/anomaly/anomaly.stories.tsx
Added anomaly axis and viewport story control
Manually validated
> chore: added anomaly axis and viewport story control

- packages/doc-site/stories/components/dashboard/Docs.mdx
> chore(doc-site): dashboard add example and fix optionals

- packages/dashboard/src/components/actions/index.tsx
- packages/dashboard/src/components/dashboard/wrapper.tsx
- packages/dashboard/src/hooks/useStableDashboardConfiguration.ts
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
Bugfix for current viewport and onSave
> fix(dashboard): ensure there is a current viewport

- docs/development-practices/SnapshotTesting.md
Add docs to describe how to update snapshot tests
> chore(docs): add snapshot testing docs

- packages/react-components/src/components/anomaly-chart/hooks/useAnomalyEchart.ts
- packages/react-components/src/components/anomaly-chart/index.tsx
- packages/react-components/src/echarts/unboundedZoom/useUnboundedDataZoom.ts
- packages/react-components/src/hooks/useECharts/useZoomableECharts.ts
- packages/react-components/src/hooks/useViewport/useUtilizedViewport.ts
- packages/react-components/stories/anomaly/anomaly.stories.tsx
Ensure that the passed in viewport updates the datazoom
> fix(react-components): fix passed in viewport for anomaly widget

- packages/dashboard/src/components/dashboard/wrapper.tsx
- packages/dashboard/src/hooks/useStableDashboardConfiguration.ts
- packages/dashboard/stories/dashboard/mocked-dashboard-custom-toolbar.stories.tsx
- packages/dashboard/stories/dashboard/sitewise-dashboard.stories.tsx
Add viewmode and viewport dependency to Dashboard wrapper's stable dashboardConfiguration
and fix up storybook for future development
> fix(dashboard): missing dependency for dashboard wrapper

- packages/doc-site/stories/components/anomalyChart/AnomalyChart.mdx
- packages/react-components/src/components/anomaly-chart/hooks/types.ts
- packages/react-components/src/components/anomaly-chart/hooks/useAnomalyEchart.ts
- packages/react-components/src/components/anomaly-chart/index.tsx
- packages/react-components/src/components/anomaly-chart/types.ts
- packages/react-components/src/echarts/unboundedZoom/constants.ts
- packages/react-components/src/echarts/unboundedZoom/useUnboundedDataZoom.ts
- packages/react-components/src/hooks/useECharts/useZoomableECharts.ts
- packages/react-components/stories/anomaly/anomaly.stories.tsx
This PR adds the `gestures` option to the Anomaly Chart, the same `gestures` from [Chart](https://awslabs.github.io/iot-app-kit/?path=/docs/components-chart--docs).
https://github.com/awslabs/iot-app-kit/assets/50635800/238cb12c-c0af-4ab6-851a-7ceddc6beae6
> feat(anomaly-chart): added `gestures` enablement option

- packages/doc-site/stories/components/gauge/Gauge.stories.tsx
- packages/doc-site/stories/mockSinWaveData.ts
* Run doc-site locally, validate all the data on the gauge is a positive value 
> fix: make gauge values absolute values in gauge docs

- packages/doc-site/stories/components/kpi/Kpi.stories.tsx
- packages/react-components/src/components/data-quality/data-quality-text.tsx
* Updating the UX for the data quality feature to match our UX mocks
* Added bad and uncertain data quality stories to KPI on doc site
> fix: update data quality UX to match mocks

- packages/dashboard/src/components/csvDownloadButton/index.tsx
- packages/dashboard/src/components/queryEditor/helpers/isModeledPropertyInvalid.ts
- packages/dashboard/src/customization/propertiesSections/fontsSettings/index.tsx
- packages/dashboard/src/customization/widgets/appKitPlugin.ts
Ungate the gauge in dashboard
Remove download button
Added min to the font size inputs
Disabled adding non-numerical values to gauge
> fix(dashboard): gauge bug fixes

- packages/react-components/src/components/resource-explorers/testing/drop-down-variant/asset-model-drop-down.spec.tsx
Flaky test is slowing down development. This PR is just to temporarily remove blocker. Fast follow to fix will be there soon.
- Tests pass on 3 re-tries
> fix(react-components): remove flaky test in new RE

- packages/react-components/src/components/resource-explorers/testing/drop-down-variant/asset-model-drop-down.spec.tsx
Flaky test is slowing down development. This PR is just to temporarily remove blocker. Fast follow to fix will be there soon.
Tests pass
> fix(react-components): skip flaky test in new RE

- packages/dashboard/e2e/tests/widgets/gauge.spec.ts
remove feature flag from gauge tests in dashboard
> chore(dashboard): remove flag for gauge e2e test

- packages/doc-site/stories/components/anomalyChart/AnomalyChart.mdx
- packages/doc-site/stories/components/chart/Docs.mdx
- packages/doc-site/stories/components/dashboard/Docs.mdx
- packages/doc-site/stories/components/kpi/Docs.mdx
* Adding doc updates for timezone support based on https://github.com/awslabs/iot-app-kit/pull/2944
* Check doc site and ensure timezone docs are there.
> feat: add timezone docs

- packages/dashboard/src/components/queryEditor/helpers/getCorrectSelectionMode.spec.ts
- packages/dashboard/src/components/queryEditor/helpers/propertySelectionLabel.ts
- packages/dashboard/src/components/queryEditor/helpers/useIsAddButtonDisabled.spec.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/queryExtender/queryExtender.spec.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/queryExtender/queryExtender.ts
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/timeSeriesExplorer/timeSeriesExplorer.tsx
- packages/dashboard/src/components/queryEditor/queryEditor.tsx
- added type declarations to type imports
- rearranged helper function to flow more logically in if/else branches
- rewrote mock function to not hold state after test
- tests should all pass, no logic changes
> fix(dashboard): fast follow improvements for new RE

- packages/doc-site/stories/components/anomalyChart/AnomalyChart.mdx
- packages/doc-site/stories/components/anomalyChart/Data.mdx
- packages/doc-site/stories/components/anomalyChart/Query.mdx
- packages/doc-site/stories/components/bar-chart/Docs.mdx
- packages/doc-site/stories/components/chart/Docs.mdx
- packages/doc-site/stories/components/dashboard/Docs.mdx
- packages/doc-site/stories/components/dashboardView/ViewOnly.mdx
- packages/doc-site/stories/components/kpi/Docs.mdx
- packages/doc-site/stories/components/scene-composer/Docs.mdx
- packages/doc-site/stories/components/status-timeline/Docs.mdx
- packages/doc-site/stories/components/table/Docs.mdx
- packages/doc-site/stories/components/time-sync/Docs.mdx
- packages/doc-site/stories/core/Styles.mdx
- packages/doc-site/stories/core/Thresholds.mdx
- packages/doc-site/stories/core/TimeSeriesData.mdx
- packages/doc-site/stories/core/Viewport.mdx
- packages/doc-site/stories/core/ViewportManager.mdx
- packages/doc-site/stories/data-sources/AWSIoTSiteWiseSource.mdx
- packages/doc-site/stories/data-sources/AWSIoTTwinMakerSource.mdx
- packages/doc-site/stories/hooks/useTimeSeriesData.mdx
- packages/doc-site/stories/hooks/useViewport.mdx
- packages/doc-site/stories/overview/GettingStarted.mdx
- packages/doc-site/stories/overview/TimeSeriesDataFeatures.mdx
> chore(docsite): kriswama doc site updates

- packages/dashboard/testing/siteWiseQueries.ts
- packages/doc-site/stories/data-sources/AWSIoTSiteWiseSource.mdx
- packages/source-iotsitewise/src/index.ts
- packages/source-iotsitewise/src/initialize.ts
- packages/source-iotsitewise/src/time-series-data/types.ts
Adding new query type in source-iotsitewise for alarm data queries.
> feat: alarms datasouce query

- packages/doc-site/stories/components/anomalyChart/AnomalyChart.mdx
- packages/doc-site/stories/components/chart/Docs.mdx
- packages/doc-site/stories/components/dashboard/Docs.mdx
- packages/doc-site/stories/components/kpi/Docs.mdx
* Update wording on timezone doc based on aws writer feedback,
> fix: update timezone docs based on feedback

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledExplorer/modeledExplorer.tsx
- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/timeSeriesExplorer/timeSeriesExplorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/internal-asset-property-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/asset-property-explorer/types.ts
- packages/react-components/src/components/resource-explorers/explorers/time-series-explorer/internal-time-series-explorer.tsx
- packages/react-components/src/components/resource-explorers/explorers/time-series-explorer/types.ts
- packages/react-components/src/components/resource-explorers/variants/resource-table/resource-table-filter.css
This reverts commit ea50880bf98e26a57ab8c30276be499b5fad6656. It was not reviewed.
> revert(dashboard): add descriptions to all tables in RE

- packages/react-components/src/components/resource-explorers/testing/table-variant/asset-table.spec.tsx
skip flaky test for release. Will fast follow with change to fix the test.
> chore(testing): skip flaky test for release

- packages/react-components/src/queries/useHistoricalAssetPropertyValues/historicalAssetPropertyValueKeyFactory.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/batchResponseProcessor.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/batcher.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/constants.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/getHistoricalAssetPropertyValueRequest.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/mapTimeOrdering.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/requestExecution/mapViewport.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/types.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/useHistoricalAssetPropertyValues.ts
- packages/react-components/src/queries/useHistoricalAssetPropertyValues/useRefreshRate.ts
Add configuration options to `useHistoricalAssetPropertyValues` 
* option to request most recent before start or end values.
* option to configure how many points to request
> fix(alarms): historical asset property value requests

- packages/dashboard/testing/siteWiseQueries.ts
- packages/react-components/src/components/resource-explorers/explorers/alarm-explorer/transformAlarmData.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/alarmToSiteWiseDataStreamQuery.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/filterDatastreamsForAlarm.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/types.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/updateAlarmInputPropertyData.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/updateAlarmStatusForDatastreams.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/useInputPropertyTimeSeriesData.spec.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/useInputPropertyTimeSeriesData.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/useTimeSeriesDataQueries.ts
- packages/react-components/src/hooks/useAlarms/types.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.spec.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.ts
- packages/react-components/src/hooks/useAlarms/utils/filterAlarmInputProperties.ts
- packages/react-components/src/hooks/useAlarms/utils/queryStatus.ts
- packages/react-components/src/testing/alarms/mockAlarmData.ts
- packages/react-components/src/testing/alarms/mockIds.ts
- packages/react-components/src/utils/queries.ts
- packages/react-components/stories/queries/queriesBase.stories.tsx
- packages/source-iotsitewise/src/index.ts
- packages/source-iotsitewise/src/initialize.ts
- packages/source-iotsitewise/src/time-series-data/types.ts
Add a hook for fetching time series data for input properties for the an alarm.
> feat(alarms): add input property data fetching

- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState.spec.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState.ts
- packages/react-components/src/hooks/useAlarms/utils/alarmValueFilterer.ts
- packages/react-components/src/hooks/useAlarms/utils/updateAlarmValues.ts
- packages/react-components/src/utils/queries.ts
Update useAlarmState to fetch latest value even if its to the left of viewport
> fix(alarm status): fetch alarm state outside of viewport

- packages/react-components/src/components/status-timeline/statusTimeline.tsx
Integrate alarms into status timeline component by turning alarms into threhsolds
https://github.com/user-attachments/assets/38a64d67-67de-49fb-8e71-e86393e67447
> feat(alarms): integrate status timeline with alarms

- packages/react-components/src/components/table/createCellItem.spec.ts
- packages/react-components/src/components/table/createTableItems.ts
- packages/react-components/src/components/table/table.tsx
- packages/react-components/src/components/table/tableBase.tsx
- packages/react-components/src/components/table/tableHelpers.tsx
- packages/react-components/src/components/table/types.ts
- packages/react-components/src/hooks/useAlarms/transformers/mapAlarmRuleExpression.ts
- packages/react-components/src/hooks/useAlarms/transformers/parseAlarmStateProperty.ts
- packages/react-components/src/hooks/useAlarms/utils/updateAlarmValues.ts
- packages/react-components/src/hooks/useAlarmsFromQueries/useAlarmsFromQueries.ts
- packages/react-components/stories/queries/queriesBase.stories.tsx
Add alarms to the table component.
> feat(alarms): add alarms to table

- packages/dashboard/src/customization/propertiesSections/constants.ts
- packages/dashboard/src/customization/widgets/lineScatterChart/plugin.tsx
- packages/dashboard/src/customization/widgets/types.ts
- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSeriesAndYAxis.ts
- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSymbol.spec.ts
- packages/react-components/src/components/chart/chartOptions/seriesAndYAxis/convertSymbol.ts
- packages/react-components/src/components/chart/chartOptions/useChartConfiguration.ts
- packages/react-components/src/components/chart/chartOptions/useChartDataset.ts
- packages/react-components/src/components/chart/eChartsConstants.ts
- packages/react-components/src/components/chart/hooks/useChartAlarms.ts
- packages/react-components/src/components/chart/hooks/useChartPreferences.ts
- packages/react-components/src/components/chart/hooks/useNormalizedDataStreams.ts
- packages/react-components/src/components/chart/legend/table/columnDefinitions/factory.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/latestAlarmStateValue/index.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/latestAlarmStateValue/latestAlarmStateValueCell.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/latestAlarmStateValue/latestAlarmStateValueHeader.tsx
- packages/react-components/src/components/chart/legend/table/columnDefinitions/trendCursor/trendCursorCell.tsx
- packages/react-components/src/components/chart/legend/table/legendTableAdapter.tsx
- packages/react-components/src/components/chart/legend/table/types.ts
- packages/react-components/src/components/chart/preferences/dataQualityModal.tsx
- packages/react-components/src/components/chart/types.ts
- packages/react-components/src/hooks/useAlarms/transformers/mapAlarmRuleExpression.ts
- packages/react-components/src/hooks/useAlarms/transformers/parseAlarmStateProperty.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.ts
- packages/react-components/stories/chart/base-chart.stories.tsx
- packages/react-components/stories/utils/query.ts
> feat(alarms): add alarms to line chart

- packages/dashboard/src/components/queryEditor/useQuery.ts
- packages/dashboard/src/customization/widgets/types.ts
- packages/dashboard/src/customization/widgets/utils/assetQuery/applyAggregationToQuery.ts
- packages/dashboard/src/customization/widgets/utils/assetQuery/applyResolutionToQuery.ts
- packages/dashboard/src/customization/widgets/utils/assignDefaultStyleSettings.ts
- packages/dashboard/src/customization/widgets/utils/widgetAggregationUtils.ts
- packages/react-components/src/components/gauge/gauge.tsx
- packages/react-components/src/components/kpi/kpi.tsx
- packages/react-components/src/utils/buildTransformAlarmForSingleQueryWidgets.ts
Add support for aggregation and resolution in query config and widgets.
> fix(alarms): complete skipped queries

- packages/react-components/src/components/chart/baseChart.tsx
- packages/react-components/src/components/chart/chartOptions/useChartDataset.ts
- packages/react-components/src/components/chart/hooks/useNormalizedDataStreams.ts
- packages/react-components/src/hooks/useAlarms/useAlarms.ts
Bugfix for chart tooltip potentially showing duplicated line items for alarm points.
Also cleans up some dead code and console logs.
> fix(alarms): remove duplicate data points

- packages/react-components/src/components/status-timeline/alarmTransforms.ts
- packages/react-components/src/components/status-timeline/statusTimeline.tsx
- packages/react-components/src/hooks/useAlarms/hookHelpers/useAlarmState.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useLatestAlarmPropertyValues.ts
https://github.com/user-attachments/assets/94e48035-e305-43a8-a5ae-a5115499c0f3
https://github.com/user-attachments/assets/8ceb2c2e-f71a-43a2-bf52-f385220956d5
> feat(alarms): update status timeline alarm implementation

- packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/modelBasedQuery/useModelBasedQuery.ts
- packages/dashboard/src/customization/widgets/utils/assignDefaultStyleSettings.ts
- packages/react-components/src/hooks/useAlarms/hookHelpers/useInputPropertyTimeSeriesData/useInputPropertyTimeSeriesData.ts
Bug fix for adding asset model alarms to a kpi widget.
Bug fix for configuring asset model alarms in preview mode.
Bug fix for displaying asset model alarms in widgets.
> fix(alarms): fix for asset-model alarms

- packages/scene-composer/src/components/Tree/tree.scss
- packages/scene-composer/src/components/panels/SceneHierarchyPanel/components/SubModelTree/SubModelTree.scss
- packages/scene-composer/src/components/panels/scene-settings/SceneBackgroundSettingsEditor.spec.tsx
- packages/scene-composer/src/enhancers/draggable.scss
- packages/scene-composer/src/interfaces/interfaces.tsx
I had some time & was tired of the scene hierarchy being out of sync with cloudscape tokens... so I fixed it.
- This also improves the ability to grab items for drag & drop.
Before
https://github.com/user-attachments/assets/31094523-5a8b-4a8c-8518-b9e1453337e8
After
https://github.com/user-attachments/assets/97d257b8-231d-4e46-b139-e2f1327e3332
> fix(scene hierarchy): cleaning up scene hierarchy ui

- packages/dashboard/src/components/grid/grid.css
Fix grid dot svg path for dashboard editor.
```
httpserver
```
> fix: dashboard editor dots

- docs/InstallingPackages.md
Quick development guide to provide commands for installing dependencies.
> docs: installation dev guide

- apps/doc-site/stories/components/dashboard/Docs.mdx
Specifies the permissions need for dashboard to operate in docs
- Previewed mdx changes - https://github.com/awslabs/iot-app-kit/blob/53efcb69b94280d9e63082f45a4b2ba6958f2bf2/apps/doc-site/stories/components/dashboard/Docs.mdx
- Verified creation of the policy in IAM console
> chore: specified permissions need for dashboard to operate in docs

- .github/workflows/doc-site-deploy.yml
Fix release action
```
release-please failed: node (awslabs/iot-app-kit): Missing required file: packages/doc-site/package.json
```
```
httpserver
```
> fix: release action

- packages/core-util/src/sdks/number.ts
Security fix for isNumeric regex test. Issue for reference - https://github.com/awslabs/iot-app-kit/pull/3126/files#annotation_32529606532
> chore(core-util): security fix for isNumeric util

- packages/react-components/src/echarts/extensions/trendCursors/echartsActions/extension.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetAggregatedPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetHistoricalPropertyDataPoints.ts
- packages/source-iotsitewise/src/time-series-data/client/batchGetLatestPropertyDataPoints.ts
Releasing bug fixes that keep causing client-side errors related to accessing null/undefined values. These changes add null checks and reduces access to `$metadata` values that could be undefined.
> fix: client side errors from accessing null/undefined values
